---
sidebar: sidebar 
permalink: rhhc/rhhc-value-prop.html 
keywords: NetApp Solutions, hybrid cloud, container workloads, containers, Red Hat OpenShift, RedHat OpenShift, VMware, ROSA, ACC, Trident Protect, Advanced Cluster Management, ACM, Hub Cluster 
summary:  
---
= Red Hat OpenShift Container 워크로드를 위한 NetApp 하이브리드 멀티 클라우드 솔루션의 가치 제안
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
대부분의 고객은 기존 인프라를 사용하지 않고 Kubernetes 기반 환경을 구축하는 것만을 시작하고 있지 않습니다. 가상 머신(예: 대규모 VMware 환경)에서 대부분의 엔터프라이즈 애플리케이션을 실행하는 기존 IT 환경일 수 있습니다. 그런 다음 최신 애플리케이션 개발 팀의 요구사항을 충족하기 위해 소규모 컨테이너 기반 환경을 구축하기 시작합니다. 이러한 이니셔티브는 일반적으로 소규모로 시작하여 팀이 새로운 기술과 기술을 익히고 이러한 기술을 채택함으로써 얻을 수 있는 많은 이점을 인식함에 따라 점차 널리 보급되기 시작합니다. 좋은 소식은 NetApp이 두 환경의 요구사항을 모두 충족할 수 있다는 것입니다. NetApp 고객은 Red Hat OpenShift를 사용하여 하이브리드 멀티 클라우드를 위한 이 솔루션 세트를 사용하여 전체 인프라와 조직을 정비하지 않고도 최신 클라우드 기술 및 서비스를 채택할 수 있습니다. 고객 애플리케이션과 데이터가 사내, 클라우드, 가상 머신 또는 컨테이너에서 호스팅되는 경우 NetApp은 일관된 데이터 관리, 보호, 보안 및 이동성을 제공할 수 있습니다. 새로운 솔루션을 통해 사내 데이터 센터 환경에서 NetApp이 수십 년 동안 제공해온 것과 동일한 가치를 재정비하거나 새로운 기술을 습득하거나 새로운 팀을 구축할 필요가 없이 기업 전체 데이터 수평선에서 사용할 수 있게 됩니다. NetApp은 고객이 클라우드 전환의 어떤 단계에 있든 관계없이 이러한 비즈니스 과제를 해결하도록 지원하기에 유리한 위치에 있습니다.

Red Hat OpenShift를 포함하는 NetApp 하이브리드 멀티 클라우드:

* NetApp 기반 스토리지 솔루션과 Red Hat OpenShift를 사용할 경우 고객이 데이터 및 애플리케이션을 관리, 보호, 보안, 마이그레이션할 수 있는 최상의 방법을 보여주는 검증된 설계와 사례를 제공합니다.
* VMware 환경, 베어 메탈 인프라 또는 이 둘을 조합하여 NetApp 스토리지와 Red Hat OpenShift를 실행하는 고객에게 모범 사례 제공
* 온프레미스 환경과 클라우드 환경 모두에서, 그리고 둘 다 사용되는 하이브리드 환경에 대한 전략과 옵션을 보여줍니다.

