---
sidebar: sidebar 
permalink: rhhc/rhhc-pm-solution.html 
keywords: NetApp Solutions, redhat OpenShift, red hat OpenShift, redhat openshift container platform, ocp, openshift container platform, Advanced Cluster Management, ACM, Hub Cluster, containers, container workloads, VMware, customer managed storage, ONTAP 
summary:  
---
= NetApp 솔루션에 관리형 Red Hat OpenShift Container Platform 워크로드 포함
:allow-uri-read: 




== NetApp 솔루션에 관리형 Red Hat OpenShift Container Platform 워크로드 포함

[role="lead"]
고객은 일부 특정 워크로드 또는 모든 워크로드를 데이터 센터에서 클라우드로 이동할 준비가 되었을 때 "클라우드에서 탄생됨" 또는 현대화 과정에서 일부가 될 수 있습니다. 고객은 클라우드에서 공급자 관리 OpenShift 컨테이너와 공급자 관리 NetApp 스토리지를 사용하여 워크로드를 실행할 수 있습니다. 컨테이너 워크로드를 위한 성공적인 운영 가능 환경을 위해 클라우드에서 Managed Red Hat OpenShift 컨테이너 클러스터를 계획 및 구축해야 합니다. . NetApp는 세 가지 주요 퍼블릭 클라우드에서 관리되는 Red Hat 솔루션을 위한 완전 관리형 스토리지 제품을 제공합니다.

* Amazon FSx for NetApp ONTAP(FSx ONTAP) *

FSx ONTAP은 AWS에서 컨테이너 배포를 위한 데이터 보호, 안정성 및 유연성을 제공합니다. Trident은 고객의 상태 저장 애플리케이션에서 영구 FSx ONTAP 스토리지를 사용하는 동적 스토리지 프로비저닝자 역할을 합니다.

여러 가용성 영역에 컨트롤 플레인 노드가 분산된 상태에서 HA 모드로 Rosa를 구축할 수 있으므로, FSx ONTAP는 고가용성을 제공하고 AZ 장애로부터 보호하는 Multi-AZ 옵션을 통해 구축할 수도 있습니다.

* Google Cloud NetApp 볼륨 *

Red Hat OpenShift Dedicated는 완전 관리형 애플리케이션 플랫폼으로, 이를 통해 하이브리드 클라우드 전반에서 애플리케이션을 신속하게 구축, 배포 및 확장할 수 있습니다. Google Cloud NetApp Volumes는 Google Cloud의 OpenShift 구축에 ONTAP의 전체 엔터프라이즈 데이터 관리 기능 제품군을 포함하는 영구 볼륨을 제공합니다.
