---
sidebar: sidebar 
permalink: xcp/xcp-bp-best-practice-guidelines-and-recommendations.html 
keywords: best practices, guidelines, recommendations, IMT 
summary: 이 섹션에서는 NetApp XCP를 사용하여 데이터를 마이그레이션하기 위한 모범 사례, 지침 및 권장 사항을 다룹니다. 
---
= 모범 사례 지침 및 권장사항
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:xcp-bp-cifs-data-migration-with-acls-from-a-source-storage-box-to-ontap.html["이전: 소스 스토리지 상자에서 ONTAP로 ACL을 사용한 CIFS 데이터 마이그레이션"]

* IMT에서 지원하는 XCP 클라이언트 운영 체제를 사용합니다. IMT 지원 클라이언트는 NetApp의 검증을 받았습니다.
* Linux 운영 체제에서 루트 사용자로 xCP를 실행하여 마이그레이션을 수행합니다. sudo 사용자로 xCP 명령을 실행할 수 있지만 xCP에서는 지원되지 않습니다.
* 클라이언트당 한 개의 xCP 인스턴스만 실행합니다. 기술적으로 동일한 호스트에서 여러 XCP를 다른 위치에서 실행할 수 있지만 이는 지원되지 않습니다. 실제로 많은 인스턴스를 실행하면 오류가 발생할 수 있습니다.
* 현재 XCP 버전에서는 라이브 소스가 지원되지 않습니다. 소스 NetApp 볼륨이 활성 상태이고 애플리케이션 및 사용자가 지속적으로 변경하는 경우 소스 볼륨의 스냅샷을 생성하여 마이그레이션을 수행해야 합니다.
* 모든 증분 동기화에 대해 다른 이름을 사용하여 새 스냅샷을 생성하는 것이 가장 좋습니다. 이렇게 하면 장애 발생 시 스냅샷 이름을 기반으로 증분 마이그레이션 경로를 쉽게 생성할 수 있습니다.
* 스냅샷 기반 마이그레이션을 수행하는 경우에는 컷오버가 완료될 때까지 스냅샷 기반 마이그레이션을 계속하는 것이 좋습니다.
* 천만 개 이상의 파일이 있고 50% 이상의 증분 데이터 변경이 있는 경우 설치 및 관리 가이드에서 권장하는 최소 구성보다 더 많은 코어 수와 메모리를 사용하는 것이 좋습니다.


link:xcp-bp-troubleshooting.html["다음: 문제 해결."]
