---
sidebar: sidebar 
permalink: xcp/xcp-bp-high-performance-computing-to-ontap-nfs.html 
keywords: use case, gpfs, nfs 
summary: NetApp XCP를 사용하여 GPFS에서 NFS로 데이터를 마이그레이션하여 GPU에서 데이터를 처리할 수 있습니다. AI는 일반적으로 네트워크 파일 시스템의 데이터를 처리합니다. 
---
= 고성능 컴퓨팅에서 ONTAP NFS로
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:xcp-bp-data-lake-to-ontap-nfs.html["이전: 데이터 레이크에서 ONTAP NFS로,"]

[role="lead"]
이 사용 사례는 현장 조직의 요청을 기반으로 합니다. 일부 NetApp 고객은 고성능 컴퓨팅 환경에서 데이터를 가지고 있으며, 교육 모델을 위한 데이터 분석을 제공하고 연구 조직에서 대량의 디지털 데이터를 통찰하고 이해할 수 있도록 지원합니다. NetApp 현장 엔지니어는 IBM의 GPFS에서 NFS로 데이터를 추출하기 위한 자세한 절차가 필요합니다. NetApp XCP를 사용하여 GPFS에서 NFS로 데이터를 마이그레이션하여 GPU에서 데이터를 처리할 수 있습니다. AI는 일반적으로 네트워크 파일 시스템의 데이터를 처리합니다.

ONTAP NFS 활용 사례에 대한 고성능 컴퓨팅, 녹화된 데모 및 테스트 결과에 대한 자세한 내용은 를 참조하십시오 https://blog.netapp.com/data-migration-xcp["XCP를 사용하여 데이터 레이크와 고성능 컴퓨팅에서 ONTAP NFS로 데이터를 이동합니다"^] 블로그:

NetApp XCP를 사용하여 MapR-FS 데이터를 ONTAP NFS로 이동하는 방법에 대한 자세한 내용은 부록 A: GPFS에서 NFS로 GPFS를 참조하십시오. 자세한 단계는 에 나와 있습니다 https://www.netapp.com/us/media/tr-4732.pdf["TR-4732: 인공 지능에 대한 빅 데이터 분석 데이터"^].

link:xcp-bp-using-the-xcp-data-mover-to-migrate-millions-of-small-files-to-flexible-storage.html["다음으로 xCP Data Mover를 사용하여 수백만 개의 작은 파일을 유연한 스토리지로 마이그레이션합니다."]
