---
sidebar: sidebar 
permalink: xcp/xcp-bp-performance-tuning.html 
keywords: performance, tuning, operations, windows 
summary: 이 섹션에서는 XCP 작업의 성능을 향상시키는 데 도움이 되는 튜닝 매개 변수 몇 가지를 제공합니다. 
---
= 성능 튜닝
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:xcp-bp-sizing-guidelines-overview.html["이전: 사이징 지침"]

이 섹션에서는 XCP 작업의 성능을 향상시키는 데 도움이 되는 튜닝 매개 변수 몇 가지를 제공합니다.

* 더 나은 확장을 위해 여러 xCP 인스턴스에 워크로드를 분산하려면 마이그레이션 및 데이터 전송을 위해 각 xCP 인스턴스에 대한 하위 폴더를 분할합니다.
* xCP는 최대 CPU 리소스를 사용할 수 있습니다. CPU 코어가 많을수록 성능이 향상됩니다. 따라서 xCP 서버에 더 많은 CPU가 있어야 합니다. 실습은 128GB RAM 및 48배 코어 CPU를 테스트했으며, 이는 8개의 CPU와 8GB RAM보다 뛰어난 성능을 제공했습니다.
* '-parallel' 옵션이 포함된 xCP 복제본은 CPU 수에 따라 달라집니다. 대부분의 XCP 데이터 전송 및 마이그레이션 작업에는 기본 병렬 스레드 수(7개)가 충분할 수 있습니다. xCP Windows의 경우 기본적으로 병렬 프로세스의 수는 CPU 수와 같습니다. '-parallel' 옵션의 최대 개수는 코어 수보다 작거나 같아야 합니다.
* 10GbE는 데이터 전송을 시작하는 데 적합합니다. 그러나 25GbE 및 100GbE로 테스트하여 데이터 전송 성능이 향상되었고 대용량 파일 크기 데이터 전송에 권장됩니다.
* Azure NetApp Files의 경우 성능은 서비스 수준에 따라 다릅니다. 자세한 내용은 Azure NetApp Files 서비스 수준 및 성능 세부 정보를 보여 주는 다음 표를 참조하십시오.


|===
| 서비스 레벨 | 표준 | 프리미엄 | 초대형 


| 처리량 | 16MBps/테라바이트(TB) | 64MBps/TB | 128MBps/TB 


| 워크로드 유형 | 범용 파일 공유, 이메일, 웹 | BMS, 데이터베이스 및 애플리케이션 | 지연 시간에 민감한 애플리케이션 


| 성능 설명 | 표준 성능: TB당 1,000 IOPS(16K I/O) 및 16MBps/TB | 프리미엄 성능 – TB당 4,000 IOPS(16k I/O) 및 TB당 64MBps | 탁월한 성능: TB당 8,000 IOPS(16k I/O) 및 128MBps/TB 
|===
처리량 및 워크로드 유형에 따라 적합한 서비스 수준을 선택해야 합니다. 대부분의 고객은 프리미엄 레벨에서 시작하고 워크로드에 따라 서비스 수준을 변경합니다.

link:xcp-bp-customer-scenarios-overview.html["다음은 고객 시나리오입니다."]
