---
sidebar: sidebar 
permalink: data-analytics/dremio-lakehouse-solution.html 
keywords: solution, architecture, details, hardware, software 
summary: 이 섹션에서는 dremio 인증에 사용되는 하드웨어 및 소프트웨어에 대해 설명합니다. 이 정보는 NetApp 스토리지를 사용한 dremio 구축에 적용됩니다. 
---
= 솔루션 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
하이브리드 Iceberg Lakehouse 솔루션은 데이터 레이크 고객이 직면한 과제를 해결할 수 있는 고유한 이점을 제공합니다. Dremio Unified Lakehouse 플랫폼과 NetApp ONTAP, StorageGRID 및 NetApp 클라우드 솔루션을 활용하여 기업은 비즈니스 운영에 상당한 가치를 더할 수 있습니다. 이 솔루션은 NetApp 소스를 비롯한 여러 데이터 소스에 대한 액세스를 제공할 뿐만 아니라 전반적인 분석 성능을 향상시키고 기업이 비즈니스 성장에 이르는 비즈니스 통찰력을 확보할 수 있도록 지원합니다.



== NetApp 개요

* ONTAP 및 StorageGRID와 같은 NetApp 제품은 스토리지와 컴퓨팅을 분리함으로써 특정 요구 사항에 따라 최적의 리소스 활용도를 제공합니다. 이러한 유연성 덕분에 고객은 NetApp 스토리지 솔루션을 사용하여 스토리지를 독립적으로 확장할 수 있습니다
* NetApp의 스토리지 컨트롤러를 활용하는 고객은 NFS 및 S3 프로토콜을 사용하여 벡터 데이터베이스에 데이터를 효율적으로 제공할 수 있습니다. 이러한 프로토콜은 고객 데이터 스토리지를 용이하게 하고 벡터 데이터베이스 인덱스를 관리하므로 파일 및 개체 방법을 통해 액세스되는 데이터의 여러 복사본이 필요하지 않습니다.
* NetApp ONTAP는 AWS, Azure, Google Cloud와 같은 주요 클라우드 서비스 공급자가 NAS 및 오브젝트 스토리지를 기본 지원합니다. 이러한 광범위한 호환성은 원활한 통합을 보장하므로 고객 데이터 이동성, 글로벌 액세스 가능성, 재해 복구, 동적 확장성 및 고성능을 지원합니다.




=== StorageGRID

NetApp의 업계 최고 오브젝트 스토리지 StorageGRID는 자동화된 데이터 배치, 유연한 구축 옵션, 계층적 삭제 코딩을 통한 강력한 정책 엔진을 제공합니다. 확장형 아키텍처를 통해 단일 네임스페이스에서 수십억 개의 오브젝트와 페타바이트급 데이터를 지원합니다. 이 솔루션을 통해 하이브리드 클라우드 통합을 지원하므로 주요 클라우드 플랫폼에 데이터를 계층화할 수 있습니다. 2019 IDC Marketscape Worldwide Object-based Vendor Assessment에서 리더로 선정되었습니다.

또한, StorageGRID은 소프트웨어 정의 오브젝트 스토리지, 지리적 이중화, 다중 사이트 기능을 통해 비정형 데이터를 대규모로 관리하는 데 탁월한 기능을 제공합니다. 또한 정책 기반 정보 라이프사이클 관리를 통합하고 미러링 및 검색과 같은 클라우드 통합 기능을 제공합니다. Common Criteria, NF203 Digital Safe Component, ISO/IEC 25051, KPMG, Cohasset Compliance Assessment 등 다양한 인증을 획득했습니다.

요약하면, NetApp StorageGRID은 강력한 기능, 확장성, 하이브리드 클라우드 통합, 규정 준수 인증을 제공하여 규모에 따른 비정형 데이터를 효율적으로 관리합니다.



=== NetApp ONTAP를 참조하십시오

NetApp ONTAP는 다양한 엔터프라이즈 기능을 제공하는 강력한 스토리지 솔루션입니다. Snapshot이 포함되어 있어 애플리케이션 정합성을 보장하고 조작 방지 기능을 갖춘 즉각적인 백업을 제공합니다. SnapRestore를 사용하면 필요 시 백업을 거의 즉각적으로 복원할 수 있고, SnapMirror는 통합된 원격 백업 및 재해 복구 기능을 제공합니다. 이 솔루션은 ARP(자율적 랜섬웨어 방어)도 통합되어 다중 관리자 검증, FIPS 인증을 통한 유휴 데이터 암호화, 전송 중 데이터 암호화, 다단계 인증(MFA), 역할 기반 액세스 제어(RBAC) 등과 같은 기능으로 데이터 보안을 보장합니다. 여러 테넌트에 대한 포괄적인 로깅, 감사, 온보드 및 외부 키 관리, 안전한 삭제, 안전한 관리 등 데이터 보안 및 규정 준수가 더욱 향상됩니다.

또한 NetApp ONTAP는 SnapLock를 통해 규정 준수 데이터에 높은 수준의 무결성, 성능 및 보존 기능을 제공하고 총 소유 비용을 절감합니다. NetApp ONTAP ® 9과 완벽하게 통합되어 악의적인 행위, 악성 관리자, 랜섬웨어로부터 보호합니다.

이 솔루션은 전송 중인 데이터 및 유휴 데이터 암호화, 다단계 관리자 액세스, 다중 관리자 검증에 대한 NSE/NVE 암호화를 포함합니다. Active IQ은 AI 정보에 기반한 예측 분석 및 수정 조치를 제공하고 QoS는 서비스 품질 워크로드 제어를 보장합니다. SysMgr/GUI/CLI/API를 통해 관리 및 자동화 통합이 직관적입니다. FabricPool는 데이터를 자동으로 계층화하고, 이 솔루션은 인라인 데이터 압축, 중복제거, 컴팩션을 통해 효율성을 제공합니다. NetApp은 고객의 비용 부담 없이 워크로드 효율성 목표를 달성할 수 있도록 보장합니다.

NetApp ONTAP는 NVMe/FC, NVMe/TCP, iSCSI, NFS, SMB, S3를 비롯한 다양한 프로토콜을 지원하여 유니파이드 스토리지 솔루션으로 거듭납니다. 전반적으로 NetApp ONTAP는 광범위한 엔터프라이즈 기능, 강력한 보안, 규정 준수, 효율성 및 다용성을 제공하여 다양한 스토리지 요구를 충족합니다.



== Dremio 개요

Dremio는 셀프 서비스 분석 및 AI를 위한 통합 Lakehouse 플랫폼입니다. Dremio Unified Analytics Platform은 기존 데이터 웨어하우스 솔루션 비용의 극히 일부만으로 Lakehouse의 유연성, 확장성 및 성능을 통해 사용자가 데이터에 더 가까이 접근할 수 있도록 지원합니다. Dremio는 "전환 필요" 분석을 통해 복잡하고 비용이 많이 드는 데이터 통합 및 ETL을 제거하여 데이터 이동 없이 원활한 엔터프라이즈 규모의 분석을 제공합니다. Dremio는 다음과 같은 기능도 제공합니다.

* 범용 시맨틱 계층과 긴밀하게 통합된 고성능 SQL 쿼리 엔진을 통해 사용이 간편한 셀프 서비스 분석을 지원하므로 클라우드와 온프레미스에서 모든 데이터를 더 쉽게 연결, 관리, 분석할 수 있습니다.
* Dremio의 Apache Iceberg 네이티브 Lakehouse 관리 기능은 데이터 검색을 단순화하고 데이터 최적화를 자동화하여 Git 기반 데이터 버전 관리를 통해 고성능 분석을 제공합니다.
* 오픈 소스 및 오픈 표준을 기반으로 구축된 Dremio를 통해 기업은 종속을 방지하고 혁신에 대한 입지를 유지할 수 있습니다. 엔터프라이즈 기업은 Dremio를 모든 워크로드에서 최고의 가격 대비 성능을 제공하는 가장 사용하기 쉬운 Lakehouse 플랫폼으로 신뢰합니다.




== Dremio 및 NetApp 하이브리드 아이스버그 레이크하우스 솔루션이 고객에게 제공하는 가치는 무엇입니까?

* * 향상된 데이터 관리 및 접근성 *: Dremio는 데이터 레이크하우스 플랫폼으로 잘 알려져 있으며, 조직은 데이터 레이크에서 데이터를 고속으로 직접 쿼리할 수 있습니다. 반면 NetApp은 업계 최고의 클라우드 데이터 서비스 및 데이터 스토리지 솔루션 공급업체입니다. 이 공동 오퍼링은 고객이 기업 데이터를 효율적이고 효율적으로 저장, 관리, 액세스, 분석할 수 있는 포괄적인 솔루션을 제공합니다.
* * 성능 최적화 * : NetApp의 Data Processing 및 데이터 최적화 전문 기술과 Dremio의 역량을 바탕으로, 이 파트너십은 데이터 작업의 성능을 개선하고 지연 시간을 줄이며 비즈니스 통찰력을 빠르게 얻을 수 있는 솔루션을 제공합니다. Dremio는 NetApp의 내부 IT 분석 인프라에도 성능 이점까지 제공했습니다.
* * 확장성 * : Dremio와 NetApp 모두 확장성을 제공하도록 설계된 솔루션을 제공합니다. 이 공동 솔루션은 고객에게 확장성이 뛰어난 데이터 스토리지, 데이터 관리 및 분석 환경을 제공합니다. 하이브리드 아이스버그 레이크하우스 환경에서 NetApp StorageGRID와 결합된 Dremio SQL 쿼리 엔진은 뛰어난 확장성, 동시성 및 쿼리 성능을 제공하여 모든 비즈니스의 분석 요구를 처리할 수 있습니다.
* * 데이터 보안 및 거버넌스 *: 두 회사는 모두 데이터 보안과 거버넌스에 중점을 두고 있습니다. 또한 강력한 보안 및 데이터 거버넌스 기능을 제공하여 데이터를 보호하고 데이터 거버넌스 요구사항을 충족할 수 있습니다. 역할 기반 및 미세 입자 액세스 제어, 포괄적인 감사, 포괄적인 데이터 계통, 통합 ID 관리, 광범위한 규정 준수 및 보안 프레임워크가 포함된 SSO 등의 기능을 통해 기업의 분석 데이터 환경을 안전하게 관리하고 관리할 수 있습니다.
* * 비용 효율성 * : Dremio의 데이터 레이크 엔진을 NetApp의 스토리지 솔루션과 통합하여 고객은 데이터 관리 및 데이터 이동과 관련된 비용을 절감할 수 있습니다. 또한 조직은 기존의 데이터 레이크 환경에서 NetApp와 Dremio로 구성된 더욱 현대적인 Lakehouse 솔루션으로 전환할 수 있습니다. 이 하이브리드 아이스버그 레이크하우스 솔루션은 고속 쿼리 성능과 시장을 선도하는 쿼리 동시성을 제공하여 TCO를 낮추고 비즈니스 통찰력을 높이는 데 걸리는 시간을 단축합니다.

