---
sidebar: sidebar 
permalink: data-analytics/stgr-splunkss-solution-overview.html 
keywords: storagegrid, splunk enterprise, smartstore, object storage, machine data 
summary: 이 페이지에서는 NetApp StorageGRID, Splunk Enterprise, Splunk SmartStore를 비롯하여 이 솔루션을 완료하는 데 사용되는 구성요소를 설명합니다. 
---
= 솔루션 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 페이지에서는 NetApp StorageGRID, Splunk Enterprise, Splunk SmartStore를 비롯하여 이 솔루션을 완료하는 데 사용되는 구성요소를 설명합니다.



== NetApp StorageGRID를 참조하십시오

NetApp StorageGRID는 비용 효율적인 고성능 오브젝트 스토리지 플랫폼입니다. 분산된 노드 기반 그리드 아키텍처를 사용하여 정책 중심의 지능형 글로벌 데이터 관리를 제공합니다. 정교한 데이터 관리 기능과 결합된 유비쿼터스 글로벌 오브젝트 네임스페이스를 통해 페타바이트 단위의 비정형 데이터와 수십억 개의 오브젝트 관리를 간소화합니다. 단일 호출 개체 액세스는 사이트 간에 확장되고 고가용성 아키텍처를 단순화하는 동시에 사이트 또는 인프라 중단과 관계없이 지속적인 개체 액세스를 보장합니다.

멀티 테넌시를 사용하면 여러 클라우드와 엔터프라이즈의 비정형 데이터 애플리케이션을 동일한 그리드 내에서 안전하게 서비스할 수 있으므로 StorageGRID의 ROI 및 사용 사례가 증가합니다. 여러 지역에서 내구성, 보호, 성능, 인접성을 최적화하여 메타데이터 기반 오브젝트 라이프사이클 정책에 따라 여러 서비스 레벨을 생성할 수 있습니다. 사용자는 정책을 조정하고 요구 사항이 변경됨에 따라 데이터 환경을 중단 없이 재조정할 수 있습니다.

SmartStore는 StorageGRID를 원격 스토리지 계층으로 활용하고 고객이 지리적으로 분산된 여러 사이트를 구축하여 단일 오브젝트 네임스페이스로 제공되는 강력한 가용성과 내구성을 확보할 수 있도록 지원합니다. 이를 통해 Splunk SmartStore는 StorageGRID의 고성능, 고밀도 용량을 활용할 수 있으며, 단일 URL을 사용하여 여러 물리적 사이트에서 수백 개의 노드로 확장할 수 있습니다. 또한 단일 URL을 통해 스토리지 확장, 업그레이드 및 수리를 단일 사이트 외부에서도 무중단으로 수행할 수 있습니다. StorageGRID의 고유한 데이터 관리 정책 엔진은 최적의 성능 및 내구성 수준을 제공하며 데이터 지역성 요구사항을 준수합니다.



== Splunk Enterprise

Splunk는 머신 생성 데이터의 수집 및 분석을 선도하는 기업으로, 운영 분석 기능을 통해 IT를 간소화 및 현대화하도록 지원합니다. 또한 비즈니스 분석, 보안, IoT 사용 사례로 확장됩니다. 스토리지는 성공적인 Splunk 소프트웨어 구축을 위한 중요한 지원 요소입니다.

시스템에서 생성되는 데이터는 가장 빠르게 증가하는 빅 데이터 유형입니다. 이 형식은 예측할 수 없으며 많은 소스에서 가져온 것으로, 대개 높은 속도와 큰 볼륨에서 사용됩니다. 이러한 워크로드 특성을 디지털 배기가라고 합니다. Splunk SmartStore를 사용하면 이러한 데이터를 쉽게 파악할 수 있으며 가장 비용 효율적인 스토리지 계층에 핫 데이터와 웜 데이터를 최적의 위치에 배치할 수 있는 스마트 데이터 계층화를 제공합니다.



== Splunk SmartStore를 참조하십시오

Splunk SmartStore는 StorageGRID와 같은 오브젝트 스토리지(원격 스토리지 또는 원격 스토리지 계층이라고도 함)를 사용하여 S3 프로토콜을 사용하여 웜 데이터를 저장하는 인덱서 기능입니다.

배포의 데이터 볼륨이 증가하면 일반적으로 컴퓨터 리소스에 대한 스토리지 요구가 보다 커집니다. SmartStore를 사용하면 컴퓨팅과 스토리지를 별도로 확장하여 인덱서 스토리지와 컴퓨팅 리소스를 비용 효율적으로 관리할 수 있습니다.

SmartStore는 S3 프로토콜 및 캐시 관리자를 사용하여 원격 스토리지 계층을 도입했습니다. 이러한 기능을 통해 데이터는 인덱서 또는 원격 스토리지에 로컬로 상주할 수 있습니다. 인덱서에 상주하는 캐시 관리자는 인덱서와 원격 스토리지 계층 간의 데이터 이동을 관리합니다. 버킷 메타데이터와 함께 버킷(핫 및 웜)에 데이터가 저장됩니다.

SmartStore를 사용하면 대부분의 데이터가 원격 스토리지 계층에 상주하므로 인덱서 스토리지 공간을 최소한으로 줄이고 I/O에 최적화된 컴퓨팅 리소스를 선택할 수 있습니다. 인덱서를 사용하면 로컬 캐시가 유지되므로 요청되고 예측된 결과를 반환하는 데 필요한 최소한의 데이터가 표시됩니다. 로컬 캐시에는 핫 버킷, 활성 또는 최근 검색에 사용되는 웜 버킷의 복사본 및 버킷 메타데이터가 포함됩니다.

고객은 Splunk SmartStore와 StorageGRID를 함께 사용하여 고성능 및 비용 효율적인 원격 스토리지를 통해 환경을 증분 확장하는 동시에 전체 솔루션에 높은 수준의 탄력성을 제공할 수 있습니다. 따라서 고객은 더 많은 인덱서와 데이터 보존 변경, 운영 중단 없이 수집 속도를 향상하든 관계없이 언제든지 특정 시간에 모든 구성요소(핫 스토리지 및/또는 웜 S3 스토리지)를 추가할 수 있습니다.
