---
sidebar: sidebar 
permalink: hyperv/hyperv-deploy.html 
keywords: hyperv, hyper-v, deploy, netapp, virtualization, overview 
summary: 이 솔루션은 NetApp 스토리지에 Hyper-V를 구축하는 데 필요한 단계를 제공합니다 
---
= NetApp 스토리지에 Microsoft Hyper-V 구축
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Windows Server 플랫폼은 Hyper-V 역할을 사용하여 가상화 기술을 제공합니다. Hyper-V는 Windows Server와 함께 제공되는 여러 선택적 역할 중 하나입니다.



== 개요

Hyper-V 역할을 통해 Windows Server에 내장된 가상화 기술을 사용하여 가상화된 컴퓨팅 환경을 만들고 관리할 수 있습니다. Hyper-V 기술은 하드웨어를 가상화하여 하나의 물리적 컴퓨터에서 동시에 여러 운영 체제를 실행할 수 있는 환경을 제공합니다. Hyper-V를 사용하면 가상 머신과 해당 리소스를 생성하고 관리할 수 있습니다. 각 가상 머신은 자체 운영 체제를 실행할 수 있는 격리된 가상화 컴퓨터 시스템입니다. Hyper-V는 효율성 향상 및 비용 절감을 목표로 하는 다양한 비즈니스 목표를 지원하는 애플리케이션 및 워크로드를 가상화하는 인프라를 제공하며, 이는 VMware ® vSphere를 대체할 수 있는 완벽한 대안입니다. 특히 현재 시장 상황에서 여러 하이퍼바이저가 공존하기를 원하는 조직의 경우 더욱 그렇습니다.



== 대상

이 문서에서는 NetApp ONTAP 시스템을 사용한 Hyper-V 클러스터 구성의 아키텍처 및 구축 절차를 설명합니다. 이 문서는 세일즈 엔지니어, 현장 컨설턴트, 프로페셔널 서비스, IT 관리자, 파트너 엔지니어, Hyper-V를 운영 하이퍼바이저로 배포하거나 대체 하이퍼바이저로 배포하려는 고객을 대상으로 합니다.



== 있습니다

이 문서에 설명된 아키텍처에는 구체적으로 Microsoft ® Windows Server ® 2022 및 Hyper-V ® 가상화가 포함됩니다. NetApp은 가상화 소프트웨어와 인프라 관리 소프트웨어를 모든 구현에 적용하는 것이 좋습니다. 이 FlexPod Express 구성은 안정적인 엔터프라이즈급 인프라를 구축할 수 있도록 각 구성요소의 모범 사례를 사용합니다.



== 사용 사례 요약입니다

이 문서에서는 NetApp All-Flash FAS 및 ASA 어레이 모델을 사용하여 Microsoft Windows Server 2022에서 워크로드로 최적으로 수행하도록 Hyper-V 클러스터를 설정하기 위한 구축 절차와 모범 사례에 대해 설명합니다. 서버 운영 체제/하이퍼바이저는 Microsoft Windows Server 2022입니다. 이 지침에서는 SAN(Storage Area Network) 및 NAS(Network-Attached Storage) 프로토콜을 통해 데이터를 제공하는 NetApp 스토리지 시스템에 대해 다룹니다.
