---
sidebar: sidebar 
permalink: ent-apps-db/getting_started_requirements.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 이 페이지에서는 NetApp ONTAP 스토리지에 Oracle19c를 구축하는 자동화된 방법에 대해 설명합니다. 
---
= 시작하기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
이 솔루션은 AWX/Tower 환경 또는 Ansible 제어 호스트의 CLI에서 실행되도록 설계되었습니다.



== AWX/타워

AWX/Tower 환경의 경우 ONTAP 클러스터 관리 및 Oracle 서버(IP 및 호스트 이름)의 인벤토리 생성, 자격 증명 생성, NetApp Automation GitHub에서 Ansible 코드를 가져오는 프로젝트 구성, 자동화를 시작하는 작업 템플릿 등이 있습니다.

. 사용자 환경에 맞는 변수를 입력하고 이를 복사하여 작업 템플릿의 추가 VAR 필드에 붙여 넣습니다.
. 추가 VAR이 작업 템플릿에 추가되면 자동화를 시작할 수 있습니다.
. 작업 템플릿은 ONTAP_config, Linux_config 및 Oracle_config에 대한 태그를 지정하여 3단계로 실행됩니다.




== Ansible 제어 호스트를 통해 CLI

. Ansible 제어 호스트로 사용할 수 있도록 Linux 호스트를 구성합니다link:../automation/automation_rhel_centos_setup.html["RHEL 7/8 또는 CentOS 7/8 에 대해서는 여기를 클릭하십시오"], 또는link:../automation/automation_ubuntu_debian_setup.html["Ubuntu/Debian의 경우 여기를 참조하십시오"]
. Ansible 제어 호스트를 구성한 후 Ansible 자동화 저장소를 클론 복제할 수 있습니다.
. ONTAP 클러스터 관리 및 Oracle 서버 관리 IP의 IP 및/또는 호스트 이름으로 hosts 파일을 편집합니다.
. 해당 환경에 맞는 변수를 작성하고 복사하여 VAR.yml 파일에 붙여 넣습니다.
. 각 Oracle 호스트에는 호스트별 변수를 포함하는 호스트 이름으로 식별되는 변수 파일이 있습니다.
. 모든 변수 파일이 완료된 후 'ONTAP_config', 'linux_config', 'oracle_config'에 대한 태그를 지정하여 3단계로 플레이북을 실행할 수 있습니다.




== 요구 사항

[cols="3, 9"]
|===
| 방법입니다 | 요구 사항 


.4+| * Ansible 환경 * | Ansible 제어 호스트가 될 AWX/Tower 또는 Linux 호스트 


| Ansible v. 2.10 이상 


| Python 3 


| Python 라이브러리 - NetApp-lib-xmltodictt-jmespath 


.3+| * ONTAP * | ONTAP 버전 9.3-9.7 


| 두 개의 데이터 애그리게이트 


| NFS VLAN 및 ifgrp가 생성되었습니다 


.5+| * Oracle 서버 * | RHEL 7/8 


| Oracle Linux 7/8 


| NFS, 공용 및 선택적 관리를 위한 네트워크 인터페이스 


| Oracle 서버에 Oracle 설치 파일 
|===


== 자동화 세부 정보

이 자동 배포는 3개의 개별 역할로 구성된 단일 Ansible 플레이북을 통해 설계되었습니다. 역할은 ONTAP, Linux 및 Oracle 구성을 위한 것입니다. 다음 표에서는 자동화되고 있는 작업을 설명합니다.

[cols="4, 9"]
|===
| 역할 | 작업 


.5+| ONTAP_구성 * 을 참조하십시오 | ONTAP 환경 사전 점검 


| Oracle용 NFS 기반 SVM 생성 


| 엑스포트 정책 생성 


| Oracle의 볼륨 생성 


| NFS LIF 생성 


.9+| Linux_config * | 마운트 지점을 생성하고 NFS 볼륨을 마운트합니다 


| NFS 마운트를 확인합니다 


| OS별 구성 


| Oracle 디렉토리를 생성합니다 


| HugePages를 구성합니다 


| SELinux 및 방화벽 데몬을 해제합니다 


| 시간 기록 서비스를 활성화하고 시작합니다 


| 파일 설명자 하드 제한값을 늘립니다 


| PAM.d 세션 파일을 생성합니다 


.8+| * oracle_config * | Oracle 소프트웨어 설치 


| Oracle Listener를 생성합니다 


| Oracle 데이터베이스를 생성합니다 


| Oracle 환경 구성 


| PDB 상태를 저장합니다 


| 인스턴스 아카이브 모드를 활성화합니다 


| DNFS 클라이언트를 활성화합니다 


| OS 재부팅 간에 데이터베이스 자동 시작 및 종료를 활성화합니다 
|===


== 기본 매개변수

자동화를 간소화하기 위해 필요한 많은 Oracle 구축 매개 변수를 기본값으로 사전 설정하였습니다. 일반적으로 대부분의 배포에서 기본 매개 변수를 변경할 필요는 없습니다. 고급 사용자는 기본 매개 변수를 주의 깊게 변경할 수 있습니다. 기본 매개 변수는 각 역할 폴더의 defaults 디렉토리에 있습니다.



== 배포 지침

시작하기 전에 다음 Oracle 설치 및 패치 파일을 다운로드하여 구축할 각 DB 서버의 모든 사용자에 대한 읽기, 쓰기 및 실행 액세스 권한이 있는 '/tmp/archive' 디렉토리에 배치합니다. 자동화 작업은 Oracle 설치 및 구성을 위해 특정 디렉토리에 명명된 설치 파일을 찾습니다.

[listing]
----
LINUX.X64_193000_db_home.zip -- 19.3 base installer
p31281355_190000_Linux-x86-64.zip -- 19.8 RU patch
p6880880_190000_Linux-x86-64.zip -- opatch version 12.2.0.1.23
----


== 라이센스

GitHub 리포지토리에 설명된 대로 라이센스 정보를 읽어야 합니다. 이 리포지토리의 콘텐츠에 액세스, 다운로드, 설치 또는 사용하면 라이선스 조항에 동의하는 것입니다 link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["여기"^].

이 저장소의 컨텐츠에서 파생 저작물을 생성 및/또는 공유하는 데는 특정 제한이 있습니다. 의 약관을 읽었는지 확인하십시오 link:https://github.com/NetApp-Automation/na_oracle19c_deploy/blob/master/LICENSE.TXT["라이센스"^] 콘텐츠를 사용하기 전에. 모든 약관에 동의하지 않는 경우 이 리포지토리에서 콘텐츠를 액세스, 다운로드 또는 사용하지 마십시오.

준비가 되면 를 클릭합니다 link:awx_automation.html["자세한 AWX/Tower 배치 절차를 보려면 여기를 클릭하십시오"] 또는 link:cli_automation.html["CLI 배포는 여기에서 확인할 수 있습니다"].
