---
settings:
  name: NetApp Solutions
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: NetApp 솔루션 설명서
    url: "/index.html"
  - section: ai
  - section: data-analytics
  - section: ehc
  - section: virtualization
  - section: containers
  - section: ent-apps-db
  - section: data-access
  - section: automation
  - title: FlexPod 솔루션
    url: https://docs.netapp.com/us-en/flexpod/
  - title: 레거시 NetApp HCI 솔루션
    url: https://docs.netapp.com/us-en/hci-solutions/
  - title: Change Log(로그 변경)
    url: "/change-log-display.html"
  - title: NetApp 솔루션 정보
    url: "/about.html"
  - title: 법적 고지
    url: "/reference_legal_notices.html"
homepage:
  tiles:
  - title: AI 최신 데이터 분석
    links:
    - title: 개요
      url: ai/index.html
    - title: 새로운 기능
      url: aimda-whatsnew.html
    - title: 비디오 및 데모
      url: aimda-videos.html
    - title: 블로그
      url: aimda-blogs.html
  - title: 엔터프라이즈 하이브리드 클라우드(EHC)
    links:
    - title: EHC 개요
      url: ehc/ehc-overview.html
    - title: 사용 사례
      url: ehc/ehc-use-cases.html
    - title: 지원되는 구성
      url: ehc/ehc-support-configs.html
    - title: 하이퍼스케일러 클라우드의 VMware Cloud
      url: ehc/ehc-hyperscalers.html
    - title: 하이퍼스케일러 지정 콘텐츠
      url: ehc/index.html
    - title: 블로그
      url: ehc-blogs.html
  - title: 가상화, 데스크톱 가상화 컨테이너
    links:
    - title: 새로운 기능
      url: hc-whatsnew.html
    - title: 비디오 및 데모
      url: hc-videos.html
    - title: 블로그
      url: hc-blogs.html
  - title: 엔터프라이즈 애플리케이션 데이터베이스
    links:
    - title: 새로운 기능
      url: appsdb-whatsnew.html
    - title: 비디오 및 데모
      url: appsdb-videos.html
    - title: 블로그
      url: appsdb-blogs.html
  - title: 솔루션 자동화
    links:
    - title: 새로운 기능
      url: automation-whatsnew.html
    - title: 비디오 및 데모
      url: automation-videos.html
    - title: 자동화 요청
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Automation]%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20%3Crequest_title%3E
  - title: FlexPod - NetApp Cisco 솔루션
    links:
    - title: FlexPod 솔루션 기술 콘텐츠
      url: https://docs.netapp.com/us-en/flexpod/
    - title: FlexPod 영업 페이지
      url: https://flexpod.com
    - title: 비디오 및 데모
      url: https://tv.netapp.com/search?q=flexpod
    - title: 블로그
      url: https://blog.netapp.com/tag/FlexPod/
  - title: 피드백
    links:
    - title: 새 솔루션 제안
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Request%20Solution]%0d%0a%0d%0aSolution%20Use%20Case:%20%0d%0aSolution%20Description:%20%0d%0aAdditional%20Comments:&title=Request%20Solution%20-%20%3Csolution%3E
    - title: 솔루션 피드백을 제공합니다
      url: https://github.com/NetAppDocs/netapp-solutions/issues/new?body=[Solution%20Feedback]%0d%0a%0d%0aSolution%20Name:%20%0d%0aSolution%20Feedback:%20%0d%0aAdditional%20Comments:&title=Solution%20Feedback%20-%20%3Csolution%3E
