---
sidebar: sidebar 
permalink: videos.html 
summary: NetApp 솔루션의 다양한 기능을 소개하는 비디오 및 데모 시리즈 
keywords: netapp, solutions, videos, demos 
---
= NetApp 솔루션: 비디오 및 데모
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./media/


[role="lead"]
NetApp 솔루션의 다양한 기능을 소개하는 비디오 및 데모를 소개합니다.

.인공 지능(AI) 및 최신 데이터 분석
[#ai%collapsible]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO["NetApp AI 솔루션"^]
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW["MLOps를 참조하십시오"^]


====
.엔터프라이즈 애플리케이션 및 데이터베이스
[#db%collapsible]
====
[underline]# * 오픈 소스 데이터베이스용 동영상 * #

[cols="5a, 5a, 5a"]
|===


 a| 
PostgreSQL 자동 구축, HA/DR 복제 설정, 페일오버, 재동기화

 a| 
 a| 

|===
[underline] # * AWS 및 FSx *#의 하이브리드 클라우드를 통한 Oracle 현대화에 대한 동영상

[cols="5a, 5a, 5a"]
|===


 a| 
1부 - 사용 사례 및 솔루션 아키텍처

 a| 
2a부 - 최대의 가용성과 자동화된 PDB 재배치를 사용하여 사내에서 AWS로 데이터베이스 마이그레이션

 a| 
파트 2b - SnapMirror를 통해 BlueXP 콘솔을 사용하여 사내에서 AWS로 데이터베이스 마이그레이션




 a| 
3부 - 자동화된 데이터베이스 HA/DR 복제 설정, 페일오버, 재동기화

 a| 
파트 4a - 복제된 대기 복제본에서 SnapCenter UI를 사용하여 개발/테스트용 데이터베이스 클론

 a| 
파트 4b - 데이터베이스 백업, 복원, SnapCenter UI를 사용한 클론




 a| 
파트 4c - BlueXP SaaS 애플리케이션 백업 및 복구를 통한 데이터베이스 백업 및 복구

 a| 
 a| 

|===
[underline]# * SQL Server 데이터베이스용 동영상 * #

[cols="5a, 5a, 5a"]
|===


 a| 
NetApp ONTAP용 Amazon FSx를 사용하여 AWS EC2에 SQL Server를 구축합니다

 a| 
스토리지 스냅샷을 사용하는 Oracle 멀티 테넌트 플러그형 데이터베이스 클론

video::krzMWjrrMb0[youtube,width=360] a| 
Ansible을 사용하여 FlexPod에 Oracle 19c RAC 구축 자동화

video::VcQMJIRzhoY[youtube,width=360]
|===
* 사례 연구 *

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study["Azure NetApp Files 기반 SAP"^]


====
.하이브리드 멀티 클라우드(HMC)
[#hmc%collapsible]
====
[underline]# * AWS/VMC * #에 대한 동영상

[cols="5a, 5a, 5a"]
|===


 a| 
iSCSI를 사용하는 FSx ONTAP가 있는 Windows 게스트 연결 스토리지

 a| 
NFS를 사용하는 FSx ONTAP가 있는 Linux 게스트 연결 스토리지

 a| 
NetApp ONTAP용 Amazon FSx를 통해 AWS에서 VMware Cloud를 TCO로 절감할 수 있습니다




 a| 
NetApp ONTAP용 Amazon FSx를 사용하는 AWS 보조 데이터 저장소의 VMware Cloud

 a| 
VMC를 위한 VMware HCX 구축 및 구성 설정

 a| 
VMC 및 FSxN용 VMware HCX와 함께 vMotion 마이그레이션 데모




 a| 
VMC 및 FSxN용 VMware HCX와 함께 콜드 마이그레이션 데모

 a| 
 a| 

|===
[underline]# * Azure/AVS * 용 동영상 #

[cols="5a, 5a, 5a"]
|===


 a| 
Azure VMware 솔루션 Azure NetApp Files의 데이터 저장소 보충 개요

 a| 
Cloud Volumes ONTAP, SnapCenter 및 Jetstream을 사용한 Azure VMware 솔루션 DR

 a| 
VMware HCX for AVS 및 ANF와 함께 콜드 마이그레이션 데모




 a| 
VMware HCX와 함께 AVS 및 ANF용 vMotion 데모

 a| 
VMware HCX for AVS 및 ANF와 함께 대량 마이그레이션 데모

 a| 

|===
====
.Red Hat OpenShift를 사용한 하이브리드 멀티 클라우드
[#rhhc%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Astra Control Service를 사용한 Rosa DR

 a| 
FSxN과 Astra Trident의 통합

 a| 
FSxN이 있는 Rosa에서 애플리케이션의 장애 복구 및 장애 복구




 a| 
Astra Control Center를 사용하여 DR을 수행합니다

link:https://www.netapp.tv/details/29504?mcid=35609780286441704190790628065560989458["NetAppTV를 시청해 보십시오"]
 a| 
 a| 

|===
====
.포함되었습니다
[#virtualization%collapsible]
====
* link:virtualization/vsphere_demos_videos.html["VMware 비디오 컬렉션"]


====
.컨테이너/Kubernetes
[#containers%collapsible]
====
* link:containers/anthos-with-netapp/a-w-n_videos_and_demos.html["NetApp 및 Google Anthos 비디오"]
* link:containers/tanzu_with_netapp/vtwn_videos_and_demos.html["NetApp with VMware Tanzu 비디오"]
* link:containers/devops_with_netapp/dwn_videos_and_demos.html["NetApp for DevOps 비디오"]
* link:containers/rh-os-n_videos_and_demos.html["NetApp 및 Red Hat OpenShift 비디오"]


====
.솔루션 자동화
[#automation%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Ansible을 사용하여 FlexPod에 Oracle 19c RAC 구축 자동화

video::VcQMJIRzhoY[youtube,width=360] a| 
 a| 

|===
====