---
sidebar: sidebar 
permalink: videos.html 
summary: NetApp 솔루션의 다양한 기능을 소개하는 비디오 및 데모 시리즈 
keywords: netapp, solutions, videos, demos 
---
= NetApp 솔루션: 비디오 및 데모
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 솔루션의 다양한 기능을 소개하는 비디오 및 데모를 소개합니다.

.인공 지능(AI) 및 최신 데이터 분석
[#ai%collapsible]
====
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7nSrRhuolRPYqvSlGLuTOAO["NetApp AI 솔루션"^]
* link:https://www.youtube.com/playlist?list=PLdXI3bZJEw7n1sWK-QGq4QMI1VBJS-ZZW["MLOps를 참조하십시오"^]


.DataOps Toolkit과 Astra Control Center 클라우드 버스트로 DevOps 가속
video::e87773e3-dc53-4195-83ed-b0d50100a788[panopto,width=360]
====
.엔터프라이즈 애플리케이션 및 데이터베이스
[#db%collapsible]
====
[underline]# * 오픈 소스 데이터베이스용 동영상 * #

.PostgreSQL 자동 구축, HA/DR 복제 설정, 페일오버, 재동기화
video::c381b887-8c8b-4d7d-8b0f-b0c0010c5c04[panopto,width=360]
[밑줄]# * Oracle 데이터베이스용 비디오 * #

.SnapCenter를 사용하여 ANF에서 Oracle 데이터베이스 백업, 복구 및 클론 생성
video::960fb370-c6e0-4406-b6d5-b110014130e8[panopto,width=360]
.NFS를 사용하여 Azure NetApp Files에 Oracle을 간편하게 자동으로 구현합니다
video::d1c859b6-e45a-44c7-8361-b10f012fc89b[panopto,width=360]
.iSCSI를 사용하여 Amazon FSx ONTAP에서 Oracle을 간편하고 자동으로 배포합니다
video::81e389a0-d9b8-495c-883b-b0d701710847[panopto,width=360]
.iSCSI를 사용하여 NetApp ASA에서 Oracle을 간편하고 자동으로 구현합니다
video::79095731-6b02-41d5-9fa1-b0c00100d055[panopto,width=360]
.1부 - AWS 및 FSx ONTAP에서 하이브리드 클라우드를 통한 Oracle 현대화
video::b1a7bb05-caea-44a0-bd9a-b01200f372e9[panopto,width=360]
.2a부 - 최대의 가용성과 자동화된 PDB 재배치를 사용하여 사내에서 AWS로 데이터베이스 마이그레이션
video::bb088a3e-bbfb-4927-bf44-b01200f38b17[panopto,width=360]
.파트 2b - SnapMirror를 통해 BlueXP 콘솔을 사용하여 사내에서 AWS로 데이터베이스 마이그레이션
video::c0df32f8-d6d3-4b79-b0bd-b01200f3a2e8[panopto,width=360]
.3부 - 자동화된 데이터베이스 HA/DR 복제 설정, 페일오버, 재동기화
video::5fd03759-a691-4007-9748-b01200f3b79c[panopto,width=360]
.파트 4a - 복제된 대기 복제본에서 SnapCenter UI를 사용하여 개발/테스트용 데이터베이스 클론
video::2f731d7c-0873-4a4d-8491-b01200f90a82[panopto,width=360]
.파트 4b - 데이터베이스 백업, 복원, SnapCenter UI를 사용한 클론
video::97790d62-ff19-40e0-9784-b01200f920ed[panopto,width=360]
.파트 4c - BlueXP SaaS 애플리케이션 백업 및 복구를 통한 데이터베이스 백업 및 복구
video::4b0fd212-7641-46b8-9e55-b01200f9383a[panopto,width=360]
[underline]# * SQL Server 데이터베이스용 동영상 * #

.Amazon FSx ONTAP을 사용하여 AWS EC2에 SQL Server를 배포합니다
video::27f28284-433d-4273-8748-b01200fb3cd7[panopto,width=360]
.스토리지 스냅샷을 사용하는 Oracle 멀티 테넌트 플러그형 데이터베이스 클론
video::krzMWjrrMb0[youtube,width=360]
.Ansible을 사용하여 FlexPod에 Oracle 19c RAC 구축 자동화
video::VcQMJIRzhoY[youtube,width=360]
* 사례 연구 *

* link:https://customers.netapp.com/en/sap-azure-netapp-files-case-study["Azure NetApp Files 기반 SAP"^]


====
.하이브리드 멀티 클라우드(HMC)
[#hmc%collapsible]
====
[underline]# * AWS/VMC * #에 대한 동영상

.iSCSI를 사용하는 FSx ONTAP가 있는 Windows 게스트 연결 스토리지
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.NFS를 사용하는 FSx ONTAP가 있는 Linux 게스트 연결 스토리지
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.Amazon FSx ONTAP를 통해 AWS 기반 VMware Cloud TCO 절감
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.Amazon FSx ONTAP을 지원하는 VMware Cloud on AWS 보조 데이터 저장소입니다
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.VMC를 위한 VMware HCX 구축 및 구성 설정
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.VMC 및 FSx ONTAP용 VMware HCX를 사용한 VMotion 마이그레이션 데모
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.VMC 및 FSx ONTAP용 VMware HCX를 사용한 콜드 마이그레이션 데모
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
[underline]# * Azure/AVS * 용 동영상 #

.Azure VMware 솔루션 Azure NetApp Files의 데이터 저장소 보충 개요
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
. Cloud Volumes ONTAP, SnapCenter 및 Jetstream을 사용한 Azure VMware 솔루션 DR
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.VMware HCX for AVS 및 ANF와 함께 콜드 마이그레이션 데모
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.VMware HCX와 함께 AVS 및 ANF용 vMotion 데모
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.VMware HCX for AVS 및 ANF와 함께 대량 마이그레이션 데모
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.Red Hat OpenShift를 사용한 하이브리드 멀티 클라우드
[#rhhc%collapsible]
====
.Amazon FSx ONTAP 스토리지를 사용하는 AWS(ROSA) 기반 Red Hat OpenShift Service의 애플리케이션을 위한 스냅샷/복원
video::36ecf505-5d1d-4e99-a6f8-b11c00341793[panopto,width=360]
.Astra Control Service를 사용한 Rosa DR
video::01dd455e-7f5a-421c-b501-b01200fa91fd[panopto,width=360]
.FSx ONTAP과 Trident의 통합
video::621ae20d-7567-4bbf-809d-b01200fa7a68[panopto,width=360]
.ROSA에서 FSx ONTAP를 사용하여 앱의 장애 조치 및 장애 조치
video::e9a07d79-42a1-4480-86be-b01200fa62f5[panopto,width=360]
[밑줄]# * Astra Control Center를 사용한 DR * #

link:https://www.netapp.tv/details/29504?mcid=35609780286441704190790628065560989458["NetAppTV를 시청해 보십시오"]

.Google Cloud Platform에 OpenShift Cluster 설치
video::4efc68f1-d37f-4cdd-874a-b09700e71da9[panopto,width=360]
.OpenShift 클러스터를 Astra Control Center로 가져오기
video::57b63822-6bf0-4d7b-b844-b09700eac6ac[panopto,width=360]
.Astra Control Center를 통한 데이터 보호
video::0cec0c90-4c6f-4018-9e4f-b09700eefb3a[panopto,width=360]
.Astra Control Center를 사용한 페일오버 페일백
video::1546191b-bc46-42eb-ac34-b0d60142c58d[panopto,width=360]
====
.포함되었습니다
[#virtualization%collapsible]
====
* link:vmware/vsphere_demos_videos.html["VMware 비디오 컬렉션"]


====
.컨테이너/Kubernetes
[#containers%collapsible]
====
* link:containers/a-w-n_videos_and_demos.html["NetApp 및 Google Anthos 비디오"]
* link:containers/vtwn_videos_and_demos.html["NetApp with VMware Tanzu 비디오"]
* link:containers/rh-os-n_videos_and_demos.html["NetApp 및 Red Hat OpenShift 비디오"]


====
.솔루션 자동화
[#automation%collapsible]
====
.Ansible을 사용하여 FlexPod에 Oracle 19c RAC 구축 자동화
video::VcQMJIRzhoY[youtube,width=360]
====