---
sidebar: sidebar 
permalink: ehc/azure-storage-options.html 
keywords: azure, netapp, anf, storage, options, nfs, supplemental, cvo 
summary: NetApp 스토리지는 게스트 연결 또는 보조 스토리지로 Azure VMware Service에 연결할 수 있습니다. 
---
= Azure 가상화 서비스: NetApp 스토리지 사용 옵션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp 스토리지는 게스트 연결 또는 보조 스토리지로 Azure VMware Service에 연결할 수 있습니다.



== Azure NetApp Files(ANF)를 보조 NFS 데이터 저장소로 사용합니다

NFS 데이터 저장소 지원은 vSphere의 스토리지 기능을 크게 확장해 주는 사내 구축 환경의 ESXi 버전 3에서 도입되었습니다.

vSphere on NFS는 강력한 성능과 안정성을 제공하기 때문에 사내 가상화 구축에 널리 채택되는 옵션입니다. 사내 데이터 센터에 NAS(Network-Attached Storage)가 많이 있는 경우 Azure NetApp 파일 데이터 저장소와 Azure에 Azure VMware 솔루션 SDDC를 구축하여 용량 및 성능 문제를 해결하는 것이 좋습니다.

Azure NetApp Files는 업계 최고의 고가용성 NetApp ONTAP 데이터 관리 소프트웨어를 기반으로 구축되었습니다. Microsoft Azure 서비스는 기본, 메인스트림, 전문 등 세 가지 범주로 분류됩니다. Azure NetApp Files는 특수 범주에 속하며 이미 여러 지역에 배포된 하드웨어를 통해 지원됩니다. Azure NetApp Files은 내장된 HA(고가용성)를 통해 대부분의 중단으로부터 데이터를 보호하고 99.99%의 가동 시간에 대한 업계 최고 수준의 SLA를 제공합니다.

보조 NFS 데이터 저장소인 ANF에 대한 자세한 내용은 다음을 참조하십시오.

* link:azure-native-overview.html["보조 NFS 데이터 저장소로서의 ANF: 개요"]
* link:azure-native-nfs-datastore-option.html["Azure의 보조 NFS 데이터 저장소 옵션"]




== 게스트 연결 스토리지로서의 Azure NetApp Files(ANF)

Azure NetApp Files는 Azure에서 워크로드와 애플리케이션을 쉽게 관리할 수 있도록 엔터프라이즈급 데이터 관리 기능과 스토리지를 제공합니다. 워크로드를 클라우드로 마이그레이션하여 성능 저하 없이 실행할 수 있습니다.

Azure NetApp Files이 장애물을 제거해주므로 모든 파일 기반 애플리케이션을 클라우드로 이전할 수 있습니다. 따라서 애플리케이션을 재설계할 필요가 없으며 애플리케이션용 영구 스토리지를 간편하게 확보할 수 있습니다.

이 서비스는 Microsoft Azure Portal을 통해 제공되므로 사용자는 Microsoft 기업 계약의 일부로 완벽하게 관리되는 서비스를 이용할 수 있습니다. Microsoft에서 관리하는 세계 최고 수준의 지원을 통해 안심하고 사용할 수 있습니다. 단일 솔루션으로 멀티프로토콜 워크로드를 빠르고 쉽게 추가할 수 있습니다. 레거시 환경에서도 Windows 및 Linux 파일 기반 애플리케이션을 모두 구축하여 배포할 수 있습니다.

자세한 내용은 를 link:azure-guest.html#anf["게스트 연결 스토리지로서의 ANF"]참조하십시오.



== CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다

CVO(Cloud Volumes ONTAP)는 NetApp의 ONTAP 스토리지 소프트웨어를 기반으로 구축되는 업계 최고의 클라우드 데이터 관리 솔루션으로, AWS(Amazon Web Services), Microsoft Azure 및 GCP(Google Cloud Platform)에서 기본적으로 제공됩니다.

ONTAP의 소프트웨어 정의 버전이며 클라우드 네이티브 스토리지를 사용합니다. 따라서 클라우드와 사내에서 동일한 스토리지 소프트웨어를 사용할 수 있으므로 데이터를 관리하는 새로운 방법을 통해 IT 직원을 재교육할 필요가 없습니다.

CVO를 사용하면 데이터를 에지에서 데이터 센터, 클라우드로 원활하게 이동하고 다시 가져올 수 있습니다. 또한 단일 창 관리 콘솔인 NetApp Cloud Manager를 사용하여 하이브리드 클라우드를 통합할 수 있습니다.

설계상 CVO는 최고 성능과 고급 데이터 관리 기능을 제공하여 클라우드에서 가장 까다로운 애플리케이션도 충족합니다

자세한 내용은 를 link:azure-guest.html#azure-cvo["CVO를 게스트 연결 스토리지로 사용"]참조하십시오.
