---
sidebar: sidebar 
permalink: ehc/ehc-datastore-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= 퍼블릭 클라우드 공급자를 위한 NetApp 스토리지 옵션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
세 가지 주요 하이퍼 스케일러의 스토리지로서의 NetApp 옵션에 대해 알아보십시오.

[role="tabbed-block"]
====
.AWS/VMC
--
AWS는 다음과 같은 구성에서 NetApp 스토리지를 지원합니다.

* FSX ONTAP를 게스트 연결 스토리지로 사용합니다
* CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다
* FSX ONTAP는 보조 NFS 데이터 저장소입니다


자세한 내용을 확인하십시오 link:aws-guest.html["VMC에 대한 게스트 연결 스토리지 옵션"]. 자세한 내용을 확인하십시오 link:aws-native-nfs-datastore-option.html["VMC에 대한 보조 NFS 데이터 저장소 옵션"].

--
.Azure/AVS
--
Azure는 다음과 같은 구성에서 NetApp 스토리지를 지원합니다.

* 게스트 연결 스토리지로서의 Azure NetApp Files(ANF)
* CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다
* Azure NetApp Files(ANF)를 보조 NFS 데이터 저장소로 사용합니다


자세한 내용을 확인하십시오 link:azure-guest.html["AVS용 게스트 연결 스토리지 옵션"]. 자세한 내용을 확인하십시오 link:azure-native-nfs-datastore-option.html["AVS용 보조 NFS 데이터 저장소 옵션"].

--
.GCP/GCVE
--
Google Cloud는 다음과 같은 구성에서 NetApp 스토리지를 지원합니다.

* CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다
* 게스트 연결 스토리지로 사용되는 Google Cloud NetApp 볼륨(NetApp 볼륨
* Google Cloud NetApp 볼륨(NetApp 볼륨)을 보조 NFS 데이터 저장소로 사용할 수 있습니다


세부 정보를 link:gcp-guest.html["GCVE에 대한 게스트 연결 저장소 옵션"]봅니다. 세부 정보를 link:gcp-ncvs-datastore.html["GCVE용 보조 NFS 데이터 저장소 옵션"]봅니다.

또는 에 대한 자세한 정보 link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Google Cloud VMware Engine을 위한 Google Cloud NetApp 볼륨 데이터 저장소 지원(NetApp 블로그)"^]link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["Google Cloud NetApp Volumes를 Google Cloud VMware Engine용 데이터 저장소로 사용하는 방법(Google 블로그)"^]

--
====