---
sidebar: sidebar 
permalink: ehc/ehc-summary.html 
keywords: NetApp Solutions, hybrid, multi-cloud, enterprise hybrid cloud, hyperscalers, vmware 
summary:  
---
= 요약 및 결론: NetApp 하이브리드 멀티 클라우드를 VMware와 함께 사용해야 하는 이유
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
주요 하이퍼스케일러를 위한 VMware 솔루션과 NetApp Cloud Volumes는 하이브리드 클라우드를 활용하려는 조직에 최고의 잠재력을 제공합니다. 이 섹션의 나머지 부분에서는 NetApp Cloud Volumes 통합을 통해 진정한 하이브리드 멀티 클라우드 기능을 실현하는 사용 사례를 소개합니다.



== 사용 사례 #1: 스토리지 최적화

RVtools 출력을 사용하여 사이징 작업을 수행할 때 마력(vCPU/vmem) 스케일이 스토리지와 평행하다는 것이 항상 명백합니다. 스토리지 공간에 필요한 드라이브의 크기가 마력을 훨씬 넘어서는 상황에 처하게 되는 경우가 많습니다.

NetApp Cloud Volumes를 통합하면 간단한 마이그레이션 방식을 통해 vSphere 기반 클라우드 솔루션을 실현할 수 있습니다. 플랫폼 재구축 또는 IP 변경 없이 아키텍처 변경 없이 모든 작업을 수행할 수 있습니다. 또한 이러한 최적화를 통해 vSphere에서 호스트 수를 최소한으로 유지하면서 스토리지 설치 공간을 확장할 수 있으며, 스토리지 계층, 보안 또는 사용 가능한 파일은 변경되지 않습니다. 따라서 구축을 최적화하고 전체 TCO를 35~45% 절감할 수 있습니다. 또한 이러한 통합을 통해 스토리지를 따뜻한 스토리지에서 운영 수준의 성능으로 몇 초 이내에 확장할 수 있습니다.



== 사용 사례 2: 클라우드 마이그레이션

조직에서는 향후 임대 만료, 자본 지출(capex) 지출에서 운영 비용(opex) 지출로 전환해야 하는 재무 지침, 모든 것을 클라우드로 이동하는 하향식 등 다양한 이유로 애플리케이션을 사내 데이터 센터에서 퍼블릭 클라우드로 마이그레이션해야 한다는 압박을 받고 있습니다.

속도가 중요한 경우에는 클라우드의 특정 IaaS 플랫폼에 맞게 애플리케이션을 재구성하고 리팩토링하는 작업이 느리고 비용이 많이 들며 종종 몇 달이 소요되기 때문에 간소화된 마이그레이션 방식만 실현 가능합니다. NetApp Cloud Volumes를 게스트 연결 스토리지를 위한 대역폭 효율적인 SnapMirror 복제(애플리케이션 정합성이 보장된 Snapshot 복사본 및 HCX와 함께 RDM 포함, 클라우드 특정 마이그레이션(예 Azure 마이그레이션) 또는 타사 제품으로 VM 복제), 시간이 많이 소요되는 I/O 필터 메커니즘에 의존하는 것보다 훨씬 더 쉽게 전환할 수 있습니다.



== 사용 사례 3: 데이터 센터 확장

데이터 센터가 특정 시기별 수요 급증 또는 지속적인 유기적 성장으로 인해 용량 제한에 도달할 경우, NetApp Cloud Volumes와 함께 클라우드 호스팅 VMware로 손쉽게 전환할 수 있습니다. NetApp Cloud Volumes를 활용하면 가용성 영역 및 동적 확장 기능에 걸쳐 고가용성을 제공하여 스토리지를 쉽게 생성, 복제 및 확장할 수 있습니다. NetApp Cloud Volumes를 활용하면 확장 클러스터의 필요성을 극복하여 호스트 클러스터 용량을 최소화할 수 있습니다.



== 사용 사례 4: 클라우드로 재해 복구

기존 방식에서는 재해가 발생할 경우 클라우드로 복제된 VM을 복원하기 전에 클라우드의 자체 하이퍼바이저 플랫폼으로 변환해야 합니다. 위기 상황에서 처리할 작업은 아닙니다.

퍼블릭 클라우드 가상화 솔루션과 함께 SnapCenter 및 온프레미스에서 SnapMirror 복제를 사용하여 게스트 연결 스토리지에 NetApp Cloud Volumes를 사용함으로써 재해 복구를 위한 더 나은 접근법을 고안하여, 클라우드 관련 복구 툴과 함께 완전히 일관된 VMware SDDC 인프라에서 VM 복제본을 복구할 수 있습니다(예 Azure Site Recovery) 또는 Veeam과 같은 타사 툴을 사용할 수 있습니다. 또한, 이 접근 방식을 통해 랜섬웨어에서 신속하게 재해 복구 훈련 및 복구를 수행할 수 있습니다. 또한 필요에 따라 호스트를 추가하여 테스트 또는 재해 발생 시 전체 운영 환경으로 확장할 수 있습니다.



== 사용 사례 5: 애플리케이션 현대화

퍼블릭 클라우드에 애플리케이션이 포함된 후에는 강력한 수백 가지 클라우드 서비스를 활용하여 애플리케이션을 현대화하고 확장하려고 할 것입니다. NetApp Cloud Volumes를 사용할 경우 애플리케이션 데이터가 vSAN에 종속되지 않고 Kubernetes를 포함한 광범위한 사용 사례에서 데이터를 이동할 수 있기 때문에 현대화는 쉬운 프로세스입니다.



== 결론

All-Cloud와 하이브리드 클라우드 중 무엇을 목표로 하든 NetApp Cloud Volumes는 파일 서비스 및 블록 프로토콜과 함께 애플리케이션 워크로드를 구축 및 관리하는 데 탁월한 옵션을 제공하는 한편, 데이터 요구사항을 애플리케이션 계층에 원활하게 구현하여 TCO를 절감합니다.

어떤 사용 사례에서든 즐겨 사용하는 클라우드/하이퍼스케일러와 NetApp Cloud Volumes를 함께 사용하여 사내 및 멀티 클라우드 전체의 클라우드 이점, 일관된 인프라 및 운영을 빠르게 실현하고, 워크로드의 양방향 이동성을 제공하며, 엔터프라이즈급 용량과 성능을 실현할 수 있습니다.

스토리지를 연결하는 데 사용되는 것과 동일한 친숙한 프로세스와 절차입니다. 이는 새로운 이름으로 변경된 데이터의 위치일 뿐입니다. 도구와 프로세스는 그대로 유지되며 NetApp Cloud Volumes는 전체 구축을 최적화하는 데 도움이 됩니다.
