---
sidebar: sidebar 
permalink: ehc/ehc-use-cases.html 
keywords: NetApp Solutions, ehc, enterprise hybrid cloud, use case, hyperscalers, vmware 
summary:  
---
= VMware를 사용하는 NetApp 하이브리드 멀티 클라우드의 사용 사례
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
하이브리드 클라우드 또는 클라우드 우선 구축을 계획할 때 IT 조직에 중요한 사용 사례에 대한 개요입니다.



== 보편적인 사용 사례

사용 사례는 다음과 같습니다.

* 재해 복구,
* 데이터 센터 유지 관리 중에 워크로드를 호스팅 * 로컬 데이터 센터에서 프로비저닝되는 것 이상의 추가 리소스가 필요한 빠른 증가,
* VMware 사이트 확장,
* 클라우드로 신속하게 마이그레이션,
* 개발/테스트, 및
* 클라우드 보완 기술을 활용하여 앱 현대화


이 설명서 전체에서 VMware 활용 사례를 사용하여 클라우드 워크로드 참조를 자세히 설명합니다. 이러한 사용 사례는 다음과 같습니다.

* 보호(재해 복구 및 백업/복원 모두 포함)
* 마이그레이션
* 확장




=== IT의 여정

대부분의 조직은 혁신과 현대화를 향한 여정을 진행 중입니다. 이 프로세스의 일환으로 기업들은 기존 VMware 투자를 활용하는 동시에 클라우드의 이점을 활용하고 마이그레이션 프로세스를 최대한 원활하게 만드는 방법을 모색하고 있습니다. 이 접근 방식은 데이터가 이미 클라우드에 있기 때문에 현대화에 대한 노력을 매우 쉽게 할 수 있습니다.

이 시나리오에 대한 가장 쉬운 답은 각 하이퍼스케일러의 VMware 오퍼링입니다. NetApp ® Cloud Volumes와 마찬가지로 VMware는 사내 VMware 환경을 클라우드로 이동 또는 확장하는 방법을 제공하므로 클라우드에서 워크로드를 기본적으로 실행하면서 기존 온프레미스 자산, 기술 및 툴을 유지할 수 있습니다. 따라서 서비스 중단이나 IP 변경이 필요하지 않고 IT 팀이 기존 기술과 툴을 사용하여 사내에서 작업하는 방식을 운영할 수 있으므로 위험이 감소합니다. 따라서 클라우드 마이그레이션을 가속화하고 하이브리드 멀티 클라우드 아키텍처로의 전환이 한층 원활해질 수 있습니다.



=== 보충 NFS 스토리지 옵션의 중요성 이해

클라우드에 구축된 VMware는 모든 고객에게 고유한 하이브리드 기능을 제공하지만, 제한된 보조 NFS 스토리지 옵션으로 스토리지 집약적인 워크로드를 사용하는 조직에는 유용성이 제한됩니다. 스토리지는 호스트에 직접 연결되므로 스토리지를 확장하는 유일한 방법은 호스트를 추가하는 것입니다. 이렇게 하면 스토리지 집약적인 워크로드의 비용이 35-40% 이상 증가할 수 있습니다. 이러한 워크로드는 추가 마력이 아닌 추가 스토리지만 필요합니다. 하지만 이는 추가 호스트에 대한 비용을 지불하는 것을 의미합니다.

다음 시나리오를 생각해 봅시다.

고객은 CPU와 메모리에 대해 5개의 호스트만 필요로 하지만 스토리지 요구 사항이 많으므로 스토리지 요구 사항을 충족하기 위해 12개의 호스트가 필요합니다. 이 요구사항은 스토리지를 증가하기만 하면 되는 추가 마력을 구매해야 하는 만큼 재무 규모를 넘어주는 결과를 제공합니다.

클라우드 도입 및 마이그레이션을 계획할 때는 항상 최상의 접근 방식을 평가하고 총 투자 비용을 절감하는 가장 쉬운 방법을 찾는 것이 중요합니다. 모든 애플리케이션 마이그레이션의 가장 일반적이고 쉬운 방법은 가상 머신(VM) 또는 데이터 변환이 없는 재호스팅(리프트 및 변속이라고도 함)입니다. NetApp Cloud Volumes를 VMware SDDC(소프트웨어 정의 데이터 센터)와 함께 사용하는 동시에 vSAN을 보완하는 것은 쉬운 전환 옵션을 제공합니다.
