---
sidebar: sidebar 
permalink: ehc/ehc-datastore-intro.html 
keywords: NetApp Solutions, amazon, vmc, aws, microsoft azure, avs, azure, google cloud, gcp, gcve, vmware managed cloud, enterprise, hybrid, cloud, cloud volumes ontap, cvo, datastore, fsx, fsx ontap 
summary:  
---
= 퍼블릭 클라우드 공급자를 위한 NetApp 스토리지 옵션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
세 가지 주요 하이퍼 스케일러의 스토리지로서의 NetApp 옵션에 대해 알아보십시오.

[role="tabbed-block"]
====
.AWS/VMC
--
AWS는 다음과 같은 구성에서 NetApp 스토리지를 지원합니다.

* FSX ONTAP를 게스트 연결 스토리지로 사용합니다
* CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다
* FSX ONTAP는 보조 NFS 데이터 저장소입니다


자세한 내용을 확인하십시오 link:aws/aws-guest.html["VMC에 대한 게스트 연결 스토리지 옵션"]. 자세한 내용을 확인하십시오 link:aws/aws-native-nfs-datastore-option.html["VMC에 대한 보조 NFS 데이터 저장소 옵션"].

--
.Azure/AVS
--
Azure는 다음과 같은 구성에서 NetApp 스토리지를 지원합니다.

* 게스트 연결 스토리지로서의 Azure NetApp Files(ANF)
* CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다
* Azure NetApp Files(ANF)를 보조 NFS 데이터 저장소 ^1^로 추가


자세한 내용을 확인하십시오 link:azure/azure-guest.html["AVS용 게스트 연결 스토리지 옵션"]. 자세한 내용을 확인하십시오 link:azure/azure-native-nfs-datastore-option.html["AVS용 보조 NFS 데이터 저장소 옵션"].


NOTE: AVS용 보조 NFS 데이터 저장소로서 1-ANF가 현재 Public Preview에 있습니다. 자세한 내용을 확인하십시오 https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?branch=main&tabs=azure-portal["여기"].

--
.GCP/GCVE
--
Google Cloud는 다음과 같은 구성에서 NetApp 스토리지를 지원합니다.

* CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다
* CVS(Cloud Volumes Service)를 게스트 연결 스토리지로 사용합니다
* Cloud Volumes Service(CVS)를 보조 NFS 데이터 저장소 ^1^으로 사용


자세한 내용을 확인하십시오 link:gcp/gcp-guest.html["GCVE에 대한 게스트 연결 저장소 옵션"].

에 대해 자세히 알아보십시오 link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/["CVS(Cloud Volumes Service)를 보조 NFS 데이터 저장소로 사용 ^1"^].


NOTE: 1-현재 비공개 미리보기에 있습니다

--
====