---
sidebar: sidebar 
permalink: ehc/ncvs-gc-basics-of-nas-protocols.html 
keywords: nas, basics, gcp, nfs, smb 
summary: NAS 프로토콜은 여러 클라이언트의 네트워크 상에서 Cloud Volumes Service on GCP와 같은 스토리지 시스템의 동일한 데이터에 액세스하는 방법입니다. NFS 및 SMB는 정의된 NAS 프로토콜로, Cloud Volumes Service이 서버 역할을 하는 클라이언트/서버 단위로 작동합니다. 
---
= NAS 프로토콜의 기본 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NAS 프로토콜은 여러 클라이언트의 네트워크 상에서 Cloud Volumes Service on GCP와 같은 스토리지 시스템의 동일한 데이터에 액세스하는 방법입니다. NFS 및 SMB는 정의된 NAS 프로토콜로, Cloud Volumes Service이 서버 역할을 하는 클라이언트/서버 단위로 작동합니다. 클라이언트는 서버에 액세스, 읽기 및 쓰기 요청을 보내고, 서버는 파일에 대한 잠금 메커니즘을 조정하고, 사용 권한을 저장하고, ID 및 인증 요청을 처리할 책임이 있습니다.

예를 들어, NAS 클라이언트가 폴더에 새 파일을 생성하려는 경우 다음과 같은 일반 프로세스가 적용됩니다.

. 클라이언트가 서버에 디렉터리(권한, 소유자, 그룹, 파일 ID, 사용 가능한 공간, 등). 서버는 요청한 클라이언트 및 사용자에게 상위 폴더에 대한 필요한 권한이 있는 경우 해당 정보로 응답합니다.
. 디렉토리의 사용 권한이 액세스를 허용할 경우 클라이언트는 생성 중인 파일 이름이 파일 시스템에 이미 있는지 서버에 묻습니다. 파일 이름이 이미 사용 중인 경우 생성이 실패합니다. 파일 이름이 없는 경우 서버는 클라이언트가 계속 진행할 수 있음을 알려 줍니다.
. 클라이언트는 디렉토리 핸들 및 파일 이름으로 파일을 만들기 위해 서버에 대한 호출을 수행하고 액세스 및 수정 시간을 설정합니다. 서버에서 파일에 고유한 파일 ID를 발급하여 동일한 파일 ID로 다른 파일이 생성되지 않도록 합니다.
. 클라이언트는 쓰기 작업 전에 파일 특성을 확인하는 호출을 전송합니다. 권한이 허용하는 경우 클라이언트는 새 파일을 씁니다. 프로토콜/응용 프로그램에서 잠금을 사용하는 경우 클라이언트는 다른 클라이언트가 잠금 상태에서 파일에 액세스하지 못하도록 서버에 잠금을 요청합니다. 잠금 상태에서는 데이터 손상을 방지할 수 있습니다.

