---
sidebar: sidebar 
permalink: vmw-sc/sc-overview.html 
keywords: NetApp Solutions, vmware, sovereign cloud 
summary:  
---
= VMware Sovereign Cloud 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
주권의 개념은 국가 및 주 정부 등 매우 민감한 데이터를 처리하고 유지하는 많은 주체와 금융 및 의료 등 고도로 규제되는 산업 분야에서 클라우드 컴퓨팅의 필수 구성 요소로 부상하고 있습니다. 또한 디지털 경제 능력을 확대하고 클라우드 서비스에 대한 다국적 기업의 의존도를 줄이고자 합니다.



== VMware Sovereign 클라우드 이니셔티브

VMware는 주권 클라우드를 다음과 같이 정의합니다.

* 민간 및 공공 부문 조직 모두에 대한 중요 데이터(예: 국가 데이터, 기업 데이터 및 개인 데이터)의 가치를 보호하고 잠금 해제합니다
* 디지털 경제를 위한 국가적 역량을 제공합니다
* 감사된 보안 제어를 통해 데이터를 보호합니다
* 데이터 개인정보 보호법을 준수하도록 보장합니다
* 데이터 상주 및 데이터 주권을 모두 관할하는 완벽하게 제어함으로써 데이터 제어 개선




== 신뢰할 수 있는 VMware Sovereign Cloud Service Provider와 협력

성공을 보장하기 위해 조직은 자신들이 신뢰하는 파트너들과 함께 공인하고 자율적인 주권 클라우드 플랫폼을 호스팅할 수 있는 역량이 있어야 합니다. VMware Sovereign Cloud 이니셔티브 내에서 인정을 받은 VMware 클라우드 공급업체는 VMware Sovereign Cloud 프레임워크에 설명된 주요 원칙과 모범 사례를 구현하는 최신 소프트웨어 정의 아키텍처를 기반으로 클라우드 솔루션을 설계하고 운영하기 위해 노력하고 있습니다.

* * 데이터 주권 및 관할권 관리 * – 모든 데이터는 해당 데이터가 수집된 국가 국가의 배타적 통제 및 권한을 따릅니다. 작업은 관할 지역 내에서 완전히 관리됩니다
* * 데이터 액세스 및 무결성 * – 클라우드 인프라는 탄력적이며 관할 지역 내의 두 데이터 센터 위치에서 사용할 수 있으며 보안 및 개인 연결 옵션을 사용할 수 있습니다.
* * 데이터 보안 및 규정 준수 * – 정보 보안 관리 시스템 제어는 업계에서 인정하는 글로벌(또는 지역) 표준에 따라 인증되고 정기적으로 감사를 받습니다.
* * 데이터 독립성 및 이동성 * – 벤더의 클라우드 종속을 방지하고 애플리케이션 이동성과 독립성을 지원하는 최신 애플리케이션 아키텍처 지원


VMware에 대한 자세한 내용은 다음 사이트를 참조하십시오.

* link:https://www.vmware.com/content/dam/digitalmarketing/vmware/en/pdf/docs/vmw-sovereign-cloud-solution-brief-customer.pdf["VMware Sovereign Cloud 개요"]
* link:https://www.vmware.com/topics/glossary/content/sovereign-cloud.html["VMware Sovereign Cloud란 무엇입니까?"]
* link:https://blogs.vmware.com/cloud/2021/10/06/vmware-sovereign-cloud/["새로운 VMware Sovereign Cloud Initiative를 소개합니다"]
* link:https://www.vmware.com/content/dam/learn/en/amer/fy22/pdf/1173457_Sovereign_Cloud_Technical_Whitepaper_V3.pdf["VMware Sovereign 클라우드 기술 백서"]

