---
sidebar: sidebar 
permalink: containers/a-w-n_overview_storint.html 
keywords: Astra, Astra Control Center, Trident, Astra Trident, persistent storage 
summary: NetApp은 Anthos와 같은 컨테이너 기반 환경에서 고객이 영구 데이터를 오케스트레이션하고 관리하도록 지원하는 다양한 제품을 제공합니다. 
---
= NetApp 스토리지 통합 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Anthos Ready 스토리지 파트너 프로그램.

Google Cloud는 Anthos Ready 스토리지 파트너 프로그램을 통해 Anthos의 새 릴리스와 파트너 스토리지 통합의 업데이트된 검증을 주기적으로 요청합니다. 현재 검증된 스토리지 솔루션, CSI 드라이버, 사용 가능한 기능 및 지원되는 Anthos의 버전 목록을 찾을 수 있습니다 https://cloud.google.com/anthos/docs/resources/partner-storage["여기"^].

NetApp은 Astra Trident CSI를 준수하는 스토리지 오케스트레이터와 Anthos 버전에서 ONTAP 스토리지 시스템을 검증하라는 요청을 포함하여 분기별로 정기적인 규정 준수를 유지해 왔습니다.

다음 표에는 Anthos Ready 스토리지 파트너 프로그램의 일부로 NetApp 및 NetApp 파트너 엔지니어가 NetApp Astra Trident CSI 드라이버 및 기능 세트를 검증하기 위해 테스트한 Anthos 버전이 포함되어 있습니다.

|===


| 배포 유형 | 버전 | 스토리지 시스템 | Astra Trident 버전 | 프로토콜 | 피처 


| VMware | 1.28 | ONTAP 9.12.1 | 24.02 | NAS | MultiWriter, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.28 | ONTAP 9.12.1 | 24.02 | 산 | 원시 블록, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.15 | ONTAP 9.12.1 | 23.04 | NAS | MultiWriter, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.15 | ONTAP 9.12.1 | 23.04 | 산 | 원시 블록, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | NAS | MultiWriter, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.14 | ONTAP 9.12.1 | 23.01 | 산 | 원시 블록, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | NAS | MultiWriter, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.13 | ONTAP 9.12.1 | 22.10 | 산 | 원시 블록, 볼륨 확장, 스냅샷, PVCDataSource 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | NAS | MultiWriter, 볼륨 확장, 스냅샷 


| VMware | 1.11 | ONTAP 9.9.1 | 22.04 | 산 | 물리적 블록, 볼륨 확장, 스냅샷 


| VMware | 1.11 | 요소 12.3 | 22.04 | 산 | 물리적 블록, 볼륨 확장, 스냅샷 


| 베어 메탈 | 1.10 | ONTAP 9.8 | 22.01 | NAS | MultiWriter, 볼륨 확장, 스냅샷 


| 베어 메탈 | 1.10 | ONTAP 9.8 | 22.01 | 산 | 물리적 블록, 볼륨 확장, 스냅샷 
|===


== NetApp 스토리지 통합

NetApp은 Anthos와 같은 컨테이너 기반 환경에서 영구 데이터를 오케스트레이션하고 관리하는 데 도움이 되는 다양한 제품을 제공합니다.

NetApp Astra Trident는 Anthos를 비롯한 컨테이너 및 Kubernetes 배포를 위한 완전히 지원되는 오픈 소스 스토리지 오케스트레이터입니다. 자세한 내용은 Astra Trident 웹 사이트를 참조하십시오 https://docs.netapp.com/us-en/trident/index.html["여기"].

다음 페이지는 NetApp 솔루션의 Anthos에서 애플리케이션 및 영구 스토리지 관리를 위해 검증된 NetApp 제품에 대한 추가 정보를 제공합니다.
