---
sidebar: sidebar 
permalink: containers/a-w-n_LB_SeeSaw.html 
summary: 이 페이지에서는 시소 로드 밸런서에 대한 설치 및 구성 지침을 자세히 설명합니다. 
keywords: Anthos, GKE, Kubernetes, SeeSaw, LoadBalancer 
---
= 시소 부하 밸런서 설치
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 페이지에는 시소 관리 로드 밸런서에 대한 설치 및 구성 지침이 나와 있습니다.

seesaw는 VMware 환경의 Anthos 클러스터에 설치된 버전 1.6에서 1.10에 이르는 기본 관리형 네트워크 로드 밸런싱 장치입니다.



== 시소 로드 밸런서 설치

시소 로드 밸런서는 VMware의 Anthos Cluster와 완벽하게 통합되며 관리 및 사용자 클러스터 설정의 일부로 자동 배포를 수행합니다. 클러스터.YAML 구성 파일에는 로드 밸런서 정보를 제공하도록 수정해야 하는 텍스트 블록이 있으며, 클러스터 배포 전에 내장된 gkectl 도구를 사용하여 로드 밸런서를 배포하기 위한 추가 단계가 있습니다.


NOTE: 시소 로드 밸런서는 HA 또는 비 HA 모드로 구축할 수 있습니다. 이 검증을 위해 시소 로드 밸런서가 비 HA 모드로 배포되었으며, 이 모드가 기본 설정입니다. 운영을 위해 HA 구성에서 시소를 구축하여 내결함성과 안정성을 높이는 것이 좋습니다.



== Anthos와의 통합

각 구성 파일에는 관리 클러스터에 대한 섹션과 온프레미스 Anthos가 관리하도록 부하 분산 장치를 구성하기 위해 배포하기로 선택한 각 사용자 클러스터에 대한 섹션이 있습니다.

다음 텍스트는 GKE-Admin 클러스터에 대한 파티션 구성의 샘플입니다. 주석 및 수정이 필요한 값은 아래 굵은 텍스트로 표시됩니다.

[listing, subs="+quotes,+verbatim"]
----
*loadBalancer:*
  # (Required) The VIPs to use for load balancing
  *vips:*
    # Used to connect to the Kubernetes API
    *controlPlaneVIP: "10.61.181.230"*
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    # # addonsVIP: ""
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" or "ManualLB". Uncomment
  # the corresponding field below to provide the detailed spec
  *kind: Seesaw*
  # # (Required when using "ManualLB" kind) Specify pre-defined nodeports
  # manualLB:
  #   # NodePort for ingress service's http (only needed for user cluster)
  #   ingressHTTPNodePort: 0
  #   # NodePort for ingress service's https (only needed for user cluster)
  #   ingressHTTPSNodePort: 0
  #   # NodePort for control plane service
  #   controlPlaneNodePort: 30968
  #   # NodePort for addon service (only needed for admin cluster)
  #   addonsNodePort: 31405
  # # (Required when using "F5BigIP" kind) Specify the already-existing partition and
  # # credentials
  # f5BigIP:
  #   address:
  #   credentials:
  #     username:
  #     password:
  #   partition:
  #   # # (Optional) Specify a pool name if using SNAT
  #   # snatPoolName: ""
  # (Required when using "Seesaw" kind) Specify the Seesaw configs
  *seesaw:*
  # (Required) The absolute or relative path to the yaml file to use for IP allocation
  #  for LB VMs. Must contain one or two IPs.
  *ipBlockFilePath: "admin-seesaw-block.yaml"*
  #   (Required) The Virtual Router IDentifier of VRRP for the Seesaw group. Must
  #   be between 1-255 and unique in a VLAN.
    *vrid: 100*
  #   (Required) The IP announced by the master of Seesaw group
    *masterIP: "10.61.181.236"*
  #   (Required) The number CPUs per machine
    *cpus: 1*
  #   (Required) Memory size in MB per machine
    *memoryMB: 2048*
  #   (Optional) Network that the LB interface of Seesaw runs in (default: cluster
  #   network)
    *vCenter:*
  #   vSphere network name
      *networkName: VM_Network*
  #   (Optional) Run two LB VMs to achieve high availability (default: false)
    *enableHA: false*
----
시소 로드 밸런서는 또한 각 클러스터 배포에 대해 제공해야 하는 별도의 정적 '시소 블록.YAML' 파일을 가지고 있습니다. 이 파일은 cluster.yAML 배포 파일과 관련된 동일한 디렉토리에 있어야 하며, 그렇지 않으면 위의 섹션에서 전체 경로를 지정해야 합니다.

관리자-시소-블록.YAML 파일의 예는 다음과 같습니다.

[listing, subs="+quotes,+verbatim"]
----
blocks:
  - netmask: "255.255.255.0"
    gateway: "10.63.172.1"
    ips:
    - ip: "10.63.172.152"
      hostname: "admin-seesaw-vm"
----

NOTE: 이 파일은 로드 밸런서가 기본 클러스터에 제공하는 네트워크의 게이트웨이와 넷마스크를 제공하고, 로드 밸런서를 실행하기 위해 구축된 가상 머신의 관리 IP 및 호스트 이름을 제공합니다.
