---
sidebar: sidebar 
permalink: containers/bmanthos_introduction.html 
keywords: WP-7337, Google Cloud, Cloud Volumes ONTAP, Cloud Volume Service, hypervisor, Kubernetes 
summary: NetApp과 Google Cloud는 수년간 긴밀한 관계를 유지하고 있었으며, NetApp은 Cloud Volumes ONTAP과 Cloud Volumes Service를 통해 Google Cloud에 클라우드 데이터 서비스를 최초로 도입했습니다. 그런 다음 NetApp HCI 플랫폼을 검증하여 VMware vSphere에 구축된 하이퍼바이저 기반 하이브리드 멀티 클라우드 Kubernetes 솔루션인 Google Cloud Anthos On-Premises와 함께 사용할 수 있도록 했습니다. NetApp은 그런 다음 NetApp Trident, ONTAP 및 NFS 프로토콜을 위한 Anthos Ready 자격을 통과해 컨테이너에 동적 영구 스토리지를 제공했습니다. 
---
= WP-7337: 베어 메탈(Bare Metal)의 Anthos
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


NetApp의 Alan Cowles와 Nikhil M Kulkarni입니다

NetApp과 Google Cloud는 수년간 긴밀한 관계를 유지하고 있었으며, NetApp은 Cloud Volumes ONTAP 및 Cloud Volumes Service를 통해 Google Cloud용 클라우드 데이터 서비스를 최초로 도입했습니다. 그런 다음 NetApp HCI 플랫폼을 검증하여 VMware vSphere에 구축된 하이퍼바이저 기반 하이브리드 멀티 클라우드 Kubernetes 솔루션인 Google Cloud Anthos On-Premises와 함께 사용할 수 있도록 했습니다. NetApp은 그런 다음 NetApp Trident, ONTAP 및 NFS 프로토콜을 위한 Anthos Ready 자격을 통과해 컨테이너에 동적 영구 스토리지를 제공했습니다.

Anthos는 이제 고객 환경의 베어 메탈 서버에 직접 설치할 수 있으며, 이를 통해 고객은 하이퍼바이저가 없는 로컬 데이터 센터로 Google Cloud를 확장할 수 있는 추가 옵션을 추가할 수 있습니다. 또한 NetApp ONTAP 스토리지 운영 체제 및 NetApp Trident의 기능을 활용하여 컨테이너용 영구 스토리지를 통합하여 플랫폼의 기능을 확장할 수 있습니다.

이러한 결합을 통해 서버, 스토리지 및 네트워킹의 모든 잠재력을 Google Cloud가 제공하는 지원, 서비스 수준, 월별 청구 및 온디맨드 유연성과 결합하여 실현할 수 있습니다. 자체 하드웨어, 네트워크 및 스토리지를 사용하고 있기 때문에 애플리케이션 규모, 보안 및 네트워크 지연 시간을 직접 제어할 수 있을 뿐 아니라 베어 메탈에서 Anthos와 함께 관리 및 컨테이너화된 애플리케이션의 이점을 누릴 수 있습니다.

link:bmanthos_solution_overview.html["다음: 솔루션 개요"]
