---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_multitenancy_overview.html 
keywords: OpenShift, OCP, Astra Trident, NetApp ONTAP, Red Hat OpenShift, Multitenancy, Multi-tenancy 
summary: NetApp과 함께 Red Hat OpenShift에서 멀티 테넌시 구성 
---
= NetApp과 함께 Red Hat OpenShift에서 멀티 테넌시를 구성합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
컨테이너에서 여러 애플리케이션 또는 워크로드를 실행하는 많은 조직에서는 애플리케이션 또는 작업 부하당 하나의 Red Hat OpenShift 클러스터를 배포하는 경향이 있습니다. 이를 통해 애플리케이션 또는 워크로드에 대한 엄격한 격리를 구현하고 성능을 최적화하며 보안 취약점을 줄일 수 있습니다. 그러나 각 애플리케이션에 대해 별도의 Red Hat OpenShift 클러스터를 배포하면 자체 문제가 발생합니다. 또한 각 클러스터를 단독으로 모니터링 및 관리해야 하는 운영 오버헤드가 늘어나고, 다양한 애플리케이션을 위한 전용 리소스로 비용이 증가하며, 효율적인 확장성을 저해합니다.

이러한 문제를 해결하기 위해 단일 Red Hat OpenShift 클러스터에서 모든 애플리케이션 또는 워크로드를 실행하는 것을 고려할 수 있습니다. 그러나 이러한 아키텍처에서 리소스 격리 및 애플리케이션 보안 취약점은 주요 과제 중 하나입니다. 한 워크로드의 보안 취약점이 다른 작업 부하로 자연스럽게 유출되어 영향 영역이 증가할 수 있습니다. 또한 한 응용 프로그램에서 갑자기 제어되지 않는 리소스 사용률은 기본적으로 리소스 할당 정책이 없기 때문에 다른 응용 프로그램의 성능에 영향을 줄 수 있습니다.

따라서 조직에서는 단일 클러스터에서 모든 워크로드를 실행하면서 각 워크로드별로 전용 클러스터의 이점을 제공하는 동시에 두 환경 모두에서 최상의 솔루션을 찾는 것이 좋습니다.

이러한 효과적인 솔루션 중 하나는 Red Hat OpenShift에서 멀티 테넌시를 구성하는 것입니다. 멀티 테넌시는 리소스, 보안 등을 적절하게 격리하여 동일한 클러스터에서 여러 테넌트를 함께 사용할 수 있는 아키텍처입니다. 이 컨텍스트에서 테넌트는 특정 사용자 그룹이 단독으로 사용하도록 구성된 클러스터 리소스의 하위 집합으로 볼 수 있습니다. Red Hat OpenShift 클러스터에서 멀티 테넌시를 구성하면 다음과 같은 이점이 있습니다.

* 클러스터 리소스를 공유하여 CapEx 및 OpEx 절감
* 운영 및 관리 오버헤드 감소
* 보안 침해의 교차 오염으로부터 워크로드를 보호합니다
* 리소스 경합으로 인해 예기치 않은 성능 저하로부터 워크로드 보호


완전히 실현된 멀티테넌트 OpenShift 클러스터의 경우 컴퓨팅, 스토리지, 네트워킹, 보안 등과 같은 다양한 리소스 버킷에 속하는 클러스터 리소스에 대해 할당량 및 제한을 구성해야 합니다. 이 솔루션에서 모든 리소스 버킷의 특정 측면을 다루지만, NetApp은 NetApp ONTAP가 지원하는 Astra Trident에 의해 동적으로 할당된 스토리지 리소스에서 멀티테넌시를 구성하여 동일한 Red Hat OpenShift 클러스터에서 여러 워크로드에서 제공 또는 소비되는 데이터를 격리하고 보호하는 모범 사례에 초점을 맞춥니다.
