---
sidebar: sidebar 
permalink: containers/rh-os-n_videos_and_demos.html 
keywords: video, demonstration, deployment 
summary:  
---
= 비디오 및 데모: NetApp의 Red Hat OpenShift
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
다음 비디오는 이 문서에 설명되어 있는 몇 가지 기능을 보여 줍니다.

.Red Hat MTV를 사용하여 NetApp ONTAP 스토리지를 통해 VM을 OpenShift 가상화로 마이그레이션합니다
video::bac58645-dd75-4e92-b5fe-b12b015dc199[panopto,width=360]
.NetApp 기반 Red Hat OpenShift인 Astra Control과 NetApp FlexClone 기술을 사용하여 소프트웨어 개발 속도를 높입니다
video::26b7ea00-9eda-4864-80ab-b01200fa13ac[panopto,width=360]
.NetApp Astra Control을 활용하여 사후 분석 및 애플리케이션 복원을 수행합니다
video::3ae8eb53-eda3-410b-99e8-b01200fa30a8[panopto,width=360]
.Astra Control Center를 통해 CI/CD 파이프라인에서 데이터 보호
video::a6400379-52ff-4c8f-867f-b01200fa4a5e[panopto,width=360]
.Astra Control Center를 사용한 워크로드 마이그레이션 - NetApp와 Red Hat OpenShift
video::e397e023-5204-464d-ab00-b01200f9e6b5[panopto,width=360]
.워크로드 마이그레이션 - NetApp의 Red Hat OpenShift
video::27773297-a80c-473c-ab41-b01200fa009a[panopto,width=360]
.OpenShift 가상화 설치 - NetApp과 함께 Red Hat OpenShift의 조합
video::e589a8a3-ce82-4a0a-adb6-b01200f9b907[panopto,width=360]
.OpenShift 가상화를 통한 가상 머신 구축 - NetApp과 Red Hat OpenShift
video::8a29fa18-8643-499e-94c7-b01200f9ce11[panopto,width=360]
.Red Hat 가상화 기반의 Red Hat OpenShift용 NetApp HCI
video::13b32159-9ea3-4056-b285-b01200f0873a[panopto,width=360]