---
sidebar: sidebar 
permalink: containers/rh-os-n_use_case_openshift_virtualization_deployment_prerequisites.html 
keywords: OpenShift, OCP, Trident, NetApp ONTAP, Red Hat OpenShift, OpenShift Virtualization, CNV, Container Native Virtualization, Red Hat OpenShift Virtualization 
summary: NetApp ONTAP 기반의 Red Hat OpenShift 가상화 
---
= NetApp ONTAP를 사용하여 Red Hat OpenShift Virtualization 배포
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 섹션에서는 NetApp ONTAP를 사용하여 Red Hat OpenShift Virtualization을 배포하는 방법에 대해 자세히 설명합니다.



== 필수 구성 요소

* RHCOS 작업자 노드가 있는 베어 메탈 인프라에 설치된 Red Hat OpenShift 클러스터(버전 4.6 이상
* VM에 대한 HA를 유지하기 위해 시스템 상태 점검을 구축합니다
* NetApp ONTAP 클러스터
* Trident가 OpenShift 클러스터에 설치되어 있습니다
* ONTAP 클러스터에서 SVM으로 구성된 Trident 백엔드
* Trident를 Provisioner로 사용하여 OpenShift 클러스터에 구성된 StorageClass
* Red Hat OpenShift 클러스터에 대한 클러스터 관리자 액세스
* NetApp ONTAP 클러스터에 대한 관리 액세스
* tridentctl 및 OC 도구가 설치되고 $PATH에 추가된 관리 워크스테이션


OpenShift Virtualization은 OpenShift 클러스터에 설치된 운영자에 의해 관리되기 때문에 클러스터에 대한 하드웨어 요구 사항을 계획하는 동안 메모리, CPU 및 스토리지에 추가적인 오버헤드를 부과합니다. 설명서를 참조하십시오 https://docs.openshift.com/container-platform/4.7/virt/install/preparing-cluster-for-virt.html#virt-cluster-resource-requirements_preparing-cluster-for-virt["여기"] 를 참조하십시오.

필요한 경우 노드 배치 규칙을 구성하여 OpenShift 가상화 운영자, 컨트롤러 및 VM을 호스팅하는 OpenShift 클러스터 노드의 하위 집합을 지정할 수도 있습니다. OpenShift 가상화를 위한 노드 배치 규칙을 구성하려면 설명서를 참조하십시오 https://docs.openshift.com/container-platform/4.7/virt/install/virt-specifying-nodes-for-virtualization-components.html["여기"].

OpenShift 가상화를 지원하는 스토리지의 경우 전용 StorageClass를 사용하여 특정 Trident 백엔드의 스토리지를 요청한 다음, 전용 SVM을 통해 지원하는 것이 좋습니다. 이를 통해 OpenShift 클러스터에서 VM 기반 워크로드에 제공되는 데이터와 관련하여 멀티 테넌시의 수준을 유지할 수 있습니다.
