---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_solutions_for_industry.html 
keywords: GPU, Azure, NVIDIA, Tesla M60, 
summary: 그래픽 워크스테이션은 일반적으로 제조, 의료, 에너지, 미디어 및 엔터테인먼트, 교육, 아키텍처 등 그래픽 집약적 애플리케이션의 경우 이동성이 제한되는 경우가 많습니다. 
---
= 솔루션을 제공합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


그래픽 워크스테이션은 일반적으로 제조, 의료, 에너지, 미디어 및 엔터테인먼트, 교육, 아키텍처 등 그래픽 집약적 애플리케이션의 경우 이동성이 제한되는 경우가 많습니다.

이동성 문제를 해결하기 위해 가상 데스크톱 서비스는 유연한 GPU 구성 옵션을 포함하여 작업 근로자, 전문 사용자, 클라우드 또는 NetApp HCI에서 하드웨어 리소스를 사용하는 등 모든 유형의 근로자를 위한 데스크톱 환경을 제공합니다. VDS를 사용하면 랩톱, 태블릿 및 기타 모바일 장치를 통해 어디에서나 작업 환경에 액세스할 수 있습니다.

ANSYS Fluent, ANSYS Mechanical, Autodesk AutoCAD, Autodesk Inventor, Autodesk 3DS Max, Dassault Systèmes SOLIDWORKS, Dassault Systèmes CATIA, PTC Creo, Siemens PLM NX 등 2021년 1월 기준 다양한 클라우드에서 사용할 수 있는 GPU가 다음 표에 나열되어 있습니다.

[cols="20,20,20,20,20"]
|===
| GPU 모델 | Microsoft Azure를 참조하십시오 | Google Compute(GCP) | AWS(Amazon Web Services) | 사내(NetApp HCI) 


| NVIDIA M60 | 예 | 예 | 예 | 아니요 


| NVIDIA T4 | 아니요 | 예 | 예 | 예 


| NVIDIA P100 | 아니요 | 예 | 아니요 | 아니요 


| NVIDIA P4 | 아니요 | 예 | 아니요 | 아니요 
|===
다른 사용자 및 전용 개인 데스크톱과의 공유 데스크톱 세션도 사용할 수 있습니다. 가상 데스크톱은 GPU를 1~4개 가질 수 있거나 NetApp HCI를 통해 부분 GPU를 활용할 수 있습니다. NVIDIA T4는 광범위한 사용자 워크로드의 요구사항을 충족할 수 있는 다기능 GPU 카드입니다. NetApp HCI H615C의 각 GPU 카드에는 서버당 16GB의 프레임 버퍼 메모리와 3개의 카드가 있습니다. 단일 H615C 서버에서 호스팅할 수 있는 사용자 수는 사용자 워크로드에 따라 다릅니다.

[cols="25,25,25,25"]
|===
| 사용자/서버 | 표시등(4GB) | 보통(8GB) | 중량지(16GB) 


| H615C | 12 | 6 | 3 
|===
사용자 유형을 확인하려면 사용자가 일반적인 작업을 수행하는 응용 프로그램으로 작업하는 동안 GPU 프로파일러 도구를 실행합니다. GPU 프로파일러는 메모리 요구 사항, 디스플레이 수 및 사용자가 요구하는 해상도를 캡처합니다. 그런 다음 요구 사항을 충족하는 vGPU 프로필을 선택할 수 있습니다.

GPU가 장착된 가상 데스크톱은 최대 8K의 디스플레이 해상도를 지원할 수 있으며, nView 유틸리티는 단일 모니터를 여러 영역으로 분할하여 여러 데이터 세트에서 작업할 수 있습니다.

ONTAP 파일 스토리지를 사용하면 다음과 같은 이점을 실현할 수 있습니다.

* 관리 입력 없이도 4천억 개의 파일로 스토리지를 최대 20PB까지 확장할 수 있는 단일 네임스페이스입니다
* 글로벌 파일 캐시로 전 세계를 확장할 수 있는 네임스페이스
* 관리되는 NetApp 스토리지를 통한 안전한 멀티 테넌시
* NetApp FabricPool를 사용하여 콜드 데이터를 오브젝트 저장소로 마이그레이션
* 파일 시스템 분석을 통한 빠른 파일 통계
* 스토리지 클러스터를 최대 24노드로 확장하여 용량과 성능 향상
* 할당량을 통해 스토리지 공간을 제어하고 QoS 제한을 통해 성능을 보장할 수 있습니다
* 암호화를 통한 데이터 보호
* 데이터 보호 및 규정 준수에 대한 광범위한 요구사항 충족
* 유연한 비즈니스 연속성 옵션 제공


link:vdi-vds/hcvdivds_conclusion.html["다음: 결론"]
