---
sidebar: sidebar 
permalink: vdi-vds/hcvdivds_nvidia_licensing.html 
keywords: Licensing, NVIDIA, GPU, GRID, Virtual PC 
summary: H610C 또는 H615C를 사용하는 경우 라이센스를 재판매할 수 있는 NVIDIA 파트너로부터 GPU 라이센스를 구입해야 합니다. 
---
= NVIDIA 라이센싱
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


H610C 또는 H615C를 사용하는 경우 라이센스를 재판매할 수 있는 NVIDIA 파트너로부터 GPU 라이센스를 구입해야 합니다. NVIDIA 파트너는 을(를) 통해 확인할 수 있습니다 https://www.nvidia.com/object/partner-locator.html["파트너 로케이터"^]. 가상 GPU(vGPU) 또는 Tesla와 같은 역량을 검색합니다.

NVIDIA vGPU 소프트웨어는 다음 4가지 버전으로 제공됩니다.

* NVIDIA GRID Virtual PC(GRID vPC)
* NVIDIA GRID 가상 애플리케이션(GRID vApp)
* NVIDIA Quadro 가상 데이터 센터 워크스테이션(Quadro vDWS)
* NVIDIA 가상 컴퓨팅 서버(vComputeServer)




== 그리드 가상 PC

이 제품은 Microsoft Windows 응용 프로그램, 브라우저, 고화질 비디오 및 다중 모니터 지원을 위한 뛰어난 사용자 환경을 제공하는 가상 데스크톱을 원하는 사용자에게 적합합니다. NVIDIA GRID Virtual PC는 가상 환경에서 기본 경험을 제공하여 모든 PC 애플리케이션을 최대 성능으로 실행할 수 있도록 지원합니다.



== 그리드 가상 애플리케이션

Grid vApps는 RDSH(Remote Desktop Session Host) 또는 기타 애플리케이션 스트리밍 또는 세션 기반 솔루션을 배포하는 조직을 위한 것입니다. Microsoft Windows 응용 프로그램을 최대 성능으로 제공하도록 설계된 Windows Server 호스팅 RDSH 데스크톱은 GRID vApp에서도 지원됩니다.



== Quadro 가상 데이터 센터 워크스테이션

이 에디션은 Dassault CATIA, SOLIDWORKS, 3Dexeite, Siemens NX, PTC Creo, Schlumberger Petrel 또는 Autodesk Maya. NVIDIA Quadro vDWS를 사용하면 사용자는 모든 장치에서 모든 기능과 성능을 갖춘 전문가용 그래픽 응용 프로그램에 액세스할 수 있습니다.



== NVIDIA 가상 컴퓨팅 서버

많은 조직에서 인공 지능(AI), 딥 러닝(DL), 데이터 과학과 같은 컴퓨팅 집약적인 서버 워크로드를 실행합니다. 이러한 사용 사례에서 NVIDIA vComputeServer 소프트웨어는 NVIDIA GPU를 가상화하여 오류 수정 코드, 페이지 폐기, NVLink를 통한 P2P, 다중 vGPU 등의 기능을 통해 컴퓨팅 집약적인 서버 워크로드를 가속화합니다.


NOTE: Quadro vDWS 라이센스를 사용하면 GRID vPC 및 NVIDIA vComputeServer를 사용할 수 있습니다.

link:hcvdivds_deployment.html["다음: 배포"]
