---
sidebar: sidebar 
permalink: virtualization/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, Cloud Sync, FabricPool, ONTAP 
summary: 이 페이지에서는 비디오 및 자습서에 대한 소개 및 설명을 제공합니다. 
---
= 가상화 비디오 및 데모
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
하이브리드 클라우드, 가상화 및 컨테이너 솔루션의 특정 기능을 소개하는 다음 비디오 및 데모를 참조하십시오.

.VMware vSphere용 NetApp ONTAP 툴
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
VMware용 ONTAP 툴 - 개요

 a| 
ONTAP를 사용한 VMware iSCSI 데이터 저장소 용량 할당

 a| 
ONTAP를 사용한 VMware NFS 데이터 저장소 용량 할당


|===
====
.NetApp ONTAP용 AWS FSx가 있는 AWS 기반 VMware Cloud
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
iSCSI를 사용하는 FSx ONTAP가 있는 Windows 게스트 연결 스토리지

 a| 
NFS를 사용하는 FSx ONTAP가 있는 Linux 게스트 연결 스토리지

 a| 
NetApp ONTAP용 Amazon FSx를 통해 AWS에서 VMware Cloud를 TCO로 절감할 수 있습니다




 a| 
NetApp ONTAP용 Amazon FSx를 사용하는 AWS 보조 데이터 저장소의 VMware Cloud

 a| 
VMC를 위한 VMware HCX 구축 및 구성 설정

 a| 
VMC 및 FSxN용 VMware HCX와 함께 vMotion 마이그레이션 데모




 a| 
VMC 및 FSxN용 VMware HCX와 함께 콜드 마이그레이션 데모

 a| 
 a| 

|===
====
.ANF(Azure NetApp Files)가 있는 Azure 기반 Azure VMware 서비스
[%collapsible]
====
[cols="5a, 5a, 5a"]
|===


 a| 
Azure VMware 솔루션 Azure NetApp Files의 데이터 저장소 보충 개요

 a| 
Cloud Volumes ONTAP, SnapCenter 및 Jetstream을 사용한 Azure VMware 솔루션 DR

 a| 
VMware HCX for AVS 및 ANF와 함께 콜드 마이그레이션 데모




 a| 
VMware HCX와 함께 AVS 및 ANF용 vMotion 데모

 a| 
VMware HCX for AVS 및 ANF와 함께 대량 마이그레이션 데모

 a| 

|===
====
.VMware vSphere용 SnapCenter 플러그인
[%collapsible]
====
NetApp SnapCenter 소프트웨어는 애플리케이션, 데이터베이스 및 파일 시스템 전반에서 데이터 보호를 안전하게 조율하고 관리하는 사용하기 쉬운 엔터프라이즈 플랫폼입니다.

VMware vSphere용 SnapCenter 플러그인을 사용하면 VM에 대한 백업, 복구 및 연결 작업과 VMware vCenter에서 직접 SnapCenter에 등록된 데이터 저장소에 대한 백업 및 마운트 작업을 수행할 수 있습니다.

NetApp SnapCenter Plug-in for VMware vSphere에 대한 자세한 내용은 를 참조하십시오 link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["VMware vSphere용 NetApp SnapCenter 플러그인 개요"].

[cols="5a, 5a, 5a"]
|===


 a| 
VMware vSphere용 SnapCenter 플러그인 - 솔루션 전제 조건

 a| 
VMware vSphere용 SnapCenter 플러그인 - 구축

 a| 
VMware vSphere용 SnapCenter 플러그인 - 백업 워크플로우




 a| 
VMware vSphere용 SnapCenter 플러그인 - 복구 워크플로우

 a| 
SnapCenter - SQL 복원 워크플로

 a| 

|===
====
.NetApp과 VMware Tanzu
[%collapsible]
====
VMware Tanzu를 사용하면 vSphere 또는 VMware Cloud Foundation을 통해 Kubernetes 환경을 구축, 관리 및 관리할 수 있습니다. 고객은 VMware의 이 제품 포트폴리오를 통해 요구사항에 가장 적합한 VMware Tanzu 에디션을 선택하여 단일 제어 플레인에서 모든 관련 Kubernetes 클러스터를 관리할 수 있습니다.

VMware Tanzu에 대한 자세한 내용은 를 참조하십시오 https://tanzu.vmware.com/tanzu["VMware Tanzu 개요"^]. 이 리뷰에서는 VMware Tanzu에 대한 사용 사례, 추가 기능 및 기타 정보를 제공합니다.

[cols="5a, 5a, 5a"]
|===


 a| 
NetApp 및 VMware Tanzu Basic에서 VVOL을 사용하는 방법 1부

video::ZtbXeOJKhrc[youtube,width=360] a| 
NetApp 및 VMware Tanzu Basic에서 VVOL을 사용하는 방법, 2부

video::FVRKjWH7AoE[youtube,width=360] a| 
NetApp 및 VMware Tanzu Basic에서 VVOL을 사용하는 방법, 3부

video::Y-34SUtTTtU[youtube,width=360]
|===
====