---
sidebar: sidebar 
permalink: virtualization/vsphere_ontap_ontap_and_vsphere_release-specific_information.html 
keywords: vSphere, release, ESXi, Cisco UCS, NFS Plug In for VMware VAAI, VASA Provider 
summary: 이 섹션에서는 특정 릴리즈의 ONTAP 및 vSphere에서 지원하는 기능에 대한 지침을 제공합니다. NetApp 상호 운용성 매트릭스와 특정 조합의 릴리즈를 확인하는 것이 좋습니다. 
---
= ONTAP 및 vSphere 릴리즈별 정보입니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
이 섹션에서는 특정 릴리즈의 ONTAP 및 vSphere에서 지원하는 기능에 대한 지침을 제공합니다. NetApp은 와 릴리스의 특정 조합을 확인하는 것이 좋습니다 http://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^].



== ONTAP 릴리스

NetApp은 출시 당시 다음과 같은 제품군을 완벽하게 지원합니다.

* ONTAP 9.5
* ONTAP 9.6
* ONTAP 9.7
* ONTAP 9.8




== vSphere 및 ESXi 지원

NetApp ONTAP는 vSphere ESXi 호스트를 광범위하게 지원합니다. 방금 설명한 네 가지 주요 릴리즈 제품군(9.5, 9.6, 9.7 및 9.8)은 6.0, 6.5 및 7.0(이러한 릴리즈에 대한 업데이트 포함)을 비롯한 최신 vSphere 릴리스의 데이터 스토리지 플랫폼으로 완벽하게 지원됩니다. NFS v3 상호 운용성은 광범위하게 정의되며 NetApp은 NFS v3 표준을 준수하는 하이퍼바이저를 포함하여 모든 클라이언트를 지원합니다. NFSv4.1 지원은 vSphere 6.0에서 7.0으로 제한됩니다.

SAN 환경의 경우 NetApp에서 SAN 구성요소를 광범위하게 테스트합니다. 일반적으로 NetApp은 표준 x86-64 랙 서버와 Cisco UCS 서버를 iSCSI 연결용 표준 이더넷 어댑터와 함께 지원합니다. FC, FCoE 및 NVMe/FC 환경에서는 필요한 HBA 펌웨어 및 드라이버로 인해 지원이 명확하게 정의되었습니다.

항상 을 확인하십시오 http://mysupport.netapp.com/matrix/["NetApp 상호 운용성 매트릭스"^] 특정 하드웨어 및 소프트웨어 구성에 대한 지원을 확인합니다.



== VMware VAAI용 NFS 플러그인

ESXi 호스트용 이 플러그인은 VAAI를 사용하여 ONTAP로 작업을 오프로드하는 데 도움이 됩니다. 최신 릴리스인 1.1.2에는 Kerberos(krb5 및 krb5i) 지원을 비롯한 NFSv4.1 데이터 저장소가 지원됩니다. ONTAP 9.5-9.8과 함께 ESXi 6.0, 6.5 및 7.0에서 지원됩니다.



== VASA 공급자

NetApp의 VASA Provider는 VVOL 프로비저닝 및 관리를 지원합니다(섹션 3.7 참조). 최신 VASA Provider 릴리즈는 ESXi 6.0, 6.5 및 7.0과 ONTAP 9.5-9.8을 함께 지원합니다.



== VMware vSphere용 ONTAP 툴

VMware vSphere용 ONTAP 툴은 ONTAP 스토리지를 vSphere와 함께 관리하는 데 있어 매우 중요합니다(모범 사례). 최신 릴리스인 9.8은 ONTAP 9.5-9.8과 함께 vSphere 6.5 및 7.0에서 지원됩니다.
