---
sidebar: sidebar 
permalink: containers/baremetal-anthos/bmanthos_solution_requirements.html 
keywords: Hardware, software, compute, storage, requirements 
summary: 베어 메탈 기반 Anthos의 하드웨어 독립적 기능을 사용하면 사용 사례에 최적화된 컴퓨팅 플랫폼을 선택할 수 있습니다. 따라서 는 기존 인프라를 일치시키고 자본 지출을 줄일 수 있습니다. 
---
= 솔루션 요구 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/




== 하드웨어 요구 사항



=== 컴퓨팅: 자체 서버를 사용합니다

베어 메탈 기반 Anthos의 하드웨어 독립적 기능을 사용하면 사용 사례에 최적화된 컴퓨팅 플랫폼을 선택할 수 있습니다. 따라서 는 기존 인프라를 일치시키고 자본 지출을 줄일 수 있습니다.

다음 표에는 이 솔루션을 구현하는 데 필요한 최소 컴퓨팅 하드웨어 구성 요소의 수가 나와 있습니다. 단, 사용되는 하드웨어 모델은 고객 요구 사항에 따라 다를 수 있습니다.

|===
| 사용 | 하드웨어 및 모델 | 수량 


| 관리 노드 | Cisco UCS B200 | 3 


| 작업자 노드 | HP ProLiant DL360 | 4 
|===


=== 스토리지: NetApp ONTAP

다음 표에는 솔루션을 구현하는 데 필요한 최소 스토리지 하드웨어 구성 요소의 수가 나와 있습니다. 단, 사용되는 하드웨어 모델은 고객 요구 사항에 따라 다를 수 있습니다.

|===
| 하드웨어 | 모델 | 수량 


| NetApp AFF를 참조하십시오 | NetApp AFF A300 | 2개(HA 쌍 1개) 
|===


== 소프트웨어 요구 사항

다음 표에 명시된 소프트웨어 버전은 NetApp과 파트너가 NetApp 솔루션을 검증하는 데 사용되었으며 소프트웨어 구성 요소는 고객 요구 사항에 따라 다를 수 있습니다.

|===
| 소프트웨어 | 목적 | 버전 


| 우분투 | 3명의 관리자가 있는 OS | 20.04 


|  | Worker4의 OS | 20.04 


|  | Worker3의 OS | 18.04 


| CentOS | Worker2의 OS | 8.2 


| Red Hat Enterprise Linux | Worker1의 OS | 8.1 


| Anthos의 Bare Metal | 컨테이너 오케스트레이션 | 1.6.0 


| NetApp ONTAP를 참조하십시오 | 스토리지 OS | 9.7P8 


| NetApp Astra Trident | 컨테이너 스토리지 관리 | 20.10 
|===

NOTE: 이 멀티 OS 환경은 베어 메탈 솔루션의 Anthos의 지원되는 OS 버전과의 상호 운용성을 보여줍니다. 우리는 고객이 구축을 위해 하나 또는 일부 운영 체제를 표준화할 것으로 예상하고 있습니다.

베어 메탈 하드웨어 및 소프트웨어 요구 사항에 대한 Anthos는 를 참조하십시오 https://cloud.google.com/anthos/gke/docs/bare-metal/concepts/hw-sw-storage["Anthos의 Bare Metal 문서"^] 페이지.

link:bmanthos_deployment_summary.html["다음: 배포 요약."]
