= 
:allow-uri-read: 


. 자격 증명을 구성합니다.
. 자격 증명 유형을 만듭니다. ONTAP와 관련된 솔루션의 경우 자격 증명 유형을 사용자 이름 및 암호 항목과 일치하도록 구성해야 합니다. 또한 Cloud Central 및 AWS에 대한 항목을 추가합니다.
+
.. Administration → Credential Types로 이동한 후 Add를 클릭합니다.
.. 이름과 설명을 입력합니다.
.. 입력 구성에 다음 내용을 붙여 넣습니다.
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: CVO Username
  - id: dst_cluster_password
    type: string
    label: CVO Password
    secret: true
  - id: cvo_svm_password
    type: string
    label: CVO SVM Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
  - id: regular_id
    type: string
    label: Cloud Central ID
    secret: true
  - id: email_id
    type: string
    label: Cloud Manager Email
    secret: true
  - id: cm_password
    type: string
    label: Cloud Manager Password
    secret: true
  - id: access_key
    type: string
    label: AWS Access Key
    secret: true
  - id: secret_key
    type: string
    label: AWS Secret Key
    secret: true
  - id: token
    type: string
    label: Cloud Central Refresh Token
    secret: true
----
.. Injector Configuration(주입기 구성)에 다음 내용을 붙여넣고 Save(저장)를 클릭합니다.
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  cvo_svm_password: '{{ cvo_svm_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
  regular_id: '{{ regular_id }}'
  email_id: '{{ email_id }}'
  cm_password: '{{ cm_password }}'
  access_key: '{{ access_key }}'
  secret_key: '{{ secret_key }}'
  token: '{{ token }}'
----


. ONTAP/CVO/AWS에 대한 자격 증명을 생성합니다
+
.. Resources → Credentials로 이동한 후 Add를 클릭합니다.
.. ONTAP 자격 증명에 대한 이름과 조직 세부 정보를 입력합니다
.. 이전 단계에서 만든 자격 증명 유형을 선택합니다.
.. 유형 세부 정보 아래에 소스 및 CVO 클러스터, Cloud Central/Manager, AWS 액세스/비밀 키 및 Cloud Central 업데이트 토큰의 사용자 이름 및 암호를 입력합니다.
.. 저장 을 클릭합니다


. Oracle에 대한 자격 증명 생성(소스)
+
.. Resources → Credentials로 이동한 후 Add를 클릭합니다.
.. Oracle 호스트의 이름 및 조직 세부 정보를 입력합니다
.. 시스템 자격 증명 유형을 선택합니다.
.. 유형 세부 정보 에서 Oracle 호스트의 사용자 이름 및 암호를 입력합니다.
.. 올바른 권한 에스컬레이션 방법을 선택하고 사용자 이름과 암호를 입력합니다.
.. 저장 을 클릭합니다


. Oracle Destination에 대한 자격 증명을 생성합니다
+
.. Resources → Credentials로 이동한 후 Add를 클릭합니다.
.. DR Oracle 호스트의 이름 및 조직 세부 정보를 입력합니다
.. 시스템 자격 증명 유형을 선택합니다.
.. 세부 정보 유형 에 사용자 이름(EC2-USER 또는 기본값에서 변경한 경우 해당 입력) 및 SSH 개인 키를 입력합니다
.. 올바른 권한 에스컬레이션 방법(sudo)을 선택하고 필요한 경우 사용자 이름과 암호를 입력합니다.
.. 저장 을 클릭합니다



