= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS/VMC
--
AWS는 다음과 같은 구성에서 NetApp 스토리지를 지원합니다.

* FSX ONTAP를 게스트 연결 스토리지로 사용합니다
* CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다
* FSX ONTAP를 기본 데이터 저장소 ^1^로 사용합니다


자세한 내용을 확인하십시오 link:aws/aws-guest.html["VMC에 대한 게스트 연결 스토리지 옵션"].

자세한 내용을 확인하십시오 link:aws-guest.html["VMC에 대한 게스트 연결 스토리지 옵션"].

에 대해 자세히 알아보십시오 link:https://blogs.vmware.com/cloud/2021/12/01/vmware-cloud-on-aws-going-big-reinvent2021/["FSX ONTAP를 기본 데이터 저장소 ^1로 사용합니다"^].


NOTE: 1-현재 비공개 미리보기에 있습니다

--
.Azure/AVS
--
Azure는 다음과 같은 구성에서 NetApp 스토리지를 지원합니다.

* 게스트 연결 스토리지로서의 Azure NetApp Files(ANF)
* CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다
* Azure NetApp Files(ANF)를 기본 데이터 저장소 ^1^로 사용


자세한 내용을 확인하십시오 link:azure/azure-guest.html["AVS용 게스트 연결 스토리지 옵션"].

자세한 내용을 확인하십시오 link:azure-guest.html["AVS용 게스트 연결 스토리지 옵션"].

에 대해 자세히 알아보십시오 link:https://azure.microsoft.com/en-us/updates/azure-netapp-files-datastores-for-azure-vmware-solution-is-coming-soon/["Azure NetApp Files(ANF)를 기본 데이터 저장소 ^1로 사용합니다"^].


NOTE: 1-현재 비공개 미리보기에 있습니다

--
.GCP/GCVE
--
Google Cloud는 다음과 같은 구성에서 NetApp 스토리지를 지원합니다.

* CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다
* CVS(Cloud Volumes Service)를 게스트 연결 스토리지로 사용합니다
* CVS(Cloud Volumes Service)를 네이티브 데이터 저장소 ^1^로 사용합니다


자세한 내용을 확인하십시오 link:gcp/gcp-guest.html["GCVE에 대한 게스트 연결 저장소 옵션"].

자세한 내용을 확인하십시오 link:gcp-guest.html["GCVE에 대한 게스트 연결 저장소 옵션"].

에 대해 자세히 알아보십시오 link:https://www.netapp.com/google-cloud/google-cloud-vmware-engine-registration/["CVS(Cloud Volumes Service)를 네이티브 데이터 저장소 ^1로 사용합니다"^].


NOTE: 1-현재 비공개 미리보기에 있습니다

--
====