= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AWS/VMC
--
이 섹션에서는 AWS SDDC에서 VMware Cloud를 설정 및 관리하고, NetApp 스토리지를 연결하는 데 사용할 수 있는 옵션과 함께 사용하는 방법을 설명합니다.


NOTE: 게스트 내 스토리지는 Cloud Volumes ONTAP을 AWS VMC에 연결하는 유일한 지원 방법입니다.

설치 프로세스는 다음 단계로 나눌 수 있습니다.

* VMware Cloud for AWS 구축 및 구성
* VMware Cloud를 FSx ONTAP에 연결합니다


자세한 내용을 확인하십시오 link:aws-setup.html["VMC에 대한 구성 단계"].

자세한 내용을 확인하십시오 link:aws-setup.html["VMC에 대한 구성 단계"].

--
.Azure/AVS
--
이 섹션에서는 Azure VMware 솔루션을 설정 및 관리하고 NetApp 스토리지를 연결하는 데 사용할 수 있는 옵션과 함께 사용하는 방법을 설명합니다.


NOTE: 게스트 내 스토리지는 Cloud Volumes ONTAP를 Azure VMware 솔루션에 연결하는 유일한 지원 방법입니다.

설치 프로세스는 다음 단계로 나눌 수 있습니다.

* 리소스 공급자를 등록하고 프라이빗 클라우드를 생성합니다
* 새 또는 기존 ExpressRoute 가상 네트워크 게이트웨이에 연결합니다
* 네트워크 연결을 확인하고 프라이빗 클라우드에 액세스합니다


자세한 내용을 확인하십시오 link:azure-setup.html["AVS의 구성 단계"].

자세한 내용을 확인하십시오 link:azure-setup.html["AVS의 구성 단계"].

--
.GCP/GCVE
--
이 섹션에서는 GCVE를 설정 및 관리하고 NetApp 스토리지를 연결하는 데 사용할 수 있는 옵션과 함께 사용하는 방법을 설명합니다.


NOTE: 게스트 내 저장소는 Cloud Volumes ONTAP 및 Cloud Volumes Services를 GCVE에 연결하는 유일한 지원 방법입니다.

설치 프로세스는 다음 단계로 나눌 수 있습니다.

* GCVE 배포 및 구성
* GCVE에 대한 개인 액세스를 활성화합니다


자세한 내용을 확인하십시오 link:gcp-setup.html["GCVE에 대한 구성 단계"].

자세한 내용을 확인하십시오 link:gcp-setup.html["GCVE에 대한 구성 단계"].

--
====