= 
:allow-uri-read: 


이 섹션에서는 NetApp 자동화 솔루션을 사용하는 환경을 준비하기 위해 AWX/Ansible 타워에서 매개 변수를 구성하는 데 필요한 단계를 설명합니다.

. 인벤토리를 구성합니다.
+
.. Resources(리소스) → Inventory(인벤토리) → Add(추가) 로 이동하여 Add Inventory(재고 추가) 를 클릭합니다.
.. 이름 및 조직 세부 정보를 입력하고 저장 을 클릭합니다.
.. 인벤토리 페이지에서 방금 만든 인벤토리 리소스를 클릭합니다.
.. 재고 변수가 있는 경우 변수 필드에 붙여 넣습니다.
.. 그룹 하위 메뉴로 이동하여 추가 를 클릭합니다.
.. 그룹 이름을 입력하고 그룹 변수에 복사한 다음(필요한 경우) 저장 을 클릭합니다.
.. 생성된 그룹을 클릭하고 Hosts 하위 메뉴로 이동한 다음 Add New Host를 클릭합니다.
.. 호스트의 호스트 이름과 IP 주소를 입력하고 필요한 경우 호스트 변수를 붙여 넣은 다음 Save(저장) 를 클릭합니다.


. 자격 증명 유형을 만듭니다. ONTAP, Element, VMware 또는 기타 HTTPS 기반 전송 연결과 관련된 솔루션의 경우 자격 증명 유형을 사용자 이름 및 암호 항목과 일치하도록 구성해야 합니다.
+
.. Administration → Credential Types로 이동하여 Add를 클릭합니다.
.. 이름과 설명을 입력합니다.
.. 다음 내용을 입력 구성에 붙여 넣습니다.




[listing]
----
fields:
- id: username
type: string
label: Username
- id: password
type: string
label: Password
secret: true
- id: vsadmin_password
type: string
label: vsadmin_password
secret: true
----
. 다음 내용을 주입기 구성에 붙여넣습니다.


[listing]
----
extra_vars:
password: '{{ password }}'
username: '{{ username }}'
vsadmin_password: '{{ vsadmin_password }}'
----
. 자격 증명을 구성합니다.
+
.. Resources → Credentials 로 이동하고 Add 를 클릭합니다.
.. 이름 및 조직 세부 정보를 입력합니다.
.. 올바른 자격 증명 유형을 선택합니다. 표준 SSH 로그인을 사용하려면 Machine 유형을 선택하거나 직접 생성한 사용자 지정 자격 증명 유형을 선택합니다.
.. 다른 해당 세부 정보를 입력하고 저장 을 클릭합니다.


. 프로젝트를 구성합니다.
+
.. Resources → Projects 로 이동한 후 Add 를 클릭합니다.
.. 이름 및 조직 세부 정보를 입력합니다.
.. 소스 제어 자격 증명 유형 으로 Git 를 선택합니다.
.. 특정 솔루션에 해당하는 소스 제어 URL(또는 git 클론 URL)을 붙여 넣습니다.
.. 필요한 경우 Git URL이 액세스를 제어하는 경우 소스 제어 자격 증명 에서 해당 자격 증명을 만들고 연결합니다.
.. 저장 을 클릭합니다.


. 작업 템플릿을 구성합니다.
+
.. Resources → Templates → Add로 이동하여 Add Job Template을 클릭합니다.
.. 이름과 설명을 입력합니다.
.. 작업 유형을 선택합니다. Run은 Playbook을 기반으로 시스템을 구성하고 Check는 실제로 시스템을 구성하지 않고 Playbook을 건조하게 실행합니다.
.. Playbook의 해당 인벤토리, 프로젝트 및 자격 증명을 선택합니다.
.. 작업 템플릿의 일부로 실행할 플레이북을 선택합니다.
.. 일반적으로 런타임에는 변수를 붙여 넣습니다. 따라서 런타임 중에 변수를 채우라는 프롬프트를 표시하려면 변수 필드에 해당하는 시작 시 프롬프트 확인란을 선택합니다.
.. 필요에 따라 다른 세부 정보를 입력하고 Save(저장) 를 클릭합니다.


. 작업 템플릿을 시작합니다.
+
.. 리소스 → 템플릿 으로 이동합니다.
.. 원하는 템플릿을 클릭한 다음 실행을 클릭합니다.
.. 실행 시 메시지가 표시되면 변수를 입력하고 다시 시작 을 클릭합니다.



