= Oracle 설치를 검증합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




=== Oracle 설치를 검증합니다

. Oracle 서버에 Oracle 사용자로 로그인하고 다음 명령을 실행합니다.


[source, cli]
----
ps -ef | grep ora
----

NOTE: 설치가 예상대로 완료되고 Oracle DB가 시작되면 Oracle 프로세스가 나열됩니다

. 데이터베이스에 로그인하여 다음 명령 세트로 생성된 DB 구성 설정과 PDB를 확인합니다.


[source, cli]
----
sqlplus / as sysdba
----
[oracle@localhost~]$sqlplus/as sysdba

SQL* Plus: 릴리스 19.0.0.0.0 - 5월 6일 목요일 프로덕션 12:52:51 2021년 버전 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle. 모든 권리 보유.

연결 대상: Oracle Database 19c Enterprise Edition 릴리스 19.0.0.0.0 - 프로덕션 버전 19.8.0.0.0

sql> 을 클릭합니다

[source, cli]
----
select name, log_mode from v$database;
----
sql> v$database에서 이름, log_mode 선택; name log_mode--------- ---------- CDB2 ARCHIVELOG

[source, cli]
----
show pdbs;
----
sql > PDB 표시

....
    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO
....
[source, cli]
----
col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;
----
sql> col svrname form a30 sql> col dirname form a30 sql> v$dnfs_servers에서 svrname, dirname, nfsversion을 선택합니다.

SVRNAME dirname NFSVERSION------------------------------------------------------------ ------------------------------------------------------------ --------------- 172.21.126.200/rhelora03_u02 NFSv3.0 172.21.126.200/rhelora03_uNFSv03 3.0 172.21.126.200/rhelora03_u01 NFSv3.0

[listing]
----
This confirms that dNFS is working properly.
----
. 다음 명령을 사용하여 listener를 통해 데이터베이스에 연결하여 hte oracle listener 구성을 확인합니다. 적절한 수신기 포트 및 데이터베이스 서비스 이름으로 변경합니다.


[source, cli]
----
sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com
----
[Oracle@localhost~]$sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com

SQL* Plus: 릴리스 19.0.0.0.0 - 5월 6일 13:19:57 2021년 11월 19일 버전 19.8.0.0.0의 목요일 프로덕션

Copyright (c) 1982, 2019, Oracle. 모든 권리 보유.

비밀번호 입력: 마지막으로 성공한 로그인 시간: 2021년 5월 5일 17:11:11-04:00

연결 대상: Oracle Database 19c Enterprise Edition 릴리스 19.0.0.0.0 - 프로덕션 버전 19.8.0.0.0

sql> show user is "system" sql> show con_name con_name CDB2_PDB1

[listing]
----
This confirms that Oracle listener is working properly.
----


=== 도움을 받을 수 있는 곳

툴킷에 대한 도움이 필요한 경우 에 가입하십시오 link:https://netapppub.slack.com/archives/C021R4WC0LC["NetApp 솔루션 자동화 커뮤니티는 여유 채널을 지원합니다"] 질문 또는 질문을 게시할 수 있는 솔루션 자동화 채널을 찾아보십시오.
