---
sidebar: sidebar 
permalink: databases/automation_ora_migration.html 
keywords: Oracle, AWS, FSx ONTAP, Database Migration, Oracle 19c, 
summary: 이 솔루션은 최대 가용성 방법론과 함께 PDB 재배치를 사용하여 Oracle 데이터베이스를 마이그레이션하기 위한 Ansible 기반 자동화 툴킷을 제공합니다. 온프레미스와 클라우드를 소스 또는 타겟으로 조합하여 마이그레이션할 수 있습니다 
---
= 자동화된 Oracle 마이그레이션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


NetApp 솔루션 엔지니어링 팀



== 목적

이 툴킷은 FSx ONTAP 스토리지 및 EC2 컴퓨팅 인스턴스를 타겟 인프라로 사용하여 온프레미스에서 AWS 클라우드로 Oracle 데이터베이스를 자동으로 마이그레이션합니다. 이 고객은 이미 CDB/PDB 모델에 온프레미스 Oracle 데이터베이스를 구축한 것으로 가정합니다. 이 툴킷을 통해 고객은 Oracle PDB 재배치 절차를 사용하여 Oracle 호스트의 컨테이너 데이터베이스에서 이름이 지정된 PDB를 재배치할 수 있으며 최대 가용성 옵션을 사용할 수 있습니다. 즉, 모든 온프레미스 스토리지 어레이의 소스 PDB는 서비스 중단을 최소화하면서 새 컨테이너 데이터베이스로 재배치됩니다. Oracle 재배치 절차는 데이터베이스가 온라인 상태일 때 Oracle 데이터 파일을 이동합니다. 이후 모든 데이터 파일이 AWS 클라우드로 이동할 때 전환 시점에 사용자 세션을 사내에서 재배치된 데이터베이스 서비스로 다시 라우팅합니다. 밑줄이 그어진 기술은 검증된 Oracle PDB 핫 클론 방법론입니다.


NOTE: 마이그레이션 툴킷은 AWS 클라우드 인프라에서 개발 및 검증되었지만 Oracle 애플리케이션 레벨 솔루션을 기반으로 합니다. 따라서 이 툴킷은 Azure, GCP 등의 다른 퍼블릭 클라우드 플랫폼에 적용할 수 있습니다

이 솔루션은 다음과 같은 사용 사례를 해결합니다.

* 온프레미스 소스 DB 서버에서 마이그레이션 사용자를 생성하고 필요한 권한을 부여합니다.
* 소스 PDB가 전환될 때까지 온라인 상태인 동안 온-프레미스 CDB에서 클라우드의 대상 CDB로 PDB를 재배치합니다.




== 대상

이 솔루션은 다음과 같은 사용자를 대상으로 합니다.

* Oracle 데이터베이스를 온라인으로 이전하는 DBA입니다.
* Oracle 데이터베이스를 AWS 클라우드로 마이그레이션하는 데 관심이 있는 데이터베이스 솔루션 설계자
* Oracle 데이터베이스를 지원하는 AWS FSx ONTAP 스토리지를 관리하는 스토리지 관리자
* Oracle 데이터베이스를 현재 베타 버전에서 AWS 클라우드로 마이그레이션하고자 하는 애플리케이션 소유자




== 라이센스

이 GitHub 리포지토리의 콘텐츠를 액세스, 다운로드, 설치 또는 사용하면 에 설명된 사용권 조항에 동의하는 것입니다 link:https://github.com/NetApp/na_ora_hadr_failover_resync/blob/master/LICENSE.TXT["라이센스 파일"^].


NOTE: 이 GitHub 저장소의 컨텐츠와 파생 저작물을 제작 및/또는 공유하는 데는 일정한 제한이 있습니다. 콘텐츠를 사용하기 전에 라이센스 약관을 읽었는지 확인하십시오. 모든 약관에 동의하지 않는 경우 이 리포지토리에 있는 콘텐츠에 액세스하거나 다운로드하거나 사용하지 마십시오.



== 솔루션 구축



=== 배포를 위한 사전 요구 사항

[%collapsible]
====
배포에는 다음과 같은 사전 요구 사항이 필요합니다.

....
Ansible v.2.10 and higher
ONTAP collection 21.19.1
Python 3
Python libraries:
  netapp-lib
  xmltodict
  jmespath
....
....
Source Oracle CDB with PDBs on-premises
Target Oracle CDB in AWS hosted on FSx and EC2 instance
Source and target CDB on same version and with same options installed
....
....
Network connectivity
  Ansible controller to source CDB
  Ansible controller to target CDB
  Source CDB to target CDB on Oracle listener port (typical 1521)
....
====


=== 툴킷을 다운로드합니다

[%collapsible]
====
[source, cli]
----
git clone https://github.com/NetApp/na_ora_aws_migration.git
----
====


=== 호스트 변수 구성

[%collapsible]
====
호스트 변수는 이름이 {{host_name}}.yml인 host_vars 디렉토리에 정의됩니다. 일반적인 구성을 보여 주는 호스트 변수 파일 HOST_NAME.yml 예가 포함되어 있습니다. 주요 고려 사항은 다음과 같습니다.

....
Source Oracle CDB - define host specific variables for the on-prem CDB
  ansible_host: IP address of source database server host
  source_oracle_sid: source Oracle CDB instance ID
  source_pdb_name: source PDB name to migrate to cloud
  source_file_directory: file directory of source PDB data files
  target_file_directory: file directory of migrated PDB data files
....
....
Target Oracle CDB - define host specific variables for the target CDB including some variables for on-prem CDB
  ansible_host: IP address of target database server host
  target_oracle_sid: target Oracle CDB instance ID
  target_pdb_name: target PDB name to be migrated to cloud (for max availability option, the source and target PDB name must be the same)
  source_oracle_sid: source Oracle CDB instance ID
  source_pdb_name: source PDB name to be migrated to cloud
  source_port: source Oracle CDB listener port
  source_oracle_domain: source Oracle database domain name
  source_file_directory: file directory of source PDB data files
  target_file_directory: file directory of migrated PDB data files
....
====


=== DB 서버 호스트 파일 구성

[%collapsible]
====
AWS EC2 인스턴스는 기본적으로 호스트 이름 지정을 위해 IP 주소를 사용합니다. Ansible용 hosts 파일에서 다른 이름을 사용하는 경우 소스 및 대상 서버에 대해 /etc/hosts 파일에서 호스트 이름 확인을 설정합니다. 다음은 예제입니다.

....
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
172.30.15.96 source_db_server
172.30.15.107 target_db_server
....
====


=== Playbook 실행 - 순서대로 실행

[%collapsible]
====
. Ansible 컨트롤러 사전 요구사항을 설치합니다.
+
[source, cli]
----
ansible-playbook -i hosts requirements.yml
----
+
[source, cli]
----
ansible-galaxy collection install -r collections/requirements.yml --force
----
. 온프레미스 서버에 대해 사전 마이그레이션 작업 실행 - 관리자가 sudo 권한이 있는 온프레미스 Oracle 호스트에 연결하기 위한 ssh 사용자라고 가정합니다.
+
[source, cli]
----
ansible-playbook -i hosts ora_pdb_relocate.yml -u admin -k -K -t ora_pdb_relo_onprem
----
. 온프레미스 CDB에서 AWS EC2 인스턴스의 타겟 CDB로의 Oracle PDB 재배치 실행 - EC2 DB 인스턴스 연결의 경우 EC2 사용자 가정, EC2 사용자 ssh 키 쌍의 db1.pem
+
[source, cli]
----
ansible-playbook -i hosts ora_pdb_relocate.yml -u ec2-user --private-key db1.pem -t ora_pdb_relo_primary
----


====


== 추가 정보를 찾을 수 있는 위치

NetApp 솔루션 자동화에 대한 자세한 내용은 다음 웹 사이트를 참조하십시오 link:https://docs.netapp.com/us-en/netapp-solutions/automation/automation_introduction.html["NetApp 솔루션 자동화"^]
