---
sidebar: sidebar 
permalink: databases/automation_ora_clone_gcnv_asm.html 
keywords: Oracle, GCP, GCNV, Database, clone 
summary: 이 솔루션은 Google Cloud NetApp Volumes 스토리지의 ASM 구성이 포함된 Google Cloud에서 호스팅되는 Oracle Data Guard의 물리적 대기 데이터베이스에서 Oracle 클론 데이터베이스를 설정, 클론 복제, 업데이트하기 위한 Ansible 기반 자동화 툴킷을 제공합니다. 
---
= ASM을 사용하여 GCNV에서 Oracle Clone Lifecycle 자동화
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Allen Cao, Niyaz Mohamed, NetApp

[role="lead"]
이 솔루션은 Google Cloud NetApp Volumes 스토리지의 ASM 구성이 포함된 Google Cloud에서 호스팅되는 Oracle Data Guard의 물리적 대기 데이터베이스에서 Oracle 클론 데이터베이스를 설정, 클론 복제, 업데이트하기 위한 Ansible 기반 자동화 툴킷을 제공합니다.



== 목적

Oracle Data Guard 구성에서 물리적 대기 Oracle 데이터베이스의 빠른 클론을 다른 활용 사례에 활용할 수 있습니다. 또한 실시간 보고 데이터베이스와 개발 또는 UAT 목적으로 프로덕션 데이터베이스의 쓰기 가능한 복제본을 제공합니다. 따라서 보고의 짧은 지연(10-15분)이 허용될 경우 고가의 Active Data Guard 라이센스 비용을 절감할 수 있습니다. 특히 운영 데이터 볼륨의 씬 클론을 옵션으로 제공하는 경우 스토리지 비용이 절감됩니다. Ansible 기반 자동화 툴킷은 사용자가 사용자 일정에 맞게 클론 복제된 Oracle 데이터베이스를 설정, 클론 복제 및 교체할 수 있도록 지원하여 라이프사이클 관리를 간소화할 수 있도록 합니다. 이 툴킷은 Google Cloud NetApp 볼륨(GCNV) 스토리지 및 Data Guard 구성의 Oracle 데이터베이스 설정을 사용하여 Google 퍼블릭 클라우드에 구축된 Oracle 데이터베이스에 적용됩니다.

이 솔루션은 다음과 같은 사용 사례를 해결합니다.

* Ansible 자동화를 위한 Oracle 대기 데이터베이스 클론 구성 파일 설정
* 사용자 정의 일정에 따라 Ansible 플레이북을 사용하여 Data Guard 대기에서 클론 Oracle 데이터베이스를 생성하거나 업데이트합니다.




== 대상

이 솔루션은 다음과 같은 사용자를 대상으로 합니다.

* Google 클라우드에서 Oracle 데이터베이스를 관리하는 DBA입니다.
* Google NetApp 볼륨 스토리지를 관리하는 스토리지 관리자
* 다른 사용 사례를 위해 Data Guard 대기에서 Oracle 데이터베이스를 복제하려는 애플리케이션 소유자




== 라이센스

이 GitHub 리포지토리의 콘텐츠를 액세스, 다운로드, 설치 또는 사용하면 에 설명된 사용권 조항에 동의하는 것입니다 link:https://github.com/NetApp/na_ora_hadr_failover_resync/blob/master/LICENSE.TXT["라이센스 파일"^].


NOTE: 이 GitHub 저장소의 컨텐츠와 파생 저작물을 제작 및/또는 공유하는 데는 일정한 제한이 있습니다. 콘텐츠를 사용하기 전에 라이센스 약관을 읽었는지 확인하십시오. 모든 약관에 동의하지 않는 경우 이 리포지토리에 있는 콘텐츠에 액세스하거나 다운로드하거나 사용하지 마십시오.



== 솔루션 구축



=== 배포를 위한 사전 요구 사항

[%collapsible%open]
====
배포에는 다음과 같은 사전 요구 사항이 필요합니다.

....
Ansible controller:
  Ansible v.2.10 and higher
  ONTAP collection 21.19.1
  Python 3
  Python libraries:
    netapp-lib
    xmltodict
    jmespath
....
....
Oracle servers:
  Physical standby Oracle servers in Data Guard configuration
  Clone target Oracle servers with ASM configuration
....

NOTE: 간소화를 위해 클론 타겟 Oracle 서버는 Oracle 소프트웨어 스택과 같은 대기 Oracle 서버뿐 아니라 Oracle Home 등의 디렉토리 레이아웃과도 동일하게 구성해야 합니다

====


=== 툴킷을 다운로드합니다

[%collapsible%open]
====
[source, cli]
----
https://bitbucket.ngage.netapp.com/projects/NS-BB/repos/na_oracle_clone_gcnv/browse
----

NOTE: 이 툴킷은 현재 BitBucket 액세스 권한이 있는 NetApp 내부 사용자만 액세스할 수 있습니다. 외부 사용자에 관심이 있는 경우, 어카운트 팀에서 액세스 권한을 요청하거나 NetApp 솔루션 엔지니어링 팀에 문의하십시오.

====


=== Ansible 소스 및 타겟 호스트의 파일 구성

[%collapsible%open]
====
이 툴킷에는 Ansible 플레이북이 실행되는 Oracle 호스트의 소스와 대상을 정의하는 hosts 파일이 포함되어 있습니다. 일반적으로 Data Guard 설정의 대기 DB 호스트와 대상 Oracle 클론 호스트가 포함됩니다. 다음은 예제 파일입니다. 호스트 항목에는 타겟 호스트 IP 주소와 클론 또는 새로 고침 명령을 실행하기 위해 호스트에 대한 사용자 액세스를 위한 ssh 키가 포함됩니다. Google Cloud NetApp 볼륨 스토리지는 gcloud CLI를 통해 액세스 및 관리됩니다.

....
[ora_stdby]
oras ansible_host=172.179.119.75 ansible_ssh_private_key_file=oras.pem
....
....
[ora_clone]
orac ansible_host=52.148.142.212 ansible_ssh_private_key_file=orac.pem
....
....
[gcp]
localhost ansible_connection=local
....
====


=== 글로벌 변수 설정

[%collapsible%open]
====
다음은 전역 수준에서 적용 가능한 변수를 포함하는 일반적인 전역 변수 파일 vars.yml의 예입니다.

....
######################################################################
###### Oracle DB clone on GCNV user configuration variables     ######
###### Consolidate all variables from GCNV, linux and oracle    ######
######################################################################
....
....
############################################
### ONTAP/GCNV specific config variables ###
############################################
....
....
# GCNV credential
key_file: /home/admin/google-cloud-sdk/service_key.json
....
....
# Cloned DB volumes from standby DB
project_id: cvs-pm-host-1p
location: us-west4
protocol: nfsv3
data_vols:
  - "{{ groups.ora_stdby[0] }}-u02"
  - "{{ groups.ora_stdby[0] }}-u03"
  - "{{ groups.ora_stdby[0] }}-u04"
  - "{{ groups.ora_stdby[0] }}-u05"
  - "{{ groups.ora_stdby[0] }}-u06"
  - "{{ groups.ora_stdby[0] }}-u07"
  - "{{ groups.ora_stdby[0] }}-u08"
....
....
nfs_lifs:
  - 10.165.128.197
  - 10.165.128.196
  - 10.165.128.197
  - 10.165.128.197
  - 10.165.128.197
  - 10.165.128.197
  - 10.165.128.197
....
 nfs_client: 0.0.0.0/0
....
###########################################
### Linux env specific config variables ###
###########################################
....
....
####################################################
### DB env specific install and config variables ###
####################################################
....
....
# Standby DB configuration
oracle_user: oracle
oracle_base: /u01/app/oracle
oracle_sid: NTAP
db_unique_name: NTAP_LA
oracle_home: '{{ oracle_base }}/product/19.0.0/{{ oracle_sid }}'
spfile: '+DATA/{{ db_unique_name }}/PARAMETERFILE/spfile.289.1198520783'
adump: '{{ oracle_base }}/admin/{{ db_unique_name }}/adump'
grid_home: /u01/app/oracle/product/19.0.0/grid
asm_disk_groups:
  - DATA
  - LOGS
....
....
# Clond DB configuration
clone_sid: NTAPDEV
sys_pwd: "XXXXXXXX"
....
....
# Data Guard mode - MaxAvailability or MaxPerformance
dg_mode: MaxAvailability
....
====


=== 호스트 변수 구성

[%collapsible%open]
====
호스트 변수는 특정 호스트에만 적용되는 {{host_name}}.yml로 명명된 host_vars 디렉토리에 정의됩니다. 이 솔루션에서는 타겟 클론 DB 호스트 매개 변수 파일만 구성됩니다. Oracle 스탠바이 DB 매개 변수는 글로벌 VAR 파일로 구성됩니다. 다음은 일반적인 구성을 보여 주는 타겟 Oracle 클론 DB 호스트 변수 파일 Orac.yml의 예입니다.

 # User configurable Oracle clone host specific parameters
....
# Database SID - clone DB SID
oracle_base: /u01/app/oracle
oracle_user: oracle
clone_sid: NTAPDEV
oracle_home: '{{ oracle_base }}/product/19.0.0/{{ oracle_sid }}'
clone_adump: '{{ oracle_base }}/admin/{{ clone_sid }}/adump'
....
....
grid_user: oracle
grid_home: '{{ oracle_base }}/product/19.0.0/grid'
asm_sid: +ASM
....
====


=== 추가 클론 대상 Oracle 서버 구성

[%collapsible%open]
====
클론 대상 Oracle 서버는 소스 Oracle 서버와 동일한 Oracle 소프트웨어 스택을 설치 및 패치해야 합니다. Oracle user.bash_profile에 $ORACLE_BASE 및 $ORACLE_HOME이 구성되어 있습니다. 또한 $ORACLE_HOME 변수는 소스 Oracle 서버 설정과 일치해야 합니다. 대상 ORACLE_HOME 설정이 대기 Oracle 서버 구성과 다른 경우 심볼 링크를 생성하여 차이점을 해결하십시오. 다음은 예제입니다.

 # .bash_profile
....
# Get the aliases and functions
if [ -f ~/.bashrc ]; then
       . ~/.bashrc
fi
....
 # User specific environment and startup programs
....
export ORACLE_BASE=/u01/app/oracle
export GRID_HOME=/u01/app/oracle/product/19.0.0/grid
export ORACLE_HOME=/u01/app/oracle/product/19.0.0/NTAP
alias asm='export ORACLE_HOME=$GRID_HOME;export PATH=$PATH:$GRID_HOME/bin;export ORACLE_SID=+ASM'
....

NOTE: DB 클론 호스트의 ASM_diskstring 구성 매개 변수에 클론 생성된 모든 볼륨 NFS 마운트 지점 및 디스크 디바이스에 대한 디렉토리 경로가 포함되어 있는지 확인합니다.

====


=== 플레이북 실행

[%collapsible%open]
====
Oracle 데이터베이스 클론 수명주기를 실행하기 위한 플레이북은 총 2개입니다. DB 클론 또는 새로 고침은 필요에 따라 실행하거나 crontab 작업으로 예약할 수 있습니다.

. Ansible 컨트롤러 사전 요구사항 설치 - 한 번만.
+
[source, cli]
----
ansible-playbook -i hosts ansible_requirements.yml
----
. 필요 시 또는 crontab에서 클론 데이터베이스를 생성하고 정기적으로 업데이트하여 클론 또는 플레이북을 호출하도록 셸 스크립트를 사용합니다.
+
[source, cli]
----
ansible-playbook -i oracle_clone_asm_gcnv.yml -u admin -e @vars/vars.yml
----
+
[source, cli]
----
0 */2 * * * /home/admin/na_oracle_clone_gcnv/oracle_clone_asm_gcnv.sh
----


추가 데이터베이스를 복제하려면 별도의 oracle_clone_n_asm_gcnv.yml 및 oracle_clone_n_asm_gcnv.sh를 생성합니다. host_vars 디렉토리에 Ansible 타겟 호스트, 글로벌 vars.yml 및 hostname.yml 파일을 적절히 구성합니다.


NOTE: 특정 작업을 완료할 수 있도록 여러 단계에서 툴킷을 실행할 때 일시 중지됩니다. 예를 들어 DB 볼륨 클론이 완료될 수 있도록 2분 동안 일시 중지됩니다. 일반적으로 채무불이행은 충분해야 하지만 타이밍은 고유한 상황이나 구현에 맞춰 조정해야 할 수 있습니다.

====


== 추가 정보를 찾을 수 있는 위치

NetApp 솔루션 자동화에 대한 자세한 내용은 다음 웹 사이트를 참조하십시오 link:../automation/automation_introduction.html["NetApp 솔루션 자동화"^]
