---
sidebar: sidebar 
permalink: databases/aws_ora_fsx_ec2_migration.html 
summary: 이 섹션에서는 사내에서 AWS EC2 인스턴스 및 FSx 스토리지로 Oracle 데이터베이스를 마이그레이션할 때 고려해야 할 요소에 대해 자세히 설명합니다. 
keywords: HA, DR, database, Oracle, RDS, AWS, SnapCenter 
---
= 사내에서 퍼블릭 클라우드로 데이터베이스 마이그레이션
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


link:aws_ora_fsx_ec2_mgmt.html["이전: 데이터베이스 관리."]

데이터베이스 마이그레이션은 어떤 방법으로든 어려운 작업입니다. Oracle 데이터베이스를 사내에서 클라우드로 마이그레이션하는 경우도 예외는 아닙니다.

다음 섹션에서는 Oracle 데이터베이스를 AWS EC2 컴퓨팅 및 FSx 스토리지 플랫폼을 통해 AWS 퍼블릭 클라우드로 마이그레이션할 때 고려해야 할 주요 요소를 제공합니다.



== ONTAP 스토리지는 온프레미스에서 사용할 수 있습니다

온프레미스 Oracle 데이터베이스가 ONTAP 스토리지 어레이에 앉아 있는 경우 NetApp SnapCenter UI 툴을 사용하여 데이터베이스 마이그레이션을 위한 복제를 쉽게 설정할 수 있습니다.

. 온프레미스 인스턴스와 일치하는 타겟 컴퓨팅 EC2 인스턴스를 구축합니다.
. FSx 콘솔에서 동일한 크기의 일치하는 데이터베이스 볼륨을 프로비저닝합니다.
. FSx 데이터베이스 볼륨을 EC2 인스턴스에 마운트합니다.
. 온프레미스 데이터베이스 볼륨에서 타겟 FSx 데이터베이스 볼륨으로의 SnapMirror 복제를 설정합니다. 초기 동기화는 운영 소스 데이터를 이동하는 데 시간이 다소 걸릴 수 있지만 다음과 같은 증분 업데이트는 훨씬 더 빠릅니다.
. 전환 시 운영 애플리케이션을 종료하여 모든 트랜잭션을 중지합니다. SnapCenter에서 로그 백업을 실행하여 나머지 트랜잭션을 타겟으로 플러시합니다.
. 미러링된 볼륨을 분할하고 타겟에서 Oracle 복구를 실행하고 서비스를 위해 데이터베이스를 불러옵니다.
. 애플리케이션을 클라우드의 Oracle 데이터베이스에 지정




== ONTAP 스토리지는 온프레미스에서 사용할 수 없습니다

사내 Oracle 데이터베이스가 ONTAP 이외의 타사 스토리지에서 호스팅되는 경우 데이터베이스 마이그레이션은 Oracle 데이터베이스 백업 복사본의 복원을 기반으로 합니다. 전환하기 전에 아카이브 로그를 재생하여 최신 상태로 만들어야 합니다.

AWS S3를 데이터베이스 이동 및 마이그레이션을 위한 스테이징 스토리지 영역으로 사용할 수 있습니다. 이 방법에 대한 자세한 내용은 다음 단계를 참조하십시오.

. 사내 인스턴스와 유사한 새로운 EC2 인스턴스를 프로비저닝합니다.
. FSx 스토리지에서 동일한 데이터베이스 볼륨을 프로비저닝하고 EC2 인스턴스에 볼륨을 마운트합니다.
. 디스크 레벨의 Oracle 백업 복사본을 생성합니다.
. 백업 복사본을 AWS S3 스토리지로 이동합니다.
. S3 스토리지에서 데이터와 아카이브 로그를 가져와 Oracle 제어 파일을 다시 생성하고 데이터베이스를 복원 및 복구합니다.
. 타겟 Oracle 데이터베이스를 사내 소스 데이터베이스와 동기화합니다.
. 전환 시 애플리케이션과 소스 Oracle 데이터베이스를 종료합니다. 최근 몇 개의 아카이브 로그를 복사하여 대상 Oracle 데이터베이스에 적용하여 최신 상태로 만듭니다.
. 사용자 액세스를 위해 대상 데이터베이스를 시작합니다.
. 대상 데이터베이스로 애플리케이션을 리디렉션하여 전환을 완료합니다.




== Oracle 멀티 테넌시 CDB/PDB 아키텍처를 사용하여 AWS에서 Oracle 데이터베이스를 통합합니다

. AWS 퍼블릭 클라우드에서 CDB를 생성합니다.
. 온-프레미스 데이터베이스가 CDB/PDB 멀티 테넌시에도 배포된 경우 마이그레이션할 PDB를 언플러그합니다.
. 메타데이터를 전송하고 밑줄이 그어진 Oracle 데이터 파일을 대상 CDB 인스턴스로 전송합니다.
. Oracle 검증 절차와의 호환성을 검증합니다.
. 호환성 검증이 통과하면 언플러그된 PDB를 대상 CDB 컨테이너에 연결합니다.
. 필요한 경우 데이터 사전을 업데이트합니다.
. 액세스를 위해 마이그레이션된 PDB를 백업하고 엽니다.



NOTE: PDB 언플러그 및 플러그인에는 마이그레이션 계획 중에 고려해야 하는 애플리케이션 다운타임이 필요합니다.

또한, NetApp 자동화 팀은 사내에서 AWS 클라우드로 Oracle 데이터베이스를 손쉽게 마이그레이션할 수 있는 마이그레이션 툴킷을 제공합니다. 최신 데이터베이스 마이그레이션 툴은 NetApp 퍼블릭 GitHub 사이트를 참조하십시오.
