---
sidebar: sidebar 
permalink: databases/awx_automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 이 페이지에서는 NetApp ONTAP 스토리지에 Oracle19c를 구축하는 자동화된 방법에 대해 설명합니다. 
---
= 단계별 배포 절차
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== AWX/Tower 구축 Oracle 19c Database



=== 환경의 인벤토리, 그룹, 호스트 및 자격 증명을 생성합니다

이 섹션에서는 NetApp 자동화 솔루션을 사용하는 환경을 준비하기 위해 AWX/Ansible 타워에서 인벤토리, 그룹, 호스트, 액세스 자격 증명을 설정하는 방법을 설명합니다.

. 인벤토리를 구성합니다.
+
.. Resources(리소스) → Inventory(인벤토리) → Add(추가) 로 이동하고 Add Inventory(재고 추가) 를 클릭합니다.
.. 이름 및 조직 세부 정보를 입력하고 저장 을 클릭합니다.
.. 재고 페이지에서 생성된 재고를 클릭합니다.
.. 재고 변수가 있는 경우 변수 필드에 붙여 넣습니다.
.. Groups 하위 메뉴로 이동하여 Add를 클릭합니다.
.. ONTAP 그룹 이름을 입력하고 그룹 변수(있는 경우)를 붙여 넣은 다음 저장을 클릭합니다.
.. Oracle에 대해 다른 그룹에 대해서도 이 프로세스를 반복합니다.
.. 생성된 ONTAP 그룹을 선택하고 Hosts 하위 메뉴로 이동한 다음 Add New Host를 클릭합니다.
.. ONTAP 클러스터 관리 IP의 IP 주소를 제공하고 호스트 변수(있는 경우)를 붙여 넣은 다음 저장 을 클릭합니다.
.. Oracle 그룹 및 Oracle 호스트 관리 IP/호스트 이름에 대해 이 프로세스를 반복해야 합니다.


. 자격 증명 유형을 만듭니다. ONTAP와 관련된 솔루션의 경우 자격 증명 유형을 사용자 이름 및 암호 항목과 일치하도록 구성해야 합니다.
+
.. Administration → Credential Types로 이동한 후 Add를 클릭합니다.
.. 이름과 설명을 입력합니다.
.. 입력 구성에 다음 내용을 붙여 넣습니다.
+
[source, cli]
----
fields:
  - id: username
    type: string
    label: Username
  - id: password
    type: string
    label: Password
    secret: true
  - id: vsadmin_password
    type: string
    label: vsadmin_password
    secret: true
----
.. 다음 내용을 주입기 구성에 붙여넣습니다.
+
[source, cli]
----
extra_vars:
  password: '{{ password }}'
  username: '{{ username }}'
  vsadmin_password: '{{ vsadmin_password }}'
----


. 자격 증명을 구성합니다.
+
.. Resources → Credentials로 이동한 후 Add를 클릭합니다.
.. ONTAP의 이름과 조직 세부 정보를 입력합니다.
.. ONTAP에 대해 만든 사용자 지정 자격 증명 유형을 선택합니다.
.. 세부 정보 입력 아래에 사용자 이름, 암호 및 vsadmin_password를 입력합니다.
.. 자격 증명으로 돌아가기 를 클릭하고 추가 를 클릭합니다.
.. Oracle의 이름 및 조직 세부 정보를 입력합니다.
.. 시스템 자격 증명 유형을 선택합니다.
.. 유형 세부 정보 에서 Oracle 호스트의 사용자 이름 및 암호를 입력합니다.
.. 올바른 권한 에스컬레이션 방법을 선택하고 사용자 이름과 암호를 입력합니다.






=== 프로젝트를 만듭니다

. Resources → Projects로 이동하여 Add를 클릭합니다.
+
.. 이름 및 조직 세부 정보를 입력합니다.
.. 소스 제어 자격 증명 유형 필드에서 Git 를 선택합니다.
.. 를 입력합니다 <https://github.com/NetApp-Automation/na_oracle19c_deploy.git>[] 소스 제어 URL입니다.
.. 저장 을 클릭합니다.
.. 소스 코드가 변경되면 프로젝트를 가끔 동기화해야 할 수 있습니다.






=== Oracle host_VAR을 구성합니다

이 섹션에 정의된 변수는 각 개별 Oracle 서버 및 데이터베이스에 적용됩니다.

. 다음과 같은 내장된 Oracle hosts 변수 또는 host_vars 양식에 환경별 매개 변수를 입력합니다.



NOTE: 파란색 항목은 환경에 맞게 변경해야 합니다.



=== 호스트 VAR 구성


. 파란색 필드에 모든 변수를 입력합니다.
. 변수 입력을 완료한 후 양식의 복사 버튼을 클릭하여 AWX 또는 타워로 전송할 모든 변수를 복사합니다.
. AWX 또는 Tower로 돌아가서 Resources → Hosts 로 이동한 다음 Oracle 서버 구성 페이지를 선택하여 엽니다.
. 세부 정보 탭에서 편집 을 클릭하고 1단계에서 복사한 변수를 YAML 탭의 변수 필드에 붙여 넣습니다.
. 저장 을 클릭합니다.
. 시스템에 있는 모든 추가 Oracle 서버에 대해 이 프로세스를 반복합니다.




=== 글로벌 변수를 설정합니다

이 섹션에 정의된 변수는 모든 Oracle 호스트, 데이터베이스 및 ONTAP 클러스터에 적용됩니다.

. 다음 임베디드 글로벌 변수 또는 VAR 양식에 환경별 매개 변수를 입력합니다.
+

NOTE: 파란색 항목은 환경에 맞게 변경해야 합니다.





=== VAR


. 파란색 필드에 모든 변수를 입력합니다.
. 변수 입력을 완료한 후 양식의 복사 버튼을 클릭하여 AWX 또는 Tower로 전송할 모든 변수를 다음 작업 템플릿으로 복사합니다.




=== 작업 템플릿을 구성하고 시작합니다.

. 작업 템플릿을 작성합니다.
+
.. Resources → Templates → Add로 이동하여 Add Job Template을 클릭합니다.
.. 이름과 설명을 입력합니다
.. 작업 유형을 선택합니다. Run은 Playbook을 기반으로 시스템을 구성하고 Check는 실제로 시스템을 구성하지 않고 Playbook을 건조하게 실행합니다.
.. Playbook의 해당 인벤토리, 프로젝트, 플레이북 및 자격 증명을 선택합니다.
.. All_Playbook.yml을 실행할 기본 플레이북으로 선택합니다.
.. 4단계에서 복사한 글로벌 변수를 YAML 탭의 템플릿 변수 필드에 붙여 넣습니다.
.. 작업 태그 필드에서 시작 시 프롬프트 표시 확인란을 선택합니다.
.. 저장 을 클릭합니다.


. 작업 템플릿을 시작합니다.
+
.. 리소스 → 템플릿 으로 이동합니다.
.. 원하는 템플릿을 클릭한 다음 실행을 클릭합니다.
.. 작업 태그를 시작할 때 메시지가 나타나면 requirements_config 를 입력합니다. 작업 태그를 입력하려면 requirements_config 아래의 작업 태그 작성 줄을 클릭해야 할 수도 있습니다.
+

NOTE: requirements_config 다른 역할을 실행할 올바른 라이브러리가 있는지 확인합니다.

.. 다음 을 클릭한 다음 시작 을 클릭하여 작업을 시작합니다.
.. 보기 → 작업 을 클릭하여 작업 출력 및 진행률을 모니터링합니다.
.. 작업 태그를 시작할 때 프롬프트가 표시되면 ONTAP_config를 입력합니다. ONTAP_config 바로 아래에 있는 "작업 태그" 생성 라인을 클릭하여 작업 태그를 입력해야 할 수 있습니다.
.. 다음 을 클릭한 다음 시작 을 클릭하여 작업을 시작합니다.
.. 보기 → 작업 을 클릭하여 작업 출력 및 진행률을 모니터링합니다
.. ONTAP_config 역할이 완료된 후 Linux_config에 대해 프로세스를 다시 실행하십시오.
.. 리소스 → 템플릿 으로 이동합니다.
.. 원하는 템플릿을 선택한 다음 실행을 클릭합니다.
.. Linux_config에서 작업 태그 유형을 시작할 때 메시지가 표시되면 Linux_config 바로 아래의 "작업 태그 생성" 행을 선택하여 작업 태그를 입력해야 할 수 있습니다.
.. 다음 을 클릭한 다음 시작 을 클릭하여 작업을 시작합니다.
.. 보기 → 작업 을 선택하여 작업 출력 및 진행률을 모니터링합니다.
.. Linux_config 역할이 완료된 후 ORACLE_config에 대해 프로세스를 다시 실행하십시오.
.. 리소스 → 템플릿 으로 이동합니다.
.. 원하는 템플릿을 선택한 다음 실행을 클릭합니다.
.. 작업 태그 시작 시 메시지가 표시되면 ORACLE_config 를 입력합니다. 작업 태그를 입력하려면 ORACLE_config 바로 아래에 있는 "작업 태그 생성" 행을 선택해야 할 수 있습니다.
.. 다음 을 클릭한 다음 시작 을 클릭하여 작업을 시작합니다.
.. 보기 → 작업 을 선택하여 작업 출력 및 진행률을 모니터링합니다.






=== 동일한 Oracle 호스트에 추가 데이터베이스를 구축합니다

플레이북의 Oracle 부분은 실행 당 Oracle 서버에 단일 Oracle 컨테이너 데이터베이스를 생성합니다. 동일한 서버에 추가 컨테이너 데이터베이스를 만들려면 다음 단계를 완료하십시오.

. host_vars 변수를 수정합니다.
+
.. 2단계 - Configure Oracle host_VAR로 돌아갑니다.
.. Oracle SID를 다른 명명 문자열로 변경합니다.
.. 수신기 포트를 다른 번호로 변경합니다.
.. EM Express를 설치할 경우 EM Express 포트를 다른 번호로 변경하십시오.
.. 호스트 구성 세부 정보 탭의 Oracle 호스트 변수 필드에 수정된 호스트 변수를 복사하여 붙여 넣습니다.


. ORACLE_config 태그만 사용하여 구축 작업 템플릿을 시작합니다.




=== Oracle 설치를 검증합니다


[source, cli]
----
ps -ef | grep ora
----

NOTE: 설치가 예상대로 완료되고 Oracle DB가 시작되면 Oracle 프로세스가 나열됩니다


[source, cli]
----
sqlplus / as sysdba
----
[oracle@localhost~]$sqlplus/as sysdba

SQL* Plus: 릴리스 19.0.0.0.0 - 5월 6일 목요일 프로덕션 12:52:51 2021년 버전 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle. 모든 권리 보유.

연결 대상: Oracle Database 19c Enterprise Edition 릴리스 19.0.0.0.0 - 프로덕션 버전 19.8.0.0.0

sql> 을 클릭합니다

[source, cli]
----
select name, log_mode from v$database;
----
sql> v$database에서 이름, log_mode 선택; name log_mode--------- ---------- CDB2 ARCHIVELOG

[source, cli]
----
show pdbs;
----
sql > PDB 표시

....
    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO
....
[source, cli]
----
col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;
----
sql> col svrname form a30 sql> col dirname form a30 sql> v$dnfs_servers에서 svrname, dirname, nfsversion을 선택합니다.

SVRNAME dirname NFSVERSION------------------------------------------------------------ ------------------------------------------------------------ --------------- 172.21.126.200/rhelora03_u02 NFSv3.0 172.21.126.200/rhelora03_uNFSv03 3.0 172.21.126.200/rhelora03_u01 NFSv3.0

[listing]
----
This confirms that dNFS is working properly.
----

[source, cli]
----
sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com
----
[Oracle@localhost~]$sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com

SQL* Plus: 릴리스 19.0.0.0.0 - 5월 6일 13:19:57 2021년 11월 19일 버전 19.8.0.0.0의 목요일 프로덕션

Copyright (c) 1982, 2019, Oracle. 모든 권리 보유.

비밀번호 입력: 마지막으로 성공한 로그인 시간: 2021년 5월 5일 17:11:11-04:00

연결 대상: Oracle Database 19c Enterprise Edition 릴리스 19.0.0.0.0 - 프로덕션 버전 19.8.0.0.0

sql> show user is "system" sql> show con_name con_name CDB2_PDB1

[listing]
----
This confirms that Oracle listener is working properly.
----


=== 도움을 받을 수 있는 곳

툴킷에 대한 도움이 필요한 경우 에 가입하십시오 link:https://netapppub.slack.com/archives/C021R4WC0LC["NetApp 솔루션 자동화 커뮤니티는 여유 채널을 지원합니다"] 질문 또는 질문을 게시할 수 있는 솔루션 자동화 채널을 찾아보십시오.
