---
sidebar: sidebar 
permalink: databases/cli_automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 이 페이지에서는 NetApp ONTAP 스토리지에 Oracle19c를 구축하는 자동화된 방법에 대해 설명합니다. 
---
= 단계별 배포 절차
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== CLI 구축 Oracle 19c Database

이 섹션에서는 CLI를 사용하여 Oracle19c 데이터베이스를 준비하고 배포하는 데 필요한 단계를 설명합니다. 을(를) 검토했는지 확인합니다 link:getting_started_requirements.html["시작하기 및 요구 사항 섹션을 참조하십시오"] 적절히 대비했습니다.



=== Oracle19c repo 를 다운로드합니다


[source, cli]
----
git clone https://github.com/NetApp-Automation/na_oracle19c_deploy.git
----



=== HOSTS 파일을 편집합니다

배포 전에 다음을 완료합니다.

. 호스트 파일 na_oracle19c_deploy 디렉토리를 편집합니다.
. [ONTAP] 아래에서 IP 주소를 클러스터 관리 IP로 변경합니다.
. [Oracle] 그룹에서 Oracle 호스트 이름을 추가합니다. 호스트 이름은 DNS 또는 호스트 파일을 통해 IP 주소로 확인되거나 호스트에 지정되어야 합니다.
. 이 단계를 완료한 후 변경 사항을 저장합니다.


다음 예에서는 호스트 파일을 보여 줍니다.


이 예에서는 Playbook을 실행하고 두 개의 Oracle DB 서버에 동시에 Oracle 19c를 구축합니다. 하나의 DB 서버만으로 테스트할 수도 있습니다. 이 경우 하나의 호스트 변수 파일만 구성하면 됩니다.


NOTE: 이 플레이북은 구축하는 Oracle 호스트 및 데이터베이스의 수에 관계없이 동일한 방식으로 실행됩니다.



=== host_name.yml 파일을 host_vars에서 편집합니다

각 Oracle 호스트에는 호스트별 변수를 포함하는 호스트 이름으로 식별되는 호스트 변수 파일이 있습니다. 호스트 이름을 지정할 수 있습니다. Host VAR Config 섹션에서 host_vars를 편집 및 복사하고 원하는 host_name.yml 파일에 붙여 넣습니다.


NOTE: 파란색 항목은 환경에 맞게 변경해야 합니다.



=== 호스트 VAR 구성




=== VAR.yml 파일을 편집합니다

VAR.yml 파일은 Oracle 구축을 위해 모든 환경 관련 변수(ONTAP, Linux 또는 Oracle)를 통합합니다.

* VAR 섹션에서 변수를 편집 및 복사하고 해당 변수를 'VAR.yml' 파일에 붙여 넣습니다.




=== VAR




=== 플레이북을 실행합니다

필요한 환경 전제 조건을 완료하고 변수를 VAR.yml과 your_host.yml에 복사하면 이제 Playbook을 배포할 준비가 된 것입니다.


NOTE: 사용자 환경과 일치하도록 <username>을(를) 변경해야 합니다.


[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t ontap_config -e @vars/vars.yml
----

[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t linux_config -e @vars/vars.yml
----

[source, cli]
----
ansible-playbook -i hosts all_playbook.yml -u username -k -K -t oracle_config -e @vars/vars.yml
----


=== 동일한 Oracle 호스트에 추가 데이터베이스를 구축합니다

플레이북의 Oracle 부분은 실행 당 Oracle 서버에 단일 Oracle 컨테이너 데이터베이스를 생성합니다. 동일한 서버에 추가 컨테이너 데이터베이스를 만들려면 다음 단계를 수행하십시오.

. host_vars 변수를 수정합니다.
+
.. 3단계로 돌아가기 - host_vars에서 host_name.yml 파일을 편집합니다.
.. Oracle SID를 다른 명명 문자열로 변경합니다.
.. 수신기 포트를 다른 번호로 변경합니다.
.. EM Express를 설치한 경우 EM Express 포트를 다른 번호로 변경하십시오.
.. 수정된 호스트 변수를 복사하여 'host_vars' 아래의 Oracle 호스트 변수 파일에 붙여넣습니다.


. 위의 에 나와 있는 것처럼 "ORACLE_config" 태그를 사용하여 플레이북을 실행합니다 <<플레이북을 실행합니다>>.




=== Oracle 설치를 검증합니다


[source, cli]
----
ps -ef | grep ora
----

NOTE: 설치가 예상대로 완료되고 Oracle DB가 시작되면 Oracle 프로세스가 나열됩니다


[source, cli]
----
sqlplus / as sysdba
----
[oracle@localhost~]$sqlplus/as sysdba

SQL* Plus: 릴리스 19.0.0.0.0 - 5월 6일 목요일 프로덕션 12:52:51 2021년 버전 19.8.0.0.0

Copyright (c) 1982, 2019, Oracle. 모든 권리 보유.

연결 대상: Oracle Database 19c Enterprise Edition 릴리스 19.0.0.0.0 - 프로덕션 버전 19.8.0.0.0

sql> 을 클릭합니다

[source, cli]
----
select name, log_mode from v$database;
----
sql> v$database에서 이름, log_mode 선택; name log_mode--------- ---------- CDB2 ARCHIVELOG

[source, cli]
----
show pdbs;
----
sql > PDB 표시

....
    CON_ID CON_NAME                       OPEN MODE  RESTRICTED
---------- ------------------------------ ---------- ----------
         2 PDB$SEED                       READ ONLY  NO
         3 CDB2_PDB1                      READ WRITE NO
         4 CDB2_PDB2                      READ WRITE NO
         5 CDB2_PDB3                      READ WRITE NO
....
[source, cli]
----
col svrname form a30
col dirname form a30
select svrname, dirname, nfsversion from v$dnfs_servers;
----
sql> col svrname form a30 sql> col dirname form a30 sql> v$dnfs_servers에서 svrname, dirname, nfsversion을 선택합니다.

SVRNAME dirname NFSVERSION------------------------------------------------------------ ------------------------------------------------------------ --------------- 172.21.126.200/rhelora03_u02 NFSv3.0 172.21.126.200/rhelora03_uNFSv03 3.0 172.21.126.200/rhelora03_u01 NFSv3.0

[listing]
----
This confirms that dNFS is working properly.
----

[source, cli]
----
sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com
----
[Oracle@localhost~]$sqlplus system@//localhost:1523/cdb2_pdb1.cie.netapp.com

SQL* Plus: 릴리스 19.0.0.0.0 - 5월 6일 13:19:57 2021년 11월 19일 버전 19.8.0.0.0의 목요일 프로덕션

Copyright (c) 1982, 2019, Oracle. 모든 권리 보유.

비밀번호 입력: 마지막으로 성공한 로그인 시간: 2021년 5월 5일 17:11:11-04:00

연결 대상: Oracle Database 19c Enterprise Edition 릴리스 19.0.0.0.0 - 프로덕션 버전 19.8.0.0.0

sql> show user is "system" sql> show con_name con_name CDB2_PDB1

[listing]
----
This confirms that Oracle listener is working properly.
----


=== 도움을 받을 수 있는 곳

툴킷에 대한 도움이 필요한 경우 에 가입하십시오 link:https://netapppub.slack.com/archives/C021R4WC0LC["NetApp 솔루션 자동화 커뮤니티는 여유 채널을 지원합니다"] 질문 또는 질문을 게시할 수 있는 솔루션 자동화 채널을 찾아보십시오.
