---
sidebar: sidebar 
permalink: databases/db_protection_awx_automation.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP 
summary: 이 페이지에서는 NetApp ONTAP 스토리지에서 Oracle19c의 자동화된 데이터 보호에 대해 설명합니다. 
---
= 단계별 배포 절차
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== AWX/Tower Oracle 데이터 보호



=== 환경의 인벤토리, 그룹, 호스트 및 자격 증명을 생성합니다

이 섹션에서는 NetApp 자동화 솔루션을 사용하는 환경을 준비하기 위해 AWX/Ansible 타워에서 인벤토리, 그룹, 호스트, 액세스 자격 증명을 설정하는 방법을 설명합니다.

. 인벤토리를 구성합니다.
+
.. Resources(리소스) → Inventory(인벤토리) → Add(추가) 로 이동하고 Add Inventory(재고 추가) 를 클릭합니다.
.. 이름 및 조직 세부 정보를 입력하고 저장 을 클릭합니다.
.. 재고 페이지에서 생성된 재고를 클릭합니다.
.. Groups 하위 메뉴로 이동하여 Add를 클릭합니다.
.. 첫 번째 그룹에 대해 Oracle 이름을 입력하고 저장 을 클릭합니다.
.. DR_ORACLE이라는 두 번째 그룹에 대해 이 프로세스를 반복합니다.
.. 생성된 Oracle 그룹을 선택하고 Hosts 하위 메뉴로 이동한 다음 Add New Host를 클릭합니다.
.. 소스 Oracle 호스트 관리 IP의 IP 주소를 제공하고 Save를 클릭합니다.
.. DR_Oracle 그룹에 대해 이 프로세스를 반복하고 DR/대상 Oracle 호스트의 관리 IP/호스트 이름을 추가해야 합니다.


+

NOTE: 다음은 ONTAP 온프레미스 또는 AWS의 CVO에 대한 자격 증명 유형 및 자격 증명을 생성하는 지침입니다.



[role="tabbed-block"]
====
.사내
--
. 자격 증명을 구성합니다.
. 자격 증명 형식을 만듭니다. ONTAP와 관련된 솔루션의 경우 자격 증명 유형을 사용자 이름 및 암호 항목과 일치하도록 구성해야 합니다.
+
.. Administration → Credential Types로 이동한 후 Add를 클릭합니다.
.. 이름과 설명을 입력합니다.
.. 입력 구성에 다음 내용을 붙여 넣습니다.
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: Destination Cluster Username
  - id: dst_cluster_password
    type: string
    label: Destination Cluster Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
----
.. Injector Configuration(주입기 구성)에 다음 내용을 붙여넣고 Save(저장)를 클릭합니다.
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
----


. ONTAP에 대한 자격 증명을 생성합니다
+
.. Resources → Credentials로 이동한 후 Add를 클릭합니다.
.. ONTAP 자격 증명에 대한 이름과 조직 세부 정보를 입력합니다
.. 이전 단계에서 만든 자격 증명 유형을 선택합니다.
.. 유형 세부 정보 에서 소스 및 대상 클러스터에 대한 사용자 이름 및 암호를 입력합니다.
.. 저장 을 클릭합니다


. Oracle에 대한 자격 증명을 생성합니다
+
.. Resources → Credentials로 이동한 후 Add를 클릭합니다.
.. Oracle의 이름 및 조직 세부 정보를 입력합니다
.. 시스템 자격 증명 유형을 선택합니다.
.. 유형 세부 정보 에서 Oracle 호스트의 사용자 이름 및 암호를 입력합니다.
.. 올바른 권한 에스컬레이션 방법을 선택하고 사용자 이름과 암호를 입력합니다.
.. 저장 을 클릭합니다
.. DR_Oracle 호스트에 대해 다른 자격 증명에 대해 필요한 경우 프로세스를 반복합니다.




--
.CVO
--
. 자격 증명을 구성합니다.
. 자격 증명 유형을 만듭니다. ONTAP와 관련된 솔루션의 경우 자격 증명 유형을 사용자 이름 및 암호 항목과 일치하도록 구성해야 합니다. 또한 Cloud Central 및 AWS에 대한 항목을 추가합니다.
+
.. Administration → Credential Types로 이동한 후 Add를 클릭합니다.
.. 이름과 설명을 입력합니다.
.. 입력 구성에 다음 내용을 붙여 넣습니다.
+
[source, cli]
----
fields:
  - id: dst_cluster_username
    type: string
    label: CVO Username
  - id: dst_cluster_password
    type: string
    label: CVO Password
    secret: true
  - id: cvo_svm_password
    type: string
    label: CVO SVM Password
    secret: true
  - id: src_cluster_username
    type: string
    label: Source Cluster Username
  - id: src_cluster_password
    type: string
    label: Source Cluster Password
    secret: true
  - id: regular_id
    type: string
    label: Cloud Central ID
    secret: true
  - id: email_id
    type: string
    label: Cloud Manager Email
    secret: true
  - id: cm_password
    type: string
    label: Cloud Manager Password
    secret: true
  - id: access_key
    type: string
    label: AWS Access Key
    secret: true
  - id: secret_key
    type: string
    label: AWS Secret Key
    secret: true
  - id: token
    type: string
    label: Cloud Central Refresh Token
    secret: true
----
.. Injector Configuration(주입기 구성)에 다음 내용을 붙여넣고 Save(저장)를 클릭합니다.
+
[source, cli]
----
extra_vars:
  dst_cluster_username: '{{ dst_cluster_username }}'
  dst_cluster_password: '{{ dst_cluster_password }}'
  cvo_svm_password: '{{ cvo_svm_password }}'
  src_cluster_username: '{{ src_cluster_username }}'
  src_cluster_password: '{{ src_cluster_password }}'
  regular_id: '{{ regular_id }}'
  email_id: '{{ email_id }}'
  cm_password: '{{ cm_password }}'
  access_key: '{{ access_key }}'
  secret_key: '{{ secret_key }}'
  token: '{{ token }}'
----


. ONTAP/CVO/AWS에 대한 자격 증명을 생성합니다
+
.. Resources → Credentials로 이동한 후 Add를 클릭합니다.
.. ONTAP 자격 증명에 대한 이름과 조직 세부 정보를 입력합니다
.. 이전 단계에서 만든 자격 증명 유형을 선택합니다.
.. 유형 세부 정보 아래에 소스 및 CVO 클러스터, Cloud Central/Manager, AWS 액세스/비밀 키 및 Cloud Central 업데이트 토큰의 사용자 이름 및 암호를 입력합니다.
.. 저장 을 클릭합니다


. Oracle에 대한 자격 증명 생성(소스)
+
.. Resources → Credentials로 이동한 후 Add를 클릭합니다.
.. Oracle 호스트의 이름 및 조직 세부 정보를 입력합니다
.. 시스템 자격 증명 유형을 선택합니다.
.. 유형 세부 정보 에서 Oracle 호스트의 사용자 이름 및 암호를 입력합니다.
.. 올바른 권한 에스컬레이션 방법을 선택하고 사용자 이름과 암호를 입력합니다.
.. 저장 을 클릭합니다


. Oracle Destination에 대한 자격 증명을 생성합니다
+
.. Resources → Credentials로 이동한 후 Add를 클릭합니다.
.. DR Oracle 호스트의 이름 및 조직 세부 정보를 입력합니다
.. 시스템 자격 증명 유형을 선택합니다.
.. 세부 정보 유형 에 사용자 이름(EC2-USER 또는 기본값에서 변경한 경우 해당 입력) 및 SSH 개인 키를 입력합니다
.. 올바른 권한 에스컬레이션 방법(sudo)을 선택하고 필요한 경우 사용자 이름과 암호를 입력합니다.
.. 저장 을 클릭합니다




--
====


=== 프로젝트를 만듭니다

. Resources → Projects로 이동하여 Add를 클릭합니다.
+
.. 이름 및 조직 세부 정보를 입력합니다.
.. 소스 제어 자격 증명 유형 필드에서 Git 를 선택합니다.
.. 를 입력합니다 <https://github.com/NetApp-Automation/na_oracle19c_data_protection.git>[] 소스 제어 URL입니다.
.. 저장 을 클릭합니다.
.. 소스 코드가 변경되면 프로젝트를 가끔 동기화해야 할 수 있습니다.






=== 글로벌 변수를 설정합니다

이 섹션에 정의된 변수는 모든 Oracle 호스트, 데이터베이스 및 ONTAP 클러스터에 적용됩니다.

. 다음 임베디드 글로벌 변수 또는 VAR 양식에 환경별 매개 변수를 입력합니다.
+

NOTE: 파란색 항목은 환경에 맞게 변경해야 합니다.

+
[role="tabbed-block"]
====
.사내
--

--
.CVO
--

--
====




=== 자동화 플레이북

4개의 개별 플레이북을 실행해야 합니다.

. 온프레미스 또는 CVO 환경 설정을 위한 플레이북
. Oracle 바이너리 및 데이터베이스 복제를 위한 일정 계획
. 일정에 따라 Oracle 로그를 복제하는 데 필요한 Playbook
. 타겟 호스트에서 데이터베이스를 복구하는 플레이북입니다


[role="tabbed-block"]
====
.ONTAP/CVO 설정
--
ONTAP 및 CVO 설정

. 작업 템플릿을 구성하고 시작합니다.
+
.. 작업 템플릿을 작성합니다.
+
... Resources → Templates → Add로 이동하여 Add Job Template을 클릭합니다.
... ONTAP/CVO 설정의 이름을 입력합니다
... 작업 유형을 선택합니다. 실행 은 Playbook을 기반으로 시스템을 구성합니다.
... Playbook의 해당 인벤토리, 프로젝트, 플레이북 및 자격 증명을 선택합니다.
... 사내 환경의 경우 ONTAP_setup.yml 플레이북을 선택하고 CVO 인스턴스로 복제할 때 cvo_setup.yml을 선택합니다.
... 4단계에서 복사한 글로벌 변수를 YAML 탭의 템플릿 변수 필드에 붙여 넣습니다.
... 저장 을 클릭합니다.


.. 작업 템플릿을 시작합니다.
+
... 리소스 → 템플릿 으로 이동합니다.
... 원하는 템플릿을 클릭한 다음 실행을 클릭합니다.
+

NOTE: 이 템플릿을 사용하여 다른 Playbook에 복사할 것입니다.







--
.바이너리 및 데이터베이스 볼륨의 복제입니다
--
바이너리 및 데이터베이스 복제 플레이북 예약

. 작업 템플릿을 구성하고 시작합니다.
+
.. 이전에 생성한 작업 템플릿을 복사합니다.
+
... 리소스 → 템플릿 으로 이동합니다.
... ONTAP/CVO 설정 템플릿을 찾은 후 Copy Template을 마우스 오른쪽 버튼으로 클릭합니다
... 복사된 템플릿에서 템플릿 편집 을 클릭하고 이름을 바이너리 및 데이터베이스 복제 플레이북으로 변경합니다.
... 템플릿에 대해 동일한 재고, 프로젝트, 자격 증명을 유지합니다.
... 실행할 플레이북으로 ora_replication_cg.yml을 선택합니다.
... 변수는 동일하게 유지되지만 CVO 클러스터 IP는 dst_cluster_ip 변수에 설정되어야 합니다.
... 저장 을 클릭합니다.


.. 작업 템플릿을 예약합니다.
+
... 리소스 → 템플릿 으로 이동합니다.
... 바이너리 및 데이터베이스 복제 플레이북 템플릿을 클릭한 다음, 최상위 옵션 세트에서 일정을 클릭합니다.
... 추가 를 클릭하고 바이너리 및 데이터베이스 복제에 대한 이름 일정 추가 를 클릭한 다음 시간 시작 시 시작 날짜/시간을 선택하고 로컬 표준 시간대를 선택한 다음 실행 빈도 를 선택합니다. 실행 빈도는 대개 SnapMirror 복제가 업데이트됩니다.
+

NOTE: 로그 볼륨 복제에 대해 별도의 일정이 생성되므로 보다 빈번한 케이던스로 복제할 수 있습니다.







--
.로그 볼륨의 복제입니다
--
로그 복제 플레이북 예약

. 작업 템플릿을 구성하고 시작합니다.
+
.. 이전에 생성한 작업 템플릿을 복사합니다.
+
... 리소스 → 템플릿 으로 이동합니다.
... ONTAP/CVO 설정 템플릿을 찾은 후 Copy Template을 마우스 오른쪽 버튼으로 클릭합니다
... 복사된 템플릿에서 템플릿 편집 을 클릭하고 이름을 로그 복제 플레이북 으로 변경합니다.
... 템플릿에 대해 동일한 재고, 프로젝트, 자격 증명을 유지합니다.
... 실행할 플레이북으로 ora_replication_logs.yml을 선택합니다.
... 변수는 동일하게 유지되지만 CVO 클러스터 IP는 dst_cluster_ip 변수에 설정되어야 합니다.
... 저장 을 클릭합니다.


.. 작업 템플릿을 예약합니다.
+
... 리소스 → 템플릿 으로 이동합니다.
... Log Replication Playbook 템플릿을 클릭한 다음 최상위 옵션 집합에서 Schedules를 클릭합니다.
... 추가, 로그 복제에 대한 이름 스케줄 추가, 시간 시작 시 시작 날짜/시간 선택, 로컬 시간대 선택 및 실행 빈도 를 차례로 클릭합니다. 실행 빈도는 대개 SnapMirror 복제가 업데이트됩니다.




+

NOTE: 마지막 1시간 단위 업데이트까지 복구할 수 있도록 매 시간마다 업데이트되도록 로그 스케줄을 설정하는 것이 좋습니다.



--
.데이터베이스 복원 및 복구
--
로그 복제 플레이북 예약

. 작업 템플릿을 구성하고 시작합니다.
+
.. 이전에 생성한 작업 템플릿을 복사합니다.
+
... 리소스 → 템플릿 으로 이동합니다.
... ONTAP/CVO 설정 템플릿을 찾은 후 Copy Template을 마우스 오른쪽 버튼으로 클릭합니다
... 복사된 템플릿에서 템플릿 편집 을 클릭하고 이름을 복원 및 복구 Playbook 으로 변경합니다.
... 템플릿에 대해 동일한 재고, 프로젝트, 자격 증명을 유지합니다.
... 실행할 플레이북으로 ora_recovery.yml을 선택합니다.
... 변수는 동일하게 유지되지만 CVO 클러스터 IP는 dst_cluster_ip 변수에 설정되어야 합니다.
... 저장 을 클릭합니다.




+

NOTE: 이 플레이북은 원격 사이트에서 데이터베이스를 복원할 준비가 될 때까지 실행할 수 없습니다.



--
====


=== 5.Oracle 데이터베이스 복구 중

. 사내 운영 Oracle 데이터베이스 데이터 볼륨은 NetApp SnapMirror 복제를 통해 2차 데이터 센터의 이중 ONTAP 클러스터나 퍼블릭 클라우드의 Cloud Volume ONTAP로 보호됩니다. 완전히 구성된 재해 복구 환경에서는 2차 데이터 센터 또는 퍼블릭 클라우드의 복구 컴퓨팅 인스턴스가 대기 상태이며 재해 발생 시 운영 데이터베이스를 복구할 수 있는 준비가 되어 있습니다. 대기 컴퓨팅 인스턴스는 OS 커널 패치에서 parellel 업데이트를 실행하거나 잠금 단계에서 업그레이드를 실행하여 온프레미스 인스턴스와 동기화된 상태를 유지합니다.
. 이 솔루션에서 Oracle 바이너리 볼륨은 타겟 인스턴스에 복제되어 타겟 인스턴스에 마운트하여 Oracle 소프트웨어 스택을 실행하는 것으로 나타났습니다. Oracle을 복구하는 이러한 접근 방식은 재해가 발생한 마지막 순간에 Oracle을 새로 설치하는 데 비해 많은 이점을 제공합니다. 이 제품은 Oracle 설치가 현재 온프레미스 프로덕션 소프트웨어 설치 및 패치 수준 등과 완벽하게 동기화되도록 보장합니다. 그러나 소프트웨어 라이센스가 Oracle과 어떻게 구성되어 있는지에 따라 복구 사이트에서 복제된 Oracle 바이너리 볼륨에 대한 소프트웨어 라이센스가 추가로 부여되거나 적용되지 않을 수 있습니다. 사용자는 동일한 접근 방식을 사용하기 전에 소프트웨어 라이센스 담당자에게 잠재적인 Oracle 라이센스 요구 사항을 평가하는 것이 좋습니다.
. 대상의 대기 Oracle 호스트는 Oracle 필수 구성 요소 구성으로 구성됩니다.
. SnapMirror가 손상되고 볼륨이 쓰기 가능으로 만들어져 대기 Oracle 호스트에 마운트됩니다.
. Oracle 복구 모듈은 모든 DB 볼륨이 대기 컴퓨팅 인스턴스에 마운트된 후 복구 사이트에서 Oracle을 복구 및 시작하는 다음과 같은 작업을 수행합니다.
+
.. 제어 파일 동기화: 중요한 데이터베이스 제어 파일을 보호하기 위해 서로 다른 데이터베이스 볼륨에 중복 Oracle 제어 파일을 구축했습니다. 하나는 데이터 볼륨에 있고 다른 하나는 로그 볼륨에 있습니다. 데이터 및 로그 볼륨은 서로 다른 빈도로 복제되므로 복구 시 동기화되지 않습니다.
.. Oracle 바이너리 다시 연결: Oracle 바이너리가 새 호스트로 재배치되므로 재링크가 필요합니다.
.. Oracle 데이터베이스 복구: 복구 메커니즘은 Oracle 로그 볼륨에서 마지막으로 사용 가능한 아카이브 로그의 마지막 시스템 변경 번호를 제어 파일에서 검색하고 Oracle 데이터베이스를 복구하여 장애 발생 시 DR 사이트에 복제할 수 있는 모든 비즈니스 트랜잭션을 복구합니다. 그런 다음 복구 사이트에서 사용자 연결 및 비즈니스 트랜잭션을 수행할 수 있도록 데이터베이스가 새로 도입되었습니다.





NOTE: 복구 플레이북을 실행하기 전에 /etc/oratab 및 /etc/oraInst.loc을 소스 Oracle 호스트에서 대상 호스트로 복제해야 합니다
