---
sidebar: sidebar 
permalink: databases/db_protection_overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: 이 페이지에서는 NetApp ONTAP 스토리지에 Oracle19c를 구축하는 자동화된 방법에 대해 설명합니다. 
---
= 솔루션 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Oracle 데이터베이스용 자동화된 데이터 보호

조직은 효율성을 높이고, 구현을 앞당기고, 수동 작업을 줄이기 위해 환경을 자동화하고 있습니다. Ansible과 같은 구성 관리 툴을 사용하여 엔터프라이즈 데이터베이스 운영을 간소화하고 있습니다. 이 솔루션에서는 Ansible을 사용하여 NetApp ONTAP을 통해 Oracle의 데이터 보호를 자동화하는 방법을 보여줍니다. 스토리지 관리자, 시스템 관리자 및 DBA가 오프사이트 데이터 센터 또는 퍼블릭 클라우드에 대한 데이터 복제를 일관되고 신속하게 설정할 수 있도록 함으로써 다음과 같은 이점을 얻을 수 있습니다.

* 설계 복잡성과 인적 오류를 제거하고 반복 가능한 일관된 구축 및 모범 사례를 구현합니다
* 클러스터 간 복제, CVO 인스턴스화 및 Oracle 데이터베이스 복구 구성 시간 단축
* 데이터베이스 관리자, 시스템 및 스토리지 관리자의 생산성 향상
* DR 시나리오의 테스트를 쉽게 수행할 수 있는 데이터베이스 복구 워크플로우를 제공합니다.


NetApp은 고객에게 검증된 Ansible 모듈과 역할을 제공하여 Oracle 데이터베이스 환경의 구축, 구성, 라이프사이클 관리를 가속합니다. 이 솔루션은 다음을 지원하기 위한 지침 및 Ansible 플레이북 코드를 제공합니다.



=== 온프레미스에서 온프레미스 복제까지

* 소스와 대상에 대한 인터클러스터 LIF를 만듭니다
* 클러스터 및 SVM 피어링 설정
* Oracle 볼륨의 SnapMirror를 생성하고 초기화합니다
* Oracle 바이너리, 데이터베이스 및 로그용 AWX/Tower를 통해 복제 일정을 생성합니다
* 대상에서 Oracle DB를 복원하고 데이터베이스를 온라인 상태로 전환합니다




=== 온프레미스에서 AWS의 CVO로

* AWS 커넥터를 생성합니다
* AWS에서 CVO 인스턴스를 생성합니다
* Cloud Manager에 온프레미스 클러스터 추가
* 소스에 대한 인터클러스터 LIF를 만듭니다
* 클러스터 및 SVM 피어링 설정
* Oracle 볼륨의 SnapMirror를 생성하고 초기화합니다
* Oracle 바이너리, 데이터베이스 및 로그용 AWX/Tower를 통해 복제 일정을 생성합니다
* 대상에서 Oracle DB를 복원하고 데이터베이스를 온라인 상태로 전환합니다


자세한 내용을 보거나 시작하려면 아래의 개요 비디오를 참조하십시오.



=== AWX/타워 배포

* 1부: TBD
+
비디오::


* 2부: TBD
+
비디오:: 준비가 되면 를 클릭합니다 link:db_protection_getting_started.html["여기 에서 솔루션 시작 을 확인하십시오"].



