---
sidebar: sidebar 
permalink: databases/hybrid_dbops_snapcenter_prereq_cloud.html 
summary: Cloud Manager 커넥터와 Cloud Volumes ONTAP를 설치하고 SnapMirror를 구성하기 전에 먼저 클라우드 환경에 대한 몇 가지 준비를 수행해야 합니다. 이 페이지에서는 수행해야 하는 작업과 Cloud Volumes ONTAP를 구축할 때의 고려 사항에 대해 설명합니다. 
keywords: prerequisites, aws, azure, gcp, cloud central, cloud volumes ontap 
---
= 퍼블릭 클라우드의 사전 요구사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:table-stripes: odd
:imagesdir: ./../media/


link:hybrid_dbops_snapcenter_prereq_onprem.html["이전: 사전 요구 사항 온-프레미스."]

Cloud Manager 커넥터와 Cloud Volumes ONTAP를 설치하고 SnapMirror를 구성하기 전에 먼저 클라우드 환경에 대한 몇 가지 준비를 수행해야 합니다. 이 페이지에서는 수행해야 하는 작업과 Cloud Volumes ONTAP를 구축할 때의 고려 사항에 대해 설명합니다.



=== Cloud Manager 및 Cloud Volumes ONTAP 구축 사전 요구 사항 체크리스트

* NetApp Cloud Central 로그인
* 웹 브라우저에서 여러 엔드포인트로 네트워크 액세스
* 커넥터의 네트워크 위치입니다
* 클라우드 공급자 권한
* 개별 서비스를 위한 네트워킹


시작하는 데 필요한 사항에 대한 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/occm/reference_checklist_cm.html["클라우드 문서"^].



== 고려 사항



=== Cloud Manager 커넥터란 무엇입니까?

대부분의 경우 Cloud Central 계정 관리자는 클라우드 또는 온-프레미스 네트워크에 커넥터를 배포해야 합니다. Connector를 사용하면 Cloud Manager에서 퍼블릭 클라우드 환경 내의 리소스 및 프로세스를 관리할 수 있습니다.

커넥터에 대한 자세한 내용은 를 참조하십시오 https://docs.netapp.com/us-en/occm/concept_connectors.html["클라우드 문서"^].



=== 2.Cloud Volumes ONTAP 사이징 및 아키텍처

Cloud Volumes ONTAP를 배포할 때 미리 정의된 패키지 또는 사용자 고유의 구성 생성 중에서 선택할 수 있습니다. 이러한 값 중 대부분은 중단 없이 변경할 수 있지만, 클라우드에 구축할 워크로드를 기반으로 구축하기 전에 결정해야 할 몇 가지 중요한 사항이 있습니다.

각 클라우드 공급자마다 구축 옵션이 다르며, 워크로드에 따라 저마다 고유한 속성이 있습니다. NetApp에는 이 있습니다 https://cloud.netapp.com/cvo-sizer["CVO 사이징 툴"^] 따라서 용량과 성능을 기준으로 구축 환경을 올바르게 사이징하는 데 도움이 될 수 있지만, 다음과 같은 몇 가지 기본 개념을 기반으로 구축되었습니다.

* 필요한 용량
* 클라우드 가상 머신의 네트워크 기능
* 클라우드 스토리지의 성능 특성


핵심은 현재의 용량 및 성능 요구사항을 충족할 뿐만 아니라 향후 성장을 내다보는 구성을 계획하는 것입니다. 이는 일반적으로 용량 여유 공간 및 성능 여유 공간 이라고 합니다.

자세한 내용을 보려면 에 대한 계획에 대한 문서를 참조하십시오 https://docs.netapp.com/us-en/occm/task_planning_your_config.html["설치하고"^], https://docs.netapp.com/us-en/occm/task_planning_your_config_azure.html["Azure를 지원합니다"^], 및 https://docs.netapp.com/us-en/occm/task_planning_your_config_gcp.html["GCP"^].



=== 3.단일 노드 또는 고가용성?

모든 클라우드에서 CVO를 단일 노드 또는 2개의 노드로 구성된 클러스터 고가용성 쌍에 구축할 수 있는 옵션이 있습니다. 사용 사례에 따라 비용 절감을 위해 단일 노드를 구축하거나 추가 가용성과 이중화를 제공하기 위해 HA 쌍을 구축할 수 있습니다.

DR 사용 사례 또는 개발 및 테스트를 위한 임시 스토리지 회전 시 갑작스러운 조널 또는 인프라 중단의 영향이 더 낮기 때문에 단일 노드가 일반적인 경우가 많습니다. 그러나 모든 운영 사용 사례에서 데이터가 단일 위치에만 있거나 데이터 세트에 더 많은 이중화 및 가용성이 필요할 경우 고가용성을 사용하는 것이 좋습니다.

각 클라우드 버전의 고가용성 아키텍처에 대한 자세한 내용은 의 설명서를 참조하십시오 https://docs.netapp.com/us-en/occm/concept_ha.html["설치하고"^], https://docs.netapp.com/us-en/occm/concept_ha_azure.html["Azure를 지원합니다"^] 및 https://docs.netapp.com/us-en/occm/concept_ha_google_cloud.html["GCP"^].

link:hybrid_dbops_snapcenter_getting_started.html["다음: 시작하기 개요"]
