---
sidebar: sidebar 
permalink: databases/marketing_overview.html 
keywords: Linux, RHEL Oracle19c, NFS, ONTAP, Ansible 
summary: 이 페이지에서는 NetApp ONTAP 스토리지에 Oracle19c를 구축하는 자동화된 방법에 대해 설명합니다. 
---
= 솔루션 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== NFS에서 ONTAP용 Oracle19c의 자동 배포

조직은 효율성을 높이고, 구현을 앞당기고, 수동 작업을 줄이기 위해 환경을 자동화하고 있습니다. Ansible과 같은 구성 관리 툴을 사용하여 엔터프라이즈 데이터베이스 운영을 간소화하고 있습니다. 이 솔루션에서는 Ansible을 사용하여 NetApp ONTAP을 사용하여 Oracle 19c의 프로비저닝과 구성을 자동화하는 방법을 보여줍니다. 스토리지 관리자, 시스템 관리자 및 DBA가 새 스토리지를 일관성 있게 신속하게 구축하고 데이터베이스 서버를 구성하며 Oracle 19c 소프트웨어를 설치할 수 있도록 함으로써 다음과 같은 이점을 얻을 수 있습니다.

* 설계 복잡성과 인적 오류를 제거하고 반복 가능한 일관된 구축 및 모범 사례를 구현합니다
* 스토리지 프로비저닝, DB 호스트 구성, Oracle 설치 시간 단축
* 데이터베이스 관리자, 시스템 및 스토리지 관리자의 생산성 향상
* 스토리지와 데이터베이스를 손쉽게 확장


NetApp은 고객에게 검증된 Ansible 모듈과 역할을 제공하여 Oracle 데이터베이스 환경의 구축, 구성, 라이프사이클 관리를 가속합니다. 이 솔루션은 다음을 지원하기 위한 지침 및 Ansible 플레이북 코드를 제공합니다.

* Oracle 데이터베이스용 ONTAP NFS 스토리지를 생성하고 구성합니다
* RedHat Enterprise Linux 7/8 또는 Oracle Linux 7/8 에 Oracle 19c를 설치합니다
* ONTAP NFS 스토리지에 Oracle 19c를 구성합니다


자세한 내용을 보거나 시작하려면 아래의 개요 비디오를 참조하십시오.



=== AWX/타워 배포

1부: 시작하기, 요구 사항, 자동화 세부 정보 및 초기 AWX/타워 구성

video::d844a9c3-4eb3-4512-bf21-b01200f09f66[panopto,width=360]
2부: 변수 및 Playbook 실행

video::6da1b960-e1c9-4950-b750-b01200f0bdfa[panopto,width=360]


=== CLI 배포

1부: 시작하기, 요구사항, 자동화 세부 정보 및 Ansible Control 호스트 설정

video::373e7f2a-c101-4292-a3e4-b01200f0d078[panopto,width=360]
2부: 변수 및 Playbook 실행

video::d58ebdb0-8bac-4ef9-b4d1-b01200f95047[panopto,width=360]