---
sidebar: sidebar 
permalink: databases/sql-srv-anf_overview.html 
keywords: use case, rehosting, enterprise resource planning, RDBMS, cloud migration 
summary: '이 문서에서는 Azure 가상 시스템을 활용하는 Azure NetApp Files의 AOAG(SQL Server Always On Availability Group)를 실시간으로 구축하는 방법에 대해 설명합니다.' 
---
= TR-4897: Azure NetApp Files 기반 SQL Server - 실제 배포 보기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
이 문서에서는 Azure 가상 시스템을 활용하는 Azure NetApp Files의 AOAG(SQL Server Always On Availability Group)를 실시간으로 구축하는 방법에 대해 설명합니다.

Niyaz Mohamed, NetApp

IT 조직은 끊임없이 변화합니다. Gartner에 따르면 모든 데이터베이스의 약 75%가 2022년까지 클라우드 기반 스토리지를 필요로 할 것이라고 합니다. 선도적인 RDBMS(관계형 데이터베이스 관리 시스템)인 Microsoft SQL Server는 ERP(전사적 자원 관리)에서 분석, 콘텐츠 관리에 이르기까지 SQL Server를 사용하는 Windows 플랫폼 설계 응용 프로그램 및 조직에 적합합니다. SQL Server는 기업이 대규모 데이터 집합을 관리하는 방식을 혁신시키고 스키마 및 쿼리 성능 요구를 충족하도록 응용 프로그램에 전력을 공급하는 데 도움을 주었습니다.

대부분의 IT 조직은 클라우드 우선 방식을 따릅니다. 전환 단계의 고객은 현재 IT 환경을 평가한 다음 평가 및 검색 결과를 기반으로 데이터베이스 워크로드를 클라우드로 마이그레이션합니다. 고객의 클라우드 마이그레이션 방향을 결정하는 요인에는 탄력성/버스트, 데이터 센터 이탈, 데이터 센터 통합, 수명 종료 시나리오, 인수 합병, 인수 합병 등 마이그레이션 이유는 각 조직과 각 조직의 비즈니스 우선 순위에 따라 달라질 수 있습니다. 클라우드로 이동할 때 SQL Server 데이터베이스 클라우드 구현의 잠재력을 최대한 활용하려면 적절한 클라우드 스토리지를 선택하는 것이 매우 중요합니다.



== 사용 사례

SQL Server 자산을 Azure로 이전하고 Azure Data Factory, Azure IoT Hub 및 Azure Machine Learning과 같은 Azure의 광범위한 PaaS(서비스로서의 플랫폼) 기능과 SQL Server를 통합하면 디지털 혁신을 지원하는 엄청난 비즈니스 가치를 창출할 수 있습니다. 또한 클라우드를 채택하면 각 사업부에서 자본 지출 모델 또는 기존 프라이빗 클라우드 모델을 사용할 때보다 생산성 및 새로운 기능/개선 기능(DevTest 사용 사례)을 더 빠르게 제공할 수 있습니다. 이 문서에서는 Azure 가상 시스템을 활용하는 Azure NetApp Files의 AOAG(SQL Server Always On Availability Group)를 실시간으로 구축하는 방법에 대해 설명합니다.

Azure NetApp Files는 지속적으로 사용 가능한 파일 공유를 지원하는 엔터프라이즈급 스토리지를 제공합니다. 지속적으로 사용 가능한 공유는 SMB 파일 공유에서 SQL Server 운영 데이터베이스에 의해 요구되며, 컨트롤러 업그레이드 또는 장애와 같은 운영 중단 시나리오를 포함하여 노드에서 항상 데이터베이스 스토리지에 액세스할 수 있도록 합니다. 지속적으로 사용 가능한 파일 공유를 사용하면 스토리지 노드 간에 데이터를 복제할 필요가 없습니다. Azure NetApp Files은 SMB 3.0 스케일아웃, 영구 핸들 및 투명한 페일오버를 사용하여 다양한 관리 작업을 포함한 계획된 다운타임과 계획되지 않은 다운타임 이벤트에 대한 무중단 운영(NDO)을 지원합니다.

클라우드 마이그레이션을 계획할 때는 항상 가장 적합한 사용 방법을 평가해야 합니다. 애플리케이션 마이그레이션에 가장 일반적이고 가장 쉬운 접근 방식은 재호스팅(리프트 및 변속이라고도 함)입니다. 이 문서에 제공된 예제 시나리오에서는 재호스팅 메서드를 사용합니다. Azure NetApp Files가 설치된 Azure 가상 시스템의 SQL Server를 사용하면 온프레미스 하드웨어를 관리할 필요 없이 클라우드에서 전체 버전의 SQL Server를 사용할 수 있습니다. 또한 SQL Server VM(가상 머신)은 사용한 만큼만 비용을 지불하면 라이센스 비용을 절감할 수 있으며 개발, 테스트 및 부동산 갱신 시나리오에 대한 탄력성과 버스팅 기능을 제공합니다.
