---
sidebar: sidebar 
permalink: ehc/azure/azure-native-overview.html 
keywords:  
summary:  
---
= ANF 데이터 저장소 솔루션 개요
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
성공적인 모든 조직은 혁신과 현대화의 길을 따라 있습니다. 이 프로세스의 일환으로, 기업은 일반적으로 기존 VMware 투자를 활용하는 동시에 클라우드의 이점을 활용하고 마이그레이션, 버스트, 확장 및 재해 복구 프로세스를 최대한 원활하게 만드는 방법을 모색합니다. 클라우드로 마이그레이션하는 고객은 탄력성 및 폭발적 문제, 데이터 센터 이탈, 데이터 센터 통합, 수명 종료 시나리오, 인수 합병 등을 평가해야 합니다. 각 조직에서 채택한 접근 방식은 각 비즈니스 우선순위에 따라 다를 수 있습니다. 클라우드 기반 운영을 선택할 때 적절한 성능과 최소 장애 요인을 갖춘 저렴한 모델을 선택하는 것이 중요한 목표입니다. 적합한 플랫폼을 선택할 뿐만 아니라, 스토리지 및 워크플로우 오케스트레이션은 클라우드의 강력한 기능과 탄력성을 최대한 활용하는 데 특히 중요합니다.



== 사용 사례

Azure VMware 솔루션은 고객에게 고유한 하이브리드 기능을 제공하지만, 제한된 기본 스토리지 옵션으로 스토리지 집약적인 워크로드를 사용하는 조직의 유용성이 제한됩니다. 스토리지가 호스트에 직접 연결되어 있으므로 스토리지를 확장하는 유일한 방법은 호스트를 추가하는 것입니다. 이렇게 하면 스토리지 집약적인 워크로드에서 비용이 35-40% 이상 증가할 수 있습니다. 이러한 워크로드는 추가 처리 능력이 아니라 추가 스토리지를 필요로 합니다. 즉, 추가 호스트에 대한 비용을 지불해야 합니다.

다음 시나리오를 고려해 보겠습니다. 고객은 마력(vCPU/vmem)을 위해 6개의 호스트를 필요로 하지만 스토리지에 대한 요구 사항도 상당히 있습니다. 평가를 기준으로 볼 때 스토리지 요구사항을 충족하기 위해 12개의 호스트가 필요합니다. 이렇게 하면 실제로 필요한 모든 것이 더 많은 스토리지일 때 마력을 추가로 구입해야 하기 때문에 전체 TCO가 증가합니다. 마이그레이션, 재해 복구, 사용 급증, 개발/테스트, 등.

Azure VMware 솔루션의 또 다른 일반적인 사용 사례는 DR(재해 복구)입니다. 대부분의 조직은 재해 복구 전략이 없거나 DR을 위한 고스트 데이터 센터의 실행을 정당화하는 데 어려움을 겪을 수 있습니다. 관리자는 파일럿 라이트 클러스터 또는 온디맨드 클러스터를 통해 설치 공간이 필요 없는 DR 옵션을 탐색할 수 있습니다. 그런 다음 호스트를 추가하지 않고 스토리지를 확장할 수 있으므로 매력적인 옵션이 될 수 있습니다.

요약하자면, 사용 사례는 다음 두 가지 방법으로 분류할 수 있습니다.

* ANF 데이터 저장소를 사용하여 스토리지 용량을 확장합니다
* 소프트웨어 정의 데이터 센터(SDDC) 간의 사내 또는 Azure 지역 내에서 비용 최적화된 복구 워크플로를 위해 ANF 데이터 저장소를 재해 복구 타겟으로 사용합니다. 이 가이드에서는 Azure NetApp Files를 사용하여 데이터 저장소에 최적화된 스토리지(현재 공개 미리 보기)를 제공하는 방법에 대해 설명합니다. Azure VMware 솔루션에서 동급 최고의 데이터 보호 및 DR 기능을 제공하므로 vSAN 스토리지에서 스토리지 용량을 오프로드할 수 있습니다.



NOTE: Azure NetApp Files 데이터 저장소 기능은 현재 공개 미리 보기에 있습니다. 자세한 내용은 해당 지역의 NetApp 또는 Microsoft 솔루션 설계자에게 문의하십시오.



== Azure의 VMware 클라우드 옵션



=== Azure VMware 솔루션

Azure VMware 솔루션(AVS)은 Microsoft Azure 퍼블릭 클라우드 내에서 완벽하게 작동하는 VMware SDDC를 제공하는 하이브리드 클라우드 서비스입니다. AVS는 Microsoft에서 완벽하게 관리 및 지원하고 Azure 인프라를 사용하는 VMware에서 검증한 최초의 솔루션입니다. 따라서 고객은 컴퓨팅 가상화를 위한 VMware ESXi, 하이퍼 컨버지드 스토리지를 위한 vSAN 및 네트워킹 및 보안을 위한 NSX를 얻는 동시에 Microsoft Azure의 세계적인 입지, 동급 최고의 데이터 센터 시설 및 네이티브 Azure 서비스 및 솔루션의 풍부한 에코시스템에 근접할 수 있는 이점을 누릴 수 있습니다. Azure VMware 솔루션 SDDC와 Azure NetApp Files를 함께 사용하면 네트워크 지연 시간을 최소화하면서 최상의 성능을 얻을 수 있습니다.

사용된 클라우드에 관계없이 VMware SDDC를 구축할 때 초기 클러스터에 포함되는 구성 요소는 다음과 같습니다.

* 관리를 위해 vCenter Server 어플라이언스를 사용하여 컴퓨팅 가상화를 위한 VMware ESXi 호스트
* VMware vSAN 하이퍼 컨버지드 스토리지는 각 ESXi 호스트의 물리적 스토리지 자산을 통합합니다.
* 관리를 위해 NSX Manager 클러스터를 사용하여 가상 네트워킹 및 보안을 위한 VMware NSX




== 결론

All-Cloud와 하이브리드 클라우드 중 무엇을 목표로 하고 있든 Azure NetApp Files는 애플리케이션 계층과 함께 애플리케이션 워크로드를 구축하고 관리하는 탁월한 옵션을 제공하는 한편 데이터 요구사항을 애플리케이션 계층으로 원활하게 충족하여 TCO를 줄여줍니다. 어떤 사용 사례에서든 Azure NetApp Files와 함께 Azure VMware 솔루션을 선택하면 클라우드의 이점, 일관된 인프라, 온프레미스 및 멀티 클라우드 전반의 운영, 워크로드의 양방향 이동성, 엔터프라이즈급 용량 및 성능을 빠르게 실현할 수 있습니다. 스토리지를 연결하는 데 사용되는 것과 동일한 친숙한 프로세스 및 절차입니다. 이는 새로운 이름과 함께 변경된 데이터의 위치일 뿐입니다. 도구 및 프로세스는 모두 동일하며 Azure NetApp Files는 전체 배포를 최적화하는 데 도움이 됩니다.



== 이점

이 문서의 핵심 사항은 다음과 같습니다.

* 이제 AVS SDDC에서 Azure NetApp Files를 데이터 저장소로 사용할 수 있습니다.
* 애플리케이션 응답 시간을 단축하고 가용성을 높여 필요할 때 언제 어디서나 액세스 워크로드 데이터를 제공합니다.
* 간단하고 즉각적인 크기 조정 기능을 통해 vSAN 스토리지의 전반적인 복잡성을 단순화합니다.
* 동적 재구성 기능을 사용하여 미션 크리티컬 워크로드의 성능 보장
* Azure VMware 솔루션 클라우드가 그 목적이라면 Azure NetApp Files는 최적의 구축을 위한 최적의 스토리지 솔루션입니다.




== 추가 정보를 찾을 수 있는 위치

이 문서에 설명된 정보에 대한 자세한 내용은 다음 웹 사이트 링크를 참조하십시오.

* Azure VMware 솔루션 설명서
+
https://docs.microsoft.com/en-us/azure/azure-vmware/["https://docs.microsoft.com/en-us/azure/azure-vmware/"^]

* Azure NetApp Files 설명서
+
https://docs.microsoft.com/en-us/azure/azure-netapp-files/["https://docs.microsoft.com/en-us/azure/azure-netapp-files/"^]

* Azure NetApp Files 데이터 저장소를 Azure VMware 솔루션 호스트에 연결(Preview)
+
https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?tabs=azure-portal/["https://docs.microsoft.com/en-us/azure/azure-vmware/attach-azure-netapp-files-to-azure-vmware-solution-hosts?tabs=azure-portal/"^]


