---
sidebar: sidebar 
permalink: ehc/azure/azure-avs.html 
keywords: NetApp Solutions, hyperscalers, azure, avs, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Azure AVS용 NetApp 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
NetApp이 AVS(Azure VMware Solution)에 제공하는 기능에 대해 자세히 알아보십시오. NetApp은 게스트 연결 스토리지 장치로, 보충 NFS 데이터 저장소에서 마이그레이션 워크플로우에 전환, 클라우드로 확장/버스팅, 백업/복원, 재해 복구까지 지원합니다.

다음 옵션 중 하나를 선택하여 원하는 콘텐츠의 섹션으로 이동합니다.

* link:#config["Azure에서 AVS 구성"]
* link:#datastore["AVS용 NetApp 스토리지 옵션"]
* link:#solutions["NetApp/VMware 클라우드 솔루션"]




== Azure에서 AVS 구성

온프레미스에서와 마찬가지로 클라우드 기반 가상화 환경을 계획하는 것은 VM 및 마이그레이션을 생성할 수 있는 성공적인 프로덕션 준비 환경에 매우 중요합니다.

이 섹션에서는 Azure VMware 솔루션을 설정 및 관리하고 NetApp 스토리지를 연결하는 데 사용할 수 있는 옵션과 함께 사용하는 방법을 설명합니다.


NOTE: 게스트 내 스토리지는 Cloud Volumes ONTAP를 Azure VMware 솔루션에 연결하는 유일한 지원 방법입니다.

설치 프로세스는 다음 단계로 나눌 수 있습니다.

* 리소스 공급자를 등록하고 프라이빗 클라우드를 생성합니다
* 새 또는 기존 ExpressRoute 가상 네트워크 게이트웨이에 연결합니다
* 네트워크 연결을 확인하고 프라이빗 클라우드에 액세스합니다


자세한 내용을 확인하십시오 link:azure-setup.html["AVS의 구성 단계"].



== AVS용 NetApp 스토리지 옵션

NetApp 스토리지는 Azure AVS에서 guess Connected 또는 보충 NFS 데이터 저장소로 여러 가지 방법으로 활용할 수 있습니다.

를 방문하십시오 link:../ehc-support-configs.html["지원되는 NetApp 스토리지 옵션"] 를 참조하십시오.

Azure는 다음과 같은 구성에서 NetApp 스토리지를 지원합니다.

* 게스트 연결 스토리지로서의 Azure NetApp Files(ANF)
* CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다
* Azure NetApp Files(ANF)를 보조 NFS 데이터 저장소로 사용합니다


자세한 내용을 확인하십시오 link:azure-guest.html["AVS용 게스트 연결 스토리지 옵션"]. 자세한 내용을 확인하십시오 link:azure-native-nfs-datastore-option.html["AVS용 보조 NFS 데이터 저장소 옵션"].



== 솔루션 사용 사례

NetApp 및 VMware 클라우드 솔루션을 사용하면 많은 사용 사례를 Azure AVS에서 간단하게 구축할 수 있습니다. SE 사례는 VMware에서 정의한 각 클라우드 영역에 대해 정의됩니다.

* 보호(재해 복구 및 백업/복원 모두 포함)
* 확장
* 마이그레이션


link:azure-solutions.html["Azure AVS용 NetApp 솔루션을 찾아보십시오"]
