---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-snapcenter-overview.html 
keywords: overview, dr, snapcenter, data replication, snapmirror 
summary: 이 솔루션에서 SnapCenter는 SQL Server 및 Oracle 애플리케이션 데이터에 대해 애플리케이션 정합성이 보장되는 스냅샷을 제공합니다. 이 구성은 SnapMirror 기술과 함께 사내 AFF와 FSx ONTAP 클러스터 간에 고속 데이터 복제를 제공합니다. 또한 Veeam Backup & Replication은 가상 머신에 백업 및 복원 기능을 제공합니다. 
---
= 개요 - 재해 복구
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-cloud-backup-tools.html["이전: 클라우드 백업 툴:"]

이 솔루션에서 SnapCenter는 SQL Server 및 Oracle 애플리케이션 데이터에 대해 애플리케이션 정합성이 보장되는 스냅샷을 제공합니다. 이 구성은 SnapMirror 기술과 함께 사내 AFF와 FSx ONTAP 클러스터 간에 고속 데이터 복제를 제공합니다. 또한 Veeam Backup & Replication은 가상 머신에 백업 및 복원 기능을 제공합니다.

이 섹션에서는 백업 및 복원을 위한 SnapCenter, SnapMirror 및 Veeam의 구성에 대해 살펴봅니다.

다음 섹션에서는 보조 사이트에서 페일오버를 완료하는 데 필요한 구성 및 단계에 대해 설명합니다.

* SnapMirror 및 보존 일정(2차 스토리지)을 구성합니다.
* 온-프레미스에서 Windows SnapCenter 서버를 배포하고 구성합니다.
* Veeam Backup & Replication 서버를 사내에서 구축 및 구성합니다.
* 클라우드 백업 툴, SnapCenter, Veeam을 구축 및 구성합니다.
* 재해 복구를 위한 SnapCenter 데이터베이스 백업
* 보조 사이트에서 SnapCenter 데이터베이스 복원
* Veeam Backup & Replication을 사용하여 애플리케이션 가상 머신을 복구합니다.
* SQL Server 응용 프로그램 데이터를 복원합니다.
* Oracle 애플리케이션 데이터를 복구합니다.


link:aws-guest-dr-config-snapmirror.html["다음: SnapMirror 관계 및 보존 일정을 구성합니다."]
