---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-cloud-backup-tools.html 
keywords: deployment, backup tools, snapcenter server, Veeam server, 
summary: 애플리케이션 VM 및 데이터베이스 볼륨을 AWS에서 실행되는 VMware Cloud Volume 서비스로 페일오버하려면 SnapCenter Server와 Veeam Backup and Replication Server의 실행 중인 인스턴스를 설치하고 구성해야 했습니다. 페일오버가 완료된 후 사내 데이터 센터에 대한 페일백이 계획 및 실행될 때까지 이러한 툴을 정상 백업 작업을 재개하도록 구성해야 합니다. 
---
= 클라우드 백업 툴
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-compute.html["이전: 컴퓨팅."]

애플리케이션 VM 및 데이터베이스 볼륨을 AWS에서 실행되는 VMware Cloud Volume 서비스로 페일오버하려면 SnapCenter Server와 Veeam Backup and Replication Server의 실행 중인 인스턴스를 설치하고 구성해야 했습니다. 페일오버가 완료된 후 사내 데이터 센터에 대한 페일백이 계획 및 실행될 때까지 이러한 툴을 정상 백업 작업을 재개하도록 구성해야 합니다.



== 백업 툴 구축

SnapCenter 서버 및 Veeam Backup & Replication Server를 VMware Cloud SDDC에 설치하거나 VPC에 상주하는 EC2 인스턴스에 설치할 수 있으며, VMware 클라우드 환경에 네트워크를 연결할 수 있습니다.



=== SnapCenter 서버

SnapCenter 소프트웨어는 NetApp Support 사이트에서 제공되며 도메인 또는 작업 그룹에 상주하는 Microsoft Windows 시스템에 설치할 수 있습니다. 자세한 계획 가이드 및 설치 지침은 에서 확인할 수 있습니다 link:https://docs.netapp.com/us-en/snapcenter/install/install_workflow.html["NetApp 문서화 센터"^].

SnapCenter 소프트웨어는 에서 찾을 수 있습니다 https://mysupport.netapp.com["이 링크"^].



=== Veeam 백업 및 복제 서버

Veeam Backup & Replication 서버를 AWS의 VMware Cloud 또는 EC2 인스턴스에 설치할 수 있습니다. 자세한 구현 지침은 를 참조하십시오 https://www.veeam.com/documentation-guides-datasheets.html["Veeam Help Center 기술 문서"^].



== 백업 툴 및 구성

설치 후 SnapCenter 및 Veeam Backup & Replication이 AWS의 VMware Cloud에 데이터를 복원하는 데 필요한 작업을 수행하도록 구성되어 있어야 합니다.



=== SnapCenter 구성

FSx ONTAP에 미러링된 응용 프로그램 데이터를 복원하려면 먼저 온-프레미스 SnapCenter 데이터베이스의 전체 복원을 수행해야 합니다. 이 프로세스가 완료되면 VM과의 통신이 다시 설정되고 FSx ONTAP를 기본 스토리지로 사용하여 응용 프로그램 백업을 다시 시작할 수 있습니다.

AWS에 있는 SnapCenter 서버에서 완료해야 하는 단계 목록은 섹션을 참조하십시오 link:aws-guest-dr-cloud-backup-config.html#deploy-secondary-windows-snapcenter-server["보조 Windows SnapCenter 서버를 배포합니다"].



=== Veeam 백업 및 복제 구성

Amazon S3 스토리지에 백업된 가상 머신을 복구하려면 Veeam Server를 Windows 서버에 설치하고 원래 백업 저장소가 포함된 VMware Cloud, FSx ONTAP 및 S3 버킷과 통신하도록 구성해야 합니다. 또한 VM이 복구된 후 새 백업을 수행하려면 FSx ONTAP에 새 백업 리포지토리가 구성되어 있어야 합니다.

애플리케이션 VM의 장애 조치를 완료하는 데 필요한 전체 단계 목록은 섹션을 참조하십시오 link:aws-guest-dr-cloud-backup-config.html#deploy-secondary-veeam-backup-&-replication-server["2차 Veeam Backup & amp; Replication Server를 구축합니다"].

link:aws-guest-dr-snapcenter-overview.html["다음: 개요 - 재해 복구."]
