---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-technology.html 
keywords: technology, vmware cloud foundation, vsphere, nsx, snapcenter, veeam, VMware Cloud on AWS, Amazon FSx 
summary: 이 섹션에서는 이 솔루션을 지원하는 다양한 기술적 구성 요소에 대해 간략하게 설명합니다. 
---
= 제공합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-solution-overview.html["이전: 솔루션 개요"]

이 솔루션에는 NetApp, VMware, AWS(Amazon Web Services), Veeam의 혁신적인 기술이 포함되어 있습니다.



== VMware



=== VMware 클라우드 기반

VMware Cloud Foundation 플랫폼은 관리자가 이기종 환경에서 논리적 인프라를 프로비저닝할 수 있도록 여러 제품 오퍼링을 통합합니다. 이러한 인프라(도메인)는 프라이빗 클라우드와 퍼블릭 클라우드 전반에서 일관된 운영을 제공합니다. Cloud Foundation 소프트웨어와 함께 제공되는 BOM은 사전 검증된 구성 요소와 검증된 구성 요소를 식별하여 고객의 위험을 줄이고 구축을 용이하게 합니다.

Cloud Foundation BOM의 구성 요소는 다음과 같습니다.

* 클라우드 빌더
* SDDC 관리자
* VMware vCenter Server 어플라이언스
* VMware ESXi
* VMware NSX
* 자동화 표준화
* Suite Lifecycle Manager vRealize
* 로그 통찰력 vRealize


VMware Cloud Foundation에 대한 자세한 내용은 을 참조하십시오 https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html["VMware Cloud Foundation 설명서"^].



=== VMware vSphere를 참조하십시오

VMware vSphere는 물리적 리소스를 고객의 워크로드 및 애플리케이션 요구 사항을 충족하는 데 사용할 수 있는 컴퓨팅, 네트워크 및 스토리지 풀로 전환하는 가상화 플랫폼입니다. VMware vSphere의 주요 구성 요소는 다음과 같습니다.

* * ESXi. * 이 VMware 하이퍼바이저는 컴퓨팅 프로세서, 메모리, 네트워크 및 기타 리소스를 추상화하여 가상 머신 및 컨테이너 워크로드에 사용할 수 있도록 합니다.
* * vCenter. * VMware vCenter는 가상 인프라의 일부로 컴퓨팅 리소스, 네트워킹 및 스토리지와 상호 작용할 수 있는 중앙 관리 환경을 제공합니다.


고객은 NetApp ONTAP와 함께 강력한 제품 통합, 강력한 지원, 강력한 기능 및 스토리지 효율성을 제공하여 강력한 하이브리드 멀티 클라우드를 구축함으로써 vSphere 환경의 잠재력을 완벽하게 실현할 수 있습니다.

VMware vSphere에 대한 자세한 내용은 을 참조하십시오 https://docs.vmware.com/en/VMware-vSphere/index.html["이 링크"^].

VMware와 함께 제공되는 NetApp 솔루션에 대한 자세한 내용은 다음 웹 사이트를 참조하십시오 https://docs.netapp.com/us-en/netapp-solutions/virtualization/netapp-vmware.html["이 링크"^].



=== VMware NSX

일반적으로 네트워크 하이퍼바이저라고 하는 VMware NSX는 소프트웨어 정의 모델을 사용하여 가상화된 워크로드를 연결합니다. VMware NSX는 온프레미스 및 AWS 기반의 VMware Cloud에서 어디에나 존재하며, 이 곳에서 고객 애플리케이션 및 워크로드를 위한 네트워크 가상화 및 보안을 강화합니다.

VMware NSX에 대한 자세한 내용은 를 참조하십시오 https://docs.vmware.com/en/VMware-NSX-T-Data-Center/index.html["이 링크"^].



== 넷엡



=== NetApp ONTAP를 참조하십시오

NetApp ONTAP 소프트웨어는 약 20년 동안 VMware vSphere 환경을 위한 최고의 스토리지 솔루션으로, 혁신적인 기능을 지속적으로 추가하여 관리를 단순화하는 동시에 비용을 절감했습니다. ONTAP와 vSphere를 함께 사용하면 호스트 하드웨어 및 VMware 소프트웨어 비용을 절감할 수 있습니다. 또한 기본 스토리지 효율성을 활용하면서도 일관된 고성능을 통해 저렴한 비용으로 데이터를 보호할 수 있습니다.

NetApp ONTAP에 대한 자세한 내용은 다음 웹 사이트를 참조하십시오 https://docs.vmware.com/en/VMware-Cloud-on-AWS/index.html["이 링크"^].



=== VMware용 NetApp ONTAP 툴

VMware용 ONTAP 툴은 여러 플러그인을 NetApp 스토리지 시스템을 사용하는 VMware 환경에서 가상 머신의 라이프사이클을 완벽하게 관리하는 단일 가상 어플라이언스에 결합했습니다. VMware용 ONTAP 툴은 다음과 같습니다.

* * VSC(가상 스토리지 콘솔) * 는 NetApp 스토리지를 사용하여 VM 및 데이터 저장소에 대한 포괄적인 관리 작업을 수행합니다.
* * ONTAP용 VASA Provider. * VMware 가상 볼륨(VVol) 및 NetApp 스토리지를 통해 SPBM(스토리지 정책 기반 관리)을 지원합니다.
* * SRA(Storage Replication Adapter) *. VMware SRM(Site Recovery Manager)과 함께 사용할 경우 장애가 발생할 경우 vCenter 데이터 저장소와 가상 머신을 복구합니다.


VMware용 ONTAP 툴을 사용하면 외부 스토리지를 관리할 뿐만 아니라 VVOL 및 VMware 사이트 복구 관리자도 통합할 수 있습니다. 따라서 vCenter 환경에서 NetApp 스토리지를 훨씬 쉽게 구축하고 운영할 수 있습니다.

VMware용 NetApp ONTAP 툴에 대한 자세한 내용은 다음 사이트를 참조하십시오 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["이 링크"^].



=== NetApp SnapCenter를 참조하십시오

NetApp SnapCenter 소프트웨어는 애플리케이션, 데이터베이스 및 파일 시스템 전반에서 데이터 보호를 안전하게 조율하고 관리하는 사용하기 쉬운 엔터프라이즈 플랫폼입니다. SnapCenter는 스토리지 시스템의 활동 감독 및 규제 범주에는 영향을 받지 않으면서 이러한 작업을 애플리케이션 소유자에게 오프로드하여 백업, 복원 및 클론 라이프사이클 관리를 단순화합니다. SnapCenter는 스토리지 기반 데이터 관리를 활용하여 성능 및 가용성을 높이는 동시에 테스트 및 개발 시간을 단축합니다.

VMware vSphere용 SnapCenter 플러그인은 VM(가상 머신), 데이터 저장소 및 VMDK(가상 머신 디스크)에 대해 충돌 시에도 정합성이 보장되고 VM 정합성이 보장되는 백업 및 복원 작업을 지원합니다. 또한 SnapCenter 애플리케이션별 플러그인을 지원하여 가상화된 데이터베이스 및 파일 시스템에 대한 애플리케이션 정합성이 보장되는 백업 및 복구 작업을 보호합니다.

NetApp SnapCenter에 대한 자세한 내용은 다음 웹 사이트를 참조하십시오 https://docs.netapp.com/us-en/snapcenter/["이 링크"^].



== 타사 데이터 보호



=== Veeam 백업 및 복제

Veeam Backup & Replication은 클라우드, 가상 및 물리적 워크로드를 위한 백업, 복구 및 데이터 관리 솔루션입니다. Veeam Backup & Replication은 NetApp Snapshot 기술과의 전문적인 통합으로 vSphere 환경을 더욱 보호합니다.

Veeam Backup & Replication에 대한 자세한 내용은 을 참조하십시오 https://www.veeam.com/vm-backup-recovery-replication-software.html["이 링크"^].



== 퍼블릭 클라우드



=== AWS ID 및 액세스 관리

AWS 환경에는 컴퓨팅, 스토리지, 데이터베이스, 네트워크, 분석, 데이터 관리 등 및 기타 다양한 기능을 통해 비즈니스 과제를 해결할 수 있습니다. 기업은 이러한 제품, 서비스 및 리소스에 액세스할 수 있는 권한이 있는 사용자를 정의할 수 있어야 합니다. 사용자가 설정을 조작, 변경 또는 추가할 수 있는 조건을 결정하는 것도 마찬가지로 중요합니다.

AWS AIM(Identity and Access Management)은 AWS 서비스 및 제품에 대한 액세스를 관리할 수 있는 안전한 제어 환경을 제공합니다. 적절하게 구성된 사용자, 액세스 키 및 사용 권한을 통해 AWS 및 Amazon FSx에서 VMware Cloud를 구축할 수 있습니다.

AIM에 대한 자세한 내용은 을 참조하십시오 https://docs.aws.amazon.com/iam/index.html["이 링크"^].



=== AWS 기반 VMware 클라우드

VMware Cloud on AWS는 기본 AWS 서비스에 최적화된 액세스를 통해 VMware의 엔터프라이즈급 SDDC 소프트웨어를 AWS 클라우드에 제공합니다. VMware Cloud Foundation을 기반으로 하는 VMware Cloud on AWS는 VMware의 컴퓨팅, 스토리지 및 네트워크 가상화 제품(VMware vSphere, VMware vSAN 및 VMware NSX)과 유연하고 탄력적인 전용 AWS 인프라에서 실행되도록 최적화된 VMware vCenter Server 관리를 통합합니다.

AWS 기반 VMware Cloud에 대한 자세한 내용은 를 참조하십시오 https://docs.vmware.com/en/VMware-Cloud-on-AWS/index.html["이 링크"^].



=== NetApp ONTAP용 Amazon FSx

NetApp ONTAP용 Amazon FSx는 모든 기능을 갖추고 있으며 완벽하게 관리되는 ONTAP 시스템으로, 기본 AWS 서비스로 제공됩니다. NetApp ONTAP을 기반으로 구축된 이 제품은 친숙한 기능을 제공하는 동시에 완전 관리형 클라우드 서비스의 단순성을 제공합니다.

ONTAP용 Amazon FSx는 퍼블릭 클라우드 또는 온프레미스의 VMware를 비롯한 다양한 컴퓨팅 유형에 대한 멀티 프로토콜 지원을 제공합니다. 현재 게스트 연결 사용 사례 및 기술 미리 보기의 NFS 데이터 저장소에 사용할 수 있는 Amazon FSx for ONTAP를 사용하면 기업은 사내 환경과 클라우드에서 익숙한 기능을 활용할 수 있습니다.

NetApp ONTAP용 Amazon FSx에 대한 자세한 내용은 를 참조하십시오 https://aws.amazon.com/fsx/netapp-ontap/["이 링크"].

link:aws-guest-dr-overview.html["다음: 개요 - AWS 게스트 연결 스토리지 재해 복구"]
