---
sidebar: sidebar 
permalink: ehc/aws/aws-guest-dr-cloud-backup-config.html 
keywords: secondary, windows, snapcenter server, veeam server 
summary: 애플리케이션 VM 및 데이터베이스 볼륨을 AWS에서 실행되는 VMware Cloud Volume 서비스로 페일오버하려면 SnapCenter Server와 Veeam Backup and Replication Server의 실행 중인 인스턴스를 설치 및 구성해야 합니다. 페일오버가 완료된 후 사내 데이터 센터에 대한 페일백이 계획 및 실행될 때까지 정상적인 백업 작업을 재개하도록 이러한 툴을 구성해야 합니다. 
---
= 클라우드 백업 툴 및 구성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


link:aws-guest-dr-config-veeam.html["이전: Veeam Backup Server를 구축 및 구성합니다."]

애플리케이션 VM 및 데이터베이스 볼륨을 AWS에서 실행되는 VMware Cloud Volume 서비스로 페일오버하려면 SnapCenter Server와 Veeam Backup and Replication Server의 실행 중인 인스턴스를 설치 및 구성해야 합니다. 페일오버가 완료된 후 사내 데이터 센터에 대한 페일백이 계획 및 실행될 때까지 정상적인 백업 작업을 재개하도록 이러한 툴을 구성해야 합니다.



== 보조 Windows SnapCenter 서버를 배포합니다

SnapCenter 서버는 VMware 클라우드 SDDC에 구축하거나 VMware 클라우드 환경에 대한 네트워크 연결을 통해 VPC에 상주하는 EC2 인스턴스에 설치됩니다.

SnapCenter 소프트웨어는 NetApp Support 사이트에서 제공되며 도메인 또는 작업 그룹에 있는 Microsoft Windows 시스템에 설치할 수 있습니다. 자세한 계획 가이드 및 설치 지침은 에서 확인할 수 있습니다 https://docs.netapp.com/us-en/snapcenter/install/install_workflow.html["NetApp 문서화 센터"^].

SnapCenter 소프트웨어는 에서 찾을 수 있습니다 https://mysupport.netapp.com["이 링크"^].



== 보조 Windows SnapCenter 서버를 구성합니다

FSx ONTAP에 미러링된 애플리케이션 데이터를 복구하려면 먼저 온-프레미스 SnapCenter 데이터베이스의 전체 복원을 수행해야 합니다. 이 프로세스가 완료되면 VM과의 통신이 다시 설정되고 FSx ONTAP를 기본 스토리지로 사용하여 응용 프로그램 백업을 다시 시작할 수 있습니다.

이를 위해서는 SnapCenter 서버에서 다음 항목을 완료해야 합니다.

. 원래 온-프레미스 SnapCenter 서버와 동일하게 컴퓨터 이름을 구성합니다.
. VMware 클라우드 및 FSx ONTAP 인스턴스와 통신하도록 네트워킹을 구성합니다.
. SnapCenter 데이터베이스를 복원하는 절차를 완료합니다.
. SnapCenter가 재해 복구 모드에 있는지 확인하여 이제 FSx가 백업용 기본 스토리지인지 확인합니다.
. 복구된 가상 머신과 통신이 다시 설정되었는지 확인합니다.


이러한 단계를 완료하는 방법에 대한 자세한 내용은 섹션을 참조하십시오 link:aws-guest-dr-failover.html#snapcenter-database-restore-process["SnapCenter 데이터베이스 복원 프로세스"].



== Secondary Veeam Backup & Replication 서버를 구축합니다

Veeam Backup & Replication 서버를 AWS의 VMware Cloud 또는 EC2 인스턴스에 설치할 수 있습니다. 자세한 구현 지침은 를 참조하십시오 https://www.veeam.com/documentation-guides-datasheets.html["Veeam Help Center 기술 문서"^].



== Secondary Veeam Backup & Replication 서버를 구성합니다

Amazon S3 스토리지에 백업된 가상 머신의 복구를 수행하려면 Veeam Server를 Windows 서버에 설치하고 원래 백업 저장소가 포함된 VMware Cloud, FSx ONTAP 및 S3 버킷과 통신하도록 구성해야 합니다. 또한 VM이 복구된 후 새 백업을 수행하려면 FSx ONTAP에 새 백업 리포지토리가 구성되어 있어야 합니다.

이 프로세스를 수행하려면 다음 항목을 완료해야 합니다.

. 네트워킹을 구성하여 원래 백업 저장소가 포함된 VMware Cloud, FSx ONTAP 및 S3 버킷과 통신합니다.
. FSx ONTAP에서 SMB 공유를 새 백업 리포지토리로 구성합니다.
. 사내에서 스케일아웃 백업 저장소의 일부로 사용된 원래 S3 버킷을 마운트합니다.
. VM을 복구한 후 SQL 및 Oracle VM을 보호하기 위한 새로운 백업 작업을 설정합니다.


Veeam을 사용하여 VM을 복원하는 방법에 대한 자세한 내용은 섹션을 참조하십시오 link:aws-guest-dr-restore-veeam-full.html["Veeam Full Restore로 애플리케이션 VM을 복구합니다"].

link:aws-guest-dr-snapcenter-db-backup.html["다음: 재해 복구를 위한 SnapCenter 데이터베이스 백업"]
