---
sidebar: sidebar 
permalink: ehc/aws/aws-vmc.html 
keywords: NetApp Solutions, hyperscalers, amazon, vmc, vmware managed cloud, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= AWS VMC를 위한 NetApp 솔루션
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
NetApp이 AWS VMware 클라우드(VMC)에 제공하는 기능에 대해 자세히 알아보십시오. NetApp은 게스트 연결 스토리지 장치 또는 기본 데이터 저장소로 마이그레이션 워크플로우에 전환하여 클라우드, 백업/복원 및 재해 복구를 확장/급증할 수 있습니다.

다음 옵션 중 하나를 선택하여 원하는 콘텐츠의 섹션으로 이동합니다.

* link:#config["하이퍼스케일 구성의 VMware"]
* link:#datastore["NetApp 스토리지 옵션"]




== AWS에서 VMC 구성

온프레미스에서와 마찬가지로 클라우드 기반 가상화 환경을 계획하는 것은 VM 및 마이그레이션을 생성할 수 있는 성공적인 프로덕션 준비 환경에 매우 중요합니다.

사내 환경과 마찬가지로, AWS에서 VMware Cloud를 계획하는 것은 VM과 마이그레이션을 성공적으로 운영 환경에 구축하는 데 매우 중요합니다.

이 섹션에서는 AWS SDDC에서 VMware Cloud를 설정 및 관리하고, NetApp 스토리지를 연결하는 데 사용할 수 있는 옵션과 함께 사용하는 방법을 설명합니다.


NOTE: 게스트 내 스토리지는 FSx ONTAP 및 Cloud Volumes ONTAP를 AWS VMC에 연결하는 유일한 지원 방법입니다.

설치 프로세스는 다음 단계로 나눌 수 있습니다.

* link:aws/aws-setup.html#deploy["VMware Cloud for AWS 구축 및 구성"]
* link:aws/aws-setup.html#connect["VMware Cloud를 FSx ONTAP에 연결합니다"]




== VMC용 NetApp 스토리지 옵션

AWS VMC에서 NetApp 스토리지를 추측으로 연결 또는 기본 데이터 저장소로 활용할 수 있습니다.

를 방문하십시오 link:ehc-support-configs.html["지원되는 NetApp 스토리지 옵션"] 를 참조하십시오.

AWS는 다음과 같은 구성에서 NetApp 스토리지를 지원합니다.

* 게스트 연결 스토리지 *

* link:aws/aws-guest.html#fsx-ontap["FSX ONTAP를 게스트 연결 스토리지로 사용합니다"]
* link:aws/aws-guest.html#cvo["CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다"]


* 네이티브 데이터 저장소 *

* link:https://blogs.vmware.com/cloud/2021/12/01/vmware-cloud-on-aws-going-big-reinvent2021/["FSX ONTAP를 기본 데이터 저장소 ^1로 사용합니다"^]



NOTE: 1-현재 비공개 미리보기에 있습니다
