---
sidebar: sidebar 
permalink: vmware/migrate-vms-to-ec2-fsxn.html 
keywords: netapp, vmware, amazon, ec2, fsxn, migration, iscsi, 
summary: '이 기술 보고서에서는 CMC(Cirrus Migration Cloud)의 MigrateOps "코드형 이동성" 기능을 사용하여 FSx for ONTAP iSCSI LUN에 배치된 데이터 디스크를 사용하여 온프레미스 VMware vSphere VM을 Amazon EC2 인스턴스로 마이그레이션하는 방법을 설명합니다.' 
---
= FSxN:Overview를 사용하여 VM을 Amazon EC2로 마이그레이션합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
조직은 AWS의 클라우드 컴퓨팅 솔루션으로 신속하게 마이그레이션하여 Amazon Elastic Compute Cloud(Amazon EC2) 인스턴스, Amazon FSx for NetApp ONTAP(FSx for ONTAP) 등의 서비스를 활용하여 IT 인프라를 현대화하고 비용을 절감하며 운영 효율성을 개선하고 있습니다. 이러한 AWS 오퍼링을 사용하면 소비 기반 가격 책정 모델 및 엔터프라이즈 스토리지 기능을 통해 TCO(총 소유 비용)를 최적화하는 마이그레이션을 수행할 수 있으며, 변화하는 글로벌 비즈니스 요구사항에 적합한 유연성과 확장성을 제공합니다.



== 개요

VMware vSphere에 크게 투자한 기업의 경우, 현재의 시장 상황을 고려할 때 AWS로 마이그레이션하는 것이 비용 효율적인 옵션이며 특별한 기회를 제공합니다.

조직에서는 AWS로 전환할 때 클라우드의 민첩성과 비용 이점을 활용하는 동시에, 특히 스토리지의 경우 친숙한 기능을 보존하려고 합니다. 워크로드를 마이그레이션하거나 재해 복구 솔루션을 설정할 때는 특히 iSCSI와 같은 익숙한 스토리지 프로토콜, 프로세스, 툴 및 기술을 통해 원활한 운영을 유지하는 것이 중요합니다.

엔터프라이즈 스토리지 기능을 유지하는 AWS 관리 스토리지 서비스 FSx for ONTAP을 사용하여 기업은 온프레미스 타사 공급업체 스토리지에서 제공하는 엔터프라이즈 스토리지 기능을 유지하면서 AWS의 기능을 최대한 활용하는 동시에 운영 중단을 최소화하고 향후 투자를 극대화할 수 있습니다.

이 기술 보고서에서는 CMC(Cirrus Migration Cloud)의 "코드형 데이터 이동성" 기능을 사용하여 FSx for ONTAP iSCSI LUN에 배치된 데이터 디스크를 통해 온프레미스 VMware vSphere VM을 Amazon EC2 인스턴스로 마이그레이션하는 방법을 다룹니다.



== 솔루션 요구 사항

VMware 고객은 현재 해결하고자 하는 여러 가지 과제가 있습니다. 이러한 조직은 다음을 원합니다.

. 씬 프로비저닝, 스토리지 효율성 기술, 설치 공간 제로 클론, 통합 백업, 블록 레벨 복제 등의 엔터프라이즈 스토리지 기능을 있습니다. 이를 통해 마이그레이션 노력을 최적화하고 Day 1부터 AWS를 기반으로 미래를 보장하는 구축을 최적화할 수 있습니다.
. FSx for ONTAP와 이 솔루션의 비용 최적화 기능을 통합하여 현재 Amazon EC2 인스턴스를 사용하는 AWS에서 스토리지 구축을 최적화합니다.
. 필요한 IOPS 및 처리량 매개 변수를 충족하도록 Amazon EC2 인스턴스의 크기를 적절하게 조정하여 블록 스토리지 솔루션과 함께 Amazon EC2 인스턴스를 사용하는 TCO(총 소유 비용)를 절감합니다. 블록 스토리지의 경우 Amazon EC2 디스크 작업의 대역폭과 I/O 속도가 제한됩니다. FSx for ONTAP의 파일 스토리지는 네트워크 대역폭을 사용합니다. 다시 말해, FSx for ONTAP에는 VM 레벨 I/O 제한이 없습니다.




== 기술 구성 요소 개요



=== FSx for ONTAP 개념

Amazon FSx for NetApp ONTAP은 NetApp ® ONTAP ® 파일 시스템에 AWS의 익숙한 ONTAP 데이터 관리 기능, 성능 및 API를 제공하는 완전 관리형 AWS 스토리지 서비스입니다. 고성능 스토리지는 다중 프로토콜(NFS, SMB, iSCSI)을 지원하여 Windows, Linux 및 macOS EC2 인스턴스를 사용하여 단일 서비스를 워크로드에 제공합니다.

FSx for ONTAP은 ONTAP 파일 시스템이므로 SnapMirror ® 데이터 복제 기술, 씬 클론, NetApp Snapshot ™ 복사본을 비롯하여 익숙한 NetApp 기능과 서비스를 많이 제공합니다. FSx for ONTAP는 데이터 계층화를 통해 저렴한 용량 계층을 활용하여 탄력적이며 사실상 제한 없이 확장할 수 있습니다. 또한, NetApp의 대표적인 NetApp 스토리지 효율성 기술을 활용하여 AWS에서 스토리지 비용을 더욱 절감할 수 있습니다. 자세한 내용은 을 참조하십시오 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Amazon FSx for ONTAP 시작하기"].



==== 파일 시스템

FSx for ONTAP의 중앙 리소스는 SSD(Solid State Drive) 스토리지를 기반으로 하는 파일 시스템입니다. FSx for ONTAP 파일 시스템을 프로비저닝할 때 사용자는 원하는 처리량과 스토리지 용량을 입력하고 파일 시스템이 있을 Amazon VPC를 선택합니다.

사용자는 파일 시스템에 대해 두 가지 기본 제공 고가용성 배포 모델(AZ(Multi-Availability Zone) 또는 단일 AZ 배포 중 하나를 선택할 수도 있습니다. 이러한 각 옵션은 고유한 수준의 내구성과 가용성을 제공하며 고객은 사용 사례의 비즈니스 연속성 요구사항에 따라 선택할 수 있습니다. 다중 AZ 배포는 두 개의 AZ에 걸쳐 원활하게 복제되는 이중 노드로 구성됩니다. 보다 비용 최적화된 단일 AZ 구축 옵션은 두 개의 노드로 분할된 두 개의 노드로 구성된 파일 시스템을 구성합니다. 두 노드는 모두 단일 AZ 내에 상주합니다.
스토리지 가상 머신
FSx for ONTAP 파일 시스템의 데이터는 SVM(스토리지 가상 머신)이라고 하는 논리적 스토리지 파티션을 통해 액세스할 수 있습니다. SVM은 실제로 자체 데이터와 관리 액세스 포인트가 탑재된 자체 파일 서버입니다. FSx for ONTAP 파일 시스템에서 iSCSI LUN에 액세스할 때 Amazon EC2 인스턴스는 SVM의 iSCSI 엔드포인트 IP 주소를 사용하여 SVM과 직접 인터페이스합니다.

클러스터에서 단일 SVM을 유지할 수도 있지만 클러스터에서 여러 SVM을 실행하는 옵션은 다양한 용도와 이점을 제공합니다. 고객은 워크로드 격리 요구사항을 비롯한 비즈니스 요구사항을 고려하여 구성할 최적의 SVM 수를 결정할 수 있습니다.



==== 볼륨

FSx for ONTAP SVM 내의 데이터는 가상 컨테이너 역할을 하는 볼륨이라는 구조로 저장되고 구성됩니다. 단일 또는 여러 개의 LUN으로 개별 볼륨을 구성할 수 있습니다. 각 볼륨에 저장된 데이터는 파일 시스템의 스토리지 용량을 사용합니다. 하지만 FSx for ONTAP는 볼륨을 씬 프로비저닝하므로 저장되는 데이터 양에 대해서만 스토리지 용량을 사용합니다.



=== Cirrus MigrateOps 개념

CMC는 Cirrus Data Solutions, Inc.에서 제공하는 SaaS(Transactable Software-as-a-Service) 서비스이며 AWS Marketplace를 통해 제공됩니다. MigrateOps는 CMC의 코드형 데이터 이동성 자동화 기능으로, YAML의 간단한 작동 구성을 사용하여 규모에 맞게 데이터 이동성 작업을 선언적으로 관리할 수 있습니다. MigrateOps 구성에 따라 데이터 이동성 작업의 실행 방법이 결정됩니다. MigrateOps에 대한 자세한 내용은 를 참조하십시오 link:https://www.google.com/url?q=https://customer.cirrusdata.com/cdc/kb/articles/about-migrateops-hCCHcmhfbj&sa=D&source=docs&ust=1715480377722215&usg=AOvVaw033gzvuAlgxAWDT_kOYLg1["MigrateOps 정보"].

MigrateOps는 전체 프로세스를 간소화하기 위해 특별 제작된 자동화 우선 접근 방식을 채택하여 운영 중단 없이 클라우드 규모 엔터프라이즈 데이터의 이동성을 보장합니다. MigrateOps는 CMC가 자동화를 위해 제공하는 풍부한 기능의 기능 외에도 다음과 같이 외부적으로 관리되는 다른 자동화를 추가로 제공합니다.

* OS 수정
* 애플리케이션 컷오버 및 승인 일정 관리
* 다운타임이 없는 클러스터 마이그레이션
* 퍼블릭/프라이빗 클라우드 플랫폼 통합
* 가상화 플랫폼 통합
* 엔터프라이즈 스토리지 관리 통합
* SAN(iSCSI) 구성


위의 작업이 완전히 자동화되어 있으므로 온프레미스 소스 VM 준비(예: AWS 에이전트 및 툴 추가), 대상 FSx LUN 생성, AWS 타겟 인스턴스에서 iSCSI 및 다중 경로/MPIO 설정 등 모든 번거로운 단계가 수행됨 또한 응용 프로그램 서비스를 중지/시작하는 모든 작업은 YAML 파일에 매개 변수를 지정하기만 하면 해결됩니다.

FSx for ONTAP은 데이터 LUN을 제공하고 Amazon EC2 인스턴스 유형의 크기를 적절하게 조정하면서 이전에 온프레미스 환경에서 사용했던 모든 기능을 제공하는 데 사용됩니다. CMC의 MigrateOps 기능은 매핑된 iSCSI LUN 프로비저닝을 포함하여 관련된 모든 단계를 자동화하여 예측 가능한 선언적 작업으로 만듭니다.

* 참고 *: 스토리지 소스 스토리지에서 FSx for ONTAP로 데이터를 안전하게 전송하기 위해서는 CMC가 소스 및 대상 가상 머신 인스턴스에 매우 얇은 에이전트를 설치해야 합니다.



== EC2 인스턴스와 함께 Amazon FSx for NetApp ONTAP를 사용할 때의 이점

Amazon EC2 인스턴스용 FSx for ONTAP 스토리지는 다음과 같은 여러 가지 이점을 제공합니다.

* 가장 까다로운 워크로드에 일관된 고성능을 제공하는 높은 처리량과 짧은 지연 시간을 보장하는 스토리지
* 지능형 NVMe 캐싱으로 성능이 개선됩니다
* 용량, 처리량 및 IOP를 상황에 맞게 변경할 수 있으며 변화하는 스토리지 수요에 빠르게 적응할 수 있습니다
* 온프레미스 ONTAP 스토리지에서 AWS로 블록 기반 데이터 복제
* 온프레미스 VMware 구축에 널리 사용되는 iSCSI를 포함한 멀티 프로토콜 액세스 가능성
* SnapMirror로 오케스트레이션된 NetApp Snapshot ™ 기술과 DR은 데이터 손실을 방지하고 복구 속도를 높입니다
* 씬 프로비저닝, 데이터 중복제거, 압축, 컴팩션을 비롯한 스토리지 효율성 기능으로 스토리지 설치 공간 및 비용을 줄여줍니다
* 효율적인 복제를 통해 백업을 생성하는 데 걸리는 시간을 몇 시간에서 단 몇 분으로 단축하여 RTO를 최적화합니다
* NetApp SnapCenter ® 를 사용한 파일 백업 및 복원을 위한 세분화된 옵션


FSx ONTAP을 사용하여 Amazon EC2 인스턴스를 iSCSI 기반 스토리지 계층으로 구축하면 AWS에서의 배포를 혁신할 수 있는 고성능, 미션 크리티컬 데이터 관리 기능 및 비용 절감 스토리지 효율성 기능을 제공할 수 있습니다.

Flash Cache 및 여러 iSCSI 세션을 실행하고 5%의 작업 세트 크기를 활용하면 FSx for ONTAP에서 350K 이상의 IOPS를 제공하여 가장 집약적인 워크로드도 충족하는 성능 수준을 제공할 수 있습니다.

블록 스토리지 대역폭 제한이 아니라 FSx for ONTAP에 네트워크 대역폭 제한만 적용되므로, 사용자가 소형 Amazon EC2 인스턴스 유형을 활용하는 동시에 훨씬 큰 인스턴스 유형과 동일한 성능 속도를 얻을 수 있습니다. 또한 이러한 작은 인스턴스 유형을 사용하면 컴퓨팅 비용을 낮게 유지하여 TCO를 최적화할 수 있습니다.

FSx for ONTAP에서 여러 프로토콜을 지원한다는 또 다른 이점입니다. 이는 단일 AWS 스토리지 서비스를 표준화하여 기존 데이터 및 파일 서비스 요구사항을 광범위하게 파악할 수 있습니다.
VMware vSphere에 크게 투자한 기업의 경우, 현재의 시장 상황을 고려할 때 AWS로 마이그레이션하는 것이 비용 효율적인 옵션이며 특별한 기회를 제공합니다.
