---
sidebar: sidebar 
permalink: vmware/vmw-getting-started-ontap-apis-automation.html 
keywords:  
summary:  
---
= NetApp API를 사용하여 VMware 관리 기능 향상
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
API(Application Programming Interface)는 가상화 환경의 자동화, 통합 및 효율적인 관리를 지원하여 VMware 관리에서 중요한 역할을 합니다.



== 소개

VMware는 관리자가 다양한 VMware 제품 및 서비스와 프로그래밍 방식으로 상호 작용할 수 있는 다양한 API를 제공하여 운영의 효율성과 일관성을 향상시킵니다. 또한 NetApp ONTAP API는 관리자가 VMware 워크로드와 함께 스토리지 환경 관리를 자동화, 통합 및 최적화할 수 있도록 하는 강력한 툴셋을 제공합니다. 이러한 API를 사용하면 ONTAP 스토리지 시스템과 VMware 간의 원활한 상호 작용을 지원하여 효율성, 성능 및 데이터 보호가 향상됩니다.



== VMware 기반 API

* * VMware vSphere API: * vSphere API는 관리자가 VMware vSphere 환경을 관리하고 자동화할 수 있는 포괄적인 API입니다. 또한 가상 머신 프로비저닝, 구성, 모니터링 및 수명주기 관리를 비롯한 다양한 vSphere 기능에 대한 액세스를 제공합니다.
* * VMware vCenter Server REST API: * vCenter Server REST API는 vCenter Server 및 관련 구성 요소를 관리하기 위한 최신 RESTful 인터페이스를 제공합니다. 자동화 및 다른 시스템 및 툴과의 통합을 간소화합니다.
* * VMware Cloud Foundation API: * VMware SDDC(소프트웨어 정의 데이터 센터) API는 VMware SDDC 환경 내의 다양한 구성 요소와 서비스에 프로그래밍 방식으로 액세스할 수 있도록 지원합니다. 관리자와 개발자는 이러한 API를 사용하여 컴퓨팅, 스토리지, 네트워킹 및 관리 서비스를 비롯하여 데이터 센터의 다양한 측면을 자동화, 관리 및 통합할 수 있습니다.
* * VMware vSphere Storage API - Storage Awareness: * VASA는 관리 및 관리를 위해 vCenter와 스토리지 어레이를 통합하는 API 집합입니다. 이 아키텍처는 VMware vSphere와 스토리지 시스템 간의 통신을 처리하는 VASA Provider를 비롯한 여러 구성 요소를 기반으로 합니다. ONTAP를 통해 이 공급자는 VMware vSphere용 ONTAP 툴의 일부로 구현됩니다.
* * VMware vSphere Storage API - 어레이 통합: * VAAI는 VMware vSphere ESXi 호스트와 스토리지 장치 간의 통신을 가능하게 하는 API 집합입니다. API에는 호스트에서 스토리지 작업을 스토리지로 오프로드하는 데 사용하는 기본 작업 세트가 포함되어 있습니다. VAAI는 스토리지 집약적인 작업에 대해 상당한 성능 향상을 제공할 수 있습니다.




== ONTAP 기반 API

* * NetApp ONTAP REST API: * ONTAP REST API는 ONTAP 스토리지 시스템 관리를 위한 최신 RESTful 인터페이스를 제공합니다. 또한 프로비저닝, 모니터링 및 구성과 같은 스토리지 작업의 자동화를 단순화합니다. VMware vSphere 및 기타 VMware 관리 툴과 쉽게 통합할 수 있으므로 VMware 환경에서 직접 자동화된 스토리지 작업을 수행할 수 있습니다. 기본 스토리지 관리부터 고급 데이터 보호 및 복제 작업에 이르기까지 광범위한 작업을 지원하므로 확장 가능하고 유연한 스토리지 관리가 가능합니다.
* * VMware vSphere용 ONTAP 툴: * VMware vSphere용 ONTAP 툴은 ONTAP와 vSphere를 통합하기 위한 툴 세트입니다. VASA API 프레임워크의 공급자 기능을 구현합니다. ONTAP 툴에는 vCenter 플러그인, VMware 사이트 복구 관리자를 위한 SRA(스토리지 복제 어댑터), 자동화 애플리케이션을 구축하는 데 사용할 수 있는 REST API 서버도 포함되어 있습니다.




== 요약

요약하면, 관리자는 ONTAP API를 사용하여 VMware 환경에서 데이터 저장소의 생성 및 구성을 스크립팅하여 신속하고 일관된 스토리지 프로비저닝을 보장할 수 있습니다. 또한 VMware 가상 머신의 스냅샷 생성, 예약 및 삭제를 자동화하여 효율적인 데이터 보호 및 복구 옵션을 제공할 수 있습니다. SnapMirror API는 복제 관계 설정 및 관리 자동화를 용이하게 하여 VMware 워크로드를 위한 강력한 재해 복구 솔루션을 보장합니다. 또한 관리자는 스크립트를 구현하여 스토리지 성능 메트릭을 모니터링하고 성능 임계값이 위반될 때 경고 또는 자동화된 작업을 트리거하여 VMware 워크로드에 최적화된 스토리지 성능을 보장할 수 있습니다. 관리자는 ONTAP API를 vSphere 및 vRealize에서 제공하는 API와 같은 VMware API와 통합하여 원활하고 고도로 자동화된 관리 환경을 구축하고 가상화된 인프라의 전반적인 효율성과 안정성을 향상시킬 수 있습니다.
