---
sidebar: sidebar 
permalink: vmware/vmw-vcf-mgmt-supplemental-fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= VMware용 ONTAP 툴을 사용하여 VI 워크로드 및 관리 도메인에 대한 보조 스토리지로 FC의 VMFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 시나리오에서는 ONTAP 툴을 사용하여 관리 및 워크로드 도메인용 FC(Fibre Channel) 백엔드를 사용하여 VMFS 데이터 저장소를 구축하는 방법을 보여 줍니다.



== 파이버 채널의 이점

* 고성능: * FC는 고속 데이터 전송률을 제공하므로 대량의 데이터에 빠르고 안정적으로 액세스해야 하는 애플리케이션에 이상적입니다.

* 낮은 지연 시간: * 매우 짧은 지연 시간으로, 데이터베이스 및 가상화 환경과 같이 성능에 민감한 애플리케이션에 매우 중요합니다.

*안정성:* FC 네트워크는 내장된 이중화 및 오류 수정 등의 기능을 통해 견고성과 신뢰성으로 잘 알려져 있습니다.

* 전용 대역폭: * FC는 스토리지 트래픽에 전용 대역폭을 제공하여 네트워크 혼잡 위험을 줄입니다.

NetApp 스토리지 시스템에서 파이버 채널을 사용하는 방법에 대한 자세한 내용은 을 참조하십시오 https://docs.netapp.com/us-en/ontap/san-admin/san-provisioning-fc-concept.html["FC를 사용한 SAN 프로비저닝"].



== 시나리오 개요

VCF Supplemental 데이터 저장소는 vCenter를 사용하여 Day-2 작업의 일부로 제공됩니다. 이 시나리오에서는 다음과 같은 상위 단계를 다룹니다.

* 관리 도메인에 ONTAP 도구 배포
* VI 워크로드 vCenter Server를 ONTAP 툴에 등록
* VMware vSphere용 ONTAP 툴 플러그인의 스토리지 백엔드를 정의합니다
* FC 전송에 VMFS 프로비저닝




== 필수 구성 요소

이 시나리오에는 다음과 같은 구성 요소 및 구성이 필요합니다.

* FC 포트가 FC 스위치에 연결된 ONTAP 스토리지 시스템
* FC 라이프를 사용하여 생성된 SVM
* FC HBA가 있는 vSphere를 FC 스위치에 연결합니다.
* 단일 이니시에이터 - 대상 조닝은 FC 스위치에 대해 구성됩니다.
+

NOTE: ONTAP 시스템의 물리적 FC 포트 대신 존 구성에 SVM FC 논리 인터페이스를 사용합니다.



NetApp은 FC LUN에 대해 다중 경로를 권장합니다.

ONTAP 스토리지 시스템에서 파이버 채널을 구성하는 방법에 대한 자세한 내용은 ONTAP 9 설명서의 을 https://docs.netapp.com/us-en/ontap/san-management/index.html["SAN 스토리지 관리"] 참조하십시오.

ONTAP 스토리지 시스템에서 VMFS를 사용하는 방법에 대한 자세한 내용은 을 https://docs.netapp.com/us-en/netapp-solutions/vmware/vmfs-deployment.html["VMFS 구축 가이드"]참조하십시오.



== 관리 도메인에 대한 배포 단계

ONTAP 툴을 구축하고 이 툴을 사용하여 VCF 관리 도메인에 VMFS 데이터 저장소를 생성하려면 다음 단계를 완료합니다.

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["관리 도메인에 ONTAP 도구를 배포합니다"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-storage-backend.html["vSphere Client 인터페이스를 사용하여 스토리지 백엔드를 정의합니다"]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["FC에서 VMFS를 프로비저닝합니다"]




== 추가 정보

ONTAP 스토리지 시스템 구성에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap["ONTAP 9 설명서"] 가운데.

VCF 구성에 대한 자세한 내용은 을 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware Cloud Foundation 설명서"]참조하십시오.



== 이 솔루션에 대한 비디오 데모입니다

.VMFS(FC) 데이터 저장소로서 VCF 관리 도메인용 보조 스토리지입니다
video::3135c36f-3a13-4c95-aac9-b2a0001816dc[panopto,width=360]