---
sidebar: sidebar 
permalink: vmware/vmw-vcf-protect-vmsc.html 
keywords: vmware, vcf, protect, vmsc, vsphere, metro, storage, cluster 
summary:  
---
= VMware vMSC(vSphere Metro Storage Cluster)를 통한 고가용성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VMware vMSC(vSphere Metro Storage Cluster)와 통합된 NetApp ONTAP High Availability는 VCF(VMware Cloud Foundation) 관리 및 VI 워크로드 도메인을 위한 강력한 솔루션을 제공합니다.

이러한 결합을 통해 지리적으로 분산된 사이트 간에 지속적인 데이터 가용성, 원활한 페일오버, 재해 복구가 보장되므로 중요한 워크로드의 복원력과 운영 연속성을 높일 수 있습니다. SnapMirror 액티브 동기화를 통해 전체 사이트 장애가 발생하더라도 비즈니스 서비스를 계속 운영할 수 있으므로 보조 복사본을 사용하여 애플리케이션을 투명하게 페일오버할 수 있습니다. SnapMirror 활성 동기화로 페일오버를 트리거하는 데 수동 개입이나 사용자 지정 스크립팅이 필요하지 않습니다.

자세한 내용은 다음 솔루션을 참조하십시오.

* link:vmw-vcf-vmsc-mgmt-smas.html["SnapMirror 활성 동기화를 사용하여 관리 도메인용 클러스터 확장"]
* link:vmw-vcf-vmsc-mgmt-mcc.html["MetroCluster를 사용하여 관리 도메인용 클러스터 확장"]
* link:vmw-vcf-vmsc-viwld-smas.html["SnapMirror 활성 동기화를 사용하여 VI 워크로드 도메인용 클러스터 확장"]
* link:vmw-vcf-vmsc-viwld-mcc.html["MetroCluster를 사용하여 VI 워크로드 도메인용 클러스터 확장"]

