---
sidebar: sidebar 
permalink: vmware/vmw-vcf-expand.html 
keywords: vmware, vcf, expand, supplemental, storage 
summary:  
---
= Supplemental Storage로 VCF 환경을 확장합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
VCF(VMware Cloud Foundation)는 VCF 관리 및 VI 워크로드 도메인에서 스토리지를 확장할 수 있는 다양한 보조 스토리지 옵션을 지원합니다.

NetApp의 VMware vSphere용 ONTAP 툴은 NetApp 스토리지를 VCF 환경에 원활하게 통합하여 이러한 확장을 위한 효율적인 솔루션을 제공합니다. ONTAP 툴을 사용하면 데이터 저장소를 간편하게 설정하고 관리할 수 있으므로 관리자가 vSphere Client에서 직접 스토리지를 프로비저닝하고 관리할 수 있습니다. 스냅샷, 클론 복제, 데이터 보호와 같은 ONTAP의 고급 기능을 통해 VCF 환경 내에서 스토리지 성능, 효율성 및 확장성을 개선합니다.

VCF 환경을 확장하는 데 필요한 기술 세부 사항은 다음 솔루션을 참조하십시오.

* link:vmw-vcf-mgmt-supplemental-iscsi.html["iSCSI를 사용하는 관리 도메인입니다"]
* link:vmw-vcf-mgmt-supplemental-fc.html["FC를 사용하는 관리 도메인입니다"]
* link:vmw-vcf-viwld-supplemental-vvols.html["VVol이 있는 가상 인프라 워크로드 도메인(iSCSI)"]
* link:vmw-vcf-viwld-supplemental-nfs-vvols.html["VVol이 있는 가상 인프라 워크로드 도메인(NFS)"]
* link:vmw-vcf-viwld-supplemental-nvme.html["NVMe/TCP가 있는 가상 인프라 워크로드 도메인"]
* link:vmw-vcf-viwld-supplemental-fc.html["FC가 있는 가상 인프라스트럭처 워크로드 도메인"]

