---
sidebar: sidebar 
permalink: vmware/vmware-smbc-cvt-smas.html 
keywords: NetApp Solutions, vMSC, Metro Storage Cluster, SnapMirror active sync, Business Continuity, SMBC, ONTAP Tools, AFD, SCV, iSCSI, backup, restore 
summary:  
---
= VMware vSphere Metro Storage Cluster를 사용하여 SM 활성 동기화를 비대칭에서 대칭형 액티브/액티브로 변환합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 문서에서는 VMware vSphere Metro Storage Cluster(VMSC)를 사용하여 SnapMirror 액티브 동기화를 비대칭에서 대칭 액티브/액티브로 변환하는 방법을 자세히 설명합니다.



== 개요

link:https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/["NetApp SnapMirror 활성 동기화(SM 활성 동기화)"] 는 가상화된 환경에서 RTO(복구 시간 목표)와 RPO(복구 시점 목표)를 0으로 달성하기 위한 강력한 솔루션입니다.

link:https://docs.netapp.com/us-en/ontap-apps-dbs/vmware/vmware_vmsc_overview.html["VMware vMSC(vSphere Metro Storage Cluster)"] 는 서로 다른 장애 도메인에 걸쳐 확장 클러스터 솔루션으로, 지리적으로 분리된 두 사이트 간에 VM(가상 머신)을 분산하여 한 사이트에 장애가 발생해도 지속적인 가용성을 제공합니다.

vMSC를 SM 활성 동기화와 결합하면 두 사이트 간에 데이터 일관성과 즉각적인 페일오버 기능이 보장됩니다. 이 설정은 데이터 손실이나 다운타임이 허용되지 않는 미션 크리티컬 애플리케이션에 특히 중요합니다.

이전에 SMBC(SnapMirror Business Continuity)라고 알려진 SM 활성 동기화는 전체 사이트 장애 시에도 비즈니스 서비스를 계속 운영할 수 있으므로 보조 복사본을 사용하여 애플리케이션을 투명하게 페일오버할 수 있습니다. ONTAP 9.15.1부터 SM 액티브 동기화는 대칭 액티브/액티브 기능을 지원합니다. 대칭 액티브/액티브를 사용하면 양방향 동기식 복제를 통해 보호된 LUN의 두 복사본에서 읽기 및 쓰기 I/O 작업을 수행할 수 있습니다. 따라서 두 LUN 복사본이 모두 로컬에서 I/O 작업을 제공할 수 있습니다.

이 문서는 VMware 확장 클러스터 환경에서 SM 액티브 동기화 비대칭 액티브/액티브를 SM 액티브 동기식 대칭 액티브/액티브로 변환하는 단계를 보여줍니다. 즉, SM 액티브 동기화를 자동 페일오버 정책에서 자동 페일오버-이중 정책으로 변환합니다. System Manager 및 ONTAP 툴을 사용하여 vMSC(SnapMirror Active sync)(SM-AS)를 설정하는 방법에 대한 자세한 내용은 를 link:https://docs.netapp.com/us-en/netapp-solutions/vmware/vmware-vmsc-with-smas.html["SnapMirror 활성 동기화가 포함된 VMware vSphere Metro 스토리지 클러스터"]참조하십시오.



== 필수 구성 요소

* NetApp 스토리지 시스템: SnapMirror 라이센스가 있는 두 개의 NetApp 스토리지 클러스터(소스 및 대상)가 있는지 확인합니다.
* 네트워크 연결: 소스 시스템과 대상 시스템 간의 지연 시간이 짧은 네트워크 연결을 확인합니다.
* 클러스터 및 SVM 피어링: 소스 클러스터와 타겟 클러스터 간에 클러스터 피어링 및 SVM(스토리지 가상 머신) 피어링을 설정합니다.
* ONTAP 버전: 두 클러스터가 동기 복제를 지원하는 ONTAP 버전을 실행하고 있는지 확인합니다. SM 활성 동기화의 경우 ONTAP 9.15.1 이상이 필요합니다.
* VMware vMSC 인프라스트럭처: 확장된 클러스터를 통해 하위 시스템이 여러 지역에 걸쳐 있을 수 있으므로 두 사이트의 vSphere 클러스터에 공통된 단일 기본 인프라스트럭처 세트를 제공할 수 있습니다. 사이트 간에 네트워크와 스토리지를 확장합니다.
* ONTAP TOOLS 10.2 이상 버전을 사용하면 NetApp SnapMirror 사용이 용이합니다. 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/release-notes/ontap-tools-9-ontap-tools-10-feature-comparison.html["VMware vSphere 10용 ONTAP 툴"]
* 운영 클러스터와 2차 클러스터 사이에 제로 RPO SnapMirror 동기식 관계가 있어야 합니다.
* 0 RTO SnapMirror 관계를 생성하려면 먼저 대상 볼륨의 모든 LUN을 매핑 해제해야 합니다.
* SnapMirror 액티브 동기화는 SAN 프로토콜만 지원합니다(NFS/CIFS 제외). NAS 액세스를 위해 정합성 보장 그룹의 구성 요소 가 마운트되지 않았는지 확인합니다.




== 비대칭에서 대칭 SM 활성 동기화로 변환하는 단계입니다

아래 예에서는 기본 사이트인 seltrz1을 선택하고 보조 사이트인 seltrz2를 선택합니다.

. 보조 사이트에서 기존 관계에 대한 SnapMirror 업데이트를 수행합니다.
+
....
selectrz2::> snapmirror update -destination-path site2:/cg/CGsite1_dest
....
. SnapMirror 업데이트가 성공적으로 완료되었는지 확인합니다.
+
....
selectrz2::> snapmirror show
....
. 각 제로 RPO 동기식 관계를 일시 중지합니다.
+
....
 selectrz2::> snapmirror quiesce -destination-path site2:/cg/CGsite1_dest
....
. 각 제로 RPO 동기식 관계를 삭제합니다.
+
....
selectrz2::> snapmirror delete -destination-path site2:/cg/CGsite1_dest
....
. 소스 SnapMirror 관계를 해제하지만 공통 스냅샷은 보존합니다.
+
....
selectrz1::> snapmirror release -relationship-info-only  true -destination-path svm0.1:/cg/CGsite1_dest                                           ".
....
. AutomatedFailoverDuplex 정책을 사용하여 제로 RTO SnapMirror 동기식 관계를 생성합니다.
+
....
selectrz2::> snapmirror create -source-path svm0.1:/cg/CGsite1 -destination-path site2:/cg/CGsite1_dest -cg-item-mappings site1lun1:@site1lun1_dest -policy AutomatedFailOverDuplex
....
. 기존 호스트가 로컬 운영 클러스터인 경우 보조 클러스터에 호스트를 추가하고 각 클러스터에 대한 각 액세스 권한을 사용하여 연결을 설정합니다.
. 2차 사이트에서 원격 호스트와 연결된 igroup에서 LUN 매핑을 삭제합니다.
+
....
selectrz2::> lun mapping delete -vserver svm0 -igroup wlkd01 -path  /vol/wkld01/wkld01
....
. 운영 사이트에서 기존 호스트의 이니시에이터 구성을 수정하여 로컬 클러스터의 이니시에이터에 대한 근위 경로를 설정합니다.
+
....
selectrz1::> set -privilege advanced
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1  -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver site1
....
. 새로운 호스트에 대한 새로운 igroup 및 이니시에이터를 추가하고 호스트 선호도를 해당 로컬 사이트에 근접하게 설정합니다. igroup 복제를 활성화하여 구성을 복제하고 원격 클러스터에서 호스트 인접성을 반전합니다.
+
....
selectrz1::*> igroup modify -vserver site1  -igroup smbc2smas -replication-peer svm0.1
selectrz1::*> igroup initiator add-proximal-vserver -vserver site1 -initiator iqn.1998-01.com.vmware:vcf-wkld-esx01.sddc.netapp.com:575556728:67 -proximal-vserver svm0.1
....
. 호스트에서 경로를 검색하고 호스트에 기본 클러스터에서 스토리지 LUN에 대한 활성/최적화 경로가 있는지 확인합니다.
. 애플리케이션을 배포하고 VM 워크로드를 클러스터 전체에 분산합니다.
. 정합성 보장 그룹을 다시 동기화합니다.
+
....
selectrz2::> snapmirror resync -destination-path site2:/cg/CGsite1_dest
....
. 호스트 LUN 입출력 경로를 재검색하여 LUN에 대한 모든 경로를 복구합니다.

