---
sidebar: sidebar 
permalink: vmware/vmware_vcf_asa_wkld_stretchcluster.html 
keywords: netapp, vmware, cloud, foundation, vcf, asa, all-flash, array, ontap tools, otv, sddc, iscsi 
summary:  
---
= VCF VI 워크로드 도메인용 ONTAP로 클러스터 확장
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 시나리오에서는 VMware vSphere(OTV)용 ONTAP 툴을 사용하여 VCF VI 워크로드 도메인에 대한 확장 클러스터를 구성하는 방법을 보여 줍니다.

저자: Suresh Thoppay



== 시나리오 개요

VCF 워크로드 도메인의 데이터 저장소는 SnapMirror 활성 동기화로 보호되어 확장 클러스터 솔루션을 제공할 수 있습니다. vSphere 클러스터 레벨에서 보호가 설정되고 클러스터의 모든 ONTAP 블록 데이터 저장소가 보호됩니다.

.워크로드 도메인의 주요 스토리지
[%collapsible]
====
워크로드 도메인은 VCF 가져오기 도구를 사용하여 가져오거나 SDDC 관리자를 사용하여 구축할 수 있습니다. SDDC 관리자를 사용하여 배포하면 기존 환경을 가져오는 것보다 더 많은 네트워킹 옵션이 제공됩니다.

. FC에서 VMFS를 사용하여 워크로드 도메인을 생성합니다
. 워크로드 도메인 vCenter를 ONTAP Tools Manager에 등록하여 vCenter 플러그인을 구축합니다
. ONTAP 툴에 스토리지 시스템을 등록합니다
. vSphere 클러스터를 보호합니다



NOTE: 클러스터가 확장되거나 축소될 때마다 소스 또는 타겟의 변경 사항을 나타내려면 클러스터에 대한 ONTAP 툴의 호스트 클러스터 관계를 업데이트해야 합니다.

====
.워크로드 도메인의 보충 스토리지
[%collapsible]
====
워크로드 도메인이 가동되어 실행 중이면 ONTAP 툴을 사용하여 추가 데이터 저장소를 생성할 수 있습니다. 이렇게 하면 정합성 보장 그룹 확장이 트리거됩니다.


TIP: vSphere 클러스터가 보호되는 경우 클러스터의 모든 데이터 저장소가 보호됩니다.

====


== 추가 정보

ONTAP 스토리지 시스템 구성에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap["ONTAP 9 설명서"] 가운데.

VCF 구성에 대한 자세한 내용은 을 참조하십시오 link:https://docs.vmware.com/en/VMware-Cloud-Foundation/index.html["VMware Cloud Foundation 설명서"].



== 이 솔루션에 대한 비디오 데모입니다

.ONTAP 툴을 사용하여 VCF용 클러스터 확장
video::569a91a9-2679-4414-b6dc-b25d00ff0c5a[panopto,width=360]