---
sidebar: sidebar 
permalink: vmware/vmware_vcf_aff_prin_fc.html 
keywords: netapp, vmware, cloud, foundation, vcf, aff, all-flash, array, ontap tools, otv, sddc, fc 
summary:  
---
= FC의 VMFS를 VCF 주 데이터 저장소로 사용합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 시나리오에서는 관리 및 워크로드 도메인용 FC(Fibre Channel) 백엔드를 사용하여 VMFS 데이터 저장소를 구축하는 방법을 보여 줍니다.

저자: Suresh Thoppay



== 시나리오 개요

VCF Principal storage는 VCF 도메인 설정 프로세스의 일부로 배포, 변환 또는 가져온 모든 유형의 스토리지를 말합니다. 이 문서에서는 다음과 같은 시나리오에 대해 설명합니다.

[cols="20% 20% 20% 20% 20%"]
|===
| 스토리지 유형 | 관리 도메인 - 기본 클러스터입니다 | 관리 도메인 - 추가 클러스터 | VI 워크로드 도메인 - 기본 클러스터 | VI 워크로드 도메인 - 추가 클러스터 


| FC의 VMFS | * 가져오기 도구 * | * 가져오기 도구, SDDC API * | 예 | 예 
|===


== 필수 구성 요소

이 시나리오에는 다음과 같은 구성 요소 및 구성이 필요합니다.

* FC 포트가 FC 스위치에 연결된 ONTAP 스토리지 시스템
* FC 라이프를 사용하여 생성된 SVM
* FC HBA가 있는 vSphere를 FC 스위치에 연결합니다.
* 단일 이니시에이터 - 대상 조닝은 FC 스위치에 대해 구성됩니다.
+

NOTE: ONTAP 시스템의 물리적 FC 포트 대신 존 구성에 SVM FC 논리 인터페이스를 사용합니다.



NetApp은 FC LUN에 대해 다중 경로를 권장합니다.



== 배포 단계



=== 관리 도메인 - 기본 클러스터입니다

초기 클러스터의 FC Principal 스토리지는 VCF brownfield 가져오기 툴에서만 지원됩니다. 클라우드 빌더 도구(버전 5.2.x까지)를 사용하여 VCF를 구축하는 경우 VSAN만 지원됩니다. 자세한 내용은 을 https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2/map-for-administering-vcf-5-2/importing-existing-vsphere-environments-admin/convert-or-import-a-vsphere-environment-into-vmware-cloud-foundation-admin.html["기존 vSphere 환경을 관리 도메인으로 변환"] 참조하십시오.



=== 관리 도메인 - 추가 클러스터

관리 도메인의 추가 vSphere 클러스터는 다음 옵션을 사용하여 구축할 수 있습니다. * vSphere 환경에 추가 클러스터를 설치하고 VCF Brownfield 가져오기 툴을 사용하여 vSphere 환경을 관리 도메인으로 변환합니다. https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/create-vvols-datastore.html["VMware vSphere용 ONTAP 툴"], https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["ONTAP API 또는 System Manager"] VMFS 데이터 저장소를 vSphere 클러스터에 구축하는 데 사용할 수 있습니다. * SDDC API를 사용하여 추가 클러스터를 구축합니다. vSphere 호스트에 VMFS 데이터 저장소가 구성되어 있어야 합니다.  https://docs.netapp.com/us-en/ontap/san-admin/provision-storage.html["ONTAP API 또는 System Manager"]vSphere 호스트에 LUN을 구축하는 데 사용합니다. * SDDC Manager UI를 사용하여 추가 클러스터를 구축합니다. 그러나 이 옵션은 버전 5.2.x까지 VSAN 데이터 저장소만 생성합니다



=== VI 워크로드 도메인 - 기본 클러스터

관리 도메인이 가동되고 실행된 후 SDDC Manager UI를 사용하여 VI 워크로드 도메인을 만들 수 있습니다 *. vSphere 호스트에 VMFS 데이터 저장소가 구성되어 있어야 합니다. System Manager 또는 ONTAP API를 사용하여 LUN을 vSphere 호스트에 구축합니다. * 기존 vSphere 환경을 새로운 VI 워크로드 도메인으로 가져옵니다. VMware vSphere, System Manager 또는 ONTAP API용 ONTAP 툴을 사용하여 VMFS 데이터 저장소를 vSphere 클러스터에 구축할 수 있습니다.



=== VI 워크로드 도메인 - 추가 클러스터

VI 워크로드가 가동되어 실행되면 다음 옵션을 사용하여 FC LUN에 VMFS를 사용하여 클러스터를 추가로 구축할 수 있습니다.

* VCF brownfield 가져오기 툴을 사용하여 vSphere 환경에서 추가 클러스터를 가져왔습니다. VMware vSphere, System Manager 또는 ONTAP API용 ONTAP 툴을 사용하여 VMFS 데이터 저장소를 vSphere 클러스터에 구축할 수 있습니다.
* SDDC Manager UI 또는 API를 사용하여 추가 클러스터 구축 vSphere 호스트에 VMFS 데이터 저장소가 구성되어 있어야 합니다. System Manager 또는 ONTAP API를 사용하여 LUN을 vSphere 호스트에 구축합니다.




== 추가 정보

ONTAP 스토리지 시스템 구성에 대한 자세한 내용은 을 참조하십시오 link:https://docs.netapp.com/us-en/ontap["ONTAP 9 설명서"] 가운데.

VCF 구성에 대한 자세한 내용은 을 link:https://techdocs.broadcom.com/us/en/vmware-cis/vcf/vcf-5-2-and-earlier/5-2.html["VMware Cloud Foundation 설명서"]참조하십시오.
