---
sidebar: sidebar 
permalink: vmware/vsphere_demos_videos.html 
keywords: vSphere, cloud, hybrid cloud, AWS, Azure, Google cloud, snapmirror cloud, cloud backup service, BlueXP Copy and Sync, FabricPool, ONTAP 
summary: 이 페이지에서는 비디오 및 자습서에 대한 소개 및 설명을 제공합니다. 
---
= 가상화 비디오 및 데모
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
하이브리드 클라우드, 가상화 및 컨테이너 솔루션의 특정 기능을 소개하는 다음 비디오 및 데모를 참조하십시오.

.VMware vSphere용 NetApp ONTAP 툴
[%collapsible]
====
.VMware용 ONTAP 툴 - 개요
video::e8071955-f6f1-45a0-a868-b12a010bba44[panopto]
.ONTAP를 사용한 VMware iSCSI 데이터 저장소 용량 할당
video::5c047271-aecc-437c-a444-b01200f9671a[panopto]
.ONTAP를 사용한 VMware NFS 데이터 저장소 용량 할당
video::a34bcd1c-3aaa-4917-9a5d-b01200f97f08[panopto]
====
.VMware vSphere용 SnapCenter 플러그인
[%collapsible]
====
NetApp SnapCenter 소프트웨어는 애플리케이션, 데이터베이스 및 파일 시스템 전반에서 데이터 보호를 안전하게 조율하고 관리하는 사용하기 쉬운 엔터프라이즈 플랫폼입니다.

VMware vSphere용 SnapCenter 플러그인을 사용하면 VM에 대한 백업, 복구 및 연결 작업과 VMware vCenter에서 직접 SnapCenter에 등록된 데이터 저장소에 대한 백업 및 마운트 작업을 수행할 수 있습니다.

NetApp SnapCenter Plug-in for VMware vSphere에 대한 자세한 내용은 를 참조하십시오 link:https://docs.netapp.com/ocsc-42/index.jsp?topic=%2Fcom.netapp.doc.ocsc-con%2FGUID-29BABBA7-B15F-452F-B137-2E5B269084B9.html["VMware vSphere용 NetApp SnapCenter 플러그인 개요"].

.VMware vSphere용 SnapCenter 플러그인 - 솔루션 전제 조건
video::38881de9-9ab5-4a8e-a17d-b01200fade6a[panopto,width=360]
.VMware vSphere용 SnapCenter 플러그인 - 구축
video::10cbcf2c-9964-41aa-ad7f-b01200faca01[panopto,width=360]
.VMware vSphere용 SnapCenter 플러그인 - 백업 워크플로우
video::b7272f18-c424-4cc3-bc0d-b01200faaf25[panopto,width=360]
.VMware vSphere용 SnapCenter 플러그인 - 복구 워크플로우
video::ed41002e-585c-445d-a60c-b01200fb1188[panopto,width=360]
.SnapCenter - SQL 복원 워크플로
video::8df4ad1f-83ad-448b-9405-b01200fb2567[panopto,width=360]
====
.3-2-1 데이터 보호 솔루션
[%collapsible]
====
3-2-1 데이터 보호 솔루션은 SnapMirror 기술을 사용하여 온프레미스 운영 및 보조 백업과 BlueXP 백업 및 복구를 사용하여 오브젝트 스토리지에 복제된 복사본을 결합합니다.

.VMware vSphere용 SnapCenter 플러그인을 사용한 VMFS 데이터 저장소의 3-2-1 데이터 보호 및 가상 머신용 BlueXP 백업 및 복구
video::7c21f3fc-4025-4d8f-b54c-b0e001504c76[panopto,width=360]
====
.AWS FSx ONTAP을 사용하는 AWS 기반 VMware Cloud를 참조하십시오
[%collapsible]
====
.iSCSI를 사용하는 FSx ONTAP가 있는 Windows 게스트 연결 스토리지
video::0d03e040-634f-4086-8cb5-b01200fb8515[panopto,width=360]
.NFS를 사용하는 FSx ONTAP가 있는 Linux 게스트 연결 스토리지
video::c3befe1b-4f32-4839-a031-b01200fb6d60[panopto,width=360]
.Amazon FSx ONTAP를 통해 AWS 기반 VMware Cloud TCO 절감
video::f0fedec5-dc17-47af-8821-b01200f00e08[panopto,width=360]
.Amazon FSx ONTAP을 지원하는 VMware Cloud on AWS 보조 데이터 저장소입니다
video::2065dcc1-f31a-4e71-a7d5-b01200f01171[panopto,width=360]
.VMC를 위한 VMware HCX 구축 및 구성 설정
video::6132c921-a44c-4c81-aab7-b01200fb5d29[panopto,width=360]
.VMC 및 FSx ONTAP용 VMware HCX를 사용한 VMotion 마이그레이션 데모
video::52661f10-3f90-4f3d-865a-b01200f06d31[panopto,width=360]
.VMC 및 FSx ONTAP용 VMware HCX를 사용한 콜드 마이그레이션 데모
video::685c0dc2-9d8a-42ff-b46d-b01200f056b0[panopto,width=360]
====
.ANF(Azure NetApp Files)가 있는 Azure 기반 Azure VMware 서비스
[%collapsible]
====
.Azure VMware 솔루션 Azure NetApp Files의 데이터 저장소 보충 개요
video::8c5ddb30-6c31-4cde-86e2-b01200effbd6[panopto,width=360]
.Cloud Volumes ONTAP, SnapCenter 및 Jetstream을 사용한 Azure VMware 솔루션 DR
video::5cd19888-8314-4cfc-ba30-b01200efff4f[panopto,width=360]
.VMware HCX for AVS 및 ANF와 함께 콜드 마이그레이션 데모
video::b7ffa5ad-5559-4e56-a166-b01200f025bc[panopto,width=360]
.VMware HCX와 함께 AVS 및 ANF용 vMotion 데모
video::986bb505-6f3d-4a5a-b016-b01200f03f18[panopto,width=360]
.VMware HCX for AVS 및 ANF와 함께 대량 마이그레이션 데모
video::255640f5-4dff-438c-8d50-b01200f017d1[panopto,width=360]
====
.NetApp ONTAP를 포함한 VMware 클라우드 기반
[%collapsible]
====
.VCF 워크로드 도메인의 주 스토리지로 사용되는 NFS 데이터 저장소입니다
video::9b66ac8d-d2b1-4ac4-a33c-b16900f67df6[panopto]
.VCF 관리 도메인에 대한 보조 스토리지로서의 iSCSI 데이터 저장소
video::1d0e1af1-40ae-483a-be6f-b156015507cc[panopto]
====
.NetApp과 VMware Tanzu
[%collapsible]
====
VMware Tanzu를 사용하면 vSphere 또는 VMware Cloud Foundation을 통해 Kubernetes 환경을 구축, 관리 및 관리할 수 있습니다. 고객은 VMware의 이 제품 포트폴리오를 통해 요구사항에 가장 적합한 VMware Tanzu 에디션을 선택하여 단일 제어 플레인에서 모든 관련 Kubernetes 클러스터를 관리할 수 있습니다.

VMware Tanzu에 대한 자세한 내용은 를 참조하십시오 https://tanzu.vmware.com/tanzu["VMware Tanzu 개요"^]. 이 리뷰에서는 VMware Tanzu에 대한 사용 사례, 추가 기능 및 기타 정보를 제공합니다.

.NetApp 및 VMware Tanzu Basic에서 VVOL을 사용하는 방법 1부
video::ZtbXeOJKhrc[youtube,width=360]
.NetApp 및 VMware Tanzu Basic에서 VVOL을 사용하는 방법, 2부
video::FVRKjWH7AoE[youtube,width=360]
.NetApp 및 VMware Tanzu Basic에서 VVOL을 사용하는 방법, 3부
video::Y-34SUtTTtU[youtube,width=360]
====
.NetApp Cloud Insights를 참조하십시오
[%collapsible]
====
NetApp Cloud Insights는 온프레미스 및 클라우드 인프라에 대한 가시성과 제어를 제공하도록 설계된 포괄적인 모니터링 및 분석 플랫폼입니다.

.NetApp Cloud Insights - 최신 데이터 센터에 대한 가시성
video::1e4da521-3104-4d51-8cde-b0e001502d3d[panopto,width=360]
====