---
sidebar: sidebar 
permalink: ai/ai-sent-support-center-analytics.html 
keywords: tr-4910, tr4910, 4910, sentiment, analysis, customer value, support center, artificial intelligence 
summary: 이 기술 보고서에서는 이전 학습 및 대화형 AI를 사용하는 NVIDIA 소프트웨어 프레임워크와 NetApp 데이터 관리 기술을 함께 사용하여 엔터프라이즈 수준의 글로벌 지원 센터에서 NetApp 데이터 관리 기술을 수행하는 고객에 대한 감정 분석을 수행할 수 있는 설계 지침을 제공합니다. 
---
= TR-4910: NetApp AI를 통한 고객 커뮤니케이션의 감정 분석
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Rick Huang, Sathish Thyagarajan, David Arnette, NetApp Diego Sosa-Coba, SFL Scientific

[role="lead"]
이 기술 보고서에서는 이전 학습 및 대화형 AI를 사용하는 NVIDIA 소프트웨어 프레임워크와 NetApp 데이터 관리 기술을 함께 사용하여 엔터프라이즈 수준의 글로벌 지원 센터에서 NetApp 데이터 관리 기술을 수행하는 고객에 대한 감정 분석을 수행할 수 있는 설계 지침을 제공합니다. 이 솔루션은 채팅 로그, 이메일 및 기타 텍스트 또는 오디오 통신을 나타내는 녹음된 음성 또는 텍스트 파일을 통해 고객 통찰력을 얻고자 하는 모든 산업에 적용됩니다. NetApp은 NetApp 클라우드 연결 All-Flash 스토리지를 통해 GPU 가속 컴퓨팅 클러스터에서 자동 음성 인식, 실시간 감정 분석, 딥 러닝 자연어 처리 모델 재교육 기능을 시연하기 위해 엔드 투 엔드 파이프라인을 구축했습니다. 방대한 최신 언어 모델을 훈련 및 최적화하여 글로벌 지원 센터와 신속하게 추론을 수행하여 탁월한 고객 경험과 객관적이고 장기적인 직원 성과 평가를 생성할 수 있습니다.

정서 분석은 자연어 처리(NLP) 내 연구 분야로서 텍스트에서 긍정적, 부정적 또는 중립적 감정을 도출합니다. 점점 더 많은 사람들이 대화하는 AI 시스템은 거의 세계적인 수준의 통합으로 부상했습니다. 감정 분석은 지원 센터 직원의 통화 성과를 확인하고 적절한 자동 챗봇 응답을 제공하는 등 다양한 활용 사례를 통해 분기별 수익 통화 시 기업 담당자와 대상 간의 상호 작용을 기반으로 회사의 주식 가격을 예측해 볼 수 있습니다. 또한, 감정 분석을 사용하여 브랜드가 제공하는 제품, 서비스 또는 지원에 대한 고객의 관점을 결정할 수 있습니다.

이 엔드 투 엔드 솔루션은 NLP 모델을 사용하여 지원 센터 분석 프레임워크를 지원하는 고수준 정서 분석을 수행합니다. 오디오 녹음은 서면 텍스트로 처리되며 대화의 각 문장에서 감정은 추출됩니다. 대시보드로 집계된 결과는 역사적, 실시간으로 대화 감정을 분석하기 위해 만들 수 있습니다. 이 솔루션은 유사한 데이터 양식 및 출력 요구가 있는 다른 솔루션으로 일반화할 수 있습니다. 적절한 데이터를 사용하여 다른 사용 사례를 수행할 수 있습니다. 예를 들어 동일한 종단간 파이프라인을 사용하여 기업 수익 통화를 분석하여 감정을 분석할 수 있습니다. 또한 파이프라인의 유연한 특성 때문에 주제 모델링 및 NER(명명된 엔티티 인식)과 같은 다른 형태의 NLP 분석이 가능합니다.

이러한 AI 구현은 NVIDIA Riva, NVIDIA TAO 툴킷 및 NetApp DataOps 툴킷을 함께 사용하여 가능했습니다. NVIDIA의 툴은 사전 구축된 모델 및 파이프라인을 사용하여 고성능 AI 솔루션을 신속하게 배포하는 데 사용됩니다. NetApp DataOps 툴킷은 다양한 데이터 관리 작업을 단순화하여 개발 속도를 높여줍니다.



== 고객 가치

기업은 감성 분석을 위해 텍스트, 오디오 및 비디오 대화를 위한 직원 평가 및 고객 반응 도구를 통해 가치를 확인합니다. 관리자는 대시보드에 표시되는 정보를 활용하여 대화 양쪽을 기준으로 직원 및 고객 만족도를 평가할 수 있습니다.

또한 NetApp DataOps 툴킷은 고객 인프라 내에서 데이터의 버전 관리 및 할당을 관리합니다. 따라서 복잡하지 않은 데이터 스토리지 비용을 발생시키지 않고 대시보드 내에 제공되는 분석 내용이 자주 업데이트됩니다.

link:ai-sent-use-cases.html["다음으로, 사용 사례를 살펴보겠습니다."]
