---
sidebar: sidebar 
permalink: ai/ai-sent-conclusion.html 
keywords: conclusion, ai augmented, customer experiences 
summary: 이 기술 보고서에서 제안된 솔루션은 이러한 탁월한 고객 경험의 제공을 지원하는 것으로 입증되었으며, 이제 기업이 AI 인프라 및 워크플로의 현대화를 위한 조치를 취하도록 하는 것이 과제입니다. 
---
= 결론
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
고객 경험이 점점 더 경쟁이 치열해지는 주요 전장으로 간주됨에 따라, 거의 모든 산업의 기업이 간과할 수 없는 중요한 구성 요소가 AI 강화 글로벌 지원 센터가 되었습니다. 이 기술 보고서에서 제안된 솔루션은 이러한 탁월한 고객 경험의 제공을 지원하는 것으로 입증되었으며, 이제 기업이 AI 인프라 및 워크플로의 현대화를 위한 조치를 취하도록 하는 것이 과제입니다.

고객 서비스에서 AI를 가장 잘 구현하는 것은 상담원을 대체하지 않는 것입니다. 오히려 AI를 사용하면 실시간 감정 분석, 분쟁 에스컬레이션, 다중 모달 Affective 컴퓨팅을 통해 탁월한 고객 경험을 창출하여 포괄적인 AI 모델이 규모에 따라 권장사항을 제시하고 개별 상담원의 부족한 사항을 보완할 수 있는 언어, 비언어적, 안면 신호를 감지할 수 있습니다. 또한 AI는 특정 고객과 현재 사용 가능한 에이전트 간에 더 나은 일치를 제공할 수 있습니다. AI를 사용하는 기업은 공급자의 제품, 서비스 및 브랜드 이미지에 대한 생각과 인상에 대해 귀중한 고객 감정을 끌어낼 수 있습니다.

이 솔루션을 사용하여 지원 상담원이 객관적인 성능 평가 메트릭으로 사용할 시계열 데이터를 구성할 수도 있습니다. 일반적인 고객 만족도 설문 조사에는 대개 충분한 응답이 없습니다. 고용주는 장기적인 직원 및 고객 감정을 수집하여 지원 상담원의 성과에 대해 충분한 정보를 바탕으로 의사 결정을 내릴 수 있습니다.

NetApp, SFL Scientific, 오픈 소스 오케스트레이션 프레임워크 및 NVIDIA의 결합을 통해 최신 기술을 관리형 서비스로 통합하고 기술 도입을 가속하고 새로운 AI/ML 애플리케이션의 출시 시기를 앞당길 수 있습니다. 이러한 고급 서비스는 클라우드 네이티브 환경과 하이브리드 구축 아키텍처에 대해 쉽게 이식할 수 있는 온프레미스 서비스입니다.
