---
sidebar: sidebar 
permalink: ai/aicp_conclusion.html 
keywords: NetApp AI Machine Deep Learning 
summary:  
---
= 결론
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
모든 규모와 업종에 상관없이 모든 기업과 조직은 실제 문제를 해결하고 혁신적인 제품과 서비스를 제공하며 경쟁이 갈수록 치열해지는 시장에서 경쟁 우위를 확보하기 위해 인공 지능(AI), 머신 러닝(ML), 딥 러닝(DL)으로 눈을 돌리고 있습니다. AI, ML 및 DL의 사용이 증가함에 따라 워크로드 확장성 및 데이터 가용성을 비롯한 많은 과제에 직면하게 됩니다. 이러한 문제는 NetApp AI Control Plane 솔루션을 사용하여 해결할 수 있습니다.

이 솔루션을 사용하면 데이터 네임스페이스를 빠르게 클론 복제할 수 있습니다. 또한 추적 가능성 및 버전 관리를 위한 데이터 및 모델 기준선의 거의 즉각적인 생성을 통합하는 AI, ML 및 DL 교육 워크플로우를 정의하고 구현할 수 있습니다. 이 솔루션을 사용하면 모든 단일 모델 교육을 모델이 훈련 및/또는 검증을 거친 정확한 데이터 세트로 추적할 수 있습니다. 끝으로, 이 솔루션을 사용하면 방대한 데이터 세트에 액세스할 수 있는 Jupyter Notebook 작업 공간을 신속하게 프로비저닝할 수 있습니다.

이 솔루션은 데이터 과학자 및 데이터 엔지니어들을 대상으로 하기 때문에 최소한의 NetApp 또는 NetApp ONTAP 전문 지식이 필요합니다. 이 솔루션에서는 단순하고 친숙한 툴과 인터페이스를 사용하여 데이터 관리 기능을 실행할 수 있습니다. 또한 이 솔루션은 완전한 오픈 소스 및 무료 구성 요소를 활용합니다. 따라서 환경에 NetApp 스토리지가 이미 있는 경우 지금 이 솔루션을 구현할 수 있습니다. 이 솔루션을 시험하고 싶지만 NetApp 스토리지가 없는 경우 를 방문하십시오 http://cloud.netapp.com/["cloud.netapp.com"^]또한 클라우드 기반 NetApp 스토리지 솔루션을 사용하여 시스템을 신속하게 가동할 수 있습니다.
