---
sidebar: sidebar 
permalink: ai/aicp_kubernetes_deployment.html 
keywords: NVIDIA, GPU, Kubernetes, Control Plane, Trident 
summary: 이 페이지에서는 NetApp AI Control Plane 솔루션을 구현하기 위해 Kubernetes 클러스터를 구축하는 데 필요한 작업에 대해 설명합니다. Kubernetes 클러스터가 이미 있는 경우, Kubeflow 및 NetApp Trident에서 지원하는 Kubernetes 버전을 실행 중인 경우 이 섹션을 건너뛸 수 있습니다. 
---
= Kubernetes 구축
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
이 섹션에서는 NetApp AI Control Plane 솔루션을 구현하기 위해 Kubernetes 클러스터를 구축하는 데 필요한 작업에 대해 설명합니다. Kubernetes 클러스터가 이미 있는 경우, Kubeflow 및 NetApp Trident에서 지원하는 Kubernetes 버전을 실행 중인 경우 이 섹션을 건너뛸 수 있습니다. Kubeflow에서 지원하는 Kubernetes 버전 목록은 를 참조하십시오 https://www.kubeflow.org/docs/started/getting-started/["Kubeflow 공식 문서"^]. Trident에서 지원하는 Kubernetes 버전 목록은 를 참조하십시오 https://netapp-trident.readthedocs.io/["Trident 문서"^].

NVIDIA GPU를 탑재한 베어 메탈 노드를 포함하는 온프레미스 Kubernetes 배포의 경우 NVIDIA의 DeepOps Kubernetes 배포 도구를 사용하는 것이 좋습니다. 이 섹션에서는 DeepOps를 사용하여 Kubernetes 클러스터 구축에 대해 간략하게 설명합니다.



=== 필수 구성 요소

이 섹션에 요약된 배포 연습을 수행하기 전에 이미 다음 작업을 수행했다고 가정합니다.

. 표준 구성 지침에 따라 베어 메탈 Kubernetes 노드(예: ONTAP AI 포드의 일부인 NVIDIA DGX 시스템)를 이미 구성했습니다.
. 모든 Kubernetes 마스터 및 작업자 노드와 배포 점프 호스트에 지원되는 운영 체제를 설치했습니다. DeepOps에서 지원하는 운영 체제 목록은 를 참조하십시오 https://github.com/NVIDIA/deepops["DeepOps GitHub 사이트"^].




=== NVIDIA DeepOps를 사용하여 Kubernetes 설치 및 구성

NVIDIA DeepOps를 사용하여 Kubernetes 클러스터를 구축하고 구성하려면 배포 점프 호스트에서 다음 작업을 수행하십시오.

. 의 지침에 따라 NVIDIA DeepOps를 다운로드합니다 https://github.com/NVIDIA/deepops/tree/master/docs["시작 페이지"^] NVIDIA DeepOps GitHub 사이트에서 다운로드할 수 있습니다.
. 의 지침에 따라 클러스터에 Kubernetes를 배포합니다 https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster["Kubernetes 배포 가이드 페이지"^] NVIDIA DeepOps GitHub 사이트에서 다운로드할 수 있습니다.


link:aicp_netapp_trident_deployment_and_configuration_overview.html["다음으로, NetApp Trident 구축 및 구성 개요 를 참조하십시오."]
