---
sidebar: sidebar 
permalink: ai/aicp_netapp_trident_deployment_and_configuration_overview.html 
keywords: Trident, Kubernetes, Storageclass 
summary: 이 페이지에서는 Kubernetes 클러스터에서 NetApp Trident를 설치 및 구성하기 위해 완료해야 하는 작업에 대해 설명합니다. 
---
= NetApp Trident 구축 및 구성
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
이 섹션에서는 Kubernetes 클러스터에 NetApp Trident를 설치 및 구성하기 위해 완료해야 하는 작업에 대해 설명합니다.



== 필수 구성 요소

이 섹션에 요약된 배포 연습을 수행하기 전에 이미 다음 작업을 수행했다고 가정합니다.

. Kubernetes 작업 클러스터가 이미 있으며, Trident에서 지원하는 Kubernetes 버전을 실행 중입니다. 지원되는 버전 목록은 를 참조하십시오 https://netapp-trident.readthedocs.io/["Trident 문서"^].
. Trident에서 지원하는 작업 중인 NetApp 스토리지 어플라이언스, 소프트웨어 정의 인스턴스 또는 클라우드 스토리지 서비스가 이미 있습니다.




== Trident를 설치합니다

Kubernetes 클러스터에 NetApp Trident를 설치 및 구성하려면 배포 점프 호스트에서 다음 작업을 수행하십시오.

. 다음 방법 중 하나를 사용하여 Trident를 배포합니다.
+
** NVIDIA DeepOps를 사용하여 Kubernetes 클러스터를 구축한 경우, NVIDIA DeepOps를 사용하여 Kubernetes 클러스터에 Trident를 구축할 수도 있습니다. DeepOps를 사용하여 Trident를 배포하려면 을 따릅니다 https://github.com/NVIDIA/deepops/tree/master/docs/k8s-cluster#netapp-trident["Trident 배포 지침"] NVIDIA DeepOps GitHub 사이트에서 다운로드할 수 있습니다.
** NVIDIA DeepOps를 사용하여 Kubernetes 클러스터를 배포하지 않았거나 Trident를 수동으로 배포하려는 경우 에 따라 Trident를 배포할 수 있습니다 https://netapp-trident.readthedocs.io/["배포 지침"^] Trident 문서 Trident 백엔드를 하나 이상 생성하고 Kubernetes StorageClass를 하나 이상 생성해야 합니다. 백엔드 및 StorageClasses에 대한 자세한 내용은 을 참조하십시오.





NOTE: ONTAP AI Pod에 NetApp AI Control Plane 솔루션을 구축하는 경우 를 참조하십시오 link:aicp_example_trident_backends_for_ontap_ai_deployments.html["ONTAP AI 배포에 대한 Trident 백엔드 예"] 및 를 생성할 수 있는 다른 Trident 백엔드의 몇 가지 예를 확인하십시오  생성할 수 있는 여러 Kubernetes StorageClasses의 몇 가지 예를 확인하십시오.

link:aicp_example_trident_backends_for_ontap_ai_deployments.html["다음: ONTAP AI 배포에 대한 Trident 백엔드 예"]
