---
sidebar: sidebar 
permalink: ai/aicp_kubeflow_deployment_overview.html 
keywords: Kubeflow, Prerequisites, Kubernetes, cluster 
summary: 오픈 소스 MLOps 및 NetApp-Kubeflow 배포 
---
= Kubeflow 구축
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 섹션에서는 Kubernetes 클러스터에 Kubeflow를 구축하기 위해 완료해야 하는 작업에 대해 설명합니다.



== 필수 구성 요소

이 섹션에 요약된 배포 연습을 수행하기 전에 이미 다음 작업을 수행했다고 가정합니다.

. 이미 작동 중인 Kubernetes 클러스터가 있으며, 구축하려는 Kubeflow 버전에서 지원하는 Kubernetes 버전을 실행하고 있습니다. 지원되는 Kubernetes 버전 목록은 에서 Kubeflow 버전에 대한 종속성을 참조하십시오 link:https://www.kubeflow.org/docs/releases/["Kubeflow 공식 문서"^].
. Kubernetes 클러스터에 NetApp Astra Trident를 이미 설치하고 구성했습니다. Astra Trident에 대한 자세한 내용은 를 참조하십시오 link:https://docs.netapp.com/us-en/trident/index.html["Astra Trident 문서"].




== 기본 Kubernetes StorageClass를 설정합니다

Kubeflow를 구축하기 전에 Kubernetes 클러스터 내에 기본 StorageClass를 지정하는 것이 좋습니다. Kubeflow 구축 프로세스에서 기본 StorageClass를 사용하여 새 영구 볼륨 프로비저닝을 시도할 수 있습니다. 기본 StorageClass 로 지정된 StorageClass 가 없으면 배포가 실패할 수 있습니다. 클러스터 내에서 기본 StorageClass를 지정하려면 배포 점프 호스트에서 다음 작업을 수행합니다. 클러스터 내에서 기본 StorageClass를 이미 지정한 경우에는 이 단계를 건너뛸 수 있습니다.

. 기존 StorageClasses 중 하나를 기본 StorageClass로 지정합니다. 다음 명령 예에서는 이름이 인 StorageClass 를 지정했습니다 `ontap-ai-flexvols-retain` 기본 StorageClass로 사용됩니다.



NOTE: ONTAP-NAS-Flexgroup Trident 백엔드 유형은 PVC 크기가 매우 큽니다. 기본적으로 Kubeflow는 크기가 몇 GB인 PVC를 프로비저닝하려고 시도합니다. 따라서 Kubeflow 구축을 위해 "ONTAP-NAS-flexgroup" 백엔드 유형을 기본 StorageClass로 사용하는 StorageClass를 지정할 수 없습니다.

....
$ kubectl get sc
NAME                                PROVISIONER             AGE
ontap-ai-flexgroups-retain          csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface1   csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface2   csi.trident.netapp.io   25h
ontap-ai-flexvols-retain            csi.trident.netapp.io   3s
$ kubectl patch storageclass ontap-ai-flexvols-retain -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
storageclass.storage.k8s.io/ontap-ai-flexvols-retain patched
$ kubectl get sc
NAME                                 PROVISIONER             AGE
ontap-ai-flexgroups-retain           csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface1    csi.trident.netapp.io   25h
ontap-ai-flexgroups-retain-iface2    csi.trident.netapp.io   25h
ontap-ai-flexvols-retain (default)   csi.trident.netapp.io   54s
....


== Kubeflow 구축 옵션

Kubeflow를 배포하는 다양한 옵션이 있습니다. 을 참조하십시오 link:https://www.kubeflow.org/docs/started/installing-kubeflow/["Kubeflow 공식 문서"] 구축 옵션 목록을 확인하고 요구사항에 가장 적합한 옵션을 선택하십시오.


NOTE: 검증을 위해 를 사용하여 Kubeflow 1.7을 배포했습니다 link:https://www.deploykf.org["구축KF"] 0.1.1.
