---
sidebar: sidebar 
permalink: ai/aicp_hardware_and_software_requirements.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: 오픈 소스 MLOps 및 NetApp-아키텍처 
---
= 있습니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
이 솔루션은 특정 하드웨어에 종속되지 않습니다. 이 솔루션은 Trident에서 지원하는 모든 NetApp 물리적 스토리지 어플라이언스, 소프트웨어 정의 인스턴스 또는 클라우드 서비스와 호환됩니다. NetApp AFF 스토리지 시스템, Amazon FSx for NetApp ONTAP, Azure NetApp Files 또는 NetApp Cloud Volumes ONTAP 인스턴스가 여기에 포함됩니다. 또한 사용되는 Kubernetes 버전이 Kubeflow 및 NetApp Astra Trident에서 지원되는 경우 모든 Kubernetes 클러스터에서 솔루션을 구현할 수 있습니다. Kubeflow에서 지원하는 Kubernetes 버전 목록은 를 참조하십시오 https://www.kubeflow.org/docs/started/getting-started/["Kubeflow 공식 문서"^]. Trident에서 지원하는 Kubernetes 버전 목록은 를 참조하십시오 https://docs.netapp.com/us-en/trident/index.html["Trident 문서"^]. 솔루션을 검증하는 데 사용된 환경에 대한 자세한 내용은 다음 표를 참조하십시오.

|===
| 소프트웨어 구성 요소 | 버전 


| 아파치 기류 | 2.0.1 


| Apache Airflow Helm Chart(Apache Airflow 제어 차트 | 8.0.8 


| Kubeflow | 1.7, 를 통해 배포 link:https://www.deploykf.org["구축KF"] 0.1.1 


| 쿠버네티스 | 1.26 


| NetApp Astra Trident | 2007년 3월 
|===


== 지원

NetApp은 Apache Airflow, Kubeflow 또는 Kubernetes에 대한 엔터프라이즈 지원을 제공하지 않습니다. 완전히 지원되는 MLOps 플랫폼에 관심이 있다면 link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["NetApp에 문의하십시오"] NetApp이 파트너와 공동으로 제공하는 모든 MLOps 솔루션에 대해 설명합니다.
