---
sidebar: sidebar 
permalink: ai/aicp_hardware_and_software_requirements.html 
keywords: Hardware, Software, Requirements, Trident, DeepOps, ONTAP, Ubuntu 
summary: 오픈 소스 MLOps 및 NetApp-아키텍처 
---
= 있습니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 솔루션은 특정 하드웨어에 종속되지 않습니다. 이 솔루션은 NetApp Astra Trident에서 지원하는 모든 NetApp 물리적 스토리지 어플라이언스, 소프트웨어 정의 인스턴스 또는 클라우드 서비스와 호환됩니다. NetApp AFF 스토리지 시스템, Amazon FSx for NetApp ONTAP, Azure NetApp Files, Google Cloud NetApp 볼륨 또는 NetApp Cloud Volumes ONTAP 인스턴스가 여기에 포함됩니다. 또한, 사용되는 Kubernetes 버전이 NetApp Astra Trident 및 구현 중인 기타 솔루션 구성 요소에서 지원되는 경우 모든 Kubernetes 클러스터에서 솔루션을 구현할 수 있습니다. Trident에서 지원되는 Kubernetes 버전 목록은 에서 https://docs.netapp.com/us-en/trident/index.html["Trident 문서"^]확인하십시오. 이 솔루션의 다양한 구성 요소를 검증하는 데 사용된 환경에 대한 자세한 내용은 다음 표를 참조하십시오.



== Apache Airflow Validation 환경

|===
| 소프트웨어 구성 요소 | 버전 


| 아파치 기류 | 2.0.1, 8.3.8을 통해 구축 link:https://artifacthub.io/packages/helm/airflow-helm/airflow["Apache Airflow Helm 차트"^] 


| 쿠버네티스 | 1.18 


| NetApp Astra Trident | 21.01 
|===


== JupyterHub 검증 환경

|===
| 소프트웨어 구성 요소 | 버전 


| 주피터허브 | 4.1.5, 3.3.7을 통해 구축 link:https://hub.jupyter.org/helm-chart/["JupyterHub Helm 차트"^] 


| 쿠버네티스 | 1.29 


| NetApp Astra Trident | 24.02 
|===


== MLflow Validation 환경

|===
| 소프트웨어 구성 요소 | 버전 


| MLflow(최소 | 2.14.1, 1.4.12를 통해 배포 link:https://artifacthub.io/packages/helm/bitnami/mlflow["MLflow 제어 차트"^] 


| 쿠버네티스 | 1.29 


| NetApp Astra Trident | 24.02 
|===


== Kubeflow Validation 환경

|===
| 소프트웨어 구성 요소 | 버전 


| Kubeflow | 1.7은 0.1.1을 통해 배포됩니다 link:https://www.deploykf.org["구축KF"^] 


| 쿠버네티스 | 1.26 


| NetApp Astra Trident | 2007년 3월 
|===


== 지원

NetApp은 Apache Airflow, JupyterHub, MLflow, Kubeflow 또는 Kubernetes에 대한 엔터프라이즈 지원을 제공하지 않습니다. 완전히 지원되는 MLOps 플랫폼에 관심이 있는 경우, link:https://www.netapp.com/us/contact-us/index.aspx?for_cr=us["NetApp에 문의하십시오"^] NetApp이 파트너와 공동으로 제공하는 MLOps 솔루션에 대해 자세히 알아보십시오.
