---
sidebar: sidebar 
permalink: ai/aks-anf_set_up_dask_with_rapids_deployment_on_aks_using_helm.html 
keywords: dask, rapids, deployment, aks, helm, pvc, persistent volume claim 
summary: '이 페이지에서는 제어(Helm)를 사용하여 AKS에서 RAPIDS를 사용하여 Dask를 설정하는 방법에 대해 설명합니다.' 
---
= Helm을 사용하여 AKS에서 RAPIDS를 사용하여 Dask를 설정합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Hrom을 사용하여 AKS에서 RAPIDS를 사용하여 Dask를 설정하려면 다음 단계를 수행하십시오.

. RAPIDS를 사용하여 Dask를 설치하기 위한 네임스페이스를 생성합니다.
+
....
kubectl create namespace rapids-dask
....
. PVC를 생성하여 클릭률 데이터 세트를 저장합니다.
+
.. 다음 YAML 콘텐츠를 파일에 저장하여 PVC를 생성합니다.
+
....
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-criteo-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: azurenetappfiles
....
.. Kubernetes 클러스터에 YAML 파일을 적용하십시오.
+
....
kubectl -n rapids-dask apply -f <your yaml file>
....


. "rapidsai git" 리포지토리 복제( https://github.com/rapidsai/helm-chart["https://github.com/rapidsai/helm-chart"^])를 클릭합니다.
+
....
git clone https://github.com/rapidsai/helm-chart helm-chart
....
. "Values.YAML"을 수정하고, 작업자와 Jupyter 작업공간을 위해 앞서 만든 PVC를 포함합니다.
+
.. 리포지토리의 "rapidsai" 디렉토리로 이동합니다.
+
....
cd helm-chart/rapidsai
....
.. Values.YAML 파일을 업데이트하고 PVC를 사용해 볼륨을 마운트합니다.
+
....
dask:
  …
  worker:
    name: worker
    …
    mounts:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-criteo-data
      volumeMounts:
        - name: data
          mountPath: /data
    …
  jupyter:
    name: jupyter
    …
    mounts:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-criteo-data
      volumeMounts:
        - name: data
          mountPath: /data
    …
....


. 리포지토리의 홈 디렉토리로 이동하여 H제어 를 사용하여 AKS에 작업자 노드 3개가 있는 Dask를 배포합니다.
+
....
cd ..
helm dep update rapidsai
helm install rapids-dask --namespace rapids-dask rapidsai
....

