---
sidebar: sidebar 
permalink: ai/aks-anf_click-through_rate_prediction_use_case_summary.html 
keywords: use case, terabyte click log, random forest, training 
summary: 이 페이지에는 분산형 또는 대규모 교육에서 Azure NetApp Files의 이점이 요약되어 있습니다. 
---
= 클릭률 예측 사용 사례 요약
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:aks-anf_cloud_resource_requirements.html["이전: 클라우드 리소스 요구사항"]

이 사용 사례는 공개적으로 제공되는 를 기반으로 합니다 http://labs.criteo.com/2013/12/download-terabyte-click-logs/["테라바이트 로그를 클릭합니다"^] 데이터 세트 시작 https://ailab.criteo.com/["Criteo AI Lab을 참조하십시오"^]. 최근 ML 플랫폼 및 애플리케이션의 발전으로 이제 대규모 학습에 많은 관심이 집중되고 있습니다. 클릭 비율(CTR)은 온라인 광고 노출 100회 당 평균 클릭 수(백분율로 표시)로 정의됩니다. 디지털 마케팅, 소매, 전자 상거래 및 서비스 공급자를 포함한 다양한 산업 및 사용 사례에서 핵심 메트릭으로 널리 채택되고 있습니다. CTR을 잠재적인 고객 트래픽에 대한 중요한 메트릭으로 사용하는 예는 다음과 같습니다.

* * 디지털 마케팅: * in https://support.google.com/google-ads/answer/2615875?hl=en["Google 웹로그 분석"^], CTR은 광고주 또는 상인의 키워드, 광고 및 무료 리스팅이 얼마나 잘 수행되고 있는지 측정하는 데 사용할 수 있습니다. 높은 CTR은 사용자가 귀하의 광고 및 리스팅을 유용하고 관련성 있는 것으로 찾도록 하는 좋은 지표입니다. 또한 CTR은 의 구성 요소인 키워드의 예상 CTR에 기여합니다 https://support.google.com/google-ads/answer/1752122?hl=en["광고 순위"^].
* * 전자 상거래: * 활용은 물론 https://analytics.google.com/analytics/web/provision/#/provision["Google 웹로그 분석"^]전자 상거래 백엔드에는 최소 일부 방문자 통계가 있습니다. 이러한 통계는 한 눈에 유용하지 않을 수 있지만 일반적으로 읽기 쉽고 다른 정보보다 정확할 수 있습니다. 이러한 통계로 구성된 타사 데이터 세트는 독점 데이터이므로 전자 상거래 셀러, 구매자 및 플랫폼과 가장 관련이 있습니다. 이러한 데이터 세트는 추가 분석을 위해 시계시리즈를 구성하여 결과를 작년도와 어제와 비교하여 벤치마크 설정에 사용할 수 있습니다.
* * 소매: * 오프라인 유통업체는 방문자 수와 고객 수를 CTR과 연관시킬 수 있습니다. 고객 수는 POS(Point of Sale) 기록에서 확인할 수 있습니다. 소매업체의 웹 사이트 또는 광고 트래픽에서 CTR을 사용하면 앞서 언급한 판매량이 발생할 수 있습니다. 로열티 프로그램은 온라인 광고나 다른 웹 사이트에서 리디렉션된 고객이 보상을 받기 위해 참여할 수 있기 때문에 또 다른 활용 사례입니다. 소매업체는 로열티 프로그램을 통해 고객을 확보하고 판매 기록에서 고객 행동을 기록하여 다양한 범주의 소비자 구매 행동을 예측할 뿐만 아니라 쿠폰을 개인화하고 이탈을 줄이는 추천 시스템을 구축할 수 있습니다.
* * 서비스 공급자: * 통신 회사 및 인터넷 서비스 공급자는 통찰력 있는 AI, ML 및 분석 사용 사례를 위한 수많은 제3자 사용자 원격 측정 데이터를 보유하고 있습니다. 예를 들어, 통신 회사는 모바일 가입자의 웹 브라우징 최상위 도메인 기록 로그를 매일 활용하여 기존 모델을 세부 조정하여 최신 사용자 세분화, 고객 행동 예측, 온라인 경험 개선을 위한 실시간 광고 제작을 위해 광고업체와 협업할 수 있습니다. 이러한 데이터 중심 마케팅 워크플로에서 CTR은 변환을 반영하는 중요한 지표입니다.


디지털 마케팅의 맥락에서 http://labs.criteo.com/2013/12/download-terabyte-click-logs/["Criteo Terabyte 클릭 로그"^] 이제 ML 플랫폼 및 알고리즘의 확장성을 평가하는 데 필요한 참조 데이터세트가 되었습니다. 광고주는 클릭 비율을 예측함으로써 광고에 반응할 가능성이 가장 높은 방문자를 선택하고, 검색 기록을 분석하고, 사용자의 관심사에 따라 가장 관련성이 높은 광고를 표시할 수 있습니다.

이 기술 보고서에 제공된 솔루션은 다음과 같은 이점을 제공합니다.

* Azure NetApp Files는 분산 또는 대규모 교육에서 이점을 제공합니다
* RAPIDS CUDA 지원 데이터 처리(cuDF, cuPy 등) 및 ML 알고리즘(cuML)
* 분산 교육을 위한 Dask 병렬 컴퓨팅 프레임워크입니다


RAPIDS AI 및 Azure NetApp Files를 기반으로 하는 엔드 투 엔드 워크플로우에서 랜덤 포리스트 모델 훈련 시간을 크게 두 배나 단축한 것으로 입증되었습니다. 이러한 개선은 매일 45GB의 구조화된 표 형식 데이터(평균)를 사용하여 실제 클릭 로그를 처리할 때 기존의 Pandas 접근 방식과 비교했을 때 매우 중요합니다. 이는 약 20억 개의 행이 포함된 DataFrame과 같습니다. 클러스터 환경 설정, 프레임워크 및 라이브러리 설치, 데이터 로드 및 처리, 기존 교육과 분산 교육 비교, 시각화 및 모니터링, 이 기술 보고서의 중요한 엔드 투 엔드 런타임 결과를 비교합니다.

link:aks-anf_install_and_set_up_the_aks_cluster.html["다음: AKS 클러스터를 설치하고 설정합니다."]
