---
sidebar: sidebar 
permalink: ai/ddlnexus_initial_setup.html 
keywords: NetApp AI, AI, Artificial Intelligence, ML, Machine Learning, NVIDIA, Hybrid, Hybrid Cloud, Hybrid Multicloud, Cloud, AWS, Amazon, Amazon Web Services, FSx ONTAP, FSx, NetApp ONTAP, FlexCache, SnapMirror, BlueXP 
summary: Domino Data Lab 및 NetApp이 지원되는 하이브리드 멀티 클라우드 MLOps - 초기 설정 
---
= 초기 설정
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 섹션에서는 사내 데이터 센터와 AWS가 통합된 하이브리드 환경에서 Domino Nexus와 NetApp 데이터 서비스를 활용하기 위해 수행해야 하는 초기 설정 작업에 대해 설명합니다.



== 필수 구성 요소

이 섹션에서 설명하는 단계를 수행하기 전에 다음 작업을 이미 수행한 것으로 가정합니다.

* 온프레미스 NetApp ONTAP 스토리지 플랫폼을 이미 구축하고 구성했습니다. 자세한 내용은 를 참조하십시오 link:https://www.netapp.com/support-and-training/documentation/["NetApp 제품 설명서"].
* AWS에서 이미 Amazon FSx ONTAP 인스턴스를 프로비저닝했습니다. 자세한 내용은 를 link:https://aws.amazon.com/fsx/netapp-ontap/["Amazon FSx ONTAP 제품 페이지 를 참조하십시오"]참조하십시오.
* 온프레미스 데이터 센터에서 이미 Kubernetes 클러스터를 프로비저닝했습니다. 자세한 내용은 를 참조하십시오 link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/["Domino 관리 가이드"].
* AWS에 이미 Amazon EKS 클러스터를 프로비저닝했습니다. 자세한 내용은 를 참조하십시오 link:https://docs.dominodatalab.com/en/latest/admin_guide/b35e66/admin-guide/["Domino 관리 가이드"].
* 온프레미스 Kubernetes 클러스터에 NetApp Trident을 설치했습니다. 또한 스토리지 리소스를 프로비저닝 및 관리할 때 온프레미스 NetApp ONTAP 스토리지 플랫폼을 사용하도록 이 Trident 인스턴스를 구성했습니다. 자세한 내용은 를 link:https://docs.netapp.com/us-en/trident/index.html["NetApp Trident 문서"]참조하십시오.
* Amazon EKS 클러스터에 NetApp Trident를 설치했습니다. 또한 스토리지 리소스를 프로비저닝하고 관리할 때 Amazon FSx ONTAP 인스턴스를 사용하도록 이 Trident 인스턴스를 구성했습니다. 자세한 내용은 를 link:https://docs.netapp.com/us-en/trident/index.html["NetApp Trident 문서"]참조하십시오.
* 사내 데이터 센터와 AWS의 VPC(Virtual Private Cloud) 간에 양방향 네트워크 연결이 있어야 합니다. 이를 구현하는 다양한 옵션에 대한 자세한 내용은 를 참조하십시오 link:https://docs.aws.amazon.com/vpc/latest/userguide/vpn-connections.html["Amazon VPN(가상 사설망) 설명서"].




== AWS에 Domino Enterprise AI 플랫폼을 설치합니다

AWS에 Domino Enterprise MLOps Platform을 설치하려면 에 설명된 지침을 link:https://docs.dominodatalab.com/en/latest/admin_guide/c1eec3/deploy-domino/["Domino 관리 가이드"]따르십시오. 이전에 프로비저닝한 동일한 Amazon EKS 클러스터에 Domino를 구축해야 합니다. 또한 이 EKS 클러스터에 NetApp Trident가 이미 설치되어 있고 구성되어 있어야 하며, domino.yml 설치 구성 파일에서 Trident 관리 저장소 클래스를 공유 저장소 클래스로 지정해야 합니다.


NOTE: 을 참조하십시오 link:https://docs.dominodatalab.com/en/latest/admin_guide/7f4331/install-configuration-reference/#storage-classes["Domino 설치 구성 참조 가이드"] domino.yml 설치 구성 파일에서 공유 저장소 클래스를 지정하는 방법에 대한 자세한 내용은 을 참조하십시오.


NOTE: link:https://www.netapp.com/media/79922-tr-4952.pdf["기술 보고서 TR-4952"] Amazon FSx ONTAP를 사용하여 AWS에서 Domino를 배포하는 과정을 안내하며, 발생하는 문제를 해결하는 데 유용한 참고 자료가 될 수 있습니다.



== Domino Nexus를 활성화합니다

다음으로 Domino Nexus를 활성화해야 합니다. 을 참조하십시오 link:https://docs.dominodatalab.com/en/latest/admin_guide/c65074/nexus-hybrid-architecture/["Domino 관리 가이드"] 를 참조하십시오.



== 온프레미스 데이터 센터에 Domino Data Plane을 구축하십시오

그런 다음 사내 데이터 센터에 Domino Data Plane을 구축해야 합니다. 이전에 프로비저닝한 온프레미스 Kubernetes 클러스터에 이 데이터 플레인을 구축해야 합니다. 또한 NetApp Trident가 이 Kubernetes 클러스터에 이미 설치되어 있어야 합니다. 자세한 내용은 을 link:https://docs.dominodatalab.com/en/latest/admin_guide/5781ea/data-planes/["Domino 관리 가이드"] 참조하십시오.
