---
sidebar: sidebar 
permalink: ai/hcaios_where_to_find_additional_information.html 
keywords: NetApp Additional Information 
summary:  
---
= 추가 정보를 찾을 수 있는 위치
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
이 문서에 설명된 정보에 대한 자세한 내용은 다음 리소스를 참조하십시오.

* cnvrg.io( https://cnvrg.io["https://cnvrg.io"^]):
+
** cnvrg 코어(무료 ML 플랫폼)
+
https://cnvrg.io/platform/core[]

** cnvrg 문서
+
https://app.cnvrg.io/docs["https://app.cnvrg.io/docs"^]



* NVIDIA DGX-1 서버:
+
** NVIDIA DGX-1 서버
+
https://www.nvidia.com/en-us/data-center/dgx-1/[]

** NVIDIA Tesla V100 Tensor 코어 GPU
+
https://www.nvidia.com/en-us/data-center/tesla-v100/[]

** NGC(NVIDIA GPU Cloud)
+
https://www.nvidia.com/en-us/gpu-cloud/[]

** AFF를 위한 NetApp FlashAdvantage
+
https://www.netapp.com/pdf.html?item=/media/19894-ds-3733.pdf[]

** ONTAP 9.x 설명서
+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286[]

** NetApp FlexGroup 기술 보고서
+
https://www.netapp.com/pdf.html?item=/media/7337-tr4557pdf.pdf[]



* 컨테이너용 NetApp 영구 스토리지:
+
** NetApp 트라이던트
+
https://netapp.io/persistent-storage-provisioner-for-kubernetes/[]



* NetApp 상호 운용성 매트릭스:
+
** NetApp 상호 운용성 매트릭스 툴
+
https://mysupport.netapp.com/matrix/#welcome[]



* ONTAP AI 네트워킹:
+
** Cisco Nexus 3232C 스위치
+
https://www.cisco.com/c/en/us/products/switches/nexus-3232c-switch/index.html[]

** Mellanox Spectrum 2000 시리즈 스위치
+
http://www.mellanox.com/page/products_dyn?product_family=251&mtag=sn2000[]



* ML 프레임워크 및 도구:
+
** 달리
+
https://github.com/NVIDIA/DALI[]

** TensorFlow: 모두를 위한 오픈 소스 머신 러닝 프레임워크
+
https://www.tensorflow.org/[]

** Horovod: Uber의 TensorFlow용 오픈 소스 분산 딥 러닝 프레임워크
+
https://eng.uber.com/horovod/[]

** 컨테이너 런타임 에코시스템에서 GPU 지원
+
https://devblogs.nvidia.com/gpu-containers-runtime/[]

** Docker 를 참조하십시오
+
https://docs.docker.com[]

** 쿠버네티스
+
https://kubernetes.io/docs/home/[]

** NVIDIA DeepOps
+
https://github.com/NVIDIA/deepops[]

** Kubeflow
+
http://www.kubeflow.org/[]

** Jupyter 노트북 서버
+
http://www.jupyter.org/[]



* 데이터 세트 및 벤치마크
+
** NIH 흉부 X선 데이터 세트
+
https://nihcc.app.box.com/v/ChestXray-NIHCC[]

** Xiaosong Wang, Yifan Peng, Le Lu, Zhivyong Lu, Mohammadadadhadi Bagheri, Ronald Summers, ChestX-ray8: 병원 스케일 흉부 X선 데이터베이스 및 약한 감독 하에 Common Thorax 질환의 분류 및 국소화에 대한 벤치마크, IEEE CVPR, pp. 3462-3471, 2017TR-4841-0620



