---
sidebar: sidebar 
permalink: ai/hciai_edge_use_cases.html 
keywords:  
summary:  
---
= 사용 사례
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
오늘날의 모든 애플리케이션은 AI가 지원하지 않지만, AI의 탁월한 이점을 활용할 수 있도록 하는 새로운 기능도 필요합니다. AI의 채택을 지원하려면 최적의 상태로 기능하고 지속적인 혁신을 지원하는 데 필요한 리소스를 제공하는 인프라가 필요합니다.

AI 기반 애플리케이션의 경우 에지 위치가 데이터의 주요 소스 역할을 합니다. 사용 가능한 데이터는 일정 기간 동안 여러 에지 위치에서 수집된 교육에 사용하여 교육 데이터 세트를 구성할 수 있습니다. 그런 다음, 훈련된 모델을 데이터가 수집된 에지 위치로 다시 구축하여 운영 데이터를 전용 추론 플랫폼으로 반복적으로 전송할 필요 없이 더 빠른 추론을 사용할 수 있습니다.

NetApp H615c 컴퓨팅 노드에서 지원하는 NetApp HCI AI 추론 솔루션은 NVIDIA T4 GPU 및 NetApp 클라우드 연결 스토리지 시스템을 통해 NetApp 및 NVIDIA를 통해 개발 및 검증되었습니다. NetApp HCI은 애매모호한 영역을 해결하여 설계 상의 복잡성을 제거하고 추측을 말하여 에지 데이터 센터에서 AI 추론 솔루션 구축을 단순화합니다. 이 솔루션은 다음과 같은 특징을 갖춘 규범적 아키텍처를 IT 조직에 제공합니다.

* 에지 데이터 센터에서 AI 추론을 사용할 수 있습니다
* GPU 리소스 소비를 최적화합니다
* 유연성 및 확장성을 위해 Kubernetes 기반 추론 플랫폼을 제공합니다
* 설계 복잡성 제거


에지 데이터 센터는 거의 생성 지점에 있는 위치에서 데이터를 관리 및 처리합니다. 이러한 근접성으로 인해 효율성이 증가하고 데이터 처리와 관련된 지연 시간이 줄어듭니다. 많은 업종별 시장에서 에지 데이터 센터의 이점을 인식하고 있으며 이러한 분산 데이터 처리 방식을 적극적으로 채택하고 있습니다.

다음 표에는 엣지 수직 시장과 애플리케이션이 나열되어 있습니다.

|===
| 수직 | 응용 프로그램 


| 의료 | 컴퓨터 보조 진단 기능은 의료진이 조기 질병 감지에 도움이 됩니다 


| 석유 및 가스 | 원격 생산 시설, 비디오 및 이미지 분석에 대한 자동 검사 


| 항공 | 항공 교통 제어 지원 및 실시간 비디오 피드 분석 


| 미디어 및 엔터테인먼트 | 오디오/비디오 콘텐츠 필터링을 통해 가족 친화적인 콘텐츠를 제공합니다 


| 비즈니스 분석 | 브랜드 인지도를 통해 라이브 스트리밍 TV 행사에서 브랜드 이미지를 분석할 수 있습니다 


| 전자 상거래 | 이상적인 가맹점과 창고 조합을 찾기 위한 공급업체 제공의 스마트 번들 


| 소매 | 고객이 장바구니에 넣은 품목을 인식하고 디지털 결제를 용이하게 하기 위한 자동 체크 아웃 


| 스마트 시티 | 교통 흐름을 개선하고, 주차 상황을 최적화하고, 보행자 및 자전거 운전자 안전을 강화합니다 


| 제조 | 품질 관리, 조립 라인 모니터링 및 결함 식별 


| 고객 서비스 | 고객 서비스 자동화 - 전화, 이메일 및 소셜 미디어 등의 질문 분석 및 분류 


| 농업 | 비료 및 살균제 사용을 최적화하기 위한 지능형 농장 운영 및 활동 계획 
|===


== 대상

이 솔루션의 대상 고객은 다음과 같은 그룹을 포함합니다.

* 데이터 과학자
* IT 설계자
* 현장 컨설턴트
* 구축
* IT 관리자
* 에지 위치에서 IT 혁신과 강력한 데이터 및 애플리케이션 서비스를 제공하는 인프라가 필요한 모든 고객


link:hciai_edge_architecture.html["다음: 아키텍처"]
