---
sidebar: sidebar 
permalink: ai/hciai_edge_virtual_infrastructure_with_automated_deployment.html 
keywords:  
summary:  
---
= NDE를 사용하여 NetApp HCI에 VMware 가상 인프라 구축(자동화된 구축)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== NDE 배포 필수 구성 요소

을 참조하십시오 https://library.netapp.com/ecm/ecm_download_file/ECMLP2798490["NetApp HCI 필수 구성 요소 체크리스트"^] 배포를 시작하기 전에 NetApp HCI에 대한 요구 사항 및 권장 사항을 확인하십시오.

. 네트워크 및 스위치 요구 사항 및 구성
. 필요한 VLAN ID를 준비합니다
. 스위치 구성
. NetApp HCI 및 VMware의 IP 주소 요구 사항
. DNS 및 시간 유지 요구 사항
. 최종 준비




== NDE 실행

NDE를 실행하기 전에 모든 구성 요소의 랙 및 스택, 네트워크 스위치 구성 및 모든 사전 요구 사항 확인을 완료해야 합니다. NDE가 모든 주소를 자동으로 구성하도록 하려면 단일 스토리지 노드의 관리 주소에 연결하여 NDE를 실행할 수 있습니다.

NDE는 HCI 시스템을 온라인으로 전환하는 다음과 같은 작업을 수행합니다.

. 최소 2개의 스토리지 노드에 스토리지 노드(NetApp Element 소프트웨어)를 설치합니다.
. 최소 2개의 컴퓨팅 노드에 VMware 하이퍼바이저를 설치합니다.
. VMware vCenter를 설치하여 전체 NetApp HCI 스택을 관리합니다.
. NetApp 스토리지 관리 노드(mNode) 및 NetApp 모니터링 에이전트를 설치 및 구성합니다.
+

NOTE: 이 검증에서는 NDE를 사용하여 모든 주소를 자동으로 구성합니다. 사용자 환경에서 DHCP를 설정하거나 각 스토리지 노드 및 컴퓨팅 노드에 대해 IP 주소를 수동으로 할당할 수도 있습니다. 이러한 단계는 본 가이드에서 다루지 않습니다.

+
앞에서 설명한 것처럼 이 검증에서는 컴퓨팅 노드에 대해 2케이블 구성을 사용합니다.

+
NDE에 대한 자세한 단계는 본 문서에서 다루지 않습니다.

+
기본 NetApp HCI 플랫폼 배포 완료에 대한 단계별 지침은 를 참조하십시오 http://docs.netapp.com/hci/topic/com.netapp.doc.hci-ude-180/home.html?cp=3_0["구축 가이드"^].

. NDE가 완료되면 vCenter에 로그인하여 ONTAP Select 및 애플리케이션에서 사용할 NFS 네트워크에 대한 분산 포트 그룹 NetApp HCI VDS 01-NFS_Network를 생성합니다.


link:hciai_edge_netapp_h615cmanual_deployment.html["다음: NetApp H615c 구성(수동 구축)"]
