---
sidebar: sidebar 
permalink: ai/osrunai_testing_details_for_section_4.10.html 
keywords:  
summary:  
---
= 섹션 4.10에 대한 테스트 세부 정보
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


이 섹션에서는 섹션에 대한 테스트 세부 정보를 다룹니다 link:osrunai_over-quota_fairness.html["할당량 초과 공정성"].

팀-A, 팀-b, 팀-c의 순서로 작업을 제출합니다.

|===
| 프로젝트 | GPU 수 | 합계 | 설명 


| 팀-A | 2 | 4월 4일 | 1개의 워크로드가 대기열에 있습니다 


| 팀-A | 2 | 4월 4일 | 2개의 작업 부하가 대기 중입니다 


| 팀-b | 2 | 2월 2일 | 2개의 작업 부하가 대기 중입니다 


| 팀 - c | 2 | 2월 2일 | 2개의 작업 부하가 대기 중입니다 
|===
다음 실행된 명령 시퀀스를 참조하십시오.

....
$ runai submit a-3-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-a$ runai submit a-4-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-a$ runai submit b-5-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-b$ runai submit c-6-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-c
....
이때 다음과 같은 상태가 있어야 합니다.

|===
| 프로젝트 | GPU가 할당되었습니다 | 작업 로드 대기 중 


| 팀-A | 4월 4일 | 각각 GPU를 묻는 2개의 워크로드 


| 팀-b | 2월 2일 | 각각 2개의 GPU를 요구하는 2개의 워크로드 


| 팀 - c | 2월 2일 | 각각 2개의 GPU를 요구하는 2개의 워크로드 


| 팀 d | 8월 8일 | 없음 
|===
그런 다음 'team-d'에 대한 모든 워크로드를 삭제합니다.

....
$ runai delete -p team-d d-1-gggg d-2-gg d-3-gg
....
섹션을 참조하십시오 link:osrunai_over-quota_fairness.html["할당량 초과 공정성"]를 참조하십시오.

link:osrunai_where_to_find_additional_information.html["다음: 추가 정보를 찾을 위치"]
