---
sidebar: sidebar 
permalink: ai/osrunai_executive_summary.html 
keywords:  
summary:  
---
= TR-4858: 실행 시 NetApp 오케스트레이션 솔루션: AI
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Rick Huang, David Arnette, Sung-Han Lin, NetApp Yaron Goldberg, Run: AI

[role="lead"]
NetApp AFF 스토리지 시스템은 탁월한 성능과 업계 최고 수준의 하이브리드 클라우드 데이터 관리 기능을 제공합니다. NetApp 및 Run: AI는 엔터프라이즈급 성능, 안정성 및 지원을 제공하는 인공 지능(AI) 및 머신 러닝(ML) 워크로드용 NetApp ONTAP AI 솔루션의 고유한 기능을 시연하기 위해 파트너 계약을 체결했습니다. 실행: AI 워크로드 오케스트레이션에서 Kubernetes 기반 스케줄링 및 리소스 활용률 플랫폼을 추가하여 연구원이 GPU 활용률을 관리하고 최적화할 수 있도록 지원합니다. NVIDIA DGX 시스템과 NetApp, NVIDIA, Run의 통합 솔루션: AI는 엔터프라이즈 AI 워크로드를 위해 특별 제작된 인프라 스택을 제공합니다. 이 기술 보고서는 다양한 사용 사례와 산업 수직 분야를 지원하기 위해 대화형 AI 시스템을 구축하는 고객에게 직접적인 지침을 제공합니다. 이 이니셔티브에는 Run:AI 및 NetApp AFF A800 스토리지 시스템 구축에 대한 정보가 포함되며, AI 이니셔티브를 빠르고 성공적으로 구현하는 가장 간단한 방법을 위한 참조 아키텍처 역할을 합니다.

이 솔루션의 대상 고객은 다음과 같은 그룹을 포함합니다.

* 컨테이너 마이크로서비스와 같은 Kubernetes 기반 사용 사례에 대한 AI 모델 및 소프트웨어 개발을 위한 솔루션을 설계하는 엔터프라이즈 설계자
* 여러 팀 및 프로젝트가 있는 클러스터 환경에서 효율적인 모델 개발 목표를 달성할 수 있는 방법을 찾는 데이터 과학자
* 운영 모델의 유지 관리 및 실행을 담당하는 데이터 엔지니어
* 최적의 Kubernetes 클러스터 리소스 활용률 경험을 만들고 AI 이니셔티브를 통한 시장 출시 기간을 단축하려는 경영진 및 IT 의사 결정자 및 비즈니스 리더

