---
sidebar: sidebar 
permalink: ai/osrunai_testing_details_for_section_4.8.html 
keywords:  
summary:  
---
= 섹션 4.8의 테스트 세부 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
이 섹션에서는 섹션의 테스트 세부 정보를 다룹니다 link:osrunai_achieving_high_cluster_utilization_with_over-uota_gpu_allocation.html["할당량 초과 GPU 할당을 통한 높은 클러스터 사용률 달성"].

다음 순서로 작업을 제출합니다.

|===
| 프로젝트 | 이미지 | GPU 수 | 합계 | 설명 


| 팀-A | Jupyter를 선택합니다 | 1 | 1/4 | – 


| 팀-A | 넷엡 | 1 | 2월 4일 | – 


| 팀-A | 실행: AI | 2 | 4월 4일 | 모든 할당량을 사용합니다 


| 팀-b | 실행: AI | 0.6 | 0.6/2 | 소수점 GPU 


| 팀-b | 실행: AI | 0.4 | 1/2로 | 소수점 GPU 


| 팀-b | 넷엡 | 1 | 2월 2일 | – 


| 팀-b | 넷엡 | 2 | 4월 2일 | 2개 초과 할당량 


| 팀 - c | 실행: AI | 0.5 | 0.5/2 | 소수점 GPU 


| 팀 - c | 실행: AI | 0.3 | 2월 8일 | 소수점 GPU 


| 팀 - c | 실행: AI | 0.2 | 1/2로 | 소수점 GPU 


| 팀 - c | 넷엡 | 2 | 3월 2일 | 1개 초과 할당 


| 팀 - c | 넷엡 | 1 | 4월 2일 | 2개 초과 할당량 


| 팀 d | 넷엡 | 4 | 8월 4일 | 할당량의 절반을 사용합니다 
|===
명령 구조:

....
$ runai submit <job-name> -p <project-name> -g <#GPUs> -i <image-name>
....
테스트에 사용된 실제 명령 시퀀스:

....
$ runai submit a-1-1-jupyter -i jupyter/base-notebook -g 1 \
  --interactive --service-type=ingress --port 8888 \
  --args="--NotebookApp.base_url=team-a-test-ingress" --command=start-notebook.sh -p team-a
$ runai submit a-1-g -i gcr.io/run-ai-demo/quickstart -g 1 -p team-a
$ runai submit a-2-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-a
$ runai submit b-1-g06 -i gcr.io/run-ai-demo/quickstart -g 0.6 --interactive -p team-b
$ runai submit b-2-g04 -i gcr.io/run-ai-demo/quickstart -g 0.4 --interactive -p team-b
$ runai submit b-3-g -i gcr.io/run-ai-demo/quickstart -g 1 -p team-b
$ runai submit b-4-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-b
$ runai submit c-1-g05 -i gcr.io/run-ai-demo/quickstart -g 0.5 --interactive -p team-c
$ runai submit c-2-g03 -i gcr.io/run-ai-demo/quickstart -g 0.3 --interactive -p team-c
$ runai submit c-3-g02 -i gcr.io/run-ai-demo/quickstart -g 0.2 --interactive -p team-c
$ runai submit c-4-gg -i gcr.io/run-ai-demo/quickstart -g 2 -p team-c
$ runai submit c-5-g -i gcr.io/run-ai-demo/quickstart -g 1 -p team-c
$ runai submit d-1-gggg -i gcr.io/run-ai-demo/quickstart -g 4 -p team-d
....
이때 다음과 같은 상태가 있어야 합니다.

|===
| 프로젝트 | GPU가 할당되었습니다 | 작업 로드 대기 중 


| 팀-A | 4/4(소프트 할당량/실제 할당) | 없음 


| 팀-b | 4월 2일 | 없음 


| 팀 - c | 4월 2일 | 없음 


| 팀 d | 8월 4일 | 없음 
|===
섹션을 참조하십시오 link:osrunai_achieving_high_cluster_utilization_with_over-uota_gpu_allocation.html["Over-uota GPU 할당을 통한 높은 클러스터 활용률 달성"] 진행 중인 테스트 시나리오에 대한 논의.
