---
sidebar: sidebar 
permalink: ai/wp-dgxc.html 
keywords: NetApp AI, AI, Artificial Intelligence, Data Management, Supercomputing 
summary: NetApp Cloud Volumes ONTAP/ANF를 사용하는 NVIDIA DGX Cloud 
---
= NVIDIA DGX Cloud를 위한 NetApp 클라우드 데이터 서비스
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


데이브 아네트(Dave Arnette)와 사티시 티아가라잔(NetApp)

[role="lead"]
세계적 수준의 슈퍼 컴퓨팅을 위한 고급 데이터 관리



== 소개

이 문서에서는 고객이 NetApp Cloud Volumes/ANF를 사용하여 NVIDIA DGX Cloud와 함께 고급 데이터 관리 기능을 제공하여 AI 데이터 파이프라인 운영을 최적화하고 간소화하는 방법을 설명합니다.



=== NVIDIA, Microsoft, NetApp와 같은 파트너 관계를 맺고 있습니다

DGX Cloud를 사용하면 고객이 웹 브라우저에서 AI 슈퍼 컴퓨터에 즉시 액세스할 수 있습니다.  DGX Cloud를 사용하는 기업은 규모에서 다중 노드 AI 교육에 액세스하여 복잡한 모델 설계를 더 빠르게 진행할 수 있습니다. 사내 인프라로 확장하려는 기업은 모든 리소스를 통합하여 NetApp BlueXP ™ 및 NVIDIA Base Command 플랫폼을 활용하여 하이브리드 클라우드를 제공할 수 있으며, 개발자에게 일관된 단일 창 뷰를 제공합니다.



=== NVIDIA DGX Cloud를 사용해 보십시오

여기에 추가할 콘텐츠를 제공해 드리기 위해 ~ NVIDIA를 방문했습니다



=== Microsoft Azure를 참조하십시오



=== NetApp BlueXP ™



=== Azure NetApp Files ® 에서 제공하는



=== NetApp 파일 - 객체 이중성



== 아키텍처 및 구성



=== 솔루션 설계/개요



=== 아키텍처 도면



=== CVO/ANF 구축

BlueXP 사용



=== 파일/오브젝트 이중성을 위한 구성입니다

Ansible을 통해 자동화되었습니까?



=== DGXC에 연결합니다



== 결론
