---
sidebar: sidebar 
permalink: ai/wp-genai.html 
keywords: NetApp AI, AI, Artificial Intelligence, Generative AI 
summary: NetApp ® AI 기능은 훈련, 재훈련, 미세 조정, 추론 및 생성 AI 모델을 위한 AI 파이프라인 전반에서 원활한 데이터 관리와 데이터 이동을 지원합니다. 
---
= Generative AI 및 NetApp 가치
:allow-uri-read: 


[role="lead"]
세대 인공 지능(AI)에 대한 수요로 인해 산업 전반에 걸쳐 변혁이 일어나고 있으며, 비즈니스 창의성과 제품 혁신이 증진되고 있습니다.

저자: 사티시 Thyagarajan, NetApp



== 추상화

많은 조직에서 세대 AI를 사용하여 새로운 제품 기능을 구축하고, 엔지니어링 생산성을 개선하고, 더 나은 결과와 소비자 경험을 제공하는 AI 기반 애플리케이션을 프로토타입을 제작하고 있습니다. GPT(Generative Pre-training Transformers)와 같은 생성 AI는 신경망을 사용하여 텍스트, 오디오 및 비디오와 같은 다양한 새로운 콘텐츠를 만듭니다. 대규모 언어 모델(LLM)과 관련된 극단적인 규모와 대규모 데이터 세트를 고려할 때, 사내, 하이브리드 및 멀티 클라우드 구축 옵션의 강력한 데이터 스토리지 기능을 활용하고 데이터 이동성과 관련된 위험을 줄여주는 강력한 AI 인프라를 구축하는 것이 매우 중요합니다. 기업이 AI 솔루션을 설계할 수 있기에 앞서 데이터 보호 및 거버넌스: 이 백서에서는 이러한 고려 사항과 더불어 훈련, 재훈련, 미세 조정 및 추론 생성 AI 모델을 위한 AI 데이터 파이프라인 전반에서 원활한 데이터 관리와 데이터 이동을 지원하는 NetApp ® AI 기능에 대해 설명합니다.



== 핵심 요약

2022년 11월 GPT-3의 분할인 ChatGPT가 출시된 이후 가장 최근에는 사용자 지시에 대응하여 텍스트, 코드, 이미지 또는 치료 단백질을 생성하는 데 사용되는 새로운 AI 도구가 유명해졌습니다. 이는 사용자가 자연어를 사용하여 요청을 할 수 있음을 의미하며, AI는 사용자 요청을 반영한 뉴스 기사 또는 제품 설명과 같은 텍스트를 해석하고 생성하며 기존 데이터에 대해 훈련된 알고리즘을 사용하여 코드, 음악, 음성, 시각 효과 및 3D 자산을 생성합니다. 그 결과 AI 시스템의 설계에서 안정적인 확산, 환각, 신속한 엔지니어링 및 가치 조정과 같은 문구가 빠르게 등장하고 있습니다. 다양한 다운스트림 NLP(자연어 처리) 작업을 위해 다양한 업종의 비즈니스 시설에서 채택하고 있는 클라우드 서비스 공급자 및 기타 AI 파트너를 통해 사전 훈련된 기반 모델(FM)으로 이러한 셀프 감독 또는 반감독 머신 러닝(ML) 모델을 널리 사용하고 있습니다. McKinsey와 같은 연구 분석 기관 에서 "Generative AI가 생산성에 미치는 영향은 글로벌 경제에 수조 달러의 가치를 더할 수 있습니다." 기업들이 AI를 인간에 대한 사려 깊은 파트너로 재해석하고 있으며, FMS는 기업과 기관이 생성 AI를 통해 수행할 수 있는 기능으로 동시에 확장되고 있지만, 대량의 데이터를 관리할 수 있는 기회는 지속적으로 증가할 것입니다. 이 문서에서는 온프레미스 환경과 하이브리드 또는 멀티 클라우드 환경에서 NetApp 고객에게 가치를 제공하는 NetApp 기능과 관련하여 생성 AI 및 설계 개념을 소개합니다.

* 이제 고객이 AI 환경에서 NetApp를 사용하는 데 필요한 IT 조직은 누구입니까? * NetApp를 통해 빠른 데이터 및 클라우드 성장, 멀티 클라우드 관리 및 AI 같은 차세대 기술 채택으로 인해 발생하는 복잡성을 충족할 수 있습니다. NetApp은 다양한 기능을 지능형 데이터 관리 소프트웨어 및 스토리지 인프라에 결합했으며 AI 워크로드에 최적화된 고성능과 잘 균형을 이루었습니다. LLM과 같은 발전적인 AI 솔루션은 인텔리전스를 증진하기 위해 스토리지에서 메모리로 여러 번 소스 데이터 세트를 읽고 처리해야 합니다. NetApp은 에지-코어-클라우드 에코시스템 전반에서 데이터 이동성, 데이터 거버넌스, 데이터 보안 기술 분야의 선두업체로서 기업 고객에게 규모에 맞는 AI 솔루션을 구축할 수 있도록 지원해 왔습니다. NetApp은 강력한 파트너 네트워크를 통해 최고 데이터 책임자, AI 엔지니어, 엔터프라이즈 설계자 및 데이터 과학자를 지원하여 데이터 준비, 데이터 보호, AI 모델 훈련 및 추론의 전략적 데이터 관리 책임을 맡아 AI/ML 라이프사이클의 성능 및 확장성을 최적화할 수 있습니다. 딥 러닝 데이터 파이프라인을 위한 ® ONTAP AI ®, 스토리지 엔드포인트 간에 데이터를 원활하고 효율적으로 전송하기 위한 NetApp NetApp ® SnapMirror ® 등의 NetApp 데이터 기술 및 기능 실시간 렌더링을 위한 NetApp ® FlexCache ® 를 활용하면 데이터 흐름이 배치에서 실시간으로 이동하고 데이터 엔지니어링이 즉각적으로 이루어질 때 실시간 생성 AI 모델 구축의 가치를 제공합니다. 모든 유형의 기업이 새로운 AI 툴을 도입할 때는 에지, 데이터 센터 및 클라우드에서 확장 가능하고 책임적이며 설명할 수 있는 AI 솔루션을 요구하는 데이터 문제가 발생합니다. 하이브리드 및 멀티 클라우드에 대한 데이터 관련 최고의 권위자인 NetApp은 생성 AI 모델 훈련(사전 교육), 미세 조정, 컨텍스트 기반 추론 및 LLM의 모델 붕괴 모니터링을 위해 데이터 파이프라인 및 데이터 레이크 구성의 모든 측면을 지원할 수 있는 파트너 네트워크와 공동 솔루션 구축을 위해 노력하고 있습니다.



== Generative AI란?

Generative AI는 콘텐츠 제작, 새로운 설계 개념 생성, 새로운 구성 탐색 방법을 변화시키고 있습니다. 텍스트, 코드, 이미지, 오디오, 비디오 등의 새로운 콘텐츠를 생성할 수 있는 GAN(Generative Adversarial Network), VAE(Variational Autoencoder) 및 GPT(Generative Pre-training Transformers)와 같은 신경망 프레임워크를 보여 줍니다. 및 합성 데이터를 관리합니다. OpenAI의 Chat-GPT, Google's Bard, 포옹하는 얼굴의 Bloom, Meta's Llama와 같은 변압기 기반 모델은 대규모 언어 모델의 많은 발전을 뒷받침하는 기초 기술로 부상했습니다. 마찬가지로 OpenAI의 Dall-E, Meta의 CM3leon 및 Google의 Imagen도 텍스트-이미지 확산 모델의 예입니다. 이 모델은 고객에게 전례 없는 수준의 사진주의를 제공하여 처음부터 복잡한 새 이미지를 만들거나 기존 이미지를 편집함으로써 데이터 세트 증강과 텍스트-이미지 합성 텍스트를 연결하는 고품질 컨텍스트 인식 이미지를 생성합니다. 디지털 아티스트들은 Nerf(Neural Radiance Field)와 생성 AI와 같은 렌더링 기술을 결합하여 정적 2D 이미지를 몰입형 3D 장면으로 변환하기 시작했습니다. 일반적으로 LLM은 (1) 모델 크기(일반적으로 수십억 개의 매개 변수), (2) 교육 데이터 세트 크기, (3) 교육 비용, (4) 교육 후 성능 모델의 4가지 매개 변수로 구성됩니다. 또한 LLM은 주로 세 가지 변압기 아키텍처에 속합니다. (i) 인코더 전용 모델. 예: BERT(Google, 2018), (ii) 인코더-디코더(예: BART(Meta, 2020) 및 (iii) 디코더 전용 모델 예: Llama(Meta, 2023), Palm-E(Google, 2023). 일반적으로 비즈니스 요구사항에 따라 회사가 모델 매개 변수 수(N)와 교육 데이터 세트의 토큰 수(D)를 선택하는 아키텍처와 관계없이 교육(사전 교육) 또는 LLM의 세부 조정 비용을 결정합니다.



=== 엔터프라이즈 사용 사례 및 다운스트림 NLP 작업

업종에 상관없이 AI가 비즈니스 운영, 영업, 마케팅, 법률 서비스를 위해 기존 데이터에서 새로운 형태의 가치를 추출하고 창출할 수 있는 가능성이 점점 더 커지고 있습니다. IDC(International Data Corporation)의 글로벌 생성 AI 사용 사례 및 투자에 대한 시장 인텔리전스에 따르면 소프트웨어 개발 및 제품 설계에 대한 지식 관리가 가장 큰 영향을 받으며, 개발자를 위한 마케팅 및 코드 생성을 위한 스토리라인 생성이 그 뒤를 이라고 합니다. 의료 분야에서는 임상 연구 조직이 의료 분야의 새로운 지평을 열고 있습니다. ProteinBERT와 같은 사전 훈련된 모델은 Gene Ontology(GO) 주석을 통합하여 약물의 단백질 구조를 신속하게 설계함으로써 약물 발견, 생물정보학 및 분자 생물학 분야에서 중요한 이정표를 제시합니다. 생명공학 기업들은 폐조직의 비가역적 흉터를 유발하는 폐섬유증(IPF)과 같은 질병을 치료하기 위한 목적으로 AI에서 발견된 신약 개발에 대한 인간 실험을 시작했습니다.

그림 1: 생성 AI 이미지를 구동하는 사용 사례::gen-ai-image1.png["그림 1: 생성 AI를 구동하는 사용 사례"]

생성 AI를 통한 자동화 채택의 증가는 많은 직업의 업무 활동의 공급과 수요도 변화시키고 있습니다. McKinsey에 따르면 미국 노동 시장(아래 다이어그램)은 AI의 영향을 고려할 때만 지속되는 급속한 전환을 겪었습니다.

출처: McKinsey & Company 이미지:: gen-ai-image3.png["그림 2: 출처: McKinsey & Company"]



=== 생성 AI에서 스토리지의 역할

LLM은 주로 딥 러닝, GPU 및 컴퓨팅에 의존하고 있습니다. 하지만 GPU 버퍼가 가득 차면 데이터를 스토리지에 빠르게 기록해야 합니다. 일부 AI 모델은 메모리에서 실행될 수 있을 만큼 작지만, LLM에는 대규모 데이터 세트에 신속하게 액세스할 수 있도록 높은 IOPS와 높은 처리량 스토리지가 필요합니다. 특히 수십억 개의 토큰 또는 수백만 개의 이미지가 필요한 경우 그렇습니다. LLM의 일반적인 GPU 메모리 요구 사항에서 10억 개의 매개 변수를 가진 모델을 훈련하는 데 필요한 메모리는 최대 80GB @ 32비트 정밀도로 작동할 수 있습니다. 이 경우 70억 - 700억 개 매개 변수의 LLM 제품군인 Meta의 Llama 2는 약 70x80이 필요할 수 있습니다 5600GB 또는 5.6TB의 GPU RAM 또한 필요한 메모리 양은 생성하려는 최대 토큰 수에 직접 비례합니다. 예를 들어, 최대 512개의 토큰(약 380 단어)의 출력을 생성하려는 경우 이 필요합니다 link:https://github.com/ray-project/llm-numbers#1-mb-gpu-memory-required-for-1-token-of-output-with-a-13b-parameter-model["512MB"]. 이것은 비순차적인 것처럼 보일 수 있지만, 더 큰 배치를 실행하려는 경우 누적되기 시작합니다. 따라서 기업에서는 메모리의 LLM을 훈련하거나 미세 조정하는 데 비용이 매우 많이 들기 때문에 스토리지가 생성 AI의 토대가 되고 있습니다.



=== LLM에 대한 세 가지 기본 접근 방식

대부분의 기업에서 최신 동향을 바탕으로 LLM을 구축하는 접근 방식을 세 가지 기본 시나리오로 요약할 수 있습니다. 최근 에 설명된 대로 link:https://hbr.org/2023/07/how-to-train-generative-ai-using-your-companys-data[""하버드 비즈니스 리뷰""] 기사: (1) LLM을 처음부터 완전히 교육(사전 교육) - 비용이 많이 들고 전문 AI/ML 기술이 필요함, (2) 복잡하고 실현 가능한 엔터프라이즈 데이터로 기반 모델 미세 조정, (3) 검색 증강 생성(RAG)을 사용하여 회사 데이터가 포함된 문서 저장소, API 및 벡터 데이터베이스를 쿼리합니다. 이러한 각 요소에는 서로 다른 유형의 문제를 해결하는 데 사용되는 노력, 반복 속도, 비용 효율성 및 모델 정확성이 서로 상충됩니다(아래 다이어그램).

그림 3: 문제 유형 이미지: gen-ai-image4.png [그림 3: 문제 유형]



=== 기초 모델

기본 모델이라고도 하는 기초 모델(FM)은 광범위한 다운스트림 NLP 작업에 맞게 일반적으로 조정되는 방대한 양의 레이블 없는 데이터에 대해 훈련된 대규모 AI 모델(LLM)입니다. 훈련 데이터는 인간이 라벨링하지 않기 때문에 모델이 명시적으로 인코딩되는 것이 아니라 등장한다. 즉, 모델은 명시적으로 프로그래밍되지 않고 자신의 이야기 또는 설명을 생성할 수 있습니다. 따라서 FM의 중요한 특징은 여러 도메인에서 동일한 방법이 사용된다는 것을 의미하는 균질화입니다. 그러나 개인화 및 미세 조정 기술을 통해 오늘날 등장하는 제품에 통합된 FMS는 텍스트, 텍스트-이미지 및 텍스트-코드 생성 기능뿐만 아니라 도메인별 작업 또는 디버깅 코드를 설명하는 데도 유용합니다. 예를 들어, OpenAI의 Codex 또는 Meta의 Code Llama와 같은 FMS는 프로그래밍 작업의 자연어 설명을 기반으로 여러 프로그래밍 언어로 코드를 생성할 수 있습니다. 이러한 모델은 파이썬, C#, 자바스크립트, 펄, 루비, 및 SQL. 이들은 사용자의 의도를 이해하고 소프트웨어 개발, 코드 최적화 및 프로그래밍 작업의 자동화에 유용한 원하는 작업을 수행하는 특정 코드를 생성합니다.



=== 미세 조정, 영역 특이성 및 재교육

데이터 준비 및 데이터 사전 처리 이후 LLM 구축의 일반적인 사례 중 하나는 크고 다양한 데이터 세트에 대해 교육을 받은 사전 훈련된 모델을 선택하는 것입니다. 세부 조정이라는 맥락에서, 과 같은 오픈 소스 대형 언어 모델이 될 수 있습니다 link:https://ai.meta.com/llama/["메타의 라마 2"] 700억 개의 매개 변수와 2조 개의 토큰에 대한 교육을 받았습니다. 사전 학습된 모델을 선택한 후 다음 단계는 도메인별 데이터에 맞게 세부 조정하는 것입니다. 이를 위해서는 모델의 매개 변수를 조정하고 새로운 데이터에 대해 훈련하여 특정 도메인 및 작업에 적응해야 합니다. 예를 들어, 금융 업계를 지원하는 광범위한 금융 데이터에 대한 교육을 받은 독점 LLM인 BloombergGPT가 있습니다. 특정 작업을 위해 설계 및 훈련된 도메인별 모델은 일반적으로 범위 내에서 정확성과 성능이 높지만 다른 작업 또는 도메인 간 전송 가능성은 낮습니다. 일정 기간 동안 비즈니스 환경과 데이터가 변경될 경우 테스트 중 FM의 예측 정확도가 성능에 비해 떨어지기 시작할 수 있습니다. 이 경우 모델을 재훈련하거나 미세 조정하는 것이 중요합니다. 기존 AI/ML에서 모델 재훈련은 배포된 ML 모델을 새 데이터로 업데이트하는 것을 의미하며, 일반적으로 두 가지 유형의 드리프트를 없애기 위해 수행됩니다. (1) 컨셉 드리프트 – 입력 변수와 목표 변수 사이의 링크가 시간에 따라 변경되면, 우리가 변화를 예측하고자 하는 것에 대한 설명 이후 모델은 부정확한 예측을 생성할 수 있습니다. (2) 데이터 드리프트 – 시간이 지남에 따라 고객 습관 또는 행동의 변화와 같이 입력 데이터의 특성이 변화하여 모델이 이러한 변화에 대응하지 못하는 경우에 발생합니다. 마찬가지로 재교육은 FMS/LLM에도 적용되지만 비용이 많이 들기 때문에(수백만 달러) 대부분의 조직이 고려할 만한 것은 아닙니다. 현재 활발한 연구 중에 있으며, LLMOps 영역에서 여전히 나타나고 있습니다. 따라서 미세 조정된 FMS에서 모델이 붕괴될 경우 재교육을 받는 대신 기업은 새로운 데이터 세트를 사용하여 다시 미세 조정을 선택할 수 있습니다(훨씬 저렴함). 비용 측면에서 아래에 나열된 것은 Azure-OpenAI Services의 모델 가격 표의 예입니다. 고객은 각 작업 범주에 대해 특정 데이터 세트에서 모델을 미세 조정하고 평가할 수 있습니다.

출처: Microsoft Azure 이미지:: gen-ai-image5.png [출처: Microsoft Azure]



=== 신속한 엔지니어링 및 추론

신속한 엔지니어링은 모델 가중치를 업데이트하지 않고 원하는 작업을 수행하기 위해 LLM과 통신하는 효과적인 방법을 의미합니다. AI 모델 훈련 및 미세 조정이 NLP 애플리케이션에 중요합니다. 하지만 추론도 마찬가지로 중요합니다. 훈련된 모델이 사용자 프롬프트에 응답합니다. 추론을 위한 시스템 요구사항은 일반적으로 수십억 개의 저장된 모델 매개 변수를 적용하여 최상의 응답을 이끌어낼 수 있어야 하기 때문에 LLM에서 GPU에 데이터를 제공하는 AI 스토리지 시스템의 읽기 성능에 훨씬 더 큰 영향을 줍니다.



=== LLMOps, 모델 모니터링 및 벡터스토어

기존의 MLOps(Machine Learning Ops)와 마찬가지로 LLMOps(Large Language Model Operations)도 데이터 과학자와 DevOps 엔지니어의 협업이 필요하며, 생산 환경에서 LLM 관리를 위한 도구와 모범 사례가 필요합니다. 그러나 LLM에 대한 워크플로와 기술 스택은 어떤 면에서 다를 수 있습니다. 예를 들어, LangChain 문자열과 같은 프레임워크를 사용하여 구축된 LLM 파이프라인은 벡터스토어 또는 벡터 데이터베이스와 같은 외부 임베디드 엔드포인트에 대한 여러 LLM API 호출을 함께 통합합니다. 벡터 데이터베이스와 같은 다운스트림 커넥터에 임베드된 끝점 및 벡터스토어를 사용하는 것은 데이터를 저장하고 액세스하는 방식에 있어 상당한 발전을 나타냅니다. 처음부터 개발된 기존의 ML 모델과 달리 LLM은 전송 학습에 의존하는 경우가 많습니다. 이러한 모델은 보다 구체적인 영역에서 성능을 향상시키기 위해 새로운 데이터로 미세 조정된 FMS로 시작되기 때문입니다. 따라서 LLMOps는 위험 관리 및 모델 붕괴 모니터링 기능을 제공하는 것이 중요합니다.



=== 발생 AI 시대의 위험과 윤리

“ChatGPT – 그것은 매끈하지만 여전히 무의미한.” – MIT 기술 리뷰. 가비지 입력 – 가비지 유출은 항상 컴퓨팅 측면에서 어려운 문제였습니다. Generative AI의 유일한 차이점은 쓰레기를 매우 신뢰할 수 있게 만들어 부정확한 결과를 도출하는 데 탁월하다는 것입니다. LLM은 자신이 만든 이야기에 맞게 사실을 발명한 경향이 있습니다. 따라서 세대 AI를 AI 등가물로 비용을 낮출 수 있는 좋은 기회로 간주하는 기업은 시스템을 정직하고 윤리적으로 유지하기 위해 심층적인 추측을 효율적으로 탐지하고 편견을 줄이며 위험을 낮춰야 합니다. 엔드 투 엔드 암호화 및 AI 가드레일을 통한 데이터 이동성, 데이터 품질, 데이터 거버넌스 및 데이터 보호를 지원하는 강력한 AI 인프라를 통해 유입되는 데이터 파이프라인은 책임지고 설명 가능한 생성 AI 모델의 설계에 포함되어 있습니다.



== 고객 시나리오 및 NetApp

그림 3: 기계 학습/대규모 언어 모델 워크플로 이미지: gen-ai-image6.png [그림 3: 기계 학습/대규모 언어 모델 워크플로]

* 우리는 교육 또는 미세 조정 중입니까? * (a) LLM 모델을 처음부터 교육하거나, 사전 훈련된 FM을 미세 조정하거나, RAG를 사용하여 기초 모델 외부의 문서 저장소에서 데이터를 검색하고, 메시지를 보강할 수 있는지 여부 (b) 오픈 소스 LLM(예: Llama 2) 또는 독점 FMS(예: ChatGPT, Bard, AWS Bedrock)를 활용하는 것은 조직의 전략적 결정입니다. 각 접근 방식에는 비용 효율성, 데이터 부담, 운영, 모델 정확도 및 LLM 관리 간의 절충이 있습니다.

기업으로서 NetApp은 업무 문화와 제품 설계 및 엔지니어링 활동에 대한 접근 방식에 내부적으로 AI를 수용합니다. 예를 들어, NetApp의 자율적 랜섬웨어 방어는 AI와 머신 러닝을 사용하여 구축됩니다. 파일 시스템 이상 징후를 조기에 감지하여 운영에 영향을 미치기 전에 위협을 식별하는 데 도움이 됩니다. 둘째, NetApp는 판매 및 재고 예측, 챗봇과 같은 비즈니스 운영에 예측 AI를 사용하여 콜센터 제품 지원 서비스, 기술 사양, 보증, 서비스 매뉴얼 등과 같은 고객을 지원합니다. 셋째, NetApp은 수요 예측, 의료 영상, 감정 분석, 심리 분석, 능동적 AI 솔루션과 같은 예측 AI 솔루션을 구축하는 고객에게 제공하는 제품 및 솔루션을 통해 AI 데이터 파이프라인 및 ML/LLM 워크플로에 고객 가치를 제공합니다. Gans와 같은 차세대 AI 솔루션은 NetApp ® ONTAP AI ®, NetApp ® SnapMirror ®, NetApp ® FlexCache ® 와 같은 NetApp 제품을 사용하여 제조 부문의 이상 징후 탐지와 금융 및 금융 서비스의 자금 세탁 방지 및 사기 범죄를 탐지합니다.



== NetApp 역량

챗봇, 코드 생성, 이미지 생성 또는 게놈 모델 표현과 같은 생성 AI 애플리케이션에서 데이터의 이동과 관리는 에지, 프라이빗 데이터 센터 및 하이브리드 멀티 클라우드 에코시스템에 걸쳐 있을 수 있습니다. 예를 들어, ChatGPT와 같은 사전 훈련된 모델의 API를 통해 노출된 최종 사용자 앱에서 승객의 항공권을 비즈니스 클래스로 업그레이드하는 데 도움을 주는 실시간 AI 봇은 인터넷에서 승객 정보를 공개하지 않기 때문에 그 자체로 해당 작업을 수행할 수 없습니다. API는 하이브리드 또는 멀티 클라우드 에코시스템에 존재할 수 있는 항공사의 승객의 개인 정보 및 티켓 정보에 액세스해야 합니다. LLM을 사용하여 일대다 바이오 의료 연구 기관과 관련된 약물 발견 시 임상 시험을 수행하는 최종 사용자 애플리케이션을 통해 약물 분자 및 환자 데이터를 공유하는 과학자에게도 이와 유사한 시나리오가 적용될 수 있습니다. FMS 또는 LLM에 전달되는 중요한 데이터에는 PII, 재무 정보, 건강 정보, 생체 데이터, 위치 데이터, 통신 데이터, 온라인 행동 및 법률 정보 실시간 렌더링, 프롬프트 실행 및 에지 추론의 경우, 오픈 소스 또는 독점 LLM 모델을 통해 최종 사용자 앱에서 스토리지 엔드포인트로 데이터가 이동하고 사내 또는 퍼블릭 클라우드 플랫폼의 데이터 센터로 이동합니다. 이 모든 시나리오에서 데이터 이동성과 데이터 보호는 대규모 훈련 데이터 세트와 이러한 데이터의 이동에 의존하는 LLM과 관련된 AI 운영에 매우 중요합니다.

그림 4: Generative AI-LLM 데이터 파이프라인 이미지: gen-ai-image7.png[그림 4: Generative AI-LLM 데이터 파이프라인]

지능형 데이터 관리 소프트웨어를 기반으로 하는 NetApp의 스토리지 인프라, 데이터 및 클라우드 서비스 포트폴리오입니다.

* Data Preparation *: LLM 기술 스택의 첫 번째 기둥은 기존의 ML 스택에서 거의 영향을 받지 않습니다. 훈련 또는 세부 조정 전에 AI 파이프라인의 데이터 사전 처리가 데이터를 정규화하고 정리해야 합니다. 이 단계에는 Amazon S3 계층 형태의 모든 위치나 파일 저장소 또는 NetApp StorageGRID와 같은 오브젝트 저장소와 같은 온프레미스 스토리지 시스템에서 데이터를 수집하는 커넥터가 포함됩니다.

* NetApp ® ONTAP * 는 데이터 센터와 클라우드에서 NetApp의 중요 스토리지 솔루션을 뒷받침하는 기초 기술입니다. ONTAP에는 사이버 공격에 대한 자동 랜섬웨어 보호, 내장 데이터 전송 기능, 사내, 하이브리드, NAS의 멀티 클라우드, SAN, 오브젝트, 등 다양한 아키텍처에 대한 스토리지 효율성 기능을 포함한 다양한 데이터 관리 및 보호 기능이 포함되어 있습니다. 소프트웨어 정의 스토리지(SDS)가 필요합니다.

* NetApp ® ONTAP AI ® *: 딥 러닝 모델 훈련. NetApp ® ONTAP ® 는 ONTAP 스토리지 클러스터와 NVIDIA DGX 컴퓨팅 노드를 통해 NetApp 고객을 위해 RDMA 기반 NFS를 사용하여 NVIDIA GPU Direct Storage ™ 를 지원합니다. 또한 스토리지에서 메모리로 소스 데이터 세트를 여러 번 읽고 처리할 수 있는 비용 효율적인 성능을 제공하므로 인텔리전스를 강화할 수 있어 조직이 LLM에 대한 교육, 미세 조정 및 확장 액세스를 수행할 수 있습니다.

* NetApp ® FlexCache ® * 는 파일 배포를 간소화하고 읽기 빈도가 높은 데이터만 캐시하는 원격 캐싱 기능입니다. 이 기능은 LLM 교육, 재교육 및 미세 조정에 유용하며 실시간 렌더링 및 LLM 추론과 같은 비즈니스 요구사항에 따라 고객에게 가치를 제공합니다.

* NetApp ® SnapMirror * 는 두 ONTAP 시스템 간에 볼륨 스냅샷을 복제하는 ONTAP 기능입니다. 이 기능은 에지의 데이터를 사내 데이터 센터 또는 클라우드로 최적으로 전송합니다. SnapMirror를 사용하여 온프레미스와 하이퍼스케일 클라우드 간에 데이터를 안전하고 효율적으로 이동할 수 있습니다. 고객이 엔터프라이즈 데이터가 포함된 RAG로 클라우드에서 생성 가능한 AI를 개발하려는 경우 SnapMirror를 사용할 수 있습니다. 변경 사항만 효율적으로 전송하여 대역폭을 절약하고 복제 속도를 높임으로써 FMS 또는 LLM의 훈련, 재교육 및 미세 조정 작업 중에 필수 데이터 이동성 기능을 제공합니다.

* NetApp ® SnapLock * 는 데이터 세트 버전 관리를 위해 ONTAP 기반 스토리지 시스템에서 변경 불가능한 디스크 기능을 제공합니다. 마이크로코어 아키텍처는 FPolicy ™ 제로 트러스트 엔진을 사용하여 고객 데이터를 보호하도록 설계되었습니다. NetApp는 공격자가 특히 리소스를 많이 사용하는 방식으로 LLM과 상호 작용할 때 DoS(Denial-of-Service) 공격을 차단하여 고객 데이터를 사용할 수 있도록 보장합니다.

* NetApp ® Cloud Data Sense * 는 엔터프라이즈 데이터 세트에 있는 개인 정보를 식별, 매핑 및 분류하고, 정책을 수립하고, 온프레미스 또는 클라우드의 개인 정보 보호 요구사항을 충족하고, 보안 태세를 개선하고, 규정을 준수하는 데 도움이 됩니다.

Cloud Data Sense 기반 * NetApp ® BlueXP ™ * 분류 고객은 데이터 자산 전체에서 데이터를 자동으로 스캔, 분석, 분류, 조치하고, 보안 위험을 감지하고, 스토리지를 최적화하고, 클라우드 구축을 가속화할 수 있습니다. 통합 제어 플레인을 통해 스토리지와 데이터 서비스가 결합되어 고객은 GPU 인스턴스를 계산에 사용하고 하이브리드 멀티 클라우드 환경을 사용하여 콜드 스토리지 계층화와 아카이브 및 백업을 수행할 수 있습니다.

* NetApp 파일 - 객체 이중성 *. NetApp ONTAP는 NFS 및 S3에 대한 이중 프로토콜 액세스를 지원합니다. 이 솔루션을 통해 고객은 NetApp Cloud Volumes ONTAP의 S3 버킷을 통해 Amazon AWS SageMaker 노트북의 NFS 데이터에 액세스할 수 있습니다. 따라서 NFS와 S3 모두에서 데이터를 공유할 수 있어야 하는 이기종 데이터 소스에 쉽게 액세스해야 하는 고객에게 유연성이 제공됩니다.  예를 들어, 파일 객체 버킷에 대한 액세스를 통해 SageMaker에서 Meta의 Llama 2 텍스트 생성 모델과 같은 FMS를 미세 조정합니다.

* NetApp ® Cloud Sync * 서비스는 데이터를 클라우드 또는 온프레미스의 모든 대상으로 마이그레이션하는 간단하고 안전한 방법을 제공합니다. Cloud Sync은 사내 또는 클라우드 스토리지, NAS 및 오브젝트 저장소 간에 데이터를 원활하게 전송 및 동기화합니다.

* NetApp XCP * 는 NetApp 환경 간 및 NetApp 환경 간 데이터 마이그레이션을 빠르고 안정적으로 지원하는 클라이언트 소프트웨어입니다. 또한 XCP는 대용량 데이터를 Hadoop HDFS 파일 시스템에서 ONTAP NFS, S3 또는 StorageGRID 및 XCP 파일 분석으로 효율적으로 이동할 수 있는 기능을 제공하여 파일 시스템에 대한 가시성을 제공합니다.

* NetApp ® DataOps Toolkit * 은 데이터 과학자, DevOps 및 데이터 엔지니어가 고성능 스케일 아웃 NetApp 스토리지를 통해 지원되는 데이터 볼륨 또는 JupyterLab 작업 공간의 즉각적인 프로비저닝, 복제, 스냅샷 생성 등의 다양한 데이터 관리 작업을 간편하게 수행할 수 있는 Python 라이브러리입니다.

* NetApp 제품 보안 *. LLM은 실수로 기밀 데이터를 응답에 노출시킬 수 있기 때문에 LLM을 활용하는 AI 응용 프로그램과 관련된 취약점을 연구하는 CISO에게 우려를 안겨 줍니다. OWASP(Open Worldwide Application Security Project)에서 설명한 바와 같이 데이터 손상, 데이터 유출, 서비스 거부 및 LLM 내 즉각적인 주입과 같은 보안 문제는 무단 액세스 서비스 공격자에 대한 데이터 노출로부터 기업에 영향을 미칠 수 있습니다. 데이터 스토리지 요구 사항에는 정형, 반정형 및 비정형 데이터에 대한 무결성 검사 및 변경 불가능한 스냅샷이 포함되어야 합니다. NetApp 스냅샷과 SnapLock가 데이터 세트 버전 관리에 사용됩니다. RBAC(역할 기반 액세스 제어)와 보안 프로토콜, 사용되지 않는 데이터와 전송 중인 데이터를 모두 보호하기 위한 업계 표준 암호화 기능을 제공합니다. Cloud Insights와 Cloud Data Sense는 함께 제공 기능을 통해 위협의 출처를 포렌적으로 식별하고 복원할 데이터의 우선순위를 지정할 수 있습니다.



=== * ONTAP AI 및 DGX BasePOD *

NVIDIA DGX BasePOD가 포함된 NetApp ® ONTAP ® AI 참조 아키텍처는 머신 러닝(ML) 및 인공 지능(AI) 워크로드를 위한 확장 가능한 아키텍처입니다. 일반적으로 LLM의 중요 교육 단계에서는 데이터 스토리지에서 교육 클러스터로 데이터가 정기적으로 복사됩니다. 이 단계에 사용되는 서버는 GPU를 사용해 컴퓨팅을 병렬화하여 방대한 양의 데이터를 수용합니다. 물리적 I/O 대역폭 요구사항을 충족하는 것은 높은 GPU 활용률을 유지하는 데 매우 중요합니다.



=== * ONTAP AI 및 NVIDIA AI Enterprise *

NVIDIA AI Enterprise는 NVIDIA 인증 시스템과 함께 VMware vSphere에서 실행하도록 NVIDIA에서 최적화, 인증 및 지원하는 엔드 투 엔드 클라우드 네이티브 AI 및 데이터 분석 소프트웨어 제품군입니다. 이 소프트웨어를 사용하면 최신 하이브리드 클라우드 환경에서 AI 워크로드를 쉽고 빠르게 구축, 관리, 확장할 수 있습니다. NetApp 및 VMware를 기반으로 하는 NVIDIA AI Enterprise는 단순하고 친숙한 패키지로 엔터프라이즈급 AI 워크로드 및 데이터 관리를 제공합니다.



=== * 1P 클라우드 플랫폼 *

완전 관리형 클라우드 스토리지 오퍼링은 Microsoft Azure As ANF(Azure NetApp Files), AWS FSxN(Amazon FSx for NetApp ONTAP), Google GNCV(Google Cloud NetApp Volumes)로 기본 제공됩니다. 1P는 고객이 퍼블릭 클라우드의 향상된 데이터 보안으로 고가용성 AI 워크로드를 실행하고 AWS SageMaker, Azure-OpenAI Services, Google의 Vertex AI와 같은 클라우드 네이티브 ML 플랫폼으로 LLM/FMS를 미세 조정할 수 있도록 지원하는 고성능 파일 관리 시스템입니다.



== NetApp 파트너 솔루션 제품군

NetApp은 핵심 데이터 제품, 기술 및 기능 외에도 강력한 AI 파트너 네트워크와 긴밀하게 협력하여 고객에게 부가 가치를 제공합니다.

* AI 시스템의 NVIDIA Guardrails * 는 AI 기술의 윤리적이고 책임 있는 사용을 보장하기 위한 보호 조치의 역할을 합니다. AI 개발자는 특정 주제에 대한 LLM 기반 애플리케이션의 동작을 정의하고 원치 않는 주제에 대한 토론에 참여하지 못하도록 선택할 수 있습니다. 오픈 소스 툴킷인 Guardrail은 LLM을 다른 서비스에 원활하고 안전하게 연결할 수 있는 기능을 제공하여 신뢰할 수 있고 안전하며 안전한 LLM 대화 시스템을 구축할 수 있습니다.

* Domino Data Lab * 은 AI 전환 과정에서 언제 어디서나 Generative AI를 빠르고 안전하며 경제적으로 구축 및 생산할 수 있는 다양한 엔터프라이즈급 도구를 제공합니다. Domino의 Enterprise MLOps Platform을 사용하면 데이터 과학자가 선호하는 도구와 모든 데이터를 사용하고, 어디에서든 모델을 쉽게 교육 및 배포하고, 위험 및 비용 효율적으로 관리할 수 있습니다. 이 모든 것이 하나의 제어 센터에서 가능합니다.

* Edge AI용 Modzy *. NetApp ® 과 Modzy는 파트너십을 통해 이미지, 오디오, 텍스트, 표를 비롯한 모든 유형의 데이터에 적합한 AI를 제공합니다. Modzy는 AI 모델을 배포, 통합 및 실행하기 위한 MLOps 플랫폼으로, 데이터 과학자에게 원활한 LLM 추론을 위한 통합 솔루션을 통해 모델 모니터링, 드리프트 감지 및 설명 기능을 제공합니다.

* Run:AI * 와 NetApp은 AI 워크로드 오케스트레이션을 간소화하는 Run:AI 클러스터 관리 플랫폼을 통해 NetApp ONTAP AI 솔루션의 고유한 기능을 입증하기 위해 파트너십을 체결했습니다. Spark, Ray, Dask 및 RAPIDS용 통합 프레임워크를 통해 데이터 처리 파이프라인을 수백 개의 머신으로 확장하도록 설계된 GPU 리소스를 자동으로 분할하고 결합합니다.



== 결론

Generative AI는 모델이 고품질 데이터에 대해 훈련될 때만 효과적인 결과를 생성할 수 있습니다. LLM은 놀라운 이정표를 달성했지만 데이터 이동성과 데이터 품질과 관련된 한계, 설계 과제 및 위험을 인식하는 것이 중요합니다. LLM은 이질적인 데이터 소스의 대규모의 이질적인 훈련 데이터 세트를 사용합니다. 모델에 의해 생성된 부정확한 결과 또는 편향된 결과는 기업과 소비자 모두에게 위기의 원인이 될 수 있습니다. 이러한 위험은 데이터 품질, 데이터 보안 및 데이터 이동성과 관련된 데이터 관리 문제로 인해 발생할 수 있는 LLM의 제약과 일치할 수 있습니다. NetApp를 사용하는 조직은 빠른 데이터 성장, 데이터 이동성, 멀티 클라우드 관리 및 AI 채택으로 인해 발생하는 복잡성을 충족할 수 있습니다. 대규모 AI 인프라와 효율적인 데이터 관리는 생성 AI와 같은 AI 애플리케이션의 성공을 정의하는 데 매우 중요합니다. 고객이 비용 효율성, 데이터 거버넌스 및 윤리적인 AI 관행을 제어하면서 엔터프라이즈에 필요한 확장 기능을 그대로 유지하면서 모든 구축 시나리오를 다룰 수 있어야 합니다. NetApp은 고객이 AI 구축을 단순화하고 가속할 수 있도록 돕기 위해 지속적으로 노력하고 있습니다.
