---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-powershell-considerations.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: 이 NetApp ONTAP 솔루션은 ONTAP 기반 사이버 볼트를 구성, 강화 및 검증하는 데 사용됩니다 
---
= 추가 고려 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
ONTAP 기반 사이버 볼트를 설계 및 배포할 때 추가로 고려해야 할 사항이 있습니다.



== 용량 사이징 고려 사항

ONTAP 사이버 소산 대상 볼륨에 필요한 디스크 공간의 양은 다양한 요인에 따라 달라집니다. 그 중 가장 중요한 것은 소스 볼륨의 데이터 변화율입니다. 대상 볼륨의 백업 일정과 스냅샷 일정은 모두 대상 볼륨의 디스크 사용량에 영향을 미치며 소스 볼륨의 변경 속도는 일정하지 않을 가능성이 높습니다. 최종 사용자 또는 애플리케이션 동작의 향후 변경 사항을 수용하는 데 필요한 추가 스토리지 용량 버퍼를 제공하는 것이 좋습니다.

ONTAP에서 보존 기간이 1개월인 관계로 사이징하려면 운영 데이터 세트의 크기, 데이터 변경률(일일 변경률), 데이터 중복 제거 및 압축 절약 효과(해당되는 경우)를 비롯한 여러 요소를 기준으로 스토리지 요구 사항을 계산해야 합니다.

단계별 접근 방식은 다음과 같습니다.

첫 번째 단계는 사이버 볼트로 보호할 소스 볼륨의 크기를 파악하는 것입니다. 이 데이터는 처음에 사이버 볼트 대상에 복제할 기본 데이터 양입니다. 그런 다음 데이터 세트의 일일 변경률을 추정합니다. 이 값은 매일 변경되는 데이터의 비율입니다. 데이터의 동적 특성을 잘 이해하는 것이 중요합니다.

예를 들면 다음과 같습니다.

* 운영 데이터 세트의 크기 = 5TB
* 일일 변경률 = 5%(0.05)
* 중복제거 및 압축 효율성 = 50%(0.50)


이제 계산에 대해 살펴보겠습니다.

* 일일 데이터 변경률 계산:
+
`Changed data per day = 5000 * 5% = 250GB`

* 30일 동안 변경된 총 데이터 계산:
+
`Total changed data in 30 days = 250 GB * 14 = 3.5TB`

* 필요한 총 스토리지 용량 계산:
+
`TOTAL = 5TB + 3.5TB = 8.5TB`

* 중복제거 및 압축 절약 효과 적용:
+
`EFFECTIVE = 8.5TB * 50% = 4.25TB`



* 스토리지 요구 사항 요약 *

* 효율성 없음: 30일간의 사이버 소산 데이터를 저장하려면 * 8.5TB * 가 필요합니다.
* 50% 효율성: 중복 제거 및 압축 후에 4.25TB * 의 스토리지가 필요합니다.



NOTE: Snapshot 복사본에는 메타데이터로 인한 추가 오버헤드가 있을 수 있지만 일반적으로 경미한 수준입니다.


NOTE: 하루에 여러 백업을 수행하는 경우 매일 생성되는 스냅샷 복사본 수로 계산을 조정합니다.


NOTE: 사이징이 미래에 대비하여 확장될 수 있도록 시간에 따른 데이터 증가를 고려하십시오.



== 운영/소스에 대한 성능 영향

데이터 전송은 풀 작업이므로 운영 스토리지 성능에 미치는 영향은 워크로드, 데이터 볼륨 및 백업 빈도에 따라 달라질 수 있습니다. 하지만 데이터 전송은 데이터 보호 및 백업 작업을 사이버 소산 스토리지 시스템으로 오프로드하도록 설계되었으므로 운영 시스템의 전반적인 성능 영향은 일반적으로 중간 정도이며 관리가 용이합니다. 초기 관계 설정과 첫 번째 전체 백업 중에 상당한 양의 데이터가 운영 시스템에서 사이버 소산 시스템(SnapLock Compliance 볼륨)으로 전송됩니다. 이로 인해 운영 시스템의 네트워크 트래픽과 I/O 로드가 증가할 수 있습니다. 초기 전체 백업이 완료되면 ONTAP는 마지막 백업 이후에 변경된 블록만 추적하고 전송하면 됩니다. 따라서 초기 복제에 비해 입출력 로드가 훨씬 적습니다. 증분 업데이트는 효율적이며 운영 스토리지 성능에 미치는 영향이 최소화됩니다. 볼트 프로세스는 백그라운드에서 실행되므로 운영 시스템의 생산 작업 부하에 대한 간섭 가능성이 줄어듭니다.

* 스토리지 시스템에 추가 로드를 처리할 수 있는 충분한 리소스(CPU, 메모리 및 IOPS)가 있는지 확인하면 성능에 미치는 영향이 줄어듭니다.

