---
sidebar: sidebar 
permalink: ehc/gcp/gcp-gcve.html 
keywords: NetApp Solutions, hyperscalers, google cloud, gcp, gcve, enterprise, hybrid, cloud, migrate, migration, disaster recovery, dr 
summary:  
---
= Google Cloud Platform GCVE를 위한 NetApp의 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../../media/


[role="lead"]
NetApp이 GCP(Google Cloud Platform) Google Cloud VMware Engine(GCVE)에 제공하는 기능에 대해 자세히 알아보십시오. NetApp(게스트 연결 스토리지 장치 또는 보조 NFS 데이터 저장소부터 마이그레이션, 클라우드로 확장/버스트, 재해 복구까지.

다음 옵션 중 하나를 선택하여 원하는 콘텐츠의 섹션으로 이동합니다.

* link:#config["GCP에서 GCVE 구성"]
* link:#datastore["GCVE용 NetApp 스토리지 옵션"]
* link:#solutions["NetApp/VMware 클라우드 솔루션"]




== GCP에서 GCVE 구성

온프레미스에서와 마찬가지로 클라우드 기반 가상화 환경을 계획하는 것은 VM 및 마이그레이션을 생성할 수 있는 성공적인 프로덕션 준비 환경에 매우 중요합니다.

이 섹션에서는 GCVE를 설정 및 관리하고 NetApp 스토리지를 연결하는 데 사용할 수 있는 옵션과 함께 사용하는 방법을 설명합니다.


NOTE: 게스트 내 저장소는 Cloud Volumes ONTAP 및 Cloud Volumes Services를 GCVE에 연결하는 유일한 지원 방법입니다.

설치 프로세스는 다음 단계로 나눌 수 있습니다.

* GCVE 배포 및 구성
* GCVE에 대한 개인 액세스를 활성화합니다


자세한 내용을 확인하십시오 link:gcp-setup.html["GCVE에 대한 구성 단계"].



== GCVE용 NetApp 스토리지 옵션

NetApp 스토리지는 GCP GCVE 내에서 guess Connected 또는 보충 NFS 데이터 저장소로 여러 가지 방법으로 활용할 수 있습니다.

를 방문하십시오 link:../ehc-support-configs.html["지원되는 NetApp 스토리지 옵션"] 를 참조하십시오.

Google Cloud는 다음과 같은 구성에서 NetApp 스토리지를 지원합니다.

* CVO(Cloud Volumes ONTAP)를 게스트 연결 스토리지로 사용합니다
* CVS(Cloud Volumes Service)를 게스트 연결 스토리지로 사용합니다
* CVS(Cloud Volumes Service)를 보조 NFS 데이터 저장소로 사용


자세한 내용을 확인하십시오 link:gcp-guest.html["GCVE에 대한 게스트 연결 저장소 옵션"].

에 대해 자세히 알아보십시오 link:https://www.netapp.com/blog/cloud-volumes-service-google-cloud-vmware-engine/["Google Cloud VMware Engine에 대한 NetApp Cloud Volumes Service 데이터 저장소 지원(NetApp 블로그)"^] 또는 link:https://cloud.google.com/blog/products/compute/how-to-use-netapp-cvs-as-datastores-with-vmware-engine["NetApp CVS를 Google Cloud VMware Engine용 데이터 저장소로 사용하는 방법(Google 블로그)"^]



== 솔루션 사용 사례

NetApp 및 VMware 클라우드 솔루션을 사용하면 많은 사용 사례를 Azure AVS에서 간단하게 구축할 수 있습니다. SE 사례는 VMware에서 정의한 각 클라우드 영역에 대해 정의됩니다.

* 보호(재해 복구 및 백업/복원 모두 포함)
* 확장
* 마이그레이션


link:gcp-solutions.html["Google Cloud GCVE용 NetApp 솔루션을 찾아보십시오"]
